INET Framework for OMNeT++/OMNEST: EtherApp_m.h File Reference
EtherApp_m.h File Reference
#include <omnetpp.h>
#include "INETDefs.h"
Classes
class EtherAppReq
class EtherAppResp
Defines
#define MSGC_VERSION 0x0401
#define ETHERAPP_CLI_SAP 0xf0
#define ETHERAPP_SRV_SAP 0xf1
Functions
void doPacking (cCommBuffer *b, EtherAppReq &obj)
void doUnpacking (cCommBuffer *b, EtherAppReq &obj)
void doPacking (cCommBuffer *b, EtherAppResp &obj)
void doUnpacking (cCommBuffer *b, EtherAppResp &obj)
Define Documentation
#define ETHERAPP_CLI_SAP 0xf0
Definition at line 19 of file EtherApp_m.h.
Referenced by EtherAppSrv::initialize(), and EtherAppCli::initialize().
#define ETHERAPP_SRV_SAP 0xf1
Definition at line 20 of file EtherApp_m.h.
Referenced by EtherAppSrv::initialize(), and EtherAppCli::initialize().
#define MSGC_VERSION 0x0401
Definition at line 11 of file EtherApp_m.h.
Function Documentation
void doPacking (cCommBuffer * b, EtherAppResp & obj) [inline]
Definition at line 98 of file EtherApp_m.h.
{obj.parsimPack(b);}
void doPacking (cCommBuffer * b, EtherAppReq & obj) [inline]
Definition at line 60 of file EtherApp_m.h.
Referenced by doPacking(), and TCPSegment::parsimPack().
{obj.parsimPack(b);}
void doUnpacking (cCommBuffer * b, EtherAppResp & obj) [inline]
Definition at line 99 of file EtherApp_m.h.
{obj.parsimUnpack(b);}
void doUnpacking (cCommBuffer * b, EtherAppReq & obj) [inline]
Definition at line 61 of file EtherApp_m.h.
Referenced by doUnpacking(), and TCPSegment::parsimUnpack().
{obj.parsimUnpack(b);}