INET Framework for OMNeT++/OMNEST: LDP.cc File Reference
LDP.cc File Reference
#include <omnetpp.h>
#include <iostream>
#include <fstream>
#include <algorithm>
#include "ConstType.h"
#include "LDP.h"
#include "LIBTable.h"
#include "InterfaceTableAccess.h"
#include "IPv4InterfaceData.h"
#include "RoutingTableAccess.h"
#include "LIBTableAccess.h"
#include "TEDAccess.h"
#include "NotifierConsts.h"
#include "UDPPacket.h"
#include "TCPSegment.h"
Functions
Define_Module (LDP)
std::ostream & operator<< (std::ostream &os, const LDP::fec_bind_t &f)
bool fecPrefixCompare (const LDP::fec_t &a, const LDP::fec_t &b)
std::ostream & operator<< (std::ostream &os, const LDP::fec_t &f)
std::ostream & operator<< (std::ostream &os, const LDP::pending_req_t &r)
std::ostream & operator<< (std::ostream &os, const LDP::peer_info &p)
bool operator== (const FEC_TLV &a, const FEC_TLV &b)
bool operator!= (const FEC_TLV &a, const FEC_TLV &b)
std::ostream & operator<< (std::ostream &os, const FEC_TLV &a)
Function Documentation
Define_Module (LDP)
bool fecPrefixCompare (const LDP::fec_t & a, const LDP::fec_t & b)
Definition at line 42 of file LDP.cc.
Referenced by LDP::rebuildFecList().
{
    return a.length > b.length;
}
bool operator!= (const FEC_TLV & a, const FEC_TLV & b)
Definition at line 72 of file LDP.cc.
{
    return !operator==(a, b);
}
std::ostream& operator<< (std::ostream & os, const FEC_TLV & a)
Definition at line 77 of file LDP.cc.
{
    os << "addr=" << a.addr << "  length=" << a.length;
    return os;
}
std::ostream& operator<< (std::ostream & os, const LDP::peer_info & p)
Definition at line 59 of file LDP.cc.
{
    os << "peerIP=" << p.peerIP << "  interface=" << p.linkInterface <<
          "  activeRole=" << (p.activeRole ? "true" : "false") <<
          "  socket=" << (p.socket ? TCPSocket::stateName(p.socket->getState()) : "NULL");
    return os;
}
std::ostream& operator<< (std::ostream & os, const LDP::pending_req_t & r)
Definition at line 53 of file LDP.cc.
{
    os << "fecid=" << r.fecid << "  peer=" << r.peer;
    return os;
}
std::ostream& operator<< (std::ostream & os, const LDP::fec_t & f)
Definition at line 47 of file LDP.cc.
{
    os << "fecid=" << f.fecid << "  addr=" << f.addr << "  length=" << f.length << "  nextHop=" << f.nextHop;
    return os;
}
std::ostream& operator<< (std::ostream & os, const LDP::fec_bind_t & f)
Definition at line 36 of file LDP.cc.
{
    os << "fecid=" << f.fecid << "  peer=" << f.peer << " label=" << f.label;
    return os;
}
bool operator== (const FEC_TLV & a, const FEC_TLV & b)
Definition at line 67 of file LDP.cc.
Referenced by operator!=(), IPv6Address::operator!=(), and OSPF::LinkStateUpdateHandler::ProcessPacket().
{
    return a.length == b.length && a.addr == b.addr;
}