INET Framework for OMNeT++/OMNEST: OSPFPacket Class Reference
OSPFPacket Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFPacket (const char *name=NULL, int kind=0)
OSPFPacket (const OSPFPacket &other)
virtual ~OSPFPacket ()
OSPFPacket & operator= (const OSPFPacket &other)
virtual OSPFPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual char getVersion () const
virtual void setVersion (char version_var)
virtual char getType () const
virtual void setType (char type_var)
virtual short getPacketLength () const
virtual void setPacketLength (short packetLength_var)
virtual IPAddress & getRouterID ()
virtual const IPAddress & getRouterID () const
virtual void setRouterID (const IPAddress &routerID_var)
virtual IPAddress & getAreaID ()
virtual const IPAddress & getAreaID () const
virtual void setAreaID (const IPAddress &areaID_var)
virtual short getChecksum () const
virtual void setChecksum (short checksum_var)
virtual short getAuthenticationType () const
virtual void setAuthenticationType (short authenticationType_var)
virtual unsigned int getAuthenticationArraySize () const
virtual char getAuthentication (unsigned int k) const
virtual void setAuthentication (unsigned int k, char authentication_var)
Protected Member Functions
bool operator== (const OSPFPacket &)
Protected Attributes
char version_var
char type_var
short packetLength_var
::IPAddress routerID_var
::IPAddress areaID_var
short checksum_var
short authenticationType_var
char authentication_var [8]
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 packet OSPFPacket
 {
     char version = 2;
     char type enum(OSPFPacketType) = HelloPacket;
     short packetLength = 0;
     IPAddress routerID;
     IPAddress areaID;
     short checksum = 0;
     short authenticationType = 0;
     char authentication[8];
 }
Definition at line 124 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFPacket::OSPFPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
OSPFPacket::OSPFPacket (const OSPFPacket & other)
virtual OSPFPacket::~OSPFPacket () [virtual]
Member Function Documentation
virtual OSPFPacket* OSPFPacket::dup () const [inline, virtual]
Reimplemented in OSPFHelloPacket, OSPFDatabaseDescriptionPacket, OSPFLinkStateRequestPacket, OSPFLinkStateUpdatePacket, and OSPFLinkStateAcknowledgementPacket.
Definition at line 144 of file OSPFPacket_m.h.
{return new OSPFPacket(*this);}
virtual const IPAddress& OSPFPacket::getAreaID () const [inline, virtual]
Definition at line 159 of file OSPFPacket_m.h.
Referenced by getAreaID().
{return const_cast<OSPFPacket*>(this)->getAreaID();}
virtual IPAddress& OSPFPacket::getAreaID () [virtual]
Referenced by OSPF::MessageHandler::ProcessPacket(), and OSPF::LinkStateUpdateHandler::ProcessPacket().
virtual char OSPFPacket::getAuthentication (unsigned int k) const [virtual]
virtual unsigned int OSPFPacket::getAuthenticationArraySize () const [virtual]
virtual short OSPFPacket::getAuthenticationType () const [virtual]
virtual short OSPFPacket::getChecksum () const [virtual]
virtual short OSPFPacket::getPacketLength () const [virtual]
virtual const IPAddress& OSPFPacket::getRouterID () const [inline, virtual]
Definition at line 156 of file OSPFPacket_m.h.
Referenced by getRouterID().
{return const_cast<OSPFPacket*>(this)->getRouterID();}
virtual IPAddress& OSPFPacket::getRouterID () [virtual]
Referenced by OSPF::MessageHandler::MessageReceived(), OSPF::MessageHandler::ProcessPacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::HelloHandler::ProcessPacket().
virtual char OSPFPacket::getType () const [virtual]
Referenced by OSPF::MessageHandler::ProcessPacket(), and OSPF::MessageHandler::SendPacket().
virtual char OSPFPacket::getVersion () const [virtual]
Referenced by OSPF::MessageHandler::ProcessPacket().
OSPFPacket& OSPFPacket::operator= (const OSPFPacket & other)
Reimplemented in OSPFHelloPacket, OSPFDatabaseDescriptionPacket, OSPFLinkStateRequestPacket, OSPFLinkStateUpdatePacket, and OSPFLinkStateAcknowledgementPacket.
bool OSPFPacket::operator== (const OSPFPacket &) [protected]
Reimplemented in OSPFHelloPacket, OSPFDatabaseDescriptionPacket, OSPFLinkStateRequestPacket, OSPFLinkStateUpdatePacket, and OSPFLinkStateAcknowledgementPacket.
virtual void OSPFPacket::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in OSPFHelloPacket, OSPFDatabaseDescriptionPacket, OSPFLinkStateRequestPacket, OSPFLinkStateUpdatePacket, and OSPFLinkStateAcknowledgementPacket.
Referenced by doPacking().
virtual void OSPFPacket::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in OSPFHelloPacket, OSPFDatabaseDescriptionPacket, OSPFLinkStateRequestPacket, OSPFLinkStateUpdatePacket, and OSPFLinkStateAcknowledgementPacket.
Referenced by doUnpacking().
virtual void OSPFPacket::setAreaID (const IPAddress & areaID_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Neighbor::RetransmitUpdatePacket(), OSPF::Neighbor::SendDatabaseDescriptionPacket(), OSPF::Interface::SendDelayedAcknowledgements(), OSPF::Interface::SendHelloPacket(), OSPF::Neighbor::SendLinkStateRequestPacket(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFPacket::setAuthentication (unsigned int k, char authentication_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Neighbor::RetransmitUpdatePacket(), OSPF::Neighbor::SendDatabaseDescriptionPacket(), OSPF::Interface::SendDelayedAcknowledgements(), OSPF::Interface::SendHelloPacket(), OSPF::Neighbor::SendLinkStateRequestPacket(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFPacket::setAuthenticationType (short authenticationType_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Neighbor::RetransmitUpdatePacket(), OSPF::Neighbor::SendDatabaseDescriptionPacket(), OSPF::Interface::SendDelayedAcknowledgements(), OSPF::Interface::SendHelloPacket(), OSPF::Neighbor::SendLinkStateRequestPacket(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFPacket::setChecksum (short checksum_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Neighbor::RetransmitUpdatePacket(), OSPF::Neighbor::SendDatabaseDescriptionPacket(), OSPF::Interface::SendDelayedAcknowledgements(), OSPF::Interface::SendHelloPacket(), OSPF::Neighbor::SendLinkStateRequestPacket(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFPacket::setPacketLength (short packetLength_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Neighbor::RetransmitUpdatePacket(), OSPF::Neighbor::SendDatabaseDescriptionPacket(), OSPF::Interface::SendDelayedAcknowledgements(), OSPF::Interface::SendHelloPacket(), OSPF::Neighbor::SendLinkStateRequestPacket(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFPacket::setRouterID (const IPAddress & routerID_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Neighbor::RetransmitUpdatePacket(), OSPF::Neighbor::SendDatabaseDescriptionPacket(), OSPF::Interface::SendDelayedAcknowledgements(), OSPF::Interface::SendHelloPacket(), OSPF::Neighbor::SendLinkStateRequestPacket(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFPacket::setType (char type_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Neighbor::RetransmitUpdatePacket(), OSPF::Neighbor::SendDatabaseDescriptionPacket(), OSPF::Interface::SendDelayedAcknowledgements(), OSPF::Neighbor::SendLinkStateRequestPacket(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFPacket::setVersion (char version_var) [virtual]
Member Data Documentation
::IPAddress OSPFPacket::areaID_var [protected]
Definition at line 131 of file OSPFPacket_m.h.
char OSPFPacket::authentication_var[8] [protected]
Definition at line 134 of file OSPFPacket_m.h.
short OSPFPacket::authenticationType_var [protected]
Definition at line 133 of file OSPFPacket_m.h.
short OSPFPacket::checksum_var [protected]
Definition at line 132 of file OSPFPacket_m.h.
short OSPFPacket::packetLength_var [protected]
Definition at line 129 of file OSPFPacket_m.h.
::IPAddress OSPFPacket::routerID_var [protected]
Definition at line 130 of file OSPFPacket_m.h.
char OSPFPacket::type_var [protected]
Definition at line 128 of file OSPFPacket_m.h.
char OSPFPacket::version_var [protected]
Definition at line 127 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h