INET Framework for OMNeT++/OMNEST: RSVPPathError_Base Class Reference
RSVPPathError_Base Class Reference
#include <RSVPPathMsg_m.h>
Public Member Functions
virtual ~RSVPPathError_Base ()
virtual RSVPPathError_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getErrorNode ()
virtual const IPAddress & getErrorNode () const
virtual void setErrorNode (const IPAddress &errorNode_var)
virtual int getErrorCode () const
virtual void setErrorCode (int errorCode_var)
virtual SenderDescriptor_t & getSender_descriptor ()
virtual const SenderDescriptor_t & getSender_descriptor () const
virtual void setSender_descriptor (const SenderDescriptor_t &sender_descriptor_var)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind_var)
Protected Member Functions
bool operator== (const RSVPPathError_Base &)
RSVPPathError_Base (const char *name=NULL, int kind=0)
RSVPPathError_Base (const RSVPPathError_Base &other)
RSVPPathError_Base & operator= (const RSVPPathError_Base &other)
Protected Attributes
::IPAddress errorNode_var
int errorCode_var
::SenderDescriptor_t sender_descriptor_var
int rsvpKind_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPPathMsg.msg by opp_msgc.
 packet RSVPPathError extends RSVPPacket
 {
     (true);
     IPAddress errorNode;
     int errorCode;
     SenderDescriptor_t sender_descriptor;
     int rsvpKind = PERROR_MESSAGE;
 }
RSVPPathError_Base is only useful if it gets subclassed, and RSVPPathError is derived from it. The minimum code to be written for RSVPPathError is the following:
 class RSVPPathError : public RSVPPathError_Base
 {
   public:
     RSVPPathError(const char *name=NULL, int kind=0) : RSVPPathError_Base(name,kind) {}
     RSVPPathError(const RSVPPathError& other) : RSVPPathError_Base(other.getName()) {operator=(other);}
     RSVPPathError& operator=(const RSVPPathError& other) {RSVPPathError_Base::operator=(other); return *this;}
     virtual RSVPPathError *dup() const {return new RSVPPathError(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPPathError_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(RSVPPathError);
Definition at line 208 of file RSVPPathMsg_m.h.
Constructor & Destructor Documentation
RSVPPathError_Base::RSVPPathError_Base (const char * name = NULL, int kind = 0) [protected]
RSVPPathError_Base::RSVPPathError_Base (const RSVPPathError_Base & other) [protected]
virtual RSVPPathError_Base::~RSVPPathError_Base () [virtual]
Member Function Documentation
virtual RSVPPathError_Base* RSVPPathError_Base::dup () const [inline, virtual]
Reimplemented from RSVPPacket.
Reimplemented in RSVPPathError.
Definition at line 226 of file RSVPPathMsg_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class RSVPPathError");}
virtual int RSVPPathError_Base::getErrorCode () const [virtual]
Referenced by RSVP::processPathErrMsg().
virtual const IPAddress& RSVPPathError_Base::getErrorNode () const [inline, virtual]
Definition at line 232 of file RSVPPathMsg_m.h.
Referenced by getErrorNode().
{return const_cast<RSVPPathError_Base*>(this)->getErrorNode();}
virtual IPAddress& RSVPPathError_Base::getErrorNode () [virtual]
virtual int RSVPPathError_Base::getRsvpKind () const [virtual]
Reimplemented from RSVPMessage.
virtual const SenderDescriptor_t& RSVPPathError_Base::getSender_descriptor () const [inline, virtual]
Definition at line 237 of file RSVPPathMsg_m.h.
Referenced by getSender_descriptor().
{return const_cast<RSVPPathError_Base*>(this)->getSender_descriptor();}
virtual SenderDescriptor_t& RSVPPathError_Base::getSender_descriptor () [virtual]
Referenced by RSVPPathError::getBW(), RSVPPathError::getLspId(), RSVPPathError::getSenderTemplate(), RSVPPathError::getSenderTspec(), RSVPPathError::getSrcAddress(), RSVPPathError::setSenderTemplate(), and RSVPPathError::setSenderTspec().
RSVPPathError_Base& RSVPPathError_Base::operator= (const RSVPPathError_Base & other) [protected]
Reimplemented from RSVPPacket.
Reimplemented in RSVPPathError.
bool RSVPPathError_Base::operator== (const RSVPPathError_Base &) [protected]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathError_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathError_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathError_Base::setErrorCode (int errorCode_var) [virtual]
Referenced by RSVP::sendPathErrorMessage().
virtual void RSVPPathError_Base::setErrorNode (const IPAddress & errorNode_var) [virtual]
Referenced by RSVP::sendPathErrorMessage().
virtual void RSVPPathError_Base::setRsvpKind (int rsvpKind_var) [virtual]
Reimplemented from RSVPMessage.
virtual void RSVPPathError_Base::setSender_descriptor (const SenderDescriptor_t & sender_descriptor_var) [virtual]
Member Data Documentation
int RSVPPathError_Base::errorCode_var [protected]
Definition at line 212 of file RSVPPathMsg_m.h.
::IPAddress RSVPPathError_Base::errorNode_var [protected]
Definition at line 211 of file RSVPPathMsg_m.h.
int RSVPPathError_Base::rsvpKind_var [protected]
Reimplemented from RSVPMessage.
Definition at line 214 of file RSVPPathMsg_m.h.
::SenderDescriptor_t RSVPPathError_Base::sender_descriptor_var [protected]
Definition at line 213 of file RSVPPathMsg_m.h.
The documentation for this class was generated from the following file:
RSVPPathMsg_m.h