INET Framework for OMNeT++/OMNEST: SCTPShutdownAckChunk Class Reference
SCTPShutdownAckChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPShutdownAckChunk (const char *name=NULL, int kind=0)
SCTPShutdownAckChunk (const SCTPShutdownAckChunk &other)
virtual ~SCTPShutdownAckChunk ()
SCTPShutdownAckChunk & operator= (const SCTPShutdownAckChunk &other)
virtual SCTPShutdownAckChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const SCTPShutdownAckChunk &)
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPShutdownAckChunk extends SCTPChunk
 {
 }
Definition at line 924 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPShutdownAckChunk::SCTPShutdownAckChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPShutdownAckChunk::SCTPShutdownAckChunk (const SCTPShutdownAckChunk & other)
virtual SCTPShutdownAckChunk::~SCTPShutdownAckChunk () [virtual]
Member Function Documentation
virtual SCTPShutdownAckChunk* SCTPShutdownAckChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 936 of file SCTPMessage_m.h.
Referenced by SCTPAssociation::retransmitShutdownAck(), and SCTPAssociation::sendShutdownAck().
{return new SCTPShutdownAckChunk(*this);}
SCTPShutdownAckChunk& SCTPShutdownAckChunk::operator= (const SCTPShutdownAckChunk & other)
Reimplemented from SCTPChunk.
bool SCTPShutdownAckChunk::operator== (const SCTPShutdownAckChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPShutdownAckChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPShutdownAckChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
SCTPMessage_m.h