INET Framework for OMNeT++/OMNEST: OSPFLinkStateRequestPacket Class Reference
OSPFLinkStateRequestPacket Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFLinkStateRequestPacket (const char *name=NULL, int kind=0)
OSPFLinkStateRequestPacket (const OSPFLinkStateRequestPacket &other)
virtual ~OSPFLinkStateRequestPacket ()
OSPFLinkStateRequestPacket & operator= (const OSPFLinkStateRequestPacket &other)
virtual
OSPFLinkStateRequestPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setRequestsArraySize (unsigned int size)
virtual unsigned int getRequestsArraySize () const
virtual LSARequest & getRequests (unsigned int k)
virtual const LSARequest & getRequests (unsigned int k) const
virtual void setRequests (unsigned int k, const LSARequest &requests_var)
Protected Member Functions
bool operator== (const OSPFLinkStateRequestPacket &)
Protected Attributes
::LSARequest * requests_var
unsigned int requests_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 packet OSPFLinkStateRequestPacket extends OSPFPacket
 {
     LSARequest requests[];
 }
Definition at line 770 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFLinkStateRequestPacket::OSPFLinkStateRequestPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
OSPFLinkStateRequestPacket::OSPFLinkStateRequestPacket (const OSPFLinkStateRequestPacket & other)
virtual OSPFLinkStateRequestPacket::~OSPFLinkStateRequestPacket () [virtual]
Member Function Documentation
virtual OSPFLinkStateRequestPacket* OSPFLinkStateRequestPacket::dup () const [inline, virtual]
Reimplemented from OSPFPacket.
Definition at line 784 of file OSPFPacket_m.h.
{return new OSPFLinkStateRequestPacket(*this);}
virtual const LSARequest& OSPFLinkStateRequestPacket::getRequests (unsigned int k) const [inline, virtual]
Definition at line 792 of file OSPFPacket_m.h.
Referenced by getRequests().
{return const_cast<OSPFLinkStateRequestPacket*>(this)->getRequests(k);}
virtual LSARequest& OSPFLinkStateRequestPacket::getRequests (unsigned int k) [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateRequestPacket(), and OSPF::LinkStateRequestHandler::ProcessPacket().
virtual unsigned int OSPFLinkStateRequestPacket::getRequestsArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateRequestPacket(), OSPF::LinkStateRequestHandler::ProcessPacket(), and OSPF::Neighbor::SendLinkStateRequestPacket().
OSPFLinkStateRequestPacket& OSPFLinkStateRequestPacket::operator= (const OSPFLinkStateRequestPacket & other)
Reimplemented from OSPFPacket.
bool OSPFLinkStateRequestPacket::operator== (const OSPFLinkStateRequestPacket &) [protected]
Reimplemented from OSPFPacket.
virtual void OSPFLinkStateRequestPacket::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doPacking().
virtual void OSPFLinkStateRequestPacket::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doUnpacking().
virtual void OSPFLinkStateRequestPacket::setRequests (unsigned int k, const LSARequest & requests_var) [virtual]
Referenced by OSPF::Neighbor::SendLinkStateRequestPacket().
virtual void OSPFLinkStateRequestPacket::setRequestsArraySize (unsigned int size) [virtual]
Referenced by OSPF::Neighbor::SendLinkStateRequestPacket().
Member Data Documentation
unsigned int OSPFLinkStateRequestPacket::requests_arraysize [protected]
Definition at line 774 of file OSPFPacket_m.h.
::LSARequest* OSPFLinkStateRequestPacket::requests_var [protected]
Definition at line 773 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h