INET Framework for OMNeT++/OMNEST: TCPStatusInfo Class Reference
TCPStatusInfo Class Reference
#include <TCPCommand_m.h>
Public Member Functions
TCPStatusInfo ()
TCPStatusInfo (const TCPStatusInfo &other)
virtual ~TCPStatusInfo ()
TCPStatusInfo & operator= (const TCPStatusInfo &other)
virtual TCPStatusInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getState () const
virtual void setState (int state_var)
virtual const char * getStateName () const
virtual void setStateName (const char *stateName_var)
virtual IPvXAddress & getLocalAddr ()
virtual const IPvXAddress & getLocalAddr () const
virtual void setLocalAddr (const IPvXAddress &localAddr_var)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort_var)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort_var)
virtual unsigned int getSnd_mss () const
virtual void setSnd_mss (unsigned int snd_mss_var)
virtual unsigned int getSnd_una () const
virtual void setSnd_una (unsigned int snd_una_var)
virtual unsigned int getSnd_nxt () const
virtual void setSnd_nxt (unsigned int snd_nxt_var)
virtual unsigned int getSnd_max () const
virtual void setSnd_max (unsigned int snd_max_var)
virtual unsigned int getSnd_wnd () const
virtual void setSnd_wnd (unsigned int snd_wnd_var)
virtual unsigned int getSnd_up () const
virtual void setSnd_up (unsigned int snd_up_var)
virtual unsigned int getSnd_wl1 () const
virtual void setSnd_wl1 (unsigned int snd_wl1_var)
virtual unsigned int getSnd_wl2 () const
virtual void setSnd_wl2 (unsigned int snd_wl2_var)
virtual unsigned int getIss () const
virtual void setIss (unsigned int iss_var)
virtual unsigned int getRcv_nxt () const
virtual void setRcv_nxt (unsigned int rcv_nxt_var)
virtual unsigned int getRcv_wnd () const
virtual void setRcv_wnd (unsigned int rcv_wnd_var)
virtual unsigned int getRcv_up () const
virtual void setRcv_up (unsigned int rcv_up_var)
virtual unsigned int getIrs () const
virtual void setIrs (unsigned int irs_var)
virtual bool getFin_ack_rcvd () const
virtual void setFin_ack_rcvd (bool fin_ack_rcvd_var)
Protected Member Functions
bool operator== (const TCPStatusInfo &)
Protected Attributes
int state_var
opp_string stateName_var
::IPvXAddress localAddr_var
::IPvXAddress remoteAddr_var
int localPort_var
int remotePort_var
unsigned int snd_mss_var
unsigned int snd_una_var
unsigned int snd_nxt_var
unsigned int snd_max_var
unsigned int snd_wnd_var
unsigned int snd_up_var
unsigned int snd_wl1_var
unsigned int snd_wl2_var
unsigned int iss_var
unsigned int rcv_nxt_var
unsigned int rcv_wnd_var
unsigned int rcv_up_var
unsigned int irs_var
bool fin_ack_rcvd_var
Detailed Description
Class generated from transport/contract/TCPCommand.msg by opp_msgc.
 class TCPStatusInfo extends TCPCommand
 {
     int state;
     string stateName;
     IPvXAddress localAddr;
     IPvXAddress remoteAddr;
     int localPort;
     int remotePort;
     unsigned int snd_mss;
     unsigned int snd_una;
     unsigned int snd_nxt;
     unsigned int snd_max;
     unsigned int snd_wnd;
     unsigned int snd_up;
     unsigned int snd_wl1;
     unsigned int snd_wl2;
     unsigned int iss;
     unsigned int rcv_nxt;
     unsigned int rcv_wnd;
     unsigned int rcv_up;
     unsigned int irs;
     bool fin_ack_rcvd;
 }
Definition at line 340 of file TCPCommand_m.h.
Constructor & Destructor Documentation
TCPStatusInfo::TCPStatusInfo ()
Referenced by dup().
TCPStatusInfo::TCPStatusInfo (const TCPStatusInfo & other)
virtual TCPStatusInfo::~TCPStatusInfo () [virtual]
Member Function Documentation
virtual TCPStatusInfo* TCPStatusInfo::dup () const [inline, virtual]
Reimplemented from TCPCommand.
Definition at line 372 of file TCPCommand_m.h.
{return new TCPStatusInfo(*this);}
virtual bool TCPStatusInfo::getFin_ack_rcvd () const [virtual]
virtual unsigned int TCPStatusInfo::getIrs () const [virtual]
virtual unsigned int TCPStatusInfo::getIss () const [virtual]
virtual const IPvXAddress& TCPStatusInfo::getLocalAddr () const [inline, virtual]
Definition at line 382 of file TCPCommand_m.h.
Referenced by getLocalAddr().
{return const_cast<TCPStatusInfo*>(this)->getLocalAddr();}
virtual IPvXAddress& TCPStatusInfo::getLocalAddr () [virtual]
virtual int TCPStatusInfo::getLocalPort () const [virtual]
virtual unsigned int TCPStatusInfo::getRcv_nxt () const [virtual]
virtual unsigned int TCPStatusInfo::getRcv_up () const [virtual]
virtual unsigned int TCPStatusInfo::getRcv_wnd () const [virtual]
virtual const IPvXAddress& TCPStatusInfo::getRemoteAddr () const [inline, virtual]
Definition at line 385 of file TCPCommand_m.h.
Referenced by getRemoteAddr().
{return const_cast<TCPStatusInfo*>(this)->getRemoteAddr();}
virtual IPvXAddress& TCPStatusInfo::getRemoteAddr () [virtual]
virtual int TCPStatusInfo::getRemotePort () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_max () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_mss () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_nxt () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_una () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_up () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_wl1 () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_wl2 () const [virtual]
virtual unsigned int TCPStatusInfo::getSnd_wnd () const [virtual]
virtual int TCPStatusInfo::getState () const [virtual]
virtual const char* TCPStatusInfo::getStateName () const [virtual]
TCPStatusInfo& TCPStatusInfo::operator= (const TCPStatusInfo & other)
Reimplemented from TCPCommand.
bool TCPStatusInfo::operator== (const TCPStatusInfo &) [protected]
Reimplemented from TCPCommand.
virtual void TCPStatusInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doPacking().
virtual void TCPStatusInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doUnpacking().
virtual void TCPStatusInfo::setFin_ack_rcvd (bool fin_ack_rcvd_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setIrs (unsigned int irs_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setIss (unsigned int iss_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setLocalAddr (const IPvXAddress & localAddr_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setLocalPort (int localPort_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setRcv_nxt (unsigned int rcv_nxt_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setRcv_up (unsigned int rcv_up_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setRcv_wnd (unsigned int rcv_wnd_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setRemotePort (int remotePort_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_max (unsigned int snd_max_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_mss (unsigned int snd_mss_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_nxt (unsigned int snd_nxt_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_una (unsigned int snd_una_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_up (unsigned int snd_up_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_wl1 (unsigned int snd_wl1_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_wl2 (unsigned int snd_wl2_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setSnd_wnd (unsigned int snd_wnd_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setState (int state_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
virtual void TCPStatusInfo::setStateName (const char * stateName_var) [virtual]
Referenced by tcp_old::TCPConnection::process_STATUS(), and TCPConnection::process_STATUS().
Member Data Documentation
bool TCPStatusInfo::fin_ack_rcvd_var [protected]
Definition at line 362 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::irs_var [protected]
Definition at line 361 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::iss_var [protected]
Definition at line 357 of file TCPCommand_m.h.
::IPvXAddress TCPStatusInfo::localAddr_var [protected]
Definition at line 345 of file TCPCommand_m.h.
int TCPStatusInfo::localPort_var [protected]
Definition at line 347 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::rcv_nxt_var [protected]
Definition at line 358 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::rcv_up_var [protected]
Definition at line 360 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::rcv_wnd_var [protected]
Definition at line 359 of file TCPCommand_m.h.
::IPvXAddress TCPStatusInfo::remoteAddr_var [protected]
Definition at line 346 of file TCPCommand_m.h.
int TCPStatusInfo::remotePort_var [protected]
Definition at line 348 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_max_var [protected]
Definition at line 352 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_mss_var [protected]
Definition at line 349 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_nxt_var [protected]
Definition at line 351 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_una_var [protected]
Definition at line 350 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_up_var [protected]
Definition at line 354 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_wl1_var [protected]
Definition at line 355 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_wl2_var [protected]
Definition at line 356 of file TCPCommand_m.h.
unsigned int TCPStatusInfo::snd_wnd_var [protected]
Definition at line 353 of file TCPCommand_m.h.
int TCPStatusInfo::state_var [protected]
Definition at line 343 of file TCPCommand_m.h.
opp_string TCPStatusInfo::stateName_var [protected]
Definition at line 344 of file TCPCommand_m.h.
The documentation for this class was generated from the following file:
TCPCommand_m.h