INET Framework for OMNeT++/OMNEST: Ieee80211BeaconFrameBody Class Reference
Ieee80211BeaconFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211BeaconFrameBody ()
Ieee80211BeaconFrameBody (const Ieee80211BeaconFrameBody &other)
virtual ~Ieee80211BeaconFrameBody ()
Ieee80211BeaconFrameBody & operator= (const Ieee80211BeaconFrameBody &other)
virtual Ieee80211BeaconFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getSSID () const
virtual void setSSID (const char *SSID_var)
virtual
Ieee80211SupportedRatesElement & getSupportedRates ()
virtual const
Ieee80211SupportedRatesElement & getSupportedRates () const
virtual void setSupportedRates (const Ieee80211SupportedRatesElement &supportedRates_var)
virtual simtime_t getBeaconInterval () const
virtual void setBeaconInterval (simtime_t beaconInterval_var)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber_var)
virtual
Ieee80211HandoverParameters & getHandoverParameters ()
virtual const
Ieee80211HandoverParameters & getHandoverParameters () const
virtual void setHandoverParameters (const Ieee80211HandoverParameters &handoverParameters_var)
Protected Member Functions
bool operator== (const Ieee80211BeaconFrameBody &)
Protected Attributes
opp_string SSID_var
::Ieee80211SupportedRatesElement supportedRates_var
simtime_t beaconInterval_var
int channelNumber_var
::Ieee80211HandoverParameters handoverParameters_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211BeaconFrameBody extends Ieee80211FrameBody
 {
     bodyLength = 50;
     string SSID;
     Ieee80211SupportedRatesElement supportedRates;
     simtime_t beaconInterval;
     int channelNumber;
     Ieee80211HandoverParameters handoverParameters;
 }
Definition at line 483 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211BeaconFrameBody::Ieee80211BeaconFrameBody ()
Referenced by dup().
Ieee80211BeaconFrameBody::Ieee80211BeaconFrameBody (const Ieee80211BeaconFrameBody & other)
virtual Ieee80211BeaconFrameBody::~Ieee80211BeaconFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211BeaconFrameBody* Ieee80211BeaconFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ProbeResponseFrameBody.
Definition at line 500 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211BeaconFrameBody(*this);}
virtual simtime_t Ieee80211BeaconFrameBody::getBeaconInterval () const [virtual]
Referenced by Ieee80211MgmtSTA::storeAPInfo().
virtual int Ieee80211BeaconFrameBody::getChannelNumber () const [virtual]
Referenced by Ieee80211MgmtSTA::storeAPInfo().
virtual const Ieee80211HandoverParameters& Ieee80211BeaconFrameBody::getHandoverParameters () const [inline, virtual]
Definition at line 515 of file Ieee80211MgmtFrames_m.h.
Referenced by getHandoverParameters().
{return const_cast<Ieee80211BeaconFrameBody*>(this)->getHandoverParameters();}
virtual Ieee80211HandoverParameters& Ieee80211BeaconFrameBody::getHandoverParameters () [virtual]
virtual const char* Ieee80211BeaconFrameBody::getSSID () const [virtual]
Referenced by Ieee80211MgmtSTA::storeAPInfo().
virtual const Ieee80211SupportedRatesElement& Ieee80211BeaconFrameBody::getSupportedRates () const [inline, virtual]
Definition at line 508 of file Ieee80211MgmtFrames_m.h.
Referenced by getSupportedRates().
{return const_cast<Ieee80211BeaconFrameBody*>(this)->getSupportedRates();}
virtual Ieee80211SupportedRatesElement& Ieee80211BeaconFrameBody::getSupportedRates () [virtual]
Referenced by Ieee80211MgmtSTA::storeAPInfo().
Ieee80211BeaconFrameBody& Ieee80211BeaconFrameBody::operator= (const Ieee80211BeaconFrameBody & other)
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ProbeResponseFrameBody.
bool Ieee80211BeaconFrameBody::operator== (const Ieee80211BeaconFrameBody &) [protected]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ProbeResponseFrameBody.
virtual void Ieee80211BeaconFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ProbeResponseFrameBody.
Referenced by doPacking().
virtual void Ieee80211BeaconFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ProbeResponseFrameBody.
Referenced by doUnpacking().
virtual void Ieee80211BeaconFrameBody::setBeaconInterval (simtime_t beaconInterval_var) [virtual]
Referenced by Ieee80211MgmtAP::handleProbeRequestFrame(), and Ieee80211MgmtAP::sendBeacon().
virtual void Ieee80211BeaconFrameBody::setChannelNumber (int channelNumber_var) [virtual]
Referenced by Ieee80211MgmtAP::handleProbeRequestFrame(), and Ieee80211MgmtAP::sendBeacon().
virtual void Ieee80211BeaconFrameBody::setHandoverParameters (const Ieee80211HandoverParameters & handoverParameters_var) [virtual]
virtual void Ieee80211BeaconFrameBody::setSSID (const char * SSID_var) [virtual]
Referenced by Ieee80211MgmtAP::handleProbeRequestFrame(), and Ieee80211MgmtAP::sendBeacon().
virtual void Ieee80211BeaconFrameBody::setSupportedRates (const Ieee80211SupportedRatesElement & supportedRates_var) [virtual]
Referenced by Ieee80211MgmtAP::handleProbeRequestFrame(), and Ieee80211MgmtAP::sendBeacon().
Member Data Documentation
simtime_t Ieee80211BeaconFrameBody::beaconInterval_var [protected]
Definition at line 488 of file Ieee80211MgmtFrames_m.h.
int Ieee80211BeaconFrameBody::channelNumber_var [protected]
Definition at line 489 of file Ieee80211MgmtFrames_m.h.
::Ieee80211HandoverParameters Ieee80211BeaconFrameBody::handoverParameters_var [protected]
Definition at line 490 of file Ieee80211MgmtFrames_m.h.
opp_string Ieee80211BeaconFrameBody::SSID_var [protected]
Definition at line 486 of file Ieee80211MgmtFrames_m.h.
::Ieee80211SupportedRatesElement Ieee80211BeaconFrameBody::supportedRates_var [protected]
Definition at line 487 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h