INET Framework for OMNeT++/OMNEST: Ieee80211Prim_AuthenticateConfirm Class Reference
Ieee80211Prim_AuthenticateConfirm Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_AuthenticateConfirm ()
Ieee80211Prim_AuthenticateConfirm (const Ieee80211Prim_AuthenticateConfirm &other)
virtual ~Ieee80211Prim_AuthenticateConfirm ()
Ieee80211Prim_AuthenticateConfirm & operator= (const Ieee80211Prim_AuthenticateConfirm &other)
virtual
Ieee80211Prim_AuthenticateConfirm * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getAddress ()
virtual const MACAddress & getAddress () const
virtual void setAddress (const MACAddress &address_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_AuthenticateConfirm &)
Protected Attributes
::MACAddress address_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_AuthenticateConfirm extends Ieee80211PrimConfirm
 {
     MACAddress address;
 }
Definition at line 384 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_AuthenticateConfirm::Ieee80211Prim_AuthenticateConfirm ()
Referenced by dup().
Ieee80211Prim_AuthenticateConfirm::Ieee80211Prim_AuthenticateConfirm (const Ieee80211Prim_AuthenticateConfirm & other)
virtual Ieee80211Prim_AuthenticateConfirm::~Ieee80211Prim_AuthenticateConfirm () [virtual]
Member Function Documentation
virtual Ieee80211Prim_AuthenticateConfirm* Ieee80211Prim_AuthenticateConfirm::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimConfirm.
Definition at line 397 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_AuthenticateConfirm(*this);}
virtual const MACAddress& Ieee80211Prim_AuthenticateConfirm::getAddress () const [inline, virtual]
Definition at line 403 of file Ieee80211Primitives_m.h.
Referenced by getAddress().
{return const_cast<Ieee80211Prim_AuthenticateConfirm*>(this)->getAddress();}
virtual MACAddress& Ieee80211Prim_AuthenticateConfirm::getAddress () [virtual]
Referenced by Ieee80211AgentSTA::processAuthenticateConfirm().
Ieee80211Prim_AuthenticateConfirm& Ieee80211Prim_AuthenticateConfirm::operator= (const Ieee80211Prim_AuthenticateConfirm & other)
Reimplemented from Ieee80211PrimConfirm.
bool Ieee80211Prim_AuthenticateConfirm::operator== (const Ieee80211Prim_AuthenticateConfirm &) [protected]
Reimplemented from Ieee80211PrimConfirm.
virtual void Ieee80211Prim_AuthenticateConfirm::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimConfirm.
Referenced by doPacking().
virtual void Ieee80211Prim_AuthenticateConfirm::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimConfirm.
Referenced by doUnpacking().
virtual void Ieee80211Prim_AuthenticateConfirm::setAddress (const MACAddress & address_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendAuthenticationConfirm().
Member Data Documentation
::MACAddress Ieee80211Prim_AuthenticateConfirm::address_var [protected]
Definition at line 387 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h