INET Framework for OMNeT++/OMNEST: LDPLabelMapping Class Reference
LDPLabelMapping Class Reference
#include <LDPPacket_m.h>
Public Member Functions
LDPLabelMapping (const char *name=NULL, int kind=0)
LDPLabelMapping (const LDPLabelMapping &other)
virtual ~LDPLabelMapping ()
LDPLabelMapping & operator= (const LDPLabelMapping &other)
virtual LDPLabelMapping * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual FEC_TLV & getFec ()
virtual const FEC_TLV & getFec () const
virtual void setFec (const FEC_TLV &fec_var)
virtual int getLabel () const
virtual void setLabel (int label_var)
Protected Member Functions
bool operator== (const LDPLabelMapping &)
Protected Attributes
::FEC_TLV fec_var
int label_var
Detailed Description
Class generated from networklayer/ldp/LDPPacket.msg by opp_msgc.
 packet LDPLabelMapping extends LDPPacket
 {
     FEC_TLV fec;
     int label;
 }
Definition at line 145 of file LDPPacket_m.h.
Constructor & Destructor Documentation
LDPLabelMapping::LDPLabelMapping (const char * name = NULL, int kind = 0)
Referenced by dup().
LDPLabelMapping::LDPLabelMapping (const LDPLabelMapping & other)
virtual LDPLabelMapping::~LDPLabelMapping () [virtual]
Member Function Documentation
virtual LDPLabelMapping* LDPLabelMapping::dup () const [inline, virtual]
Reimplemented from LDPPacket.
Definition at line 159 of file LDPPacket_m.h.
{return new LDPLabelMapping(*this);}
virtual const FEC_TLV& LDPLabelMapping::getFec () const [inline, virtual]
Definition at line 165 of file LDPPacket_m.h.
Referenced by getFec().
{return const_cast<LDPLabelMapping*>(this)->getFec();}
virtual FEC_TLV& LDPLabelMapping::getFec () [virtual]
Referenced by LDP::processLABEL_MAPPING(), LDP::processLABEL_RELEASE(), and LDP::processLABEL_WITHDRAW().
virtual int LDPLabelMapping::getLabel () const [virtual]
Referenced by LDP::processLABEL_MAPPING(), LDP::processLABEL_RELEASE(), and LDP::processLABEL_WITHDRAW().
LDPLabelMapping& LDPLabelMapping::operator= (const LDPLabelMapping & other)
Reimplemented from LDPPacket.
bool LDPLabelMapping::operator== (const LDPLabelMapping &) [protected]
Reimplemented from LDPPacket.
virtual void LDPLabelMapping::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doPacking().
virtual void LDPLabelMapping::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doUnpacking().
virtual void LDPLabelMapping::setFec (const FEC_TLV & fec_var) [virtual]
Referenced by LDP::sendMapping().
virtual void LDPLabelMapping::setLabel (int label_var) [virtual]
Referenced by LDP::sendMapping().
Member Data Documentation
::FEC_TLV LDPLabelMapping::fec_var [protected]
Definition at line 148 of file LDPPacket_m.h.
int LDPLabelMapping::label_var [protected]
Definition at line 149 of file LDPPacket_m.h.
The documentation for this class was generated from the following file:
LDPPacket_m.h