INET Framework for OMNeT++/OMNEST: Ieee80211ProbeRequestFrame Class Reference
Ieee80211ProbeRequestFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ProbeRequestFrame (const char *name=NULL, int kind=0)
Ieee80211ProbeRequestFrame (const Ieee80211ProbeRequestFrame &other)
virtual ~Ieee80211ProbeRequestFrame ()
Ieee80211ProbeRequestFrame & operator= (const Ieee80211ProbeRequestFrame &other)
virtual
Ieee80211ProbeRequestFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211ProbeRequestFrameBody & getBody ()
virtual const
Ieee80211ProbeRequestFrameBody & getBody () const
virtual void setBody (const Ieee80211ProbeRequestFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211ProbeRequestFrame &)
Protected Attributes
::Ieee80211ProbeRequestFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211ProbeRequestFrame extends Ieee80211ManagementFrame
 {
     type = ST_PROBEREQUEST;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211ProbeRequestFrameBody body;
 }
Definition at line 674 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ProbeRequestFrame::Ieee80211ProbeRequestFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211ProbeRequestFrame::Ieee80211ProbeRequestFrame (const Ieee80211ProbeRequestFrame & other)
virtual Ieee80211ProbeRequestFrame::~Ieee80211ProbeRequestFrame () [virtual]
Member Function Documentation
virtual Ieee80211ProbeRequestFrame* Ieee80211ProbeRequestFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 687 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ProbeRequestFrame(*this);}
virtual const Ieee80211ProbeRequestFrameBody& Ieee80211ProbeRequestFrame::getBody () const [inline, virtual]
Definition at line 693 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211ProbeRequestFrame*>(this)->getBody();}
virtual Ieee80211ProbeRequestFrameBody& Ieee80211ProbeRequestFrame::getBody () [virtual]
Referenced by Ieee80211MgmtAP::handleProbeRequestFrame(), and Ieee80211MgmtSTA::sendProbeRequest().
Ieee80211ProbeRequestFrame& Ieee80211ProbeRequestFrame::operator= (const Ieee80211ProbeRequestFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211ProbeRequestFrame::operator== (const Ieee80211ProbeRequestFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211ProbeRequestFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211ProbeRequestFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211ProbeRequestFrame::setBody (const Ieee80211ProbeRequestFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211ProbeRequestFrameBody Ieee80211ProbeRequestFrame::body_var [protected]
Definition at line 677 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h