INET Framework for OMNeT++/OMNEST: Ieee80211Prim_AuthenticateRequest Class Reference
Ieee80211Prim_AuthenticateRequest Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_AuthenticateRequest ()
Ieee80211Prim_AuthenticateRequest (const Ieee80211Prim_AuthenticateRequest &other)
virtual ~Ieee80211Prim_AuthenticateRequest ()
Ieee80211Prim_AuthenticateRequest & operator= (const Ieee80211Prim_AuthenticateRequest &other)
virtual
Ieee80211Prim_AuthenticateRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getAddress ()
virtual const MACAddress & getAddress () const
virtual void setAddress (const MACAddress &address_var)
virtual simtime_t getTimeout () const
virtual void setTimeout (simtime_t timeout_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_AuthenticateRequest &)
Protected Attributes
::MACAddress address_var
simtime_t timeout_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_AuthenticateRequest extends Ieee80211PrimRequest
 {
     MACAddress address;
     simtime_t timeout;
 }
Definition at line 346 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_AuthenticateRequest::Ieee80211Prim_AuthenticateRequest ()
Referenced by dup().
Ieee80211Prim_AuthenticateRequest::Ieee80211Prim_AuthenticateRequest (const Ieee80211Prim_AuthenticateRequest & other)
virtual Ieee80211Prim_AuthenticateRequest::~Ieee80211Prim_AuthenticateRequest () [virtual]
Member Function Documentation
virtual Ieee80211Prim_AuthenticateRequest* Ieee80211Prim_AuthenticateRequest::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimRequest.
Definition at line 360 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_AuthenticateRequest(*this);}
virtual const MACAddress& Ieee80211Prim_AuthenticateRequest::getAddress () const [inline, virtual]
Definition at line 366 of file Ieee80211Primitives_m.h.
Referenced by getAddress().
{return const_cast<Ieee80211Prim_AuthenticateRequest*>(this)->getAddress();}
virtual MACAddress& Ieee80211Prim_AuthenticateRequest::getAddress () [virtual]
Referenced by Ieee80211MgmtSTA::processAuthenticateCommand().
virtual simtime_t Ieee80211Prim_AuthenticateRequest::getTimeout () const [virtual]
Referenced by Ieee80211MgmtSTA::processAuthenticateCommand().
Ieee80211Prim_AuthenticateRequest& Ieee80211Prim_AuthenticateRequest::operator= (const Ieee80211Prim_AuthenticateRequest & other)
Reimplemented from Ieee80211PrimRequest.
bool Ieee80211Prim_AuthenticateRequest::operator== (const Ieee80211Prim_AuthenticateRequest &) [protected]
Reimplemented from Ieee80211PrimRequest.
virtual void Ieee80211Prim_AuthenticateRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doPacking().
virtual void Ieee80211Prim_AuthenticateRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doUnpacking().
virtual void Ieee80211Prim_AuthenticateRequest::setAddress (const MACAddress & address_var) [virtual]
Referenced by Ieee80211AgentSTA::sendAuthenticateRequest().
virtual void Ieee80211Prim_AuthenticateRequest::setTimeout (simtime_t timeout_var) [virtual]
Referenced by Ieee80211AgentSTA::sendAuthenticateRequest().
Member Data Documentation
::MACAddress Ieee80211Prim_AuthenticateRequest::address_var [protected]
Definition at line 349 of file Ieee80211Primitives_m.h.
simtime_t Ieee80211Prim_AuthenticateRequest::timeout_var [protected]
Definition at line 350 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h