INET Framework for OMNeT++/OMNEST: RSVPPacket Class Reference
RSVPPacket Class Reference
#include <RSVPPacket.h>
Public Member Functions
RSVPPacket (const char *name=NULL, int kind=0)
RSVPPacket (const RSVPPacket &other)
RSVPPacket & operator= (const RSVPPacket &other)
virtual RSVPPacket * dup () const
IPAddress getDestAddress ()
int getTunnelId ()
int getExTunnelId ()
int getSetupPri ()
int getHoldingPri ()
bool isInSession (SessionObj_t *s)
Detailed Description
RSVP message common part.
This class adds convenience get() and set() methods to the generated base class, but no extra data.
Definition at line 29 of file RSVPPacket.h.
Constructor & Destructor Documentation
RSVPPacket::RSVPPacket (const char * name = NULL, int kind = 0) [inline]
Definition at line 32 of file RSVPPacket.h.
Referenced by dup().
: RSVPPacket_Base(name,RSVP_TRAFFIC) { this->rsvpKind_var = kind; }
RSVPPacket::RSVPPacket (const RSVPPacket & other) [inline]
Definition at line 33 of file RSVPPacket.h.
: RSVPPacket_Base(other.getName()) {operator=(other);}
Member Function Documentation
virtual RSVPPacket* RSVPPacket::dup () const [inline, virtual]
Reimplemented from RSVPPacket_Base.
Reimplemented in RSVPPathMsg, RSVPPathTear, RSVPPathError, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg, RSVPResvTear, RSVPResvError, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Definition at line 35 of file RSVPPacket.h.
{return new RSVPPacket(*this);}
IPAddress RSVPPacket::getDestAddress () [inline]
Definition at line 37 of file RSVPPacket.h.
Referenced by RSVP::createPSB().
{return getSession().DestAddress;}
int RSVPPacket::getExTunnelId () [inline]
Definition at line 39 of file RSVPPacket.h.
{return getSession().Extended_Tunnel_Id;}
int RSVPPacket::getHoldingPri () [inline]
Definition at line 41 of file RSVPPacket.h.
{return getSession().holdingPri;}
int RSVPPacket::getSetupPri () [inline]
Definition at line 40 of file RSVPPacket.h.
{return getSession().setupPri;}
int RSVPPacket::getTunnelId () [inline]
Definition at line 38 of file RSVPPacket.h.
{return getSession().Tunnel_Id;}
bool RSVPPacket::isInSession (SessionObj_t * s) [inline]
Definition at line 42 of file RSVPPacket.h.
Referenced by RSVP::processResvMsg().
{
        return getSession().DestAddress==s->DestAddress &&
               getSession().Tunnel_Id==s->Tunnel_Id &&
               getSession().Extended_Tunnel_Id==s->Extended_Tunnel_Id;
    }
RSVPPacket& RSVPPacket::operator= (const RSVPPacket & other) [inline]
Reimplemented from RSVPPacket_Base.
Reimplemented in RSVPPathMsg, RSVPPathTear, RSVPPathError, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg, RSVPResvTear, RSVPResvError, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Definition at line 34 of file RSVPPacket.h.
Referenced by RSVPPacket().
{RSVPPacket_Base::operator=(other); return *this;}
The documentation for this class was generated from the following file:
RSVPPacket.h