INET Framework for OMNeT++/OMNEST: SCTPHeartbeatAckChunk Class Reference
SCTPHeartbeatAckChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPHeartbeatAckChunk (const char *name=NULL, int kind=0)
SCTPHeartbeatAckChunk (const SCTPHeartbeatAckChunk &other)
virtual ~SCTPHeartbeatAckChunk ()
SCTPHeartbeatAckChunk & operator= (const SCTPHeartbeatAckChunk &other)
virtual SCTPHeartbeatAckChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual simtime_t getTimeField () const
virtual void setTimeField (simtime_t timeField_var)
virtual void setInfoArraySize (unsigned int size)
virtual unsigned int getInfoArraySize () const
virtual char getInfo (unsigned int k) const
virtual void setInfo (unsigned int k, char info_var)
Protected Member Functions
bool operator== (const SCTPHeartbeatAckChunk &)
Protected Attributes
::IPvXAddress remoteAddr_var
simtime_t timeField_var
char * info_var
unsigned int info_arraysize
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPHeartbeatAckChunk extends SCTPChunk
 {
      IPvXAddress remoteAddr;
      simtime_t timeField;
      char info[];
 }
Definition at line 847 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPHeartbeatAckChunk::SCTPHeartbeatAckChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPHeartbeatAckChunk::SCTPHeartbeatAckChunk (const SCTPHeartbeatAckChunk & other)
virtual SCTPHeartbeatAckChunk::~SCTPHeartbeatAckChunk () [virtual]
Member Function Documentation
virtual SCTPHeartbeatAckChunk* SCTPHeartbeatAckChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 863 of file SCTPMessage_m.h.
{return new SCTPHeartbeatAckChunk(*this);}
virtual char SCTPHeartbeatAckChunk::getInfo (unsigned int k) const [virtual]
virtual unsigned int SCTPHeartbeatAckChunk::getInfoArraySize () const [virtual]
virtual const IPvXAddress& SCTPHeartbeatAckChunk::getRemoteAddr () const [inline, virtual]
Definition at line 869 of file SCTPMessage_m.h.
Referenced by getRemoteAddr().
{return const_cast<SCTPHeartbeatAckChunk*>(this)->getRemoteAddr();}
virtual IPvXAddress& SCTPHeartbeatAckChunk::getRemoteAddr () [virtual]
Referenced by SCTPAssociation::processHeartbeatAckArrived().
virtual simtime_t SCTPHeartbeatAckChunk::getTimeField () const [virtual]
Referenced by SCTPAssociation::processHeartbeatAckArrived().
SCTPHeartbeatAckChunk& SCTPHeartbeatAckChunk::operator= (const SCTPHeartbeatAckChunk & other)
Reimplemented from SCTPChunk.
bool SCTPHeartbeatAckChunk::operator== (const SCTPHeartbeatAckChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPHeartbeatAckChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPHeartbeatAckChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPHeartbeatAckChunk::setInfo (unsigned int k, char info_var) [virtual]
Referenced by SCTPAssociation::sendHeartbeatAck().
virtual void SCTPHeartbeatAckChunk::setInfoArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendHeartbeatAck().
virtual void SCTPHeartbeatAckChunk::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Referenced by SCTPAssociation::sendHeartbeatAck().
virtual void SCTPHeartbeatAckChunk::setTimeField (simtime_t timeField_var) [virtual]
Referenced by SCTPAssociation::sendHeartbeatAck().
Member Data Documentation
unsigned int SCTPHeartbeatAckChunk::info_arraysize [protected]
Definition at line 853 of file SCTPMessage_m.h.
char* SCTPHeartbeatAckChunk::info_var [protected]
Definition at line 852 of file SCTPMessage_m.h.
::IPvXAddress SCTPHeartbeatAckChunk::remoteAddr_var [protected]
Definition at line 850 of file SCTPMessage_m.h.
simtime_t SCTPHeartbeatAckChunk::timeField_var [protected]
Definition at line 851 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h