INET Framework for OMNeT++/OMNEST: Ieee80211DisassociationFrame Class Reference
Ieee80211DisassociationFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211DisassociationFrame (const char *name=NULL, int kind=0)
Ieee80211DisassociationFrame (const Ieee80211DisassociationFrame &other)
virtual ~Ieee80211DisassociationFrame ()
Ieee80211DisassociationFrame & operator= (const Ieee80211DisassociationFrame &other)
virtual
Ieee80211DisassociationFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211DisassociationFrameBody & getBody ()
virtual const
Ieee80211DisassociationFrameBody & getBody () const
virtual void setBody (const Ieee80211DisassociationFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211DisassociationFrame &)
Protected Attributes
::Ieee80211DisassociationFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211DisassociationFrame extends Ieee80211ManagementFrame
 {
     type = ST_DISASSOCIATION;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211DisassociationFrameBody body;
 }
Definition at line 637 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211DisassociationFrame::Ieee80211DisassociationFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211DisassociationFrame::Ieee80211DisassociationFrame (const Ieee80211DisassociationFrame & other)
virtual Ieee80211DisassociationFrame::~Ieee80211DisassociationFrame () [virtual]
Member Function Documentation
virtual Ieee80211DisassociationFrame* Ieee80211DisassociationFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 650 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211DisassociationFrame(*this);}
virtual const Ieee80211DisassociationFrameBody& Ieee80211DisassociationFrame::getBody () const [inline, virtual]
Definition at line 656 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211DisassociationFrame*>(this)->getBody();}
virtual Ieee80211DisassociationFrameBody& Ieee80211DisassociationFrame::getBody () [virtual]
Referenced by Ieee80211MgmtSTA::processDisassociateCommand().
Ieee80211DisassociationFrame& Ieee80211DisassociationFrame::operator= (const Ieee80211DisassociationFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211DisassociationFrame::operator== (const Ieee80211DisassociationFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211DisassociationFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211DisassociationFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211DisassociationFrame::setBody (const Ieee80211DisassociationFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211DisassociationFrameBody Ieee80211DisassociationFrame::body_var [protected]
Definition at line 640 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h