INET Framework for OMNeT++/OMNEST: Ieee80211ProbeRequestFrameBody Class Reference
Ieee80211ProbeRequestFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ProbeRequestFrameBody ()
Ieee80211ProbeRequestFrameBody (const Ieee80211ProbeRequestFrameBody &other)
virtual ~Ieee80211ProbeRequestFrameBody ()
Ieee80211ProbeRequestFrameBody & operator= (const Ieee80211ProbeRequestFrameBody &other)
virtual
Ieee80211ProbeRequestFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getSSID () const
virtual void setSSID (const char *SSID_var)
virtual
Ieee80211SupportedRatesElement & getSupportedRates ()
virtual const
Ieee80211SupportedRatesElement & getSupportedRates () const
virtual void setSupportedRates (const Ieee80211SupportedRatesElement &supportedRates_var)
Protected Member Functions
bool operator== (const Ieee80211ProbeRequestFrameBody &)
Protected Attributes
opp_string SSID_var
::Ieee80211SupportedRatesElement supportedRates_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211ProbeRequestFrameBody extends Ieee80211FrameBody
 {
     bodyLength = 12;
     string SSID;
     Ieee80211SupportedRatesElement supportedRates;
 }
Definition at line 290 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ProbeRequestFrameBody::Ieee80211ProbeRequestFrameBody ()
Referenced by dup().
Ieee80211ProbeRequestFrameBody::Ieee80211ProbeRequestFrameBody (const Ieee80211ProbeRequestFrameBody & other)
virtual Ieee80211ProbeRequestFrameBody::~Ieee80211ProbeRequestFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211ProbeRequestFrameBody* Ieee80211ProbeRequestFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211FrameBody.
Definition at line 304 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ProbeRequestFrameBody(*this);}
virtual const char* Ieee80211ProbeRequestFrameBody::getSSID () const [virtual]
Referenced by Ieee80211MgmtAP::handleProbeRequestFrame().
virtual const Ieee80211SupportedRatesElement& Ieee80211ProbeRequestFrameBody::getSupportedRates () const [inline, virtual]
Definition at line 312 of file Ieee80211MgmtFrames_m.h.
Referenced by getSupportedRates().
{return const_cast<Ieee80211ProbeRequestFrameBody*>(this)->getSupportedRates();}
virtual Ieee80211SupportedRatesElement& Ieee80211ProbeRequestFrameBody::getSupportedRates () [virtual]
Ieee80211ProbeRequestFrameBody& Ieee80211ProbeRequestFrameBody::operator= (const Ieee80211ProbeRequestFrameBody & other)
Reimplemented from Ieee80211FrameBody.
bool Ieee80211ProbeRequestFrameBody::operator== (const Ieee80211ProbeRequestFrameBody &) [protected]
Reimplemented from Ieee80211FrameBody.
virtual void Ieee80211ProbeRequestFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doPacking().
virtual void Ieee80211ProbeRequestFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doUnpacking().
virtual void Ieee80211ProbeRequestFrameBody::setSSID (const char * SSID_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendProbeRequest().
virtual void Ieee80211ProbeRequestFrameBody::setSupportedRates (const Ieee80211SupportedRatesElement & supportedRates_var) [virtual]
Member Data Documentation
opp_string Ieee80211ProbeRequestFrameBody::SSID_var [protected]
Definition at line 293 of file Ieee80211MgmtFrames_m.h.
::Ieee80211SupportedRatesElement Ieee80211ProbeRequestFrameBody::supportedRates_var [protected]
Definition at line 294 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h