INET Framework for OMNeT++/OMNEST: PhyControlInfo Class Reference
PhyControlInfo Class Reference
#include <PhyControlInfo_m.h>
Public Member Functions
PhyControlInfo ()
PhyControlInfo (const PhyControlInfo &other)
virtual ~PhyControlInfo ()
PhyControlInfo & operator= (const PhyControlInfo &other)
virtual PhyControlInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber_var)
virtual double getBitrate () const
virtual void setBitrate (double bitrate_var)
Protected Member Functions
bool operator== (const PhyControlInfo &)
Protected Attributes
int channelNumber_var
double bitrate_var
Detailed Description
Class generated from linklayer/contract/PhyControlInfo.msg by opp_msgc.
 class PhyControlInfo
 {
     int channelNumber = -1;
     double bitrate = -1;
 }
Definition at line 47 of file PhyControlInfo_m.h.
Constructor & Destructor Documentation
PhyControlInfo::PhyControlInfo ()
Referenced by dup().
PhyControlInfo::PhyControlInfo (const PhyControlInfo & other)
virtual PhyControlInfo::~PhyControlInfo () [virtual]
Member Function Documentation
virtual PhyControlInfo* PhyControlInfo::dup () const [inline, virtual]
Definition at line 61 of file PhyControlInfo_m.h.
{return new PhyControlInfo(*this);}
virtual double PhyControlInfo::getBitrate () const [virtual]
Referenced by AbstractRadio::encapsulatePacket(), SnrEval::handleCommand(), Ieee80211Mac::handleCommand(), and AbstractRadio::handleCommand().
virtual int PhyControlInfo::getChannelNumber () const [virtual]
Referenced by AbstractRadio::encapsulatePacket(), SnrEval::handleCommand(), Ieee80211Mac::handleCommand(), and AbstractRadio::handleCommand().
PhyControlInfo& PhyControlInfo::operator= (const PhyControlInfo & other)
bool PhyControlInfo::operator== (const PhyControlInfo &) [protected]
virtual void PhyControlInfo::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void PhyControlInfo::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void PhyControlInfo::setBitrate (double bitrate_var) [virtual]
virtual void PhyControlInfo::setChannelNumber (int channelNumber_var) [virtual]
Referenced by Ieee80211MgmtSTA::changeChannel().
Member Data Documentation
double PhyControlInfo::bitrate_var [protected]
Definition at line 51 of file PhyControlInfo_m.h.
int PhyControlInfo::channelNumber_var [protected]
Definition at line 50 of file PhyControlInfo_m.h.
The documentation for this class was generated from the following file:
PhyControlInfo_m.h