INET Framework for OMNeT++/OMNEST: Ieee80211Prim_AssociateConfirm Class Reference
Ieee80211Prim_AssociateConfirm Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_AssociateConfirm ()
Ieee80211Prim_AssociateConfirm (const Ieee80211Prim_AssociateConfirm &other)
virtual ~Ieee80211Prim_AssociateConfirm ()
Ieee80211Prim_AssociateConfirm & operator= (const Ieee80211Prim_AssociateConfirm &other)
virtual
Ieee80211Prim_AssociateConfirm * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211Prim_AssociateConfirm &)
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_AssociateConfirm extends Ieee80211PrimConfirm
 {
 }
Definition at line 496 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_AssociateConfirm::Ieee80211Prim_AssociateConfirm ()
Referenced by dup().
Ieee80211Prim_AssociateConfirm::Ieee80211Prim_AssociateConfirm (const Ieee80211Prim_AssociateConfirm & other)
virtual Ieee80211Prim_AssociateConfirm::~Ieee80211Prim_AssociateConfirm () [virtual]
Member Function Documentation
virtual Ieee80211Prim_AssociateConfirm* Ieee80211Prim_AssociateConfirm::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimConfirm.
Reimplemented in Ieee80211Prim_ReassociateConfirm.
Definition at line 508 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_AssociateConfirm(*this);}
Ieee80211Prim_AssociateConfirm& Ieee80211Prim_AssociateConfirm::operator= (const Ieee80211Prim_AssociateConfirm & other)
Reimplemented from Ieee80211PrimConfirm.
Reimplemented in Ieee80211Prim_ReassociateConfirm.
bool Ieee80211Prim_AssociateConfirm::operator== (const Ieee80211Prim_AssociateConfirm &) [protected]
Reimplemented from Ieee80211PrimConfirm.
Reimplemented in Ieee80211Prim_ReassociateConfirm.
virtual void Ieee80211Prim_AssociateConfirm::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimConfirm.
Reimplemented in Ieee80211Prim_ReassociateConfirm.
Referenced by doPacking().
virtual void Ieee80211Prim_AssociateConfirm::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimConfirm.
Reimplemented in Ieee80211Prim_ReassociateConfirm.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h