INET Framework for OMNeT++/OMNEST: EthernetIIFrame Class Reference
EthernetIIFrame Class Reference
#include <EtherFrame_m.h>
Public Member Functions
EthernetIIFrame (const char *name=NULL, int kind=0)
EthernetIIFrame (const EthernetIIFrame &other)
virtual ~EthernetIIFrame ()
EthernetIIFrame & operator= (const EthernetIIFrame &other)
virtual EthernetIIFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getEtherType () const
virtual void setEtherType (int etherType_var)
Protected Member Functions
bool operator== (const EthernetIIFrame &)
Protected Attributes
int etherType_var
Detailed Description
Class generated from linklayer/ethernet/EtherFrame.msg by opp_msgc.
 packet EthernetIIFrame extends EtherFrame
 {
     int etherType;
 }
Definition at line 105 of file EtherFrame_m.h.
Constructor & Destructor Documentation
EthernetIIFrame::EthernetIIFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
EthernetIIFrame::EthernetIIFrame (const EthernetIIFrame & other)
virtual EthernetIIFrame::~EthernetIIFrame () [virtual]
Member Function Documentation
virtual EthernetIIFrame* EthernetIIFrame::dup () const [inline, virtual]
Reimplemented from EtherFrame.
Definition at line 118 of file EtherFrame_m.h.
{return new EthernetIIFrame(*this);}
virtual int EthernetIIFrame::getEtherType () const [virtual]
EthernetIIFrame& EthernetIIFrame::operator= (const EthernetIIFrame & other)
Reimplemented from EtherFrame.
bool EthernetIIFrame::operator== (const EthernetIIFrame &) [protected]
Reimplemented from EtherFrame.
virtual void EthernetIIFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doPacking().
virtual void EthernetIIFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doUnpacking().
virtual void EthernetIIFrame::setEtherType (int etherType_var) [virtual]
Member Data Documentation
int EthernetIIFrame::etherType_var [protected]
Definition at line 108 of file EtherFrame_m.h.
The documentation for this class was generated from the following file:
EtherFrame_m.h