INET Framework for OMNeT++/OMNEST: Ieee80211Prim_DisassociateRequest Class Reference
Ieee80211Prim_DisassociateRequest Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_DisassociateRequest ()
Ieee80211Prim_DisassociateRequest (const Ieee80211Prim_DisassociateRequest &other)
virtual ~Ieee80211Prim_DisassociateRequest ()
Ieee80211Prim_DisassociateRequest & operator= (const Ieee80211Prim_DisassociateRequest &other)
virtual
Ieee80211Prim_DisassociateRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getAddress ()
virtual const MACAddress & getAddress () const
virtual void setAddress (const MACAddress &address_var)
virtual int getReasonCode () const
virtual void setReasonCode (int reasonCode_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_DisassociateRequest &)
Protected Attributes
::MACAddress address_var
int reasonCode_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_DisassociateRequest extends Ieee80211PrimRequest
 {
     MACAddress address;
     int reasonCode enum(Ieee80211ReasonCode);
 }
Definition at line 588 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_DisassociateRequest::Ieee80211Prim_DisassociateRequest ()
Referenced by dup().
Ieee80211Prim_DisassociateRequest::Ieee80211Prim_DisassociateRequest (const Ieee80211Prim_DisassociateRequest & other)
virtual Ieee80211Prim_DisassociateRequest::~Ieee80211Prim_DisassociateRequest () [virtual]
Member Function Documentation
virtual Ieee80211Prim_DisassociateRequest* Ieee80211Prim_DisassociateRequest::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimRequest.
Definition at line 602 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_DisassociateRequest(*this);}
virtual const MACAddress& Ieee80211Prim_DisassociateRequest::getAddress () const [inline, virtual]
Definition at line 608 of file Ieee80211Primitives_m.h.
Referenced by getAddress().
{return const_cast<Ieee80211Prim_DisassociateRequest*>(this)->getAddress();}
virtual MACAddress& Ieee80211Prim_DisassociateRequest::getAddress () [virtual]
Referenced by Ieee80211MgmtSTA::processDisassociateCommand().
virtual int Ieee80211Prim_DisassociateRequest::getReasonCode () const [virtual]
Referenced by Ieee80211MgmtSTA::processDisassociateCommand().
Ieee80211Prim_DisassociateRequest& Ieee80211Prim_DisassociateRequest::operator= (const Ieee80211Prim_DisassociateRequest & other)
Reimplemented from Ieee80211PrimRequest.
bool Ieee80211Prim_DisassociateRequest::operator== (const Ieee80211Prim_DisassociateRequest &) [protected]
Reimplemented from Ieee80211PrimRequest.
virtual void Ieee80211Prim_DisassociateRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doPacking().
virtual void Ieee80211Prim_DisassociateRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doUnpacking().
virtual void Ieee80211Prim_DisassociateRequest::setAddress (const MACAddress & address_var) [virtual]
Referenced by Ieee80211AgentSTA::sendDisassociateRequest().
virtual void Ieee80211Prim_DisassociateRequest::setReasonCode (int reasonCode_var) [virtual]
Referenced by Ieee80211AgentSTA::sendDisassociateRequest().
Member Data Documentation
::MACAddress Ieee80211Prim_DisassociateRequest::address_var [protected]
Definition at line 591 of file Ieee80211Primitives_m.h.
int Ieee80211Prim_DisassociateRequest::reasonCode_var [protected]
Definition at line 592 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h