INET Framework for OMNeT++/OMNEST: SCTPInitAckChunk Class Reference
SCTPInitAckChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPInitAckChunk (const char *name=NULL, int kind=0)
SCTPInitAckChunk (const SCTPInitAckChunk &other)
virtual ~SCTPInitAckChunk ()
SCTPInitAckChunk & operator= (const SCTPInitAckChunk &other)
virtual SCTPInitAckChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32 getInitTag () const
virtual void setInitTag (uint32 initTag_var)
virtual uint32 getA_rwnd () const
virtual void setA_rwnd (uint32 a_rwnd_var)
virtual uint16 getNoOutStreams () const
virtual void setNoOutStreams (uint16 noOutStreams_var)
virtual uint16 getNoInStreams () const
virtual void setNoInStreams (uint16 noInStreams_var)
virtual uint32 getInitTSN () const
virtual void setInitTSN (uint32 initTSN_var)
virtual bool getForwardTsn () const
virtual void setForwardTsn (bool forwardTsn_var)
virtual void setAddressesArraySize (unsigned int size)
virtual unsigned int getAddressesArraySize () const
virtual IPvXAddress & getAddresses (unsigned int k)
virtual const IPvXAddress & getAddresses (unsigned int k) const
virtual void setAddresses (unsigned int k, const IPvXAddress &addresses_var)
virtual void setCookieArraySize (unsigned int size)
virtual unsigned int getCookieArraySize () const
virtual char getCookie (unsigned int k) const
virtual void setCookie (unsigned int k, char cookie_var)
virtual void setUnrecognizedParametersArraySize (unsigned int size)
virtual unsigned int getUnrecognizedParametersArraySize () const
virtual uint8 getUnrecognizedParameters (unsigned int k) const
virtual void setUnrecognizedParameters (unsigned int k, uint8 unrecognizedParameters_var)
virtual cPacketPtr & getStateCookie ()
virtual const cPacketPtr & getStateCookie () const
virtual void setStateCookie (const cPacketPtr &stateCookie_var)
Protected Member Functions
bool operator== (const SCTPInitAckChunk &)
Protected Attributes
uint32 initTag_var
uint32 a_rwnd_var
uint16 noOutStreams_var
uint16 noInStreams_var
uint32 initTSN_var
bool forwardTsn_var
::IPvXAddress * addresses_var
unsigned int addresses_arraysize
char * cookie_var
unsigned int cookie_arraysize
uint8 * unrecognizedParameters_var
unsigned int unrecognizedParameters_arraysize
::cPacketPtr stateCookie_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPInitAckChunk extends SCTPChunk
 {
      uint32 initTag;
      uint32 a_rwnd;
      uint16 noOutStreams;
      uint16 noInStreams;
      uint32 initTSN;
      bool forwardTsn;
      IPvXAddress addresses[];
      char cookie[];
      uint8 unrecognizedParameters[];
      cPacketPtr stateCookie;
 }
Definition at line 286 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPInitAckChunk::SCTPInitAckChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPInitAckChunk::SCTPInitAckChunk (const SCTPInitAckChunk & other)
virtual SCTPInitAckChunk::~SCTPInitAckChunk () [virtual]
Member Function Documentation
virtual SCTPInitAckChunk* SCTPInitAckChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 311 of file SCTPMessage_m.h.
{return new SCTPInitAckChunk(*this);}
virtual uint32 SCTPInitAckChunk::getA_rwnd () const [virtual]
Referenced by SCTPAssociation::processInitAckArrived(), and TCPDumper::sctpDump().
virtual const IPvXAddress& SCTPInitAckChunk::getAddresses (unsigned int k) const [inline, virtual]
Definition at line 331 of file SCTPMessage_m.h.
Referenced by getAddresses().
{return const_cast<SCTPInitAckChunk*>(this)->getAddresses(k);}
virtual IPvXAddress& SCTPInitAckChunk::getAddresses (unsigned int k) [virtual]
Referenced by SCTPAssociation::processInitAckArrived(), and TCPDumper::sctpDump().
virtual unsigned int SCTPInitAckChunk::getAddressesArraySize () const [virtual]
Referenced by SCTPAssociation::processInitAckArrived(), and TCPDumper::sctpDump().
virtual char SCTPInitAckChunk::getCookie (unsigned int k) const [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
virtual unsigned int SCTPInitAckChunk::getCookieArraySize () const [virtual]
Referenced by TCPDumper::sctpDump(), SCTPAssociation::sendCookieEcho(), and SCTPAssociation::sendInitAck().
virtual bool SCTPInitAckChunk::getForwardTsn () const [virtual]
virtual uint32 SCTPInitAckChunk::getInitTag () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), SCTPAssociation::processInitAckArrived(), TCPDumper::sctpDump(), and SCTPAssociation::sendInitAck().
virtual uint32 SCTPInitAckChunk::getInitTSN () const [virtual]
Referenced by SCTPAssociation::processInitAckArrived(), TCPDumper::sctpDump(), and SCTPAssociation::sendInitAck().
virtual uint16 SCTPInitAckChunk::getNoInStreams () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), SCTPAssociation::processInitAckArrived(), TCPDumper::sctpDump(), and SCTPAssociation::sendInitAck().
virtual uint16 SCTPInitAckChunk::getNoOutStreams () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), SCTPAssociation::processInitAckArrived(), TCPDumper::sctpDump(), and SCTPAssociation::sendInitAck().
virtual const cPacketPtr& SCTPInitAckChunk::getStateCookie () const [inline, virtual]
Definition at line 342 of file SCTPMessage_m.h.
Referenced by getStateCookie().
{return const_cast<SCTPInitAckChunk*>(this)->getStateCookie();}
virtual cPacketPtr& SCTPInitAckChunk::getStateCookie () [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
virtual uint8 SCTPInitAckChunk::getUnrecognizedParameters (unsigned int k) const [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
virtual unsigned int SCTPInitAckChunk::getUnrecognizedParametersArraySize () const [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
SCTPInitAckChunk& SCTPInitAckChunk::operator= (const SCTPInitAckChunk & other)
Reimplemented from SCTPChunk.
bool SCTPInitAckChunk::operator== (const SCTPInitAckChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPInitAckChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPInitAckChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPInitAckChunk::setA_rwnd (uint32 a_rwnd_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setAddresses (unsigned int k, const IPvXAddress & addresses_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setAddressesArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setCookie (unsigned int k, char cookie_var) [virtual]
virtual void SCTPInitAckChunk::setCookieArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setForwardTsn (bool forwardTsn_var) [virtual]
virtual void SCTPInitAckChunk::setInitTag (uint32 initTag_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setInitTSN (uint32 initTSN_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setNoInStreams (uint16 noInStreams_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setNoOutStreams (uint16 noOutStreams_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setStateCookie (const cPacketPtr & stateCookie_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setUnrecognizedParameters (unsigned int k, uint8 unrecognizedParameters_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPInitAckChunk::setUnrecognizedParametersArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendInitAck().
Member Data Documentation
uint32 SCTPInitAckChunk::a_rwnd_var [protected]
Definition at line 290 of file SCTPMessage_m.h.
unsigned int SCTPInitAckChunk::addresses_arraysize [protected]
Definition at line 296 of file SCTPMessage_m.h.
::IPvXAddress* SCTPInitAckChunk::addresses_var [protected]
Definition at line 295 of file SCTPMessage_m.h.
unsigned int SCTPInitAckChunk::cookie_arraysize [protected]
Definition at line 298 of file SCTPMessage_m.h.
char* SCTPInitAckChunk::cookie_var [protected]
Definition at line 297 of file SCTPMessage_m.h.
bool SCTPInitAckChunk::forwardTsn_var [protected]
Definition at line 294 of file SCTPMessage_m.h.
uint32 SCTPInitAckChunk::initTag_var [protected]
Definition at line 289 of file SCTPMessage_m.h.
uint32 SCTPInitAckChunk::initTSN_var [protected]
Definition at line 293 of file SCTPMessage_m.h.
uint16 SCTPInitAckChunk::noInStreams_var [protected]
Definition at line 292 of file SCTPMessage_m.h.
uint16 SCTPInitAckChunk::noOutStreams_var [protected]
Definition at line 291 of file SCTPMessage_m.h.
::cPacketPtr SCTPInitAckChunk::stateCookie_var [protected]
Definition at line 301 of file SCTPMessage_m.h.
unsigned int SCTPInitAckChunk::unrecognizedParameters_arraysize [protected]
Definition at line 300 of file SCTPMessage_m.h.
uint8* SCTPInitAckChunk::unrecognizedParameters_var [protected]
Definition at line 299 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h