INET Framework for OMNeT++/OMNEST: SCTPCookieEchoChunk Class Reference
SCTPCookieEchoChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPCookieEchoChunk (const char *name=NULL, int kind=0)
SCTPCookieEchoChunk (const SCTPCookieEchoChunk &other)
virtual ~SCTPCookieEchoChunk ()
SCTPCookieEchoChunk & operator= (const SCTPCookieEchoChunk &other)
virtual SCTPCookieEchoChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setCookieArraySize (unsigned int size)
virtual unsigned int getCookieArraySize () const
virtual char getCookie (unsigned int k) const
virtual void setCookie (unsigned int k, char cookie_var)
virtual cPacketPtr & getStateCookie ()
virtual const cPacketPtr & getStateCookie () const
virtual void setStateCookie (const cPacketPtr &stateCookie_var)
virtual void setUnrecognizedParametersArraySize (unsigned int size)
virtual unsigned int getUnrecognizedParametersArraySize () const
virtual uint8 getUnrecognizedParameters (unsigned int k) const
virtual void setUnrecognizedParameters (unsigned int k, uint8 unrecognizedParameters_var)
Protected Member Functions
bool operator== (const SCTPCookieEchoChunk &)
Protected Attributes
char * cookie_var
unsigned int cookie_arraysize
::cPacketPtr stateCookie_var
uint8 * unrecognizedParameters_var
unsigned int unrecognizedParameters_arraysize
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPCookieEchoChunk extends SCTPChunk
 {
      char cookie[];
      cPacketPtr stateCookie;
      uint8 unrecognizedParameters[];
 }
Definition at line 360 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPCookieEchoChunk::SCTPCookieEchoChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPCookieEchoChunk::SCTPCookieEchoChunk (const SCTPCookieEchoChunk & other)
virtual SCTPCookieEchoChunk::~SCTPCookieEchoChunk () [virtual]
Member Function Documentation
virtual SCTPCookieEchoChunk* SCTPCookieEchoChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 377 of file SCTPMessage_m.h.
Referenced by SCTPAssociation::retransmitCookieEcho(), and SCTPAssociation::sendCookieEcho().
{return new SCTPCookieEchoChunk(*this);}
virtual char SCTPCookieEchoChunk::getCookie (unsigned int k) const [virtual]
virtual unsigned int SCTPCookieEchoChunk::getCookieArraySize () const [virtual]
Referenced by SCTPAssociation::processCookieAckArrived(), and SCTPAssociation::retransmitCookieEcho().
virtual const cPacketPtr& SCTPCookieEchoChunk::getStateCookie () const [inline, virtual]
Definition at line 387 of file SCTPMessage_m.h.
Referenced by getStateCookie().
{return const_cast<SCTPCookieEchoChunk*>(this)->getStateCookie();}
virtual cPacketPtr& SCTPCookieEchoChunk::getStateCookie () [virtual]
Referenced by SCTPAssociation::processCookieAckArrived(), SCTPAssociation::processCookieEchoArrived(), and SCTPAssociation::retransmitCookieEcho().
virtual uint8 SCTPCookieEchoChunk::getUnrecognizedParameters (unsigned int k) const [virtual]
virtual unsigned int SCTPCookieEchoChunk::getUnrecognizedParametersArraySize () const [virtual]
SCTPCookieEchoChunk& SCTPCookieEchoChunk::operator= (const SCTPCookieEchoChunk & other)
Reimplemented from SCTPChunk.
bool SCTPCookieEchoChunk::operator== (const SCTPCookieEchoChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPCookieEchoChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPCookieEchoChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPCookieEchoChunk::setCookie (unsigned int k, char cookie_var) [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
virtual void SCTPCookieEchoChunk::setCookieArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
virtual void SCTPCookieEchoChunk::setStateCookie (const cPacketPtr & stateCookie_var) [virtual]
Referenced by SCTPAssociation::retransmitCookieEcho(), and SCTPAssociation::sendCookieEcho().
virtual void SCTPCookieEchoChunk::setUnrecognizedParameters (unsigned int k, uint8 unrecognizedParameters_var) [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
virtual void SCTPCookieEchoChunk::setUnrecognizedParametersArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendCookieEcho().
Member Data Documentation
unsigned int SCTPCookieEchoChunk::cookie_arraysize [protected]
Definition at line 364 of file SCTPMessage_m.h.
char* SCTPCookieEchoChunk::cookie_var [protected]
Definition at line 363 of file SCTPMessage_m.h.
::cPacketPtr SCTPCookieEchoChunk::stateCookie_var [protected]
Definition at line 365 of file SCTPMessage_m.h.
unsigned int SCTPCookieEchoChunk::unrecognizedParameters_arraysize [protected]
Definition at line 367 of file SCTPMessage_m.h.
uint8* SCTPCookieEchoChunk::unrecognizedParameters_var [protected]
Definition at line 366 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h