INET Framework for OMNeT++/OMNEST: IPv6NeighbourAdvertisement Class Reference
IPv6NeighbourAdvertisement Class Reference
#include <IPv6NDMessage_m.h>
Public Member Functions
IPv6NeighbourAdvertisement (const char *name=NULL, int kind=0)
IPv6NeighbourAdvertisement (const IPv6NeighbourAdvertisement &other)
virtual ~IPv6NeighbourAdvertisement ()
IPv6NeighbourAdvertisement & operator= (const IPv6NeighbourAdvertisement &other)
virtual
IPv6NeighbourAdvertisement * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getRouterFlag () const
virtual void setRouterFlag (bool routerFlag_var)
virtual bool getSolicitedFlag () const
virtual void setSolicitedFlag (bool solicitedFlag_var)
virtual bool getOverrideFlag () const
virtual void setOverrideFlag (bool overrideFlag_var)
virtual IPv6Address & getTargetAddress ()
virtual const IPv6Address & getTargetAddress () const
virtual void setTargetAddress (const IPv6Address &targetAddress_var)
virtual MACAddress & getTargetLinkLayerAddress ()
virtual const MACAddress & getTargetLinkLayerAddress () const
virtual void setTargetLinkLayerAddress (const MACAddress &targetLinkLayerAddress_var)
Protected Member Functions
bool operator== (const IPv6NeighbourAdvertisement &)
Protected Attributes
bool routerFlag_var
bool solicitedFlag_var
bool overrideFlag_var
::IPv6Address targetAddress_var
::MACAddress targetLinkLayerAddress_var
Detailed Description
Class generated from networklayer/icmpv6/IPv6NDMessage.msg by opp_msgc.
 packet IPv6NeighbourAdvertisement extends IPv6NDMessage
 {
     bool routerFlag;
     bool solicitedFlag;
     bool overrideFlag;
     IPv6Address targetAddress;
     MACAddress targetLinkLayerAddress;
 }
Definition at line 284 of file IPv6NDMessage_m.h.
Constructor & Destructor Documentation
IPv6NeighbourAdvertisement::IPv6NeighbourAdvertisement (const char * name = NULL, int kind = 0)
Referenced by dup().
IPv6NeighbourAdvertisement::IPv6NeighbourAdvertisement (const IPv6NeighbourAdvertisement & other)
virtual IPv6NeighbourAdvertisement::~IPv6NeighbourAdvertisement () [virtual]
Member Function Documentation
virtual IPv6NeighbourAdvertisement* IPv6NeighbourAdvertisement::dup () const [inline, virtual]
Reimplemented from IPv6NDMessage.
Definition at line 301 of file IPv6NDMessage_m.h.
{return new IPv6NeighbourAdvertisement(*this);}
virtual bool IPv6NeighbourAdvertisement::getOverrideFlag () const [virtual]
Referenced by IPv6NeighbourDiscovery::processNAForOtherNCEStates().
virtual bool IPv6NeighbourAdvertisement::getRouterFlag () const [virtual]
Referenced by IPv6NeighbourDiscovery::processNAForIncompleteNCEState(), and IPv6NeighbourDiscovery::processNAForOtherNCEStates().
virtual bool IPv6NeighbourAdvertisement::getSolicitedFlag () const [virtual]
Referenced by IPv6NeighbourDiscovery::processNAForIncompleteNCEState(), IPv6NeighbourDiscovery::processNAForOtherNCEStates(), and IPv6NeighbourDiscovery::validateNAPacket().
virtual const IPv6Address& IPv6NeighbourAdvertisement::getTargetAddress () const [inline, virtual]
Definition at line 313 of file IPv6NDMessage_m.h.
Referenced by getTargetAddress().
{return const_cast<IPv6NeighbourAdvertisement*>(this)->getTargetAddress();}
virtual IPv6Address& IPv6NeighbourAdvertisement::getTargetAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processNAPacket(), and IPv6NeighbourDiscovery::validateNAPacket().
virtual const MACAddress& IPv6NeighbourAdvertisement::getTargetLinkLayerAddress () const [inline, virtual]
Definition at line 316 of file IPv6NDMessage_m.h.
Referenced by getTargetLinkLayerAddress().
{return const_cast<IPv6NeighbourAdvertisement*>(this)->getTargetLinkLayerAddress();}
virtual MACAddress& IPv6NeighbourAdvertisement::getTargetLinkLayerAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processNAForIncompleteNCEState(), and IPv6NeighbourDiscovery::processNAForOtherNCEStates().
IPv6NeighbourAdvertisement& IPv6NeighbourAdvertisement::operator= (const IPv6NeighbourAdvertisement & other)
Reimplemented from IPv6NDMessage.
bool IPv6NeighbourAdvertisement::operator== (const IPv6NeighbourAdvertisement &) [protected]
Reimplemented from IPv6NDMessage.
virtual void IPv6NeighbourAdvertisement::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doPacking().
virtual void IPv6NeighbourAdvertisement::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doUnpacking().
virtual void IPv6NeighbourAdvertisement::setOverrideFlag (bool overrideFlag_var) [virtual]
Referenced by IPv6NeighbourDiscovery::sendSolicitedNA().
virtual void IPv6NeighbourAdvertisement::setRouterFlag (bool routerFlag_var) [virtual]
Referenced by IPv6NeighbourDiscovery::sendSolicitedNA().
virtual void IPv6NeighbourAdvertisement::setSolicitedFlag (bool solicitedFlag_var) [virtual]
Referenced by IPv6NeighbourDiscovery::sendSolicitedNA().
virtual void IPv6NeighbourAdvertisement::setTargetAddress (const IPv6Address & targetAddress_var) [virtual]
Referenced by IPv6NeighbourDiscovery::sendSolicitedNA().
virtual void IPv6NeighbourAdvertisement::setTargetLinkLayerAddress (const MACAddress & targetLinkLayerAddress_var) [virtual]
Referenced by IPv6NeighbourDiscovery::sendSolicitedNA().
Member Data Documentation
bool IPv6NeighbourAdvertisement::overrideFlag_var [protected]
Definition at line 289 of file IPv6NDMessage_m.h.
bool IPv6NeighbourAdvertisement::routerFlag_var [protected]
Definition at line 287 of file IPv6NDMessage_m.h.
bool IPv6NeighbourAdvertisement::solicitedFlag_var [protected]
Definition at line 288 of file IPv6NDMessage_m.h.
::IPv6Address IPv6NeighbourAdvertisement::targetAddress_var [protected]
Definition at line 290 of file IPv6NDMessage_m.h.
::MACAddress IPv6NeighbourAdvertisement::targetLinkLayerAddress_var [protected]
Definition at line 291 of file IPv6NDMessage_m.h.
The documentation for this class was generated from the following file:
IPv6NDMessage_m.h