INET Framework for OMNeT++/OMNEST: Ieee802Ctrl Class Reference
Ieee802Ctrl Class Reference
#include <Ieee802Ctrl_m.h>
Public Member Functions
Ieee802Ctrl ()
Ieee802Ctrl (const Ieee802Ctrl &other)
virtual ~Ieee802Ctrl ()
Ieee802Ctrl & operator= (const Ieee802Ctrl &other)
virtual Ieee802Ctrl * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getSrc ()
virtual const MACAddress & getSrc () const
virtual void setSrc (const MACAddress &src_var)
virtual MACAddress & getDest ()
virtual const MACAddress & getDest () const
virtual void setDest (const MACAddress &dest_var)
virtual int getEtherType () const
virtual void setEtherType (int etherType_var)
virtual int getSsap () const
virtual void setSsap (int ssap_var)
virtual int getDsap () const
virtual void setDsap (int dsap_var)
virtual int getPauseUnits () const
virtual void setPauseUnits (int pauseUnits_var)
virtual int getInputPort () const
virtual void setInputPort (int inputPort_var)
Protected Member Functions
bool operator== (const Ieee802Ctrl &)
Protected Attributes
::MACAddress src_var
::MACAddress dest_var
int etherType_var
int ssap_var
int dsap_var
int pauseUnits_var
int inputPort_var
Detailed Description
Class generated from linklayer/contract/Ieee802Ctrl.msg by opp_msgc.
 class Ieee802Ctrl
 {
     MACAddress src;
     MACAddress dest;
     int etherType;
     int ssap;
     int dsap;
     int pauseUnits;
     int inputPort;
 }
Definition at line 104 of file Ieee802Ctrl_m.h.
Constructor & Destructor Documentation
Ieee802Ctrl::Ieee802Ctrl ()
Referenced by dup().
Ieee802Ctrl::Ieee802Ctrl (const Ieee802Ctrl & other)
virtual Ieee802Ctrl::~Ieee802Ctrl () [virtual]
Member Function Documentation
virtual Ieee802Ctrl* Ieee802Ctrl::dup () const [inline, virtual]
Definition at line 123 of file Ieee802Ctrl_m.h.
{return new Ieee802Ctrl(*this);}
virtual const MACAddress& Ieee802Ctrl::getDest () const [inline, virtual]
Definition at line 132 of file Ieee802Ctrl_m.h.
Referenced by getDest().
{return const_cast<Ieee802Ctrl*>(this)->getDest();}
virtual MACAddress& Ieee802Ctrl::getDest () [virtual]
Referenced by Mac80211::encapsMsg(), CSMAMacLayer::encapsMsg(), Ieee80211MgmtSTASimplified::encapsulate(), Ieee80211MgmtSTA::encapsulate(), EtherLLC::processPacketFromHigherLayer(), and EtherEncap::processPacketFromHigherLayer().
virtual int Ieee802Ctrl::getDsap () const [virtual]
Referenced by EtherLLC::handleDeregisterSAP(), EtherLLC::handleRegisterSAP(), and EtherLLC::processPacketFromHigherLayer().
virtual int Ieee802Ctrl::getEtherType () const [virtual]
Referenced by EtherEncap::processPacketFromHigherLayer().
virtual int Ieee802Ctrl::getInputPort () const [virtual]
virtual int Ieee802Ctrl::getPauseUnits () const [virtual]
Referenced by EtherLLC::handleSendPause(), and EtherEncap::handleSendPause().
virtual const MACAddress& Ieee802Ctrl::getSrc () const [inline, virtual]
Definition at line 129 of file Ieee802Ctrl_m.h.
Referenced by getSrc().
{return const_cast<Ieee802Ctrl*>(this)->getSrc();}
virtual MACAddress& Ieee802Ctrl::getSrc () [virtual]
Referenced by EtherEncap::processPacketFromHigherLayer().
virtual int Ieee802Ctrl::getSsap () const [virtual]
Referenced by EtherLLC::processPacketFromHigherLayer().
Ieee802Ctrl& Ieee802Ctrl::operator= (const Ieee802Ctrl & other)
bool Ieee802Ctrl::operator== (const Ieee802Ctrl &) [protected]
virtual void Ieee802Ctrl::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void Ieee802Ctrl::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void Ieee802Ctrl::setDest (const MACAddress & dest_var) [virtual]
Referenced by Ieee80211MgmtBase::decapsulate(), EtherLLC::processFrameFromMAC(), EtherEncap::processFrameFromMAC(), IPv6::sendDatagramToOutput(), EtherAppSrv::sendPacket(), EtherAppCli::sendPacket(), and ARP::sendPacketToNIC().
virtual void Ieee802Ctrl::setDsap (int dsap_var) [virtual]
Referenced by EtherLLC::processFrameFromMAC(), EtherAppSrv::registerDSAP(), EtherAppCli::registerDSAP(), EtherAppSrv::sendPacket(), and EtherAppCli::sendPacket().
virtual void Ieee802Ctrl::setEtherType (int etherType_var) [virtual]
virtual void Ieee802Ctrl::setInputPort (int inputPort_var) [virtual]
virtual void Ieee802Ctrl::setPauseUnits (int pauseUnits_var) [virtual]
virtual void Ieee802Ctrl::setSrc (const MACAddress & src_var) [virtual]
Referenced by Ieee80211MgmtBase::decapsulate(), EtherLLC::processFrameFromMAC(), and EtherEncap::processFrameFromMAC().
virtual void Ieee802Ctrl::setSsap (int ssap_var) [virtual]
Referenced by EtherLLC::processFrameFromMAC(), EtherAppSrv::sendPacket(), and EtherAppCli::sendPacket().
Member Data Documentation
::MACAddress Ieee802Ctrl::dest_var [protected]
Definition at line 108 of file Ieee802Ctrl_m.h.
int Ieee802Ctrl::dsap_var [protected]
Definition at line 111 of file Ieee802Ctrl_m.h.
int Ieee802Ctrl::etherType_var [protected]
Definition at line 109 of file Ieee802Ctrl_m.h.
int Ieee802Ctrl::inputPort_var [protected]
Definition at line 113 of file Ieee802Ctrl_m.h.
int Ieee802Ctrl::pauseUnits_var [protected]
Definition at line 112 of file Ieee802Ctrl_m.h.
::MACAddress Ieee802Ctrl::src_var [protected]
Definition at line 107 of file Ieee802Ctrl_m.h.
int Ieee802Ctrl::ssap_var [protected]
Definition at line 110 of file Ieee802Ctrl_m.h.
The documentation for this class was generated from the following file:
Ieee802Ctrl_m.h