INET Framework for OMNeT++/OMNEST: RsbTimeoutMsg Class Reference
RsbTimeoutMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
RsbTimeoutMsg (const char *name=NULL, int kind=0)
RsbTimeoutMsg (const RsbTimeoutMsg &other)
virtual ~RsbTimeoutMsg ()
RsbTimeoutMsg & operator= (const RsbTimeoutMsg &other)
virtual RsbTimeoutMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getId () const
virtual void setId (int id_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const RsbTimeoutMsg &)
Protected Attributes
int id_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message RsbTimeoutMsg extends SignallingMsg
 {
     int id;
     int command = MSG_RSB_TIMEOUT;
 }
Definition at line 243 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
RsbTimeoutMsg::RsbTimeoutMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
RsbTimeoutMsg::RsbTimeoutMsg (const RsbTimeoutMsg & other)
virtual RsbTimeoutMsg::~RsbTimeoutMsg () [virtual]
Member Function Documentation
virtual RsbTimeoutMsg* RsbTimeoutMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 257 of file SignallingMsg_m.h.
{return new RsbTimeoutMsg(*this);}
virtual int RsbTimeoutMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual int RsbTimeoutMsg::getId () const [virtual]
Referenced by RSVP::processRSB_TIMEOUT().
RsbTimeoutMsg& RsbTimeoutMsg::operator= (const RsbTimeoutMsg & other)
Reimplemented from SignallingMsg.
bool RsbTimeoutMsg::operator== (const RsbTimeoutMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void RsbTimeoutMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void RsbTimeoutMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void RsbTimeoutMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void RsbTimeoutMsg::setId (int id_var) [virtual]
Referenced by RSVP::createEgressRSB(), and RSVP::createRSB().
Member Data Documentation
int RsbTimeoutMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 247 of file SignallingMsg_m.h.
int RsbTimeoutMsg::id_var [protected]
Definition at line 246 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h