INET Framework for OMNeT++/OMNEST: IRadioModel Class Reference
IRadioModel Class Reference
#include <IRadioModel.h>
Public Member Functions
virtual void initializeFrom (cModule *radioModule)=0
virtual ~IRadioModel ()
virtual double calculateDuration (AirFrame *)=0
virtual bool isReceivedCorrectly (AirFrame *airframe, const SnrList &receivedList)=0
Detailed Description
Abstract class to encapsulate the calculation of received power of a radio transmission. The calculation may include the effects of path loss, antenna gain, etc.
Definition at line 30 of file IRadioModel.h.
Constructor & Destructor Documentation
virtual IRadioModel::~IRadioModel () [inline, virtual]
Virtual destructor.
Definition at line 42 of file IRadioModel.h.
{}
Member Function Documentation
virtual double IRadioModel::calculateDuration (AirFrame *) [pure virtual]
Should be defined to calculate the duration of the AirFrame. Usually the duration is just the frame length divided by the bitrate. However, in some cases, notably IEEE 802.11, the header has a different modulation (and thus a different bitrate) than the rest of the message.
Implemented in GenericRadioModel, and Ieee80211RadioModel.
Referenced by AbstractRadio::encapsulatePacket().
virtual void IRadioModel::initializeFrom (cModule * radioModule) [pure virtual]
Allows parameters to be read from the module parameters of a module that contains this object.
Implemented in GenericRadioModel, and Ieee80211RadioModel.
Referenced by AbstractRadio::initialize().
virtual bool IRadioModel::isReceivedCorrectly (AirFrame * airframe, const SnrList & receivedList) [pure virtual]
Should be defined to calculate whether the frame has been received correctly. Input is the signal-noise ratio over the duration of the frame. The calculation may take into account the modulation scheme, possible error correction code, etc.
Implemented in GenericRadioModel, and Ieee80211RadioModel.
Referenced by AbstractRadio::handleLowerMsgEnd().
The documentation for this class was generated from the following file:
IRadioModel.h