INET Framework for OMNeT++/OMNEST: RSVPPathMsg Class Reference
RSVPPathMsg Class Reference
#include <RSVPPathMsg.h>
Public Member Functions
RSVPPathMsg (const char *name=NULL, int kind=PATH_MESSAGE)
RSVPPathMsg (const RSVPPathMsg &other)
RSVPPathMsg & operator= (const RSVPPathMsg &other)
virtual RSVPPathMsg * dup () const
IPAddress getSrcAddress ()
int getLspId ()
IPAddress getNHOP ()
IPAddress getLIH ()
double getBW ()
SenderTemplateObj_t & getSenderTemplate ()
void setSenderTemplate (const SenderTemplateObj_t &s)
SenderTspecObj_t & getSenderTspec ()
void setSenderTspec (const SenderTspecObj_t &s)
Detailed Description
RSVP PATH message
This class adds convenience get() and set() methods to the generated base class, but no extra data.
Definition at line 28 of file RSVPPathMsg.h.
Constructor & Destructor Documentation
RSVPPathMsg::RSVPPathMsg (const char * name = NULL, int kind = PATH_MESSAGE) [inline]
Definition at line 31 of file RSVPPathMsg.h.
Referenced by dup().
: RSVPPathMsg_Base(name,kind) {}
RSVPPathMsg::RSVPPathMsg (const RSVPPathMsg & other) [inline]
Definition at line 32 of file RSVPPathMsg.h.
: RSVPPathMsg_Base(other.getName()) {operator=(other);}
Member Function Documentation
virtual RSVPPathMsg* RSVPPathMsg::dup () const [inline, virtual]
Reimplemented from RSVPPathMsg_Base.
Definition at line 34 of file RSVPPathMsg.h.
{return new RSVPPathMsg(*this);}
double RSVPPathMsg::getBW () [inline]
Definition at line 40 of file RSVPPathMsg.h.
{return getSender_descriptor().Sender_Tspec_Object.req_bandwidth;}
IPAddress RSVPPathMsg::getLIH () [inline]
Definition at line 39 of file RSVPPathMsg.h.
{return getHop().Logical_Interface_Handle;}
int RSVPPathMsg::getLspId () [inline]
Definition at line 37 of file RSVPPathMsg.h.
Referenced by RSVP::print().
{return getSender_descriptor().Sender_Template_Object.Lsp_Id;}
IPAddress RSVPPathMsg::getNHOP () [inline]
Definition at line 38 of file RSVPPathMsg.h.
Referenced by RSVP::createPSB(), and RSVP::processPathMsg().
{return getHop().Next_Hop_Address;}
SenderTemplateObj_t& RSVPPathMsg::getSenderTemplate () [inline]
Definition at line 41 of file RSVPPathMsg.h.
Referenced by RSVP::createPSB(), and RSVP::processPathMsg().
{return getSender_descriptor().Sender_Template_Object;}
SenderTspecObj_t& RSVPPathMsg::getSenderTspec () [inline]
Definition at line 43 of file RSVPPathMsg.h.
Referenced by RSVP::createPSB(), and RSVP::processPathMsg().
{return getSender_descriptor().Sender_Tspec_Object;}
IPAddress RSVPPathMsg::getSrcAddress () [inline]
Definition at line 36 of file RSVPPathMsg.h.
{return getSender_descriptor().Sender_Template_Object.SrcAddress;}
RSVPPathMsg& RSVPPathMsg::operator= (const RSVPPathMsg & other) [inline]
Reimplemented from RSVPPathMsg_Base.
Definition at line 33 of file RSVPPathMsg.h.
Referenced by RSVPPathMsg().
{RSVPPathMsg_Base::operator=(other); return *this;}
void RSVPPathMsg::setSenderTemplate (const SenderTemplateObj_t & s) [inline]
Definition at line 42 of file RSVPPathMsg.h.
{getSender_descriptor().Sender_Template_Object = s;}
void RSVPPathMsg::setSenderTspec (const SenderTspecObj_t & s) [inline]
Definition at line 44 of file RSVPPathMsg.h.
{getSender_descriptor().Sender_Tspec_Object = s;}
The documentation for this class was generated from the following file:
RSVPPathMsg.h