INET Framework for OMNeT++/OMNEST: OSPF::LSATrackingInfo Class Reference
OSPF::LSATrackingInfo Class Reference
#include <LSA.h>
Public Types
enum InstallSource { Originated = 0, Flooded = 1 }
Public Member Functions
LSATrackingInfo (void)
LSATrackingInfo (const LSATrackingInfo &info)
void SetSource (InstallSource installSource)
InstallSource GetSource (void) const
void IncrementInstallTime (void)
void ResetInstallTime (void)
unsigned long GetInstallTime (void) const
Private Attributes
InstallSource source
unsigned long installTime
Detailed Description
Definition at line 58 of file LSA.h.
Member Enumeration Documentation
enum OSPF::LSATrackingInfo::InstallSource
Enumerator:
Originated
Flooded
Definition at line 61 of file LSA.h.
                       {
        Originated = 0,
        Flooded = 1
    };
Constructor & Destructor Documentation
OSPF::LSATrackingInfo::LSATrackingInfo (void) [inline]
Definition at line 71 of file LSA.h.
: source(Flooded), installTime(0) {}
OSPF::LSATrackingInfo::LSATrackingInfo (const LSATrackingInfo & info) [inline]
Definition at line 72 of file LSA.h.
: source(info.source), installTime(info.installTime) {}
Member Function Documentation
unsigned long OSPF::LSATrackingInfo::GetInstallTime (void) const [inline]
Definition at line 78 of file LSA.h.
Referenced by OSPF::LinkStateUpdateHandler::ProcessPacket().
{ return installTime; }
InstallSource OSPF::LSATrackingInfo::GetSource (void) const [inline]
Definition at line 75 of file LSA.h.
Referenced by OSPF::LinkStateUpdateHandler::ProcessPacket().
{ return source; }
void OSPF::LSATrackingInfo::IncrementInstallTime (void) [inline]
Definition at line 76 of file LSA.h.
Referenced by OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::NeighborState::ChangeState(), OSPF::InterfaceState::ChangeState(), and OSPF::HelloHandler::ProcessPacket().
{ installTime++; }
void OSPF::LSATrackingInfo::ResetInstallTime (void) [inline]
Definition at line 77 of file LSA.h.
Referenced by OSPF::SummaryLSA::Update(), OSPF::RouterLSA::Update(), OSPF::NetworkLSA::Update(), and OSPF::ASExternalLSA::Update().
{ installTime = 0; }
void OSPF::LSATrackingInfo::SetSource (InstallSource installSource) [inline]
Definition at line 74 of file LSA.h.
Referenced by OSPF::Router::OriginateASExternalLSA(), OSPF::Area::OriginateRouterLSA(), and OSPF::Router::UpdateExternalRoute().
{ source = installSource; }
Member Data Documentation
unsigned long OSPF::LSATrackingInfo::installTime [private]
Definition at line 68 of file LSA.h.
Referenced by GetInstallTime(), IncrementInstallTime(), and ResetInstallTime().
InstallSource OSPF::LSATrackingInfo::source [private]
Definition at line 67 of file LSA.h.
Referenced by GetSource(), and SetSource().
The documentation for this class was generated from the following file:
LSA.h