INET Framework for OMNeT++/OMNEST: ICMPv6EchoRequestMsg Class Reference
ICMPv6EchoRequestMsg Class Reference
#include <ICMPv6Message_m.h>
Public Member Functions
ICMPv6EchoRequestMsg (const char *name=NULL, int kind=0)
ICMPv6EchoRequestMsg (const ICMPv6EchoRequestMsg &other)
virtual ~ICMPv6EchoRequestMsg ()
ICMPv6EchoRequestMsg & operator= (const ICMPv6EchoRequestMsg &other)
virtual ICMPv6EchoRequestMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCode () const
virtual void setCode (int code_var)
virtual int getIdentifier () const
virtual void setIdentifier (int identifier_var)
virtual int getSeqNumber () const
virtual void setSeqNumber (int seqNumber_var)
Protected Member Functions
bool operator== (const ICMPv6EchoRequestMsg &)
Protected Attributes
int code_var
int identifier_var
int seqNumber_var
Detailed Description
Class generated from networklayer/icmpv6/ICMPv6Message.msg by opp_msgc.
 packet ICMPv6EchoRequestMsg extends ICMPv6Message
 {
     int code;
     int identifier;
     int seqNumber;
 }
Definition at line 310 of file ICMPv6Message_m.h.
Constructor & Destructor Documentation
ICMPv6EchoRequestMsg::ICMPv6EchoRequestMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPv6EchoRequestMsg::ICMPv6EchoRequestMsg (const ICMPv6EchoRequestMsg & other)
virtual ICMPv6EchoRequestMsg::~ICMPv6EchoRequestMsg () [virtual]
Member Function Documentation
virtual ICMPv6EchoRequestMsg* ICMPv6EchoRequestMsg::dup () const [inline, virtual]
Reimplemented from ICMPv6Message.
Definition at line 325 of file ICMPv6Message_m.h.
{return new ICMPv6EchoRequestMsg(*this);}
virtual int ICMPv6EchoRequestMsg::getCode () const [virtual]
virtual int ICMPv6EchoRequestMsg::getIdentifier () const [virtual]
virtual int ICMPv6EchoRequestMsg::getSeqNumber () const [virtual]
ICMPv6EchoRequestMsg& ICMPv6EchoRequestMsg::operator= (const ICMPv6EchoRequestMsg & other)
Reimplemented from ICMPv6Message.
bool ICMPv6EchoRequestMsg::operator== (const ICMPv6EchoRequestMsg &) [protected]
Reimplemented from ICMPv6Message.
virtual void ICMPv6EchoRequestMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doPacking().
virtual void ICMPv6EchoRequestMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doUnpacking().
virtual void ICMPv6EchoRequestMsg::setCode (int code_var) [virtual]
virtual void ICMPv6EchoRequestMsg::setIdentifier (int identifier_var) [virtual]
virtual void ICMPv6EchoRequestMsg::setSeqNumber (int seqNumber_var) [virtual]
Member Data Documentation
int ICMPv6EchoRequestMsg::code_var [protected]
Definition at line 313 of file ICMPv6Message_m.h.
int ICMPv6EchoRequestMsg::identifier_var [protected]
Definition at line 314 of file ICMPv6Message_m.h.
int ICMPv6EchoRequestMsg::seqNumber_var [protected]
Definition at line 315 of file ICMPv6Message_m.h.
The documentation for this class was generated from the following file:
ICMPv6Message_m.h