INET Framework for OMNeT++/OMNEST: Ieee80211Frame Class Reference
Ieee80211Frame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211Frame (const char *name=NULL, int kind=0)
Ieee80211Frame (const Ieee80211Frame &other)
virtual ~Ieee80211Frame ()
Ieee80211Frame & operator= (const Ieee80211Frame &other)
virtual Ieee80211Frame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual short getType () const
virtual void setType (short type_var)
virtual bool getToDS () const
virtual void setToDS (bool toDS_var)
virtual bool getFromDS () const
virtual void setFromDS (bool fromDS_var)
virtual bool getRetry () const
virtual void setRetry (bool retry_var)
virtual bool getMoreFragments () const
virtual void setMoreFragments (bool moreFragments_var)
virtual simtime_t getDuration () const
virtual void setDuration (simtime_t duration_var)
virtual short getAID () const
virtual void setAID (short AID_var)
virtual MACAddress & getReceiverAddress ()
virtual const MACAddress & getReceiverAddress () const
virtual void setReceiverAddress (const MACAddress &receiverAddress_var)
Protected Member Functions
bool operator== (const Ieee80211Frame &)
Protected Attributes
short type_var
bool toDS_var
bool fromDS_var
bool retry_var
bool moreFragments_var
simtime_t duration_var
short AID_var
::MACAddress receiverAddress_var
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211Frame
 {
     byteLength = 14;
     short type enum(Ieee80211FrameType);
     bool toDS;
     bool fromDS;
     bool retry;
     bool moreFragments;
     simtime_t duration = -1;
     short AID = -1;
     MACAddress receiverAddress;
 }
Definition at line 90 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211Frame::Ieee80211Frame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211Frame::Ieee80211Frame (const Ieee80211Frame & other)
virtual Ieee80211Frame::~Ieee80211Frame () [virtual]
Member Function Documentation
virtual Ieee80211Frame* Ieee80211Frame::dup () const [inline, virtual]
Reimplemented in Ieee80211OneAddressFrame, Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Definition at line 110 of file Ieee80211Frame_m.h.
Referenced by Ieee80211Mac::scheduleSIFSPeriod().
{return new Ieee80211Frame(*this);}
virtual short Ieee80211Frame::getAID () const [virtual]
virtual simtime_t Ieee80211Frame::getDuration () const [virtual]
Referenced by Ieee80211Mac::buildACKFrame(), Ieee80211Mac::buildCTSFrame(), and Ieee80211Mac::scheduleReservePeriod().
virtual bool Ieee80211Frame::getFromDS () const [virtual]
virtual bool Ieee80211Frame::getMoreFragments () const [virtual]
Referenced by Ieee80211Mac::buildACKFrame(), and Ieee80211Mac::buildDataFrame().
virtual const MACAddress& Ieee80211Frame::getReceiverAddress () const [inline, virtual]
Definition at line 130 of file Ieee80211Frame_m.h.
Referenced by getReceiverAddress().
{return const_cast<Ieee80211Frame*>(this)->getReceiverAddress();}
virtual MACAddress& Ieee80211Frame::getReceiverAddress () [virtual]
Referenced by Ieee80211Mac::buildRTSFrame(), Ieee80211MgmtBase::decapsulate(), Ieee80211Mac::handleLowerMsg(), Ieee80211Mac::handleUpperMsg(), Ieee80211Mac::isBroadcast(), and Ieee80211Mac::isForUs().
virtual bool Ieee80211Frame::getRetry () const [virtual]
virtual bool Ieee80211Frame::getToDS () const [virtual]
Referenced by Ieee80211MgmtAPSimplified::handleDataFrame(), and Ieee80211MgmtAP::handleDataFrame().
virtual short Ieee80211Frame::getType () const [virtual]
Referenced by Ieee80211Mac::handleWithFSM(), and Ieee80211MgmtBase::processFrame().
Ieee80211Frame& Ieee80211Frame::operator= (const Ieee80211Frame & other)
Reimplemented in Ieee80211OneAddressFrame, Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
bool Ieee80211Frame::operator== (const Ieee80211Frame &) [protected]
Reimplemented in Ieee80211OneAddressFrame, Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
virtual void Ieee80211Frame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211OneAddressFrame, Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doPacking().
virtual void Ieee80211Frame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211OneAddressFrame, Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doUnpacking().
virtual void Ieee80211Frame::setAID (short AID_var) [virtual]
virtual void Ieee80211Frame::setDuration (simtime_t duration_var) [virtual]
Referenced by Ieee80211Mac::buildACKFrame(), Ieee80211Mac::buildBroadcastFrame(), Ieee80211Mac::buildCTSFrame(), Ieee80211Mac::buildDataFrame(), and Ieee80211Mac::buildRTSFrame().
virtual void Ieee80211Frame::setFromDS (bool fromDS_var) [virtual]
Referenced by Ieee80211MgmtAPBase::convertFromEtherFrame(), Ieee80211MgmtAPBase::distributeReceivedDataFrame(), Ieee80211MgmtAP::sendBeacon(), and Ieee80211MgmtAP::sendManagementFrame().
virtual void Ieee80211Frame::setMoreFragments (bool moreFragments_var) [virtual]
virtual void Ieee80211Frame::setReceiverAddress (const MACAddress & receiverAddress_var) [virtual]
Referenced by Ieee80211Mac::buildACKFrame(), Ieee80211Mac::buildCTSFrame(), Ieee80211Mac::buildRTSFrame(), Ieee80211MgmtAPBase::convertFromEtherFrame(), Ieee80211MgmtAPBase::distributeReceivedDataFrame(), Ieee80211MgmtSTASimplified::encapsulate(), Ieee80211MgmtSTA::encapsulate(), Ieee80211MgmtAdhoc::encapsulate(), Ieee80211MgmtAP::sendBeacon(), Ieee80211MgmtSTA::sendManagementFrame(), and Ieee80211MgmtAP::sendManagementFrame().
virtual void Ieee80211Frame::setRetry (bool retry_var) [virtual]
Referenced by Ieee80211Mac::resetStateVariables(), and Ieee80211Mac::retryCurrentTransmission().
virtual void Ieee80211Frame::setToDS (bool toDS_var) [virtual]
Referenced by Ieee80211MgmtAPBase::distributeReceivedDataFrame(), Ieee80211MgmtSTASimplified::encapsulate(), Ieee80211MgmtSTA::encapsulate(), and Ieee80211MgmtSTA::sendManagementFrame().
virtual void Ieee80211Frame::setType (short type_var) [virtual]
Member Data Documentation
short Ieee80211Frame::AID_var [protected]
Definition at line 99 of file Ieee80211Frame_m.h.
simtime_t Ieee80211Frame::duration_var [protected]
Definition at line 98 of file Ieee80211Frame_m.h.
bool Ieee80211Frame::fromDS_var [protected]
Definition at line 95 of file Ieee80211Frame_m.h.
bool Ieee80211Frame::moreFragments_var [protected]
Definition at line 97 of file Ieee80211Frame_m.h.
::MACAddress Ieee80211Frame::receiverAddress_var [protected]
Definition at line 100 of file Ieee80211Frame_m.h.
bool Ieee80211Frame::retry_var [protected]
Definition at line 96 of file Ieee80211Frame_m.h.
bool Ieee80211Frame::toDS_var [protected]
Definition at line 94 of file Ieee80211Frame_m.h.
short Ieee80211Frame::type_var [protected]
Definition at line 93 of file Ieee80211Frame_m.h.
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h