INET Framework for OMNeT++/OMNEST: Link Class Reference
Link Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
Link ()
Link (const Link &other)
virtual ~Link ()
Link & operator= (const Link &other)
virtual Link * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getLinkID ()
virtual const IPAddress & getLinkID () const
virtual void setLinkID (const IPAddress &linkID_var)
virtual unsigned long getLinkData () const
virtual void setLinkData (unsigned long linkData_var)
virtual unsigned char getType () const
virtual void setType (unsigned char type_var)
virtual unsigned char getNumberOfTOS () const
virtual void setNumberOfTOS (unsigned char numberOfTOS_var)
virtual unsigned long getLinkCost () const
virtual void setLinkCost (unsigned long linkCost_var)
virtual void setTosDataArraySize (unsigned int size)
virtual unsigned int getTosDataArraySize () const
virtual TOSData & getTosData (unsigned int k)
virtual const TOSData & getTosData (unsigned int k) const
virtual void setTosData (unsigned int k, const TOSData &tosData_var)
Protected Member Functions
bool operator== (const Link &)
Protected Attributes
::IPAddress linkID_var
unsigned long linkData_var
unsigned char type_var
unsigned char numberOfTOS_var
unsigned long linkCost_var
::TOSData * tosData_var
unsigned int tosData_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class Link
 {
     IPAddress linkID;
     unsigned long linkData = 0;
     unsigned char type enum(LinkType) = PointToPointLink;
     unsigned char numberOfTOS = 0;
     unsigned long linkCost = 1;
     TOSData tosData[];
 }
Definition at line 373 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
Link::Link ()
Referenced by dup().
Link::Link (const Link & other)
virtual Link::~Link () [virtual]
Member Function Documentation
virtual Link* Link::dup () const [inline, virtual]
Definition at line 392 of file OSPFPacket_m.h.
{return new Link(*this);}
virtual unsigned long Link::getLinkCost () const [virtual]
Referenced by OSPF::RouterLSA::DiffersFrom(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual unsigned long Link::getLinkData () const [virtual]
Referenced by OSPF::Area::CalculateNextHops(), OSPF::RouterLSA::DiffersFrom(), OSPF::Area::HasLink(), OSPF::Router::IsDestinationUnreachable(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual const IPAddress& Link::getLinkID () const [inline, virtual]
Definition at line 398 of file OSPFPacket_m.h.
Referenced by getLinkID().
{return const_cast<Link*>(this)->getLinkID();}
virtual IPAddress& Link::getLinkID () [virtual]
Referenced by OSPF::Area::CalculateNextHops(), OSPF::RouterLSA::DiffersFrom(), OSPF::Area::HasLink(), OSPF::Router::IsDestinationUnreachable(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual unsigned char Link::getNumberOfTOS () const [virtual]
Referenced by OSPF::RouterLSA::DiffersFrom().
virtual const TOSData& Link::getTosData (unsigned int k) const [inline, virtual]
Definition at line 411 of file OSPFPacket_m.h.
Referenced by getTosData().
{return const_cast<Link*>(this)->getTosData(k);}
virtual TOSData& Link::getTosData (unsigned int k) [virtual]
Referenced by OSPF::RouterLSA::DiffersFrom().
virtual unsigned int Link::getTosDataArraySize () const [virtual]
Referenced by CalculateLSASize(), and OSPF::RouterLSA::DiffersFrom().
virtual unsigned char Link::getType () const [virtual]
Referenced by OSPF::Area::CalculateNextHops(), OSPF::RouterLSA::DiffersFrom(), OSPF::Area::HasLink(), OSPF::Router::IsDestinationUnreachable(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
Link& Link::operator= (const Link & other)
bool Link::operator== (const Link &) [protected]
virtual void Link::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void Link::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void Link::setLinkCost (unsigned long linkCost_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void Link::setLinkData (unsigned long linkData_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void Link::setLinkID (const IPAddress & linkID_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void Link::setNumberOfTOS (unsigned char numberOfTOS_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void Link::setTosData (unsigned int k, const TOSData & tosData_var) [virtual]
virtual void Link::setTosDataArraySize (unsigned int size) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void Link::setType (unsigned char type_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
Member Data Documentation
unsigned long Link::linkCost_var [protected]
Definition at line 380 of file OSPFPacket_m.h.
unsigned long Link::linkData_var [protected]
Definition at line 377 of file OSPFPacket_m.h.
::IPAddress Link::linkID_var [protected]
Definition at line 376 of file OSPFPacket_m.h.
unsigned char Link::numberOfTOS_var [protected]
Definition at line 379 of file OSPFPacket_m.h.
unsigned int Link::tosData_arraysize [protected]
Definition at line 382 of file OSPFPacket_m.h.
::TOSData* Link::tosData_var [protected]
Definition at line 381 of file OSPFPacket_m.h.
unsigned char Link::type_var [protected]
Definition at line 378 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h