INET Framework for OMNeT++/OMNEST: Ieee80211ProbeResponseFrameBody Class Reference
Ieee80211ProbeResponseFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ProbeResponseFrameBody ()
Ieee80211ProbeResponseFrameBody (const Ieee80211ProbeResponseFrameBody &other)
virtual ~Ieee80211ProbeResponseFrameBody ()
Ieee80211ProbeResponseFrameBody & operator= (const Ieee80211ProbeResponseFrameBody &other)
virtual
Ieee80211ProbeResponseFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211ProbeResponseFrameBody &)
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211ProbeResponseFrameBody extends Ieee80211BeaconFrameBody
 {
 }
Definition at line 530 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ProbeResponseFrameBody::Ieee80211ProbeResponseFrameBody ()
Referenced by dup().
Ieee80211ProbeResponseFrameBody::Ieee80211ProbeResponseFrameBody (const Ieee80211ProbeResponseFrameBody & other)
virtual Ieee80211ProbeResponseFrameBody::~Ieee80211ProbeResponseFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211ProbeResponseFrameBody* Ieee80211ProbeResponseFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211BeaconFrameBody.
Definition at line 542 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ProbeResponseFrameBody(*this);}
Ieee80211ProbeResponseFrameBody& Ieee80211ProbeResponseFrameBody::operator= (const Ieee80211ProbeResponseFrameBody & other)
Reimplemented from Ieee80211BeaconFrameBody.
bool Ieee80211ProbeResponseFrameBody::operator== (const Ieee80211ProbeResponseFrameBody &) [protected]
Reimplemented from Ieee80211BeaconFrameBody.
virtual void Ieee80211ProbeResponseFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211BeaconFrameBody.
Referenced by doPacking().
virtual void Ieee80211ProbeResponseFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211BeaconFrameBody.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h