INET Framework for OMNeT++/OMNEST: TEDChangeInfo Class Reference
TEDChangeInfo Class Reference
#include <TED_m.h>
Public Member Functions
TEDChangeInfo ()
TEDChangeInfo (const TEDChangeInfo &other)
virtual ~TEDChangeInfo ()
TEDChangeInfo & operator= (const TEDChangeInfo &other)
virtual TEDChangeInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setTedLinkIndicesArraySize (unsigned int size)
virtual unsigned int getTedLinkIndicesArraySize () const
virtual int getTedLinkIndices (unsigned int k) const
virtual void setTedLinkIndices (unsigned int k, int tedLinkIndices_var)
Protected Member Functions
bool operator== (const TEDChangeInfo &)
Protected Attributes
int * tedLinkIndices_var
unsigned int tedLinkIndices_arraysize
Detailed Description
Class generated from networklayer/ted/TED.msg by opp_msgc.
 class TEDChangeInfo
 {
     int tedLinkIndices[];
 }
Definition at line 58 of file TED_m.h.
Constructor & Destructor Documentation
TEDChangeInfo::TEDChangeInfo ()
Referenced by dup().
TEDChangeInfo::TEDChangeInfo (const TEDChangeInfo & other)
virtual TEDChangeInfo::~TEDChangeInfo () [virtual]
Member Function Documentation
virtual TEDChangeInfo* TEDChangeInfo::dup () const [inline, virtual]
Definition at line 72 of file TED_m.h.
{return new TEDChangeInfo(*this);}
virtual int TEDChangeInfo::getTedLinkIndices (unsigned int k) const [virtual]
Referenced by LinkStateRouting::receiveChangeNotification().
virtual unsigned int TEDChangeInfo::getTedLinkIndicesArraySize () const [virtual]
Referenced by LinkStateRouting::receiveChangeNotification().
TEDChangeInfo& TEDChangeInfo::operator= (const TEDChangeInfo & other)
bool TEDChangeInfo::operator== (const TEDChangeInfo &) [protected]
virtual void TEDChangeInfo::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TEDChangeInfo::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void TEDChangeInfo::setTedLinkIndices (unsigned int k, int tedLinkIndices_var) [virtual]
Referenced by RSVP::announceLinkChange(), and LDP::announceLinkChange().
virtual void TEDChangeInfo::setTedLinkIndicesArraySize (unsigned int size) [virtual]
Referenced by RSVP::announceLinkChange(), and LDP::announceLinkChange().
Member Data Documentation
unsigned int TEDChangeInfo::tedLinkIndices_arraysize [protected]
Definition at line 62 of file TED_m.h.
int* TEDChangeInfo::tedLinkIndices_var [protected]
Definition at line 61 of file TED_m.h.
The documentation for this class was generated from the following file:
TED_m.h