INET Framework for OMNeT++/OMNEST: SCTPParameter Class Reference
SCTPParameter Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPParameter (const char *name=NULL, int kind=0)
SCTPParameter (const SCTPParameter &other)
virtual ~SCTPParameter ()
SCTPParameter & operator= (const SCTPParameter &other)
virtual SCTPParameter * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint16 getParameterType () const
virtual void setParameterType (uint16 parameterType_var)
Protected Member Functions
bool operator== (const SCTPParameter &)
Protected Attributes
uint16 parameterType_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPParameter extends cPacket
 {
      uint16 parameterType;
 }
Definition at line 1054 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPParameter::SCTPParameter (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPParameter::SCTPParameter (const SCTPParameter & other)
virtual SCTPParameter::~SCTPParameter () [virtual]
Member Function Documentation
virtual SCTPParameter* SCTPParameter::dup () const [inline, virtual]
Definition at line 1067 of file SCTPMessage_m.h.
{return new SCTPParameter(*this);}
virtual uint16 SCTPParameter::getParameterType () const [virtual]
Referenced by TCPDumper::sctpDump().
SCTPParameter& SCTPParameter::operator= (const SCTPParameter & other)
bool SCTPParameter::operator== (const SCTPParameter &) [protected]
virtual void SCTPParameter::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SCTPParameter::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SCTPParameter::setParameterType (uint16 parameterType_var) [virtual]
Member Data Documentation
uint16 SCTPParameter::parameterType_var [protected]
Definition at line 1057 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h