INET Framework for OMNeT++/OMNEST: Ieee80211Prim_ReassociateRequest Class Reference
Ieee80211Prim_ReassociateRequest Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_ReassociateRequest ()
Ieee80211Prim_ReassociateRequest (const Ieee80211Prim_ReassociateRequest &other)
virtual ~Ieee80211Prim_ReassociateRequest ()
Ieee80211Prim_ReassociateRequest & operator= (const Ieee80211Prim_ReassociateRequest &other)
virtual
Ieee80211Prim_ReassociateRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211Prim_ReassociateRequest &)
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_ReassociateRequest extends Ieee80211Prim_AssociateRequest
 {
 }
Definition at line 526 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_ReassociateRequest::Ieee80211Prim_ReassociateRequest ()
Referenced by dup().
Ieee80211Prim_ReassociateRequest::Ieee80211Prim_ReassociateRequest (const Ieee80211Prim_ReassociateRequest & other)
virtual Ieee80211Prim_ReassociateRequest::~Ieee80211Prim_ReassociateRequest () [virtual]
Member Function Documentation
virtual Ieee80211Prim_ReassociateRequest* Ieee80211Prim_ReassociateRequest::dup () const [inline, virtual]
Reimplemented from Ieee80211Prim_AssociateRequest.
Definition at line 538 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_ReassociateRequest(*this);}
Ieee80211Prim_ReassociateRequest& Ieee80211Prim_ReassociateRequest::operator= (const Ieee80211Prim_ReassociateRequest & other)
Reimplemented from Ieee80211Prim_AssociateRequest.
bool Ieee80211Prim_ReassociateRequest::operator== (const Ieee80211Prim_ReassociateRequest &) [protected]
Reimplemented from Ieee80211Prim_AssociateRequest.
virtual void Ieee80211Prim_ReassociateRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211Prim_AssociateRequest.
Referenced by doPacking().
virtual void Ieee80211Prim_ReassociateRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211Prim_AssociateRequest.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h