INET Framework for OMNeT++/OMNEST: RTPSenderStatusMessage Class Reference
RTPSenderStatusMessage Class Reference
#include <RTPSenderStatusMessage_m.h>
Public Member Functions
RTPSenderStatusMessage (const char *name=NULL, int kind=0)
RTPSenderStatusMessage (const RTPSenderStatusMessage &other)
virtual ~RTPSenderStatusMessage ()
RTPSenderStatusMessage & operator= (const RTPSenderStatusMessage &other)
virtual RTPSenderStatusMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getStatus () const
virtual void setStatus (const char *status_var)
virtual uint32 getTimeStamp () const
virtual void setTimeStamp (uint32 timeStamp_var)
Protected Member Functions
bool operator== (const RTPSenderStatusMessage &)
Protected Attributes
opp_string status_var
uint32 timeStamp_var
Detailed Description
Class generated from transport/rtp/RTPSenderStatusMessage.msg by opp_msgc.
 packet RTPSenderStatusMessage
 {
     string status;
     uint32 timeStamp;
 };
Definition at line 33 of file RTPSenderStatusMessage_m.h.
Constructor & Destructor Documentation
RTPSenderStatusMessage::RTPSenderStatusMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
RTPSenderStatusMessage::RTPSenderStatusMessage (const RTPSenderStatusMessage & other)
virtual RTPSenderStatusMessage::~RTPSenderStatusMessage () [virtual]
Member Function Documentation
virtual RTPSenderStatusMessage* RTPSenderStatusMessage::dup () const [inline, virtual]
Definition at line 47 of file RTPSenderStatusMessage_m.h.
{return new RTPSenderStatusMessage(*this);}
virtual const char* RTPSenderStatusMessage::getStatus () const [virtual]
Referenced by RTPApplication::activity().
virtual uint32 RTPSenderStatusMessage::getTimeStamp () const [virtual]
RTPSenderStatusMessage& RTPSenderStatusMessage::operator= (const RTPSenderStatusMessage & other)
bool RTPSenderStatusMessage::operator== (const RTPSenderStatusMessage &) [protected]
virtual void RTPSenderStatusMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void RTPSenderStatusMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void RTPSenderStatusMessage::setStatus (const char * status_var) [virtual]
Referenced by RTPPayloadSender::endOfFile(), RTPPayloadSender::pause(), RTPPayloadSender::play(), and RTPPayloadSender::stop().
virtual void RTPSenderStatusMessage::setTimeStamp (uint32 timeStamp_var) [virtual]
Referenced by RTPPayloadSender::play().
Member Data Documentation
opp_string RTPSenderStatusMessage::status_var [protected]
Definition at line 36 of file RTPSenderStatusMessage_m.h.
uint32 RTPSenderStatusMessage::timeStamp_var [protected]
Definition at line 37 of file RTPSenderStatusMessage_m.h.
The documentation for this class was generated from the following file:
RTPSenderStatusMessage_m.h