INET Framework for OMNeT++/OMNEST: ARPPacket Class Reference
ARPPacket Class Reference
#include <ARPPacket_m.h>
Public Member Functions
ARPPacket (const char *name=NULL, int kind=0)
ARPPacket (const ARPPacket &other)
virtual ~ARPPacket ()
ARPPacket & operator= (const ARPPacket &other)
virtual ARPPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getOpcode () const
virtual void setOpcode (int opcode_var)
virtual MACAddress & getSrcMACAddress ()
virtual const MACAddress & getSrcMACAddress () const
virtual void setSrcMACAddress (const MACAddress &srcMACAddress_var)
virtual MACAddress & getDestMACAddress ()
virtual const MACAddress & getDestMACAddress () const
virtual void setDestMACAddress (const MACAddress &destMACAddress_var)
virtual IPAddress & getSrcIPAddress ()
virtual const IPAddress & getSrcIPAddress () const
virtual void setSrcIPAddress (const IPAddress &srcIPAddress_var)
virtual IPAddress & getDestIPAddress ()
virtual const IPAddress & getDestIPAddress () const
virtual void setDestIPAddress (const IPAddress &destIPAddress_var)
Protected Member Functions
bool operator== (const ARPPacket &)
Protected Attributes
int opcode_var
::MACAddress srcMACAddress_var
::MACAddress destMACAddress_var
::IPAddress srcIPAddress_var
::IPAddress destIPAddress_var
Detailed Description
Class generated from networklayer/arp/ARPPacket.msg by opp_msgc.
 packet ARPPacket
 {
     int opcode enum(ARPOpcode);
     MACAddress srcMACAddress;
     MACAddress destMACAddress;
     IPAddress srcIPAddress;
     IPAddress destIPAddress;
 }
Definition at line 60 of file ARPPacket_m.h.
Constructor & Destructor Documentation
ARPPacket::ARPPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
ARPPacket::ARPPacket (const ARPPacket & other)
virtual ARPPacket::~ARPPacket () [virtual]
Member Function Documentation
virtual ARPPacket* ARPPacket::dup () const [inline, virtual]
Definition at line 77 of file ARPPacket_m.h.
{return new ARPPacket(*this);}
virtual const IPAddress& ARPPacket::getDestIPAddress () const [inline, virtual]
Definition at line 94 of file ARPPacket_m.h.
Referenced by getDestIPAddress().
{return const_cast<ARPPacket*>(this)->getDestIPAddress();}
virtual IPAddress& ARPPacket::getDestIPAddress () [virtual]
Referenced by ARP::dumpARPPacket().
virtual const MACAddress& ARPPacket::getDestMACAddress () const [inline, virtual]
Definition at line 88 of file ARPPacket_m.h.
Referenced by getDestMACAddress().
{return const_cast<ARPPacket*>(this)->getDestMACAddress();}
virtual MACAddress& ARPPacket::getDestMACAddress () [virtual]
Referenced by ARP::dumpARPPacket().
virtual int ARPPacket::getOpcode () const [virtual]
Referenced by ARP::dumpARPPacket().
virtual const IPAddress& ARPPacket::getSrcIPAddress () const [inline, virtual]
Definition at line 91 of file ARPPacket_m.h.
Referenced by getSrcIPAddress().
{return const_cast<ARPPacket*>(this)->getSrcIPAddress();}
virtual IPAddress& ARPPacket::getSrcIPAddress () [virtual]
Referenced by ARP::dumpARPPacket().
virtual const MACAddress& ARPPacket::getSrcMACAddress () const [inline, virtual]
Definition at line 85 of file ARPPacket_m.h.
Referenced by getSrcMACAddress().
{return const_cast<ARPPacket*>(this)->getSrcMACAddress();}
virtual MACAddress& ARPPacket::getSrcMACAddress () [virtual]
Referenced by ARP::dumpARPPacket().
ARPPacket& ARPPacket::operator= (const ARPPacket & other)
bool ARPPacket::operator== (const ARPPacket &) [protected]
virtual void ARPPacket::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ARPPacket::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ARPPacket::setDestIPAddress (const IPAddress & destIPAddress_var) [virtual]
virtual void ARPPacket::setDestMACAddress (const MACAddress & destMACAddress_var) [virtual]
virtual void ARPPacket::setOpcode (int opcode_var) [virtual]
virtual void ARPPacket::setSrcIPAddress (const IPAddress & srcIPAddress_var) [virtual]
virtual void ARPPacket::setSrcMACAddress (const MACAddress & srcMACAddress_var) [virtual]
Member Data Documentation
::IPAddress ARPPacket::destIPAddress_var [protected]
Definition at line 67 of file ARPPacket_m.h.
::MACAddress ARPPacket::destMACAddress_var [protected]
Definition at line 65 of file ARPPacket_m.h.
int ARPPacket::opcode_var [protected]
Definition at line 63 of file ARPPacket_m.h.
::IPAddress ARPPacket::srcIPAddress_var [protected]
Definition at line 66 of file ARPPacket_m.h.
::MACAddress ARPPacket::srcMACAddress_var [protected]
Definition at line 64 of file ARPPacket_m.h.
The documentation for this class was generated from the following file:
ARPPacket_m.h