INET Framework for OMNeT++/OMNEST: EtherPauseFrame Class Reference
EtherPauseFrame Class Reference
#include <EtherFrame_m.h>
Public Member Functions
EtherPauseFrame (const char *name=NULL, int kind=0)
EtherPauseFrame (const EtherPauseFrame &other)
virtual ~EtherPauseFrame ()
EtherPauseFrame & operator= (const EtherPauseFrame &other)
virtual EtherPauseFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getPauseTime () const
virtual void setPauseTime (int pauseTime_var)
Protected Member Functions
bool operator== (const EtherPauseFrame &)
Protected Attributes
int pauseTime_var
Detailed Description
Class generated from linklayer/ethernet/EtherFrame.msg by opp_msgc.
 packet EtherPauseFrame extends EtherFrame
 {
     int pauseTime;
 }
Definition at line 219 of file EtherFrame_m.h.
Constructor & Destructor Documentation
EtherPauseFrame::EtherPauseFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherPauseFrame::EtherPauseFrame (const EtherPauseFrame & other)
virtual EtherPauseFrame::~EtherPauseFrame () [virtual]
Member Function Documentation
virtual EtherPauseFrame* EtherPauseFrame::dup () const [inline, virtual]
Reimplemented from EtherFrame.
Definition at line 232 of file EtherFrame_m.h.
{return new EtherPauseFrame(*this);}
virtual int EtherPauseFrame::getPauseTime () const [virtual]
Referenced by EtherMACBase::frameReceptionComplete().
EtherPauseFrame& EtherPauseFrame::operator= (const EtherPauseFrame & other)
Reimplemented from EtherFrame.
bool EtherPauseFrame::operator== (const EtherPauseFrame &) [protected]
Reimplemented from EtherFrame.
virtual void EtherPauseFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doPacking().
virtual void EtherPauseFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doUnpacking().
virtual void EtherPauseFrame::setPauseTime (int pauseTime_var) [virtual]
Referenced by EtherLLC::handleSendPause(), EtherEncap::handleSendPause(), and MACRelayUnitBase::sendPauseFrame().
Member Data Documentation
int EtherPauseFrame::pauseTime_var [protected]
Definition at line 222 of file EtherFrame_m.h.
The documentation for this class was generated from the following file:
EtherFrame_m.h