INET Framework for OMNeT++/OMNEST: RSVPResvTear_Base Class Reference
RSVPResvTear_Base Class Reference
#include <RSVPResvMsg_m.h>
Public Member Functions
virtual ~RSVPResvTear_Base ()
virtual RSVPResvTear_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual RsvpHopObj_t & getHop ()
virtual const RsvpHopObj_t & getHop () const
virtual void setHop (const RsvpHopObj_t &hop_var)
virtual FlowDescriptorVector & getFlowDescriptor ()
virtual const
FlowDescriptorVector & getFlowDescriptor () const
virtual void setFlowDescriptor (const FlowDescriptorVector &flowDescriptor_var)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind_var)
Protected Member Functions
bool operator== (const RSVPResvTear_Base &)
RSVPResvTear_Base (const char *name=NULL, int kind=0)
RSVPResvTear_Base (const RSVPResvTear_Base &other)
RSVPResvTear_Base & operator= (const RSVPResvTear_Base &other)
Protected Attributes
::RsvpHopObj_t hop_var
::FlowDescriptorVector flowDescriptor_var
int rsvpKind_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPResvMsg.msg by opp_msgc.
 packet RSVPResvTear extends RSVPPacket
 {
     (true);
     RsvpHopObj_t hop;
     FlowDescriptorVector flowDescriptor;
     int rsvpKind = RTEAR_MESSAGE;
 }
RSVPResvTear_Base is only useful if it gets subclassed, and RSVPResvTear is derived from it. The minimum code to be written for RSVPResvTear is the following:
 class RSVPResvTear : public RSVPResvTear_Base
 {
   public:
     RSVPResvTear(const char *name=NULL, int kind=0) : RSVPResvTear_Base(name,kind) {}
     RSVPResvTear(const RSVPResvTear& other) : RSVPResvTear_Base(other.getName()) {operator=(other);}
     RSVPResvTear& operator=(const RSVPResvTear& other) {RSVPResvTear_Base::operator=(other); return *this;}
     virtual RSVPResvTear *dup() const {return new RSVPResvTear(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPResvTear_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(RSVPResvTear);
Definition at line 122 of file RSVPResvMsg_m.h.
Constructor & Destructor Documentation
RSVPResvTear_Base::RSVPResvTear_Base (const char * name = NULL, int kind = 0) [protected]
RSVPResvTear_Base::RSVPResvTear_Base (const RSVPResvTear_Base & other) [protected]
virtual RSVPResvTear_Base::~RSVPResvTear_Base () [virtual]
Member Function Documentation
virtual RSVPResvTear_Base* RSVPResvTear_Base::dup () const [inline, virtual]
Reimplemented from RSVPPacket.
Reimplemented in RSVPResvTear.
Definition at line 139 of file RSVPResvMsg_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class RSVPResvTear");}
virtual const FlowDescriptorVector& RSVPResvTear_Base::getFlowDescriptor () const [inline, virtual]
Definition at line 148 of file RSVPResvMsg_m.h.
Referenced by getFlowDescriptor().
{return const_cast<RSVPResvTear_Base*>(this)->getFlowDescriptor();}
virtual FlowDescriptorVector& RSVPResvTear_Base::getFlowDescriptor () [virtual]
virtual const RsvpHopObj_t& RSVPResvTear_Base::getHop () const [inline, virtual]
Definition at line 145 of file RSVPResvMsg_m.h.
Referenced by getHop().
{return const_cast<RSVPResvTear_Base*>(this)->getHop();}
virtual RsvpHopObj_t& RSVPResvTear_Base::getHop () [virtual]
Referenced by RSVPResvTear::getLIH(), and RSVPResvTear::getNHOP().
virtual int RSVPResvTear_Base::getRsvpKind () const [virtual]
Reimplemented from RSVPMessage.
RSVPResvTear_Base& RSVPResvTear_Base::operator= (const RSVPResvTear_Base & other) [protected]
Reimplemented from RSVPPacket.
Reimplemented in RSVPResvTear.
bool RSVPResvTear_Base::operator== (const RSVPResvTear_Base &) [protected]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvTear_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvTear_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvTear_Base::setFlowDescriptor (const FlowDescriptorVector & flowDescriptor_var) [virtual]
virtual void RSVPResvTear_Base::setHop (const RsvpHopObj_t & hop_var) [virtual]
virtual void RSVPResvTear_Base::setRsvpKind (int rsvpKind_var) [virtual]
Reimplemented from RSVPMessage.
Member Data Documentation
::FlowDescriptorVector RSVPResvTear_Base::flowDescriptor_var [protected]
Definition at line 126 of file RSVPResvMsg_m.h.
::RsvpHopObj_t RSVPResvTear_Base::hop_var [protected]
Definition at line 125 of file RSVPResvMsg_m.h.
int RSVPResvTear_Base::rsvpKind_var [protected]
Reimplemented from RSVPMessage.
Definition at line 127 of file RSVPResvMsg_m.h.
The documentation for this class was generated from the following file:
RSVPResvMsg_m.h