INET Framework for OMNeT++/OMNEST: Ieee80211Prim_ScanConfirm Class Reference
Ieee80211Prim_ScanConfirm Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_ScanConfirm ()
Ieee80211Prim_ScanConfirm (const Ieee80211Prim_ScanConfirm &other)
virtual ~Ieee80211Prim_ScanConfirm ()
Ieee80211Prim_ScanConfirm & operator= (const Ieee80211Prim_ScanConfirm &other)
virtual Ieee80211Prim_ScanConfirm * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setBssListArraySize (unsigned int size)
virtual unsigned int getBssListArraySize () const
virtual
Ieee80211Prim_BSSDescription & getBssList (unsigned int k)
virtual const
Ieee80211Prim_BSSDescription & getBssList (unsigned int k) const
virtual void setBssList (unsigned int k, const Ieee80211Prim_BSSDescription &bssList_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_ScanConfirm &)
Protected Attributes
::Ieee80211Prim_BSSDescription * bssList_var
unsigned int bssList_arraysize
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_ScanConfirm extends Ieee80211PrimConfirm
 {
     Ieee80211Prim_BSSDescription bssList[];
 }
Definition at line 307 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_ScanConfirm::Ieee80211Prim_ScanConfirm ()
Referenced by dup().
Ieee80211Prim_ScanConfirm::Ieee80211Prim_ScanConfirm (const Ieee80211Prim_ScanConfirm & other)
virtual Ieee80211Prim_ScanConfirm::~Ieee80211Prim_ScanConfirm () [virtual]
Member Function Documentation
virtual Ieee80211Prim_ScanConfirm* Ieee80211Prim_ScanConfirm::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimConfirm.
Definition at line 321 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_ScanConfirm(*this);}
virtual const Ieee80211Prim_BSSDescription& Ieee80211Prim_ScanConfirm::getBssList (unsigned int k) const [inline, virtual]
Definition at line 329 of file Ieee80211Primitives_m.h.
Referenced by getBssList().
{return const_cast<Ieee80211Prim_ScanConfirm*>(this)->getBssList(k);}
virtual Ieee80211Prim_BSSDescription& Ieee80211Prim_ScanConfirm::getBssList (unsigned int k) [virtual]
Referenced by Ieee80211AgentSTA::chooseBSS(), Ieee80211AgentSTA::dumpAPList(), Ieee80211AgentSTA::processScanConfirm(), and Ieee80211MgmtSTA::sendScanConfirm().
virtual unsigned int Ieee80211Prim_ScanConfirm::getBssListArraySize () const [virtual]
Referenced by Ieee80211AgentSTA::chooseBSS(), and Ieee80211AgentSTA::dumpAPList().
Ieee80211Prim_ScanConfirm& Ieee80211Prim_ScanConfirm::operator= (const Ieee80211Prim_ScanConfirm & other)
Reimplemented from Ieee80211PrimConfirm.
bool Ieee80211Prim_ScanConfirm::operator== (const Ieee80211Prim_ScanConfirm &) [protected]
Reimplemented from Ieee80211PrimConfirm.
virtual void Ieee80211Prim_ScanConfirm::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimConfirm.
Referenced by doPacking().
virtual void Ieee80211Prim_ScanConfirm::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimConfirm.
Referenced by doUnpacking().
virtual void Ieee80211Prim_ScanConfirm::setBssList (unsigned int k, const Ieee80211Prim_BSSDescription & bssList_var) [virtual]
virtual void Ieee80211Prim_ScanConfirm::setBssListArraySize (unsigned int size) [virtual]
Referenced by Ieee80211MgmtSTA::sendScanConfirm().
Member Data Documentation
unsigned int Ieee80211Prim_ScanConfirm::bssList_arraysize [protected]
Definition at line 311 of file Ieee80211Primitives_m.h.
::Ieee80211Prim_BSSDescription* Ieee80211Prim_ScanConfirm::bssList_var [protected]
Definition at line 310 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h