INET Framework for OMNeT++/OMNEST: TCPCommand Class Reference
TCPCommand Class Reference
#include <TCPCommand_m.h>
Public Member Functions
TCPCommand ()
TCPCommand (const TCPCommand &other)
virtual ~TCPCommand ()
TCPCommand & operator= (const TCPCommand &other)
virtual TCPCommand * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getConnId () const
virtual void setConnId (int connId_var)
virtual int getUserId () const
virtual void setUserId (int userId_var)
Protected Member Functions
bool operator== (const TCPCommand &)
Protected Attributes
int connId_var
int userId_var
Detailed Description
Class generated from transport/contract/TCPCommand.msg by opp_msgc.
 class TCPCommand
 {
     int connId = -1;
     int userId = -1;
 }
Definition at line 99 of file TCPCommand_m.h.
Constructor & Destructor Documentation
TCPCommand::TCPCommand ()
Referenced by dup().
TCPCommand::TCPCommand (const TCPCommand & other)
virtual TCPCommand::~TCPCommand () [virtual]
Member Function Documentation
virtual TCPCommand* TCPCommand::dup () const [inline, virtual]
Reimplemented in TCPErrorInfo, TCPOpenCommand, TCPSendCommand, TCPConnectInfo, and TCPStatusInfo.
Definition at line 113 of file TCPCommand_m.h.
{return new TCPCommand(*this);}
virtual int TCPCommand::getConnId () const [virtual]
Referenced by TCPSocketMap::findSocketFor(), TCPEchoApp::handleMessage(), tcp_old::TCP::handleMessage(), TCP::handleMessage(), and TCPSocket::TCPSocket().
virtual int TCPCommand::getUserId () const [virtual]
TCPCommand& TCPCommand::operator= (const TCPCommand & other)
Reimplemented in TCPErrorInfo, TCPOpenCommand, TCPSendCommand, TCPConnectInfo, and TCPStatusInfo.
bool TCPCommand::operator== (const TCPCommand &) [protected]
Reimplemented in TCPErrorInfo, TCPOpenCommand, TCPSendCommand, TCPConnectInfo, and TCPStatusInfo.
virtual void TCPCommand::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in TCPErrorInfo, TCPOpenCommand, TCPSendCommand, TCPConnectInfo, and TCPStatusInfo.
Referenced by doPacking().
virtual void TCPCommand::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in TCPErrorInfo, TCPOpenCommand, TCPSendCommand, TCPConnectInfo, and TCPStatusInfo.
Referenced by doUnpacking().
virtual void TCPCommand::setConnId (int connId_var) [virtual]
Referenced by TCPSocket::abort(), TCPSocket::close(), TCPSocket::connect(), TCPGenericSrvApp::handleMessage(), TCPSocket::listen(), tcp_old::TCPConnection::processSegment1stThru8th(), TCPConnection::processSegment1stThru8th(), TCPSocket::requestStatus(), TCPSocket::send(), tcp_old::TCPConnection::sendEstabIndicationToApp(), TCPConnection::sendEstabIndicationToApp(), tcp_old::TCPConnection::sendIndicationToApp(), and TCPConnection::sendIndicationToApp().
virtual void TCPCommand::setUserId (int userId_var) [virtual]
Member Data Documentation
int TCPCommand::connId_var [protected]
Definition at line 102 of file TCPCommand_m.h.
int TCPCommand::userId_var [protected]
Definition at line 103 of file TCPCommand_m.h.
The documentation for this class was generated from the following file:
TCPCommand_m.h