INET Framework for OMNeT++/OMNEST: IPDatagram Class Reference
IPDatagram Class Reference
#include <IPDatagram_m.h>
Public Member Functions
IPDatagram (const char *name=NULL, int kind=0)
IPDatagram (const IPDatagram &other)
virtual ~IPDatagram ()
IPDatagram & operator= (const IPDatagram &other)
virtual IPDatagram * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual short getVersion () const
virtual void setVersion (short version_var)
virtual short getHeaderLength () const
virtual void setHeaderLength (short headerLength_var)
virtual IPAddress & getSrcAddress ()
virtual const IPAddress & getSrcAddress () const
virtual void setSrcAddress (const IPAddress &srcAddress_var)
virtual IPAddress & getDestAddress ()
virtual const IPAddress & getDestAddress () const
virtual void setDestAddress (const IPAddress &destAddress_var)
virtual int getTransportProtocol () const
virtual void setTransportProtocol (int transportProtocol_var)
virtual short getTimeToLive () const
virtual void setTimeToLive (short timeToLive_var)
virtual int getIdentification () const
virtual void setIdentification (int identification_var)
virtual bool getMoreFragments () const
virtual void setMoreFragments (bool moreFragments_var)
virtual bool getDontFragment () const
virtual void setDontFragment (bool dontFragment_var)
virtual int getFragmentOffset () const
virtual void setFragmentOffset (int fragmentOffset_var)
virtual unsigned char getDiffServCodePoint () const
virtual void setDiffServCodePoint (unsigned char diffServCodePoint_var)
virtual int getOptionCode () const
virtual void setOptionCode (int optionCode_var)
virtual IPRecordRouteOption & getRecordRoute ()
virtual const IPRecordRouteOption & getRecordRoute () const
virtual void setRecordRoute (const IPRecordRouteOption &recordRoute_var)
virtual IPTimestampOption & getTimestampOption ()
virtual const IPTimestampOption & getTimestampOption () const
virtual void setTimestampOption (const IPTimestampOption &timestampOption_var)
virtual IPSourceRoutingOption & getSourceRoutingOption ()
virtual const
IPSourceRoutingOption & getSourceRoutingOption () const
virtual void setSourceRoutingOption (const IPSourceRoutingOption &sourceRoutingOption_var)
Protected Member Functions
bool operator== (const IPDatagram &)
Protected Attributes
short version_var
short headerLength_var
::IPAddress srcAddress_var
::IPAddress destAddress_var
int transportProtocol_var
short timeToLive_var
int identification_var
bool moreFragments_var
bool dontFragment_var
int fragmentOffset_var
unsigned char diffServCodePoint_var
int optionCode_var
::IPRecordRouteOption recordRoute_var
::IPTimestampOption timestampOption_var
::IPSourceRoutingOption sourceRoutingOption_var
Detailed Description
Class generated from networklayer/ipv4/IPDatagram.msg by opp_msgc.
 packet IPDatagram
 {
     short version = 4;
     short headerLength = IP_HEADER_BYTES;
     IPAddress srcAddress;
     IPAddress destAddress;
     int transportProtocol enum(IPProtocolId) = IP_PROT_NONE;
     short timeToLive;
     int identification;
     bool moreFragments;
     bool dontFragment;
     int fragmentOffset;
     unsigned char diffServCodePoint;
     int optionCode enum(IPOption) = IPOPTION_NO_OPTION;
     IPRecordRouteOption recordRoute;
     IPTimestampOption timestampOption;
     IPSourceRoutingOption sourceRoutingOption;
 }
Definition at line 266 of file IPDatagram_m.h.
Constructor & Destructor Documentation
IPDatagram::IPDatagram (const char * name = NULL, int kind = 0)
Referenced by dup().
IPDatagram::IPDatagram (const IPDatagram & other)
virtual IPDatagram::~IPDatagram () [virtual]
Member Function Documentation
virtual IPDatagram* IPDatagram::dup () const [inline, virtual]
Definition at line 293 of file IPDatagram_m.h.
Referenced by IP::fragmentAndSend(), and IP::routeMulticastPacket().
{return new IPDatagram(*this);}
virtual const IPAddress& IPDatagram::getDestAddress () const [inline, virtual]
Definition at line 306 of file IPDatagram_m.h.
Referenced by getDestAddress().
{return const_cast<IPDatagram*>(this)->getDestAddress();}
virtual IPAddress& IPDatagram::getDestAddress () [virtual]
Referenced by IPFragBuf::addFragment(), IP::decapsulateIP(), IP::encapsulate(), ExtInterface::handleMessage(), IP::handleMessageFromHL(), IP::handlePacketFromNetwork(), TCPDumper::ipDump(), SimpleClassifier::lookupLabel(), LDP::lookupLabel(), UDP::processICMPError(), ARP::processOutboundPacket(), IP::routeMulticastPacket(), IP::routePacket(), ICMP::sendErrorMessage(), IPSerializer::serialize(), TCPDumper::tcpDump(), and TCPDumper::udpDump().
virtual unsigned char IPDatagram::getDiffServCodePoint () const [virtual]
Referenced by BasicDSCPClassifier::classifyPacket(), IP::decapsulateIP(), and IPSerializer::serialize().
virtual bool IPDatagram::getDontFragment () const [virtual]
Referenced by IP::fragmentAndSend().
virtual int IPDatagram::getFragmentOffset () const [virtual]
Referenced by IPFragBuf::addFragment(), IP::reassembleAndDeliver(), and IPSerializer::serialize().
virtual short IPDatagram::getHeaderLength () const [virtual]
Referenced by IPFragBuf::addFragment(), IP::fragmentAndSend(), IP::handlePacketFromNetwork(), ICMP::sendErrorMessage(), and IPSerializer::serialize().
virtual int IPDatagram::getIdentification () const [virtual]
Referenced by IPFragBuf::addFragment(), and IPSerializer::serialize().
virtual bool IPDatagram::getMoreFragments () const [virtual]
Referenced by IPFragBuf::addFragment(), and IP::reassembleAndDeliver().
virtual int IPDatagram::getOptionCode () const [virtual]
virtual const IPRecordRouteOption& IPDatagram::getRecordRoute () const [inline, virtual]
Definition at line 325 of file IPDatagram_m.h.
Referenced by getRecordRoute().
{return const_cast<IPDatagram*>(this)->getRecordRoute();}
virtual IPRecordRouteOption& IPDatagram::getRecordRoute () [virtual]
virtual const IPSourceRoutingOption& IPDatagram::getSourceRoutingOption () const [inline, virtual]
Definition at line 331 of file IPDatagram_m.h.
Referenced by getSourceRoutingOption().
{return const_cast<IPDatagram*>(this)->getSourceRoutingOption();}
virtual IPSourceRoutingOption& IPDatagram::getSourceRoutingOption () [virtual]
virtual const IPAddress& IPDatagram::getSrcAddress () const [inline, virtual]
Definition at line 303 of file IPDatagram_m.h.
Referenced by getSrcAddress().
{return const_cast<IPDatagram*>(this)->getSrcAddress();}
virtual IPAddress& IPDatagram::getSrcAddress () [virtual]
Referenced by IPFragBuf::addFragment(), IP::decapsulateIP(), ExtInterface::handleMessage(), TCPDumper::ipDump(), SimpleClassifier::lookupLabel(), UDP::processICMPError(), IP::routeMulticastPacket(), IP::routePacket(), ICMP::sendErrorMessage(), IPSerializer::serialize(), TCPDumper::tcpDump(), and TCPDumper::udpDump().
virtual const IPTimestampOption& IPDatagram::getTimestampOption () const [inline, virtual]
Definition at line 328 of file IPDatagram_m.h.
Referenced by getTimestampOption().
{return const_cast<IPDatagram*>(this)->getTimestampOption();}
virtual IPTimestampOption& IPDatagram::getTimestampOption () [virtual]
virtual short IPDatagram::getTimeToLive () const [virtual]
Referenced by IP::handlePacketFromNetwork(), IP::sendDatagramToOutput(), and IPSerializer::serialize().
virtual int IPDatagram::getTransportProtocol () const [virtual]
Referenced by IP::decapsulateIP(), ExtInterface::handleMessage(), IP::handleReceivedICMP(), SimpleClassifier::lookupLabel(), LDP::lookupLabel(), IPSerializer::parse(), MPLS::processPacketFromL3(), IP::reassembleAndDeliver(), ICMP::sendErrorMessage(), and IPSerializer::serialize().
virtual short IPDatagram::getVersion () const [virtual]
Referenced by IPSerializer::serialize().
IPDatagram& IPDatagram::operator= (const IPDatagram & other)
bool IPDatagram::operator== (const IPDatagram &) [protected]
virtual void IPDatagram::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void IPDatagram::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void IPDatagram::setDestAddress (const IPAddress & destAddress_var) [virtual]
Referenced by IP::encapsulate(), IPSerializer::parse(), and IP::routeMulticastPacket().
virtual void IPDatagram::setDiffServCodePoint (unsigned char diffServCodePoint_var) [virtual]
Referenced by IP::encapsulate(), and IPSerializer::parse().
virtual void IPDatagram::setDontFragment (bool dontFragment_var) [virtual]
Referenced by IP::encapsulate(), and IPSerializer::parse().
virtual void IPDatagram::setFragmentOffset (int fragmentOffset_var) [virtual]
Referenced by IPFragBuf::addFragment(), IP::encapsulate(), IP::fragmentAndSend(), and IPSerializer::parse().
virtual void IPDatagram::setHeaderLength (short headerLength_var) [virtual]
Referenced by IPSerializer::parse().
virtual void IPDatagram::setIdentification (int identification_var) [virtual]
Referenced by IP::encapsulate(), and IPSerializer::parse().
virtual void IPDatagram::setMoreFragments (bool moreFragments_var) [virtual]
Referenced by IPFragBuf::addFragment(), IP::encapsulate(), IP::fragmentAndSend(), and IPSerializer::parse().
virtual void IPDatagram::setOptionCode (int optionCode_var) [virtual]
virtual void IPDatagram::setRecordRoute (const IPRecordRouteOption & recordRoute_var) [virtual]
virtual void IPDatagram::setSourceRoutingOption (const IPSourceRoutingOption & sourceRoutingOption_var) [virtual]
virtual void IPDatagram::setSrcAddress (const IPAddress & srcAddress_var) [virtual]
Referenced by IP::encapsulate(), IPSerializer::parse(), IP::routeMulticastPacket(), and IP::routePacket().
virtual void IPDatagram::setTimestampOption (const IPTimestampOption & timestampOption_var) [virtual]
virtual void IPDatagram::setTimeToLive (short timeToLive_var) [virtual]
Referenced by IP::encapsulate(), IP::handlePacketFromNetwork(), and IPSerializer::parse().
virtual void IPDatagram::setTransportProtocol (int transportProtocol_var) [virtual]
Referenced by IP::encapsulate(), and IPSerializer::parse().
virtual void IPDatagram::setVersion (short version_var) [virtual]
Referenced by IPSerializer::parse().
Member Data Documentation
::IPAddress IPDatagram::destAddress_var [protected]
Definition at line 272 of file IPDatagram_m.h.
unsigned char IPDatagram::diffServCodePoint_var [protected]
Definition at line 279 of file IPDatagram_m.h.
bool IPDatagram::dontFragment_var [protected]
Definition at line 277 of file IPDatagram_m.h.
int IPDatagram::fragmentOffset_var [protected]
Definition at line 278 of file IPDatagram_m.h.
short IPDatagram::headerLength_var [protected]
Definition at line 270 of file IPDatagram_m.h.
int IPDatagram::identification_var [protected]
Definition at line 275 of file IPDatagram_m.h.
bool IPDatagram::moreFragments_var [protected]
Definition at line 276 of file IPDatagram_m.h.
int IPDatagram::optionCode_var [protected]
Definition at line 280 of file IPDatagram_m.h.
::IPRecordRouteOption IPDatagram::recordRoute_var [protected]
Definition at line 281 of file IPDatagram_m.h.
::IPSourceRoutingOption IPDatagram::sourceRoutingOption_var [protected]
Definition at line 283 of file IPDatagram_m.h.
::IPAddress IPDatagram::srcAddress_var [protected]
Definition at line 271 of file IPDatagram_m.h.
::IPTimestampOption IPDatagram::timestampOption_var [protected]
Definition at line 282 of file IPDatagram_m.h.
short IPDatagram::timeToLive_var [protected]
Definition at line 274 of file IPDatagram_m.h.
int IPDatagram::transportProtocol_var [protected]
Definition at line 273 of file IPDatagram_m.h.
short IPDatagram::version_var [protected]
Definition at line 269 of file IPDatagram_m.h.
The documentation for this class was generated from the following file:
IPDatagram_m.h