INET Framework for OMNeT++/OMNEST: PsbTimerMsg Class Reference
PsbTimerMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
PsbTimerMsg (const char *name=NULL, int kind=0)
PsbTimerMsg (const PsbTimerMsg &other)
virtual ~PsbTimerMsg ()
PsbTimerMsg & operator= (const PsbTimerMsg &other)
virtual PsbTimerMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getId () const
virtual void setId (int id_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const PsbTimerMsg &)
Protected Attributes
int id_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message PsbTimerMsg extends SignallingMsg
 {
     int id;
     int command = MSG_PSB_TIMER;
 }
Definition at line 87 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
PsbTimerMsg::PsbTimerMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
PsbTimerMsg::PsbTimerMsg (const PsbTimerMsg & other)
virtual PsbTimerMsg::~PsbTimerMsg () [virtual]
Member Function Documentation
virtual PsbTimerMsg* PsbTimerMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 101 of file SignallingMsg_m.h.
{return new PsbTimerMsg(*this);}
virtual int PsbTimerMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual int PsbTimerMsg::getId () const [virtual]
Referenced by RSVP::processPSB_TIMER().
PsbTimerMsg& PsbTimerMsg::operator= (const PsbTimerMsg & other)
Reimplemented from SignallingMsg.
bool PsbTimerMsg::operator== (const PsbTimerMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void PsbTimerMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void PsbTimerMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void PsbTimerMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void PsbTimerMsg::setId (int id_var) [virtual]
Referenced by RSVP::createIngressPSB(), and RSVP::createPSB().
Member Data Documentation
int PsbTimerMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 91 of file SignallingMsg_m.h.
int PsbTimerMsg::id_var [protected]
Definition at line 90 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h