INET Framework for OMNeT++/OMNEST: EtherFrame Class Reference
EtherFrame Class Reference
#include <EtherFrame_m.h>
Public Member Functions
EtherFrame (const char *name=NULL, int kind=0)
EtherFrame (const EtherFrame &other)
virtual ~EtherFrame ()
EtherFrame & operator= (const EtherFrame &other)
virtual EtherFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getDest ()
virtual const MACAddress & getDest () const
virtual void setDest (const MACAddress &dest_var)
virtual MACAddress & getSrc ()
virtual const MACAddress & getSrc () const
virtual void setSrc (const MACAddress &src_var)
Protected Member Functions
bool operator== (const EtherFrame &)
Protected Attributes
::MACAddress dest_var
::MACAddress src_var
Detailed Description
Class generated from linklayer/ethernet/EtherFrame.msg by opp_msgc.
 packet EtherFrame
 {
     MACAddress dest;
     MACAddress src;
 }
Definition at line 66 of file EtherFrame_m.h.
Constructor & Destructor Documentation
EtherFrame::EtherFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherFrame::EtherFrame (const EtherFrame & other)
virtual EtherFrame::~EtherFrame () [virtual]
Member Function Documentation
virtual EtherFrame* EtherFrame::dup () const [inline, virtual]
Reimplemented in EthernetIIFrame, EtherFrameWithLLC, EtherFrameWithSNAP, and EtherPauseFrame.
Definition at line 80 of file EtherFrame_m.h.
Referenced by MACRelayUnitBase::broadcastFrame(), and EtherMAC2::startFrameTransmission().
{return new EtherFrame(*this);}
virtual const MACAddress& EtherFrame::getDest () const [inline, virtual]
Definition at line 86 of file EtherFrame_m.h.
Referenced by getDest().
{return const_cast<EtherFrame*>(this)->getDest();}
virtual MACAddress& EtherFrame::getDest () [virtual]
Referenced by EtherMACBase::checkDestinationAddress(), Ieee80211MgmtAPBase::convertFromEtherFrame(), MACRelayUnitBase::handleAndDispatchFrame(), Ieee80211MgmtAP::handleUpperMessage(), EtherLLC::processFrameFromMAC(), EtherEncap::processFrameFromMAC(), and EtherMACBase::processFrameFromUpperLayer().
virtual const MACAddress& EtherFrame::getSrc () const [inline, virtual]
Definition at line 89 of file EtherFrame_m.h.
Referenced by getSrc().
{return const_cast<EtherFrame*>(this)->getSrc();}
virtual MACAddress& EtherFrame::getSrc () [virtual]
Referenced by Ieee80211MgmtAPBase::convertFromEtherFrame(), MACRelayUnitBase::handleAndDispatchFrame(), EtherLLC::processFrameFromMAC(), EtherEncap::processFrameFromMAC(), EtherMACBase::processFrameFromUpperLayer(), and EtherMAC2::startFrameTransmission().
EtherFrame& EtherFrame::operator= (const EtherFrame & other)
Reimplemented in EthernetIIFrame, EtherFrameWithLLC, EtherFrameWithSNAP, and EtherPauseFrame.
bool EtherFrame::operator== (const EtherFrame &) [protected]
Reimplemented in EthernetIIFrame, EtherFrameWithLLC, EtherFrameWithSNAP, and EtherPauseFrame.
virtual void EtherFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in EthernetIIFrame, EtherFrameWithLLC, EtherFrameWithSNAP, and EtherPauseFrame.
Referenced by doPacking().
virtual void EtherFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in EthernetIIFrame, EtherFrameWithLLC, EtherFrameWithSNAP, and EtherPauseFrame.
Referenced by doUnpacking().
virtual void EtherFrame::setDest (const MACAddress & dest_var) [virtual]
Referenced by Ieee80211MgmtAPBase::convertToEtherFrame().
virtual void EtherFrame::setSrc (const MACAddress & src_var) [virtual]
Referenced by Ieee80211MgmtAPBase::convertToEtherFrame(), EtherMACBase::processFrameFromUpperLayer(), and EtherMAC2::startFrameTransmission().
Member Data Documentation
::MACAddress EtherFrame::dest_var [protected]
Definition at line 69 of file EtherFrame_m.h.
::MACAddress EtherFrame::src_var [protected]
Definition at line 70 of file EtherFrame_m.h.
The documentation for this class was generated from the following file:
EtherFrame_m.h