INET Framework for OMNeT++/OMNEST: Ieee80211CTSFrame Class Reference
Ieee80211CTSFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211CTSFrame (const char *name=NULL, int kind=0)
Ieee80211CTSFrame (const Ieee80211CTSFrame &other)
virtual ~Ieee80211CTSFrame ()
Ieee80211CTSFrame & operator= (const Ieee80211CTSFrame &other)
virtual Ieee80211CTSFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211CTSFrame &)
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211CTSFrame extends Ieee80211OneAddressFrame
 {
     type = ST_CTS;
 }
Definition at line 274 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211CTSFrame::Ieee80211CTSFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211CTSFrame::Ieee80211CTSFrame (const Ieee80211CTSFrame & other)
virtual Ieee80211CTSFrame::~Ieee80211CTSFrame () [virtual]
Member Function Documentation
virtual Ieee80211CTSFrame* Ieee80211CTSFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211OneAddressFrame.
Definition at line 286 of file Ieee80211Frame_m.h.
{return new Ieee80211CTSFrame(*this);}
Ieee80211CTSFrame& Ieee80211CTSFrame::operator= (const Ieee80211CTSFrame & other)
Reimplemented from Ieee80211OneAddressFrame.
bool Ieee80211CTSFrame::operator== (const Ieee80211CTSFrame &) [protected]
Reimplemented from Ieee80211OneAddressFrame.
virtual void Ieee80211CTSFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211OneAddressFrame.
Referenced by doPacking().
virtual void Ieee80211CTSFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211OneAddressFrame.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h