INET Framework for OMNeT++/OMNEST: SCTPInfo Class Reference
SCTPInfo Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPInfo (const char *name=NULL)
SCTPInfo (const SCTPInfo &other)
virtual ~SCTPInfo ()
SCTPInfo & operator= (const SCTPInfo &other)
virtual SCTPInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getText () const
virtual void setText (int text_var)
Protected Member Functions
bool operator== (const SCTPInfo &)
Protected Attributes
int text_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPInfo extends SCTPCommand
 {
     int text = 0;
 }
Definition at line 461 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPInfo::SCTPInfo (const char * name = NULL)
Referenced by dup().
SCTPInfo::SCTPInfo (const SCTPInfo & other)
virtual SCTPInfo::~SCTPInfo () [virtual]
Member Function Documentation
virtual SCTPInfo* SCTPInfo::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 474 of file SCTPCommand_m.h.
{return new SCTPInfo(*this);}
virtual int SCTPInfo::getText () const [virtual]
Referenced by SCTPAssociation::process_QUEUE_BYTES_LIMIT(), and SCTPAssociation::process_QUEUE_MSGS_LIMIT().
SCTPInfo& SCTPInfo::operator= (const SCTPInfo & other)
Reimplemented from SCTPCommand.
bool SCTPInfo::operator== (const SCTPInfo &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPInfo::setText (int text_var) [virtual]
Referenced by SCTPServer::handleMessage(), SCTPPeer::handleMessage(), SCTPPeer::sendQueueRequest(), and SCTPClient::sendQueueRequest().
Member Data Documentation
int SCTPInfo::text_var [protected]
Definition at line 464 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h