INET Framework for OMNeT++/OMNEST: IPv6AuthenticationHeader Class Reference
IPv6AuthenticationHeader Class Reference
#include <IPv6ExtensionHeaders_m.h>
Public Member Functions
IPv6AuthenticationHeader ()
IPv6AuthenticationHeader (const IPv6AuthenticationHeader &other)
virtual ~IPv6AuthenticationHeader ()
IPv6AuthenticationHeader & operator= (const IPv6AuthenticationHeader &other)
virtual IPv6AuthenticationHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const IPv6AuthenticationHeader &)
Detailed Description
Class generated from networklayer/ipv6/IPv6ExtensionHeaders.msg by opp_msgc.
 class IPv6AuthenticationHeader extends IPv6ExtensionHeader
 {
 }
Definition at line 180 of file IPv6ExtensionHeaders_m.h.
Constructor & Destructor Documentation
IPv6AuthenticationHeader::IPv6AuthenticationHeader ()
Referenced by dup().
IPv6AuthenticationHeader::IPv6AuthenticationHeader (const IPv6AuthenticationHeader & other)
virtual IPv6AuthenticationHeader::~IPv6AuthenticationHeader () [virtual]
Member Function Documentation
virtual IPv6AuthenticationHeader* IPv6AuthenticationHeader::dup () const [inline, virtual]
Reimplemented from IPv6ExtensionHeader.
Definition at line 192 of file IPv6ExtensionHeaders_m.h.
{return new IPv6AuthenticationHeader(*this);}
IPv6AuthenticationHeader& IPv6AuthenticationHeader::operator= (const IPv6AuthenticationHeader & other)
Reimplemented from IPv6ExtensionHeader.
bool IPv6AuthenticationHeader::operator== (const IPv6AuthenticationHeader &) [protected]
Reimplemented from IPv6ExtensionHeader_Base.
virtual void IPv6AuthenticationHeader::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doPacking().
virtual void IPv6AuthenticationHeader::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
IPv6ExtensionHeaders_m.h