INET Framework for OMNeT++/OMNEST: ExtFrame Class Reference
ExtFrame Class Reference
#include <ExtFrame_m.h>
Public Member Functions
ExtFrame (const char *name=NULL, int kind=0)
ExtFrame (const ExtFrame &other)
virtual ~ExtFrame ()
ExtFrame & operator= (const ExtFrame &other)
virtual ExtFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setDataArraySize (unsigned int size)
virtual unsigned int getDataArraySize () const
virtual uint8 getData (unsigned int k) const
virtual void setData (unsigned int k, uint8 data_var)
Protected Member Functions
bool operator== (const ExtFrame &)
Protected Attributes
uint8 * data_var
unsigned int data_arraysize
Detailed Description
Class generated from linklayer/ext/ExtFrame.msg by opp_msgc.
 message ExtFrame
 {
     uint8 data[];
 }
Definition at line 27 of file ExtFrame_m.h.
Constructor & Destructor Documentation
ExtFrame::ExtFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
ExtFrame::ExtFrame (const ExtFrame & other)
virtual ExtFrame::~ExtFrame () [virtual]
Member Function Documentation
virtual ExtFrame* ExtFrame::dup () const [inline, virtual]
Definition at line 41 of file ExtFrame_m.h.
{return new ExtFrame(*this);}
virtual uint8 ExtFrame::getData (unsigned int k) const [virtual]
Referenced by ExtInterface::handleMessage().
virtual unsigned int ExtFrame::getDataArraySize () const [virtual]
Referenced by ExtInterface::handleMessage().
ExtFrame& ExtFrame::operator= (const ExtFrame & other)
bool ExtFrame::operator== (const ExtFrame &) [protected]
virtual void ExtFrame::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ExtFrame::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ExtFrame::setData (unsigned int k, uint8 data_var) [virtual]
virtual void ExtFrame::setDataArraySize (unsigned int size) [virtual]
Member Data Documentation
unsigned int ExtFrame::data_arraysize [protected]
Definition at line 31 of file ExtFrame_m.h.
uint8* ExtFrame::data_var [protected]
Definition at line 30 of file ExtFrame_m.h.
The documentation for this class was generated from the following file:
ExtFrame_m.h