INET Framework for OMNeT++/OMNEST: Blackboard::BBItem Class Reference
Blackboard::BBItem Class Reference
#include <Blackboard.h>
Public Member Functions
const char * getLabel ()
cPolymorphic * getData ()
const cPolymorphic * getData () const
Private Attributes
cPolymorphic * _item
std::string _label
SubscriberVector subscribers
Friends
class Blackboard
Detailed Description
Represents a blackboard item.
Definition at line 170 of file Blackboard.h.
Member Function Documentation
const cPolymorphic* Blackboard::BBItem::getData () const [inline]
Return the data item
Definition at line 183 of file Blackboard.h.
{return _item;}
cPolymorphic* Blackboard::BBItem::getData () [inline]
Return the data item
Definition at line 181 of file Blackboard.h.
Referenced by operator<<().
{return _item;}
const char* Blackboard::BBItem::getLabel () [inline]
Return the label of this data item
Definition at line 179 of file Blackboard.h.
Referenced by Blackboard::changed(), Blackboard::publish(), Blackboard::subscribe(), Blackboard::unsubscribe(), and Blackboard::withdraw().
{return _label.c_str();}
Friends And Related Function Documentation
friend class Blackboard [friend]
Definition at line 173 of file Blackboard.h.
Member Data Documentation
cPolymorphic* Blackboard::BBItem::_item [private]
Definition at line 174 of file Blackboard.h.
Referenced by Blackboard::changed(), Blackboard::publish(), and Blackboard::withdraw().
std::string Blackboard::BBItem::_label [private]
Definition at line 175 of file Blackboard.h.
Referenced by Blackboard::publish(), and Blackboard::withdraw().
SubscriberVector Blackboard::BBItem::subscribers [private]
Definition at line 176 of file Blackboard.h.
Referenced by Blackboard::changed(), Blackboard::subscribe(), Blackboard::unsubscribe(), and Blackboard::withdraw().
The documentation for this class was generated from the following file:
Blackboard.h