INET Framework for OMNeT++/OMNEST: UDPControlInfo Class Reference
UDPControlInfo Class Reference
#include <UDPControlInfo_m.h>
Public Member Functions
UDPControlInfo ()
UDPControlInfo (const UDPControlInfo &other)
virtual ~UDPControlInfo ()
UDPControlInfo & operator= (const UDPControlInfo &other)
virtual UDPControlInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSockId () const
virtual void setSockId (int sockId_var)
virtual int getUserId () const
virtual void setUserId (int userId_var)
virtual IPvXAddress & getSrcAddr ()
virtual const IPvXAddress & getSrcAddr () const
virtual void setSrcAddr (const IPvXAddress &srcAddr_var)
virtual IPvXAddress & getDestAddr ()
virtual const IPvXAddress & getDestAddr () const
virtual void setDestAddr (const IPvXAddress &destAddr_var)
virtual int getSrcPort () const
virtual void setSrcPort (int srcPort_var)
virtual int getDestPort () const
virtual void setDestPort (int destPort_var)
virtual int getInterfaceId () const
virtual void setInterfaceId (int interfaceId_var)
Protected Member Functions
bool operator== (const UDPControlInfo &)
Protected Attributes
int sockId_var
int userId_var
::IPvXAddress srcAddr_var
::IPvXAddress destAddr_var
int srcPort_var
int destPort_var
int interfaceId_var
Detailed Description
Class generated from transport/contract/UDPControlInfo.msg by opp_msgc.
 class UDPControlInfo
 {
     int sockId = -1;
     int userId = -1;
     IPvXAddress srcAddr;
     IPvXAddress destAddr;
     int srcPort;
     int destPort;
     int interfaceId = -1;
 }
Definition at line 74 of file UDPControlInfo_m.h.
Constructor & Destructor Documentation
UDPControlInfo::UDPControlInfo ()
Referenced by dup().
UDPControlInfo::UDPControlInfo (const UDPControlInfo & other)
virtual UDPControlInfo::~UDPControlInfo () [virtual]
Member Function Documentation
virtual UDPControlInfo* UDPControlInfo::dup () const [inline, virtual]
Definition at line 93 of file UDPControlInfo_m.h.
{return new UDPControlInfo(*this);}
virtual const IPvXAddress& UDPControlInfo::getDestAddr () const [inline, virtual]
Definition at line 106 of file UDPControlInfo_m.h.
Referenced by getDestAddr().
{return const_cast<UDPControlInfo*>(this)->getDestAddr();}
virtual IPvXAddress& UDPControlInfo::getDestAddr () [virtual]
Referenced by UDP::bind(), SCTP::handleMessage(), UDPAppBase::printPacket(), UDP::processCommandFromApp(), UDP::processMsgFromApp(), and UDPEchoApp::processPacket().
virtual int UDPControlInfo::getDestPort () const [virtual]
Referenced by UDP::bind(), UDPAppBase::printPacket(), UDP::processCommandFromApp(), UDP::processMsgFromApp(), and UDPEchoApp::processPacket().
virtual int UDPControlInfo::getInterfaceId () const [virtual]
Referenced by UDP::bind(), LDP::processLDPHello(), and UDP::processMsgFromApp().
virtual int UDPControlInfo::getSockId () const [virtual]
Referenced by UDP::bind(), UDP::processCommandFromApp(), and UDPSocket::processMessage().
virtual const IPvXAddress& UDPControlInfo::getSrcAddr () const [inline, virtual]
Definition at line 103 of file UDPControlInfo_m.h.
Referenced by getSrcAddr().
{return const_cast<UDPControlInfo*>(this)->getSrcAddr();}
virtual IPvXAddress& UDPControlInfo::getSrcAddr () [virtual]
Referenced by UDP::bind(), SCTP::handleMessage(), UDPAppBase::printPacket(), UDP::processMsgFromApp(), UDPEchoApp::processPacket(), and UDPVideoStreamSvr::processStreamRequest().
virtual int UDPControlInfo::getSrcPort () const [virtual]
Referenced by UDP::bind(), UDPAppBase::printPacket(), UDP::processMsgFromApp(), UDPEchoApp::processPacket(), and UDPVideoStreamSvr::processStreamRequest().
virtual int UDPControlInfo::getUserId () const [virtual]
Referenced by UDP::bind().
UDPControlInfo& UDPControlInfo::operator= (const UDPControlInfo & other)
bool UDPControlInfo::operator== (const UDPControlInfo &) [protected]
virtual void UDPControlInfo::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void UDPControlInfo::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void UDPControlInfo::setDestAddr (const IPvXAddress & destAddr_var) [virtual]
Referenced by UDPSocket::connect(), RTCP::createPacket(), RTP::dataOut(), UDPEchoApp::processPacket(), SCTP::sendAbortFromMain(), UDPSocket::sendTo(), SCTPAssociation::sendToIP(), UDPAppBase::sendToUDP(), UDP::sendUp(), and UDP::sendUpErrorNotification().
virtual void UDPControlInfo::setDestPort (int destPort_var) [virtual]
Referenced by UDPSocket::connect(), RTCP::createPacket(), RTP::dataOut(), UDPEchoApp::processPacket(), SCTP::sendAbortFromMain(), UDPSocket::sendTo(), SCTPAssociation::sendToIP(), UDPAppBase::sendToUDP(), UDP::sendUp(), and UDP::sendUpErrorNotification().
virtual void UDPControlInfo::setInterfaceId (int interfaceId_var) [virtual]
Referenced by UDPSocket::sendTo(), and UDP::sendUp().
virtual void UDPControlInfo::setSockId (int sockId_var) [virtual]
Referenced by UDPSocket::bind(), SCTP::bindPortForUDP(), UDPAppBase::bindToPort(), UDPSocket::close(), UDPSocket::connect(), RTCP::createPacket(), RTP::createSocket(), RTCP::createSocket(), UDPSocket::sendTo(), UDP::sendUp(), and UDP::sendUpErrorNotification().
virtual void UDPControlInfo::setSrcAddr (const IPvXAddress & srcAddr_var) [virtual]
Referenced by UDPSocket::bind(), RTP::createSocket(), RTCP::createSocket(), UDPEchoApp::processPacket(), UDPSocket::sendTo(), UDP::sendUp(), and UDP::sendUpErrorNotification().
virtual void UDPControlInfo::setSrcPort (int srcPort_var) [virtual]
Referenced by UDPSocket::bind(), SCTP::bindPortForUDP(), UDPAppBase::bindToPort(), RTP::createSocket(), RTCP::createSocket(), UDPEchoApp::processPacket(), SCTP::sendAbortFromMain(), UDPSocket::sendTo(), SCTPAssociation::sendToIP(), UDPAppBase::sendToUDP(), UDP::sendUp(), and UDP::sendUpErrorNotification().
virtual void UDPControlInfo::setUserId (int userId_var) [virtual]
Referenced by UDPSocket::bind(), UDP::sendUp(), and UDP::sendUpErrorNotification().
Member Data Documentation
::IPvXAddress UDPControlInfo::destAddr_var [protected]
Definition at line 80 of file UDPControlInfo_m.h.
int UDPControlInfo::destPort_var [protected]
Definition at line 82 of file UDPControlInfo_m.h.
int UDPControlInfo::interfaceId_var [protected]
Definition at line 83 of file UDPControlInfo_m.h.
int UDPControlInfo::sockId_var [protected]
Definition at line 77 of file UDPControlInfo_m.h.
::IPvXAddress UDPControlInfo::srcAddr_var [protected]
Definition at line 79 of file UDPControlInfo_m.h.
int UDPControlInfo::srcPort_var [protected]
Definition at line 81 of file UDPControlInfo_m.h.
int UDPControlInfo::userId_var [protected]
Definition at line 78 of file UDPControlInfo_m.h.
The documentation for this class was generated from the following file:
UDPControlInfo_m.h