INET Framework for OMNeT++/OMNEST: Ieee80211AuthenticationFrame Class Reference
Ieee80211AuthenticationFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211AuthenticationFrame (const char *name=NULL, int kind=0)
Ieee80211AuthenticationFrame (const Ieee80211AuthenticationFrame &other)
virtual ~Ieee80211AuthenticationFrame ()
Ieee80211AuthenticationFrame & operator= (const Ieee80211AuthenticationFrame &other)
virtual
Ieee80211AuthenticationFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211AuthenticationFrameBody & getBody ()
virtual const
Ieee80211AuthenticationFrameBody & getBody () const
virtual void setBody (const Ieee80211AuthenticationFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211AuthenticationFrame &)
Protected Attributes
::Ieee80211AuthenticationFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211AuthenticationFrame extends Ieee80211ManagementFrame
 {
     type = ST_AUTHENTICATION;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211AuthenticationFrameBody body;
 }
Definition at line 563 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211AuthenticationFrame::Ieee80211AuthenticationFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211AuthenticationFrame::Ieee80211AuthenticationFrame (const Ieee80211AuthenticationFrame & other)
virtual Ieee80211AuthenticationFrame::~Ieee80211AuthenticationFrame () [virtual]
Member Function Documentation
virtual Ieee80211AuthenticationFrame* Ieee80211AuthenticationFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 576 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211AuthenticationFrame(*this);}
virtual const Ieee80211AuthenticationFrameBody& Ieee80211AuthenticationFrame::getBody () const [inline, virtual]
Definition at line 582 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211AuthenticationFrame*>(this)->getBody();}
virtual Ieee80211AuthenticationFrameBody& Ieee80211AuthenticationFrame::getBody () [virtual]
Referenced by Ieee80211MgmtSTA::handleAuthenticationFrame(), Ieee80211MgmtAP::handleAuthenticationFrame(), and Ieee80211MgmtSTA::startAuthentication().
Ieee80211AuthenticationFrame& Ieee80211AuthenticationFrame::operator= (const Ieee80211AuthenticationFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211AuthenticationFrame::operator== (const Ieee80211AuthenticationFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211AuthenticationFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211AuthenticationFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211AuthenticationFrame::setBody (const Ieee80211AuthenticationFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211AuthenticationFrameBody Ieee80211AuthenticationFrame::body_var [protected]
Definition at line 566 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h