INET Framework for OMNeT++/OMNEST: IPv6NDMessage Class Reference
IPv6NDMessage Class Reference
#include <IPv6NDMessage_m.h>
Public Member Functions
IPv6NDMessage (const char *name=NULL, int kind=0)
IPv6NDMessage (const IPv6NDMessage &other)
virtual ~IPv6NDMessage ()
IPv6NDMessage & operator= (const IPv6NDMessage &other)
virtual IPv6NDMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCode () const
virtual void setCode (int code_var)
Protected Member Functions
bool operator== (const IPv6NDMessage &)
Protected Attributes
int code_var
Detailed Description
Class generated from networklayer/icmpv6/IPv6NDMessage.msg by opp_msgc.
 packet IPv6NDMessage extends ICMPv6Message
 {
     int code = 0;
 }
Definition at line 90 of file IPv6NDMessage_m.h.
Constructor & Destructor Documentation
IPv6NDMessage::IPv6NDMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
IPv6NDMessage::IPv6NDMessage (const IPv6NDMessage & other)
virtual IPv6NDMessage::~IPv6NDMessage () [virtual]
Member Function Documentation
virtual IPv6NDMessage* IPv6NDMessage::dup () const [inline, virtual]
Reimplemented from ICMPv6Message.
Reimplemented in IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
Definition at line 103 of file IPv6NDMessage_m.h.
{return new IPv6NDMessage(*this);}
virtual int IPv6NDMessage::getCode () const [virtual]
IPv6NDMessage& IPv6NDMessage::operator= (const IPv6NDMessage & other)
Reimplemented from ICMPv6Message.
Reimplemented in IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
bool IPv6NDMessage::operator== (const IPv6NDMessage &) [protected]
Reimplemented from ICMPv6Message.
Reimplemented in IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
virtual void IPv6NDMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Reimplemented in IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
Referenced by doPacking().
virtual void IPv6NDMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Reimplemented in IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
Referenced by doUnpacking().
virtual void IPv6NDMessage::setCode (int code_var) [virtual]
Member Data Documentation
int IPv6NDMessage::code_var [protected]
Definition at line 93 of file IPv6NDMessage_m.h.
The documentation for this class was generated from the following file:
IPv6NDMessage_m.h