INET Framework for OMNeT++/OMNEST: ICMPMessage Class Reference
ICMPMessage Class Reference
#include <ICMPMessage_m.h>
Public Member Functions
ICMPMessage (const char *name=NULL, int kind=0)
ICMPMessage (const ICMPMessage &other)
virtual ~ICMPMessage ()
ICMPMessage & operator= (const ICMPMessage &other)
virtual ICMPMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type_var)
virtual int getCode () const
virtual void setCode (int code_var)
Protected Member Functions
bool operator== (const ICMPMessage &)
Protected Attributes
int type_var
int code_var
Detailed Description
Class generated from networklayer/ipv4/ICMPMessage.msg by opp_msgc.
 packet ICMPMessage
 {
     int type enum(ICMPType);
     int code;
 }
Definition at line 92 of file ICMPMessage_m.h.
Constructor & Destructor Documentation
ICMPMessage::ICMPMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPMessage::ICMPMessage (const ICMPMessage & other)
virtual ICMPMessage::~ICMPMessage () [virtual]
Member Function Documentation
virtual ICMPMessage* ICMPMessage::dup () const [inline, virtual]
Definition at line 106 of file ICMPMessage_m.h.
{return new ICMPMessage(*this);}
virtual int ICMPMessage::getCode () const [virtual]
Referenced by ErrorHandling::handleMessage(), and UDP::processICMPError().
virtual int ICMPMessage::getType () const [virtual]
Referenced by ErrorHandling::handleMessage(), IP::handleReceivedICMP(), UDP::processICMPError(), ICMP::processICMPMessage(), and ICMP::sendErrorMessage().
ICMPMessage& ICMPMessage::operator= (const ICMPMessage & other)
bool ICMPMessage::operator== (const ICMPMessage &) [protected]
virtual void ICMPMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ICMPMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ICMPMessage::setCode (int code_var) [virtual]
Referenced by ICMP::sendErrorMessage().
virtual void ICMPMessage::setType (int type_var) [virtual]
Referenced by ICMP::processEchoRequest(), ICMP::sendEchoRequest(), and ICMP::sendErrorMessage().
Member Data Documentation
int ICMPMessage::code_var [protected]
Definition at line 96 of file ICMPMessage_m.h.
int ICMPMessage::type_var [protected]
Definition at line 95 of file ICMPMessage_m.h.
The documentation for this class was generated from the following file:
ICMPMessage_m.h