INET Framework for OMNeT++/OMNEST: TCPSocket::CallbackInterface Class Reference
TCPSocket::CallbackInterface Class Reference
#include <TCPSocket.h>
Public Member Functions
virtual ~CallbackInterface ()
virtual void socketDataArrived (int connId, void *yourPtr, cPacket *msg, bool urgent)=0
virtual void socketEstablished (int connId, void *yourPtr)
virtual void socketPeerClosed (int connId, void *yourPtr)
virtual void socketClosed (int connId, void *yourPtr)
virtual void socketFailure (int connId, void *yourPtr, int code)
virtual void socketStatusArrived (int connId, void *yourPtr, TCPStatusInfo *status)
Detailed Description
Abstract base class for your callback objects. See setCallbackObject() and processMessage() for more info.
Note: this class is not subclassed from cPolymorphic, because classes may have both this class and cSimpleModule as base class, and cSimpleModule is already a cPolymorphic.
Definition at line 134 of file TCPSocket.h.
Constructor & Destructor Documentation
virtual TCPSocket::CallbackInterface::~CallbackInterface () [inline, virtual]
Definition at line 137 of file TCPSocket.h.
{}
Member Function Documentation
virtual void TCPSocket::CallbackInterface::socketClosed (int connId, void * yourPtr) [inline, virtual]
Reimplemented in TCPBasicClientApp, TCPGenericCliAppBase, TCPServerThreadBase, TelnetApp, and LDP.
Definition at line 141 of file TCPSocket.h.
Referenced by TCPSocket::processMessage().
{}
virtual void TCPSocket::CallbackInterface::socketDataArrived (int connId, void * yourPtr, cPacket * msg, bool urgent) [pure virtual]
Implemented in TCPBasicClientApp, TCPGenericCliAppBase, TCPServerThreadBase, TelnetApp, and LDP.
Referenced by TCPSocket::processMessage().
virtual void TCPSocket::CallbackInterface::socketEstablished (int connId, void * yourPtr) [inline, virtual]
Reimplemented in TCPBasicClientApp, TCPGenericCliAppBase, TCPServerThreadBase, TelnetApp, and LDP.
Definition at line 139 of file TCPSocket.h.
Referenced by TCPSocket::processMessage().
{}
virtual void TCPSocket::CallbackInterface::socketFailure (int connId, void * yourPtr, int code) [inline, virtual]
Reimplemented in TCPBasicClientApp, TCPGenericCliAppBase, TCPServerThreadBase, TelnetApp, and LDP.
Definition at line 142 of file TCPSocket.h.
Referenced by TCPSocket::processMessage().
{}
virtual void TCPSocket::CallbackInterface::socketPeerClosed (int connId, void * yourPtr) [inline, virtual]
Reimplemented in TCPGenericCliAppBase, TCPServerThreadBase, and LDP.
Definition at line 140 of file TCPSocket.h.
Referenced by TCPSocket::processMessage().
{}
virtual void TCPSocket::CallbackInterface::socketStatusArrived (int connId, void * yourPtr, TCPStatusInfo * status) [inline, virtual]
Reimplemented in TCPGenericCliAppBase, TCPServerThreadBase, and LDP.
Definition at line 143 of file TCPSocket.h.
Referenced by TCPSocket::processMessage().
{delete status;}
The documentation for this class was generated from the following file:
TCPSocket.h