INET Framework for OMNeT++/OMNEST: OSPFTimer Class Reference
OSPFTimer Class Reference
#include <OSPFTimer_m.h>
Public Member Functions
OSPFTimer (const char *name=NULL, int kind=0)
OSPFTimer (const OSPFTimer &other)
virtual ~OSPFTimer ()
OSPFTimer & operator= (const OSPFTimer &other)
virtual OSPFTimer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual char getTimerKind () const
virtual void setTimerKind (char timerKind_var)
Protected Member Functions
bool operator== (const OSPFTimer &)
Protected Attributes
char timerKind_var
Detailed Description
Class generated from networklayer/ospfv2/OSPFTimer.msg by opp_msgc.
 packet OSPFTimer extends cMessage
 {
     char timerKind enum(OSPFTimerType) = InterfaceHelloTimer;
 }
Definition at line 62 of file OSPFTimer_m.h.
Constructor & Destructor Documentation
OSPFTimer::OSPFTimer (const char * name = NULL, int kind = 0)
Referenced by dup().
OSPFTimer::OSPFTimer (const OSPFTimer & other)
virtual OSPFTimer::~OSPFTimer () [virtual]
Member Function Documentation
virtual OSPFTimer* OSPFTimer::dup () const [inline, virtual]
Definition at line 75 of file OSPFTimer_m.h.
{return new OSPFTimer(*this);}
virtual char OSPFTimer::getTimerKind () const [virtual]
Referenced by OSPF::MessageHandler::HandleTimer().
OSPFTimer& OSPFTimer::operator= (const OSPFTimer & other)
bool OSPFTimer::operator== (const OSPFTimer &) [protected]
virtual void OSPFTimer::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void OSPFTimer::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void OSPFTimer::setTimerKind (char timerKind_var) [virtual]
Referenced by OSPF::Interface::Interface(), OSPF::Neighbor::Neighbor(), and OSPF::Router::Router().
Member Data Documentation
char OSPFTimer::timerKind_var [protected]
Definition at line 65 of file OSPFTimer_m.h.
The documentation for this class was generated from the following file:
OSPFTimer_m.h