INET Framework for OMNeT++/OMNEST: Ieee80211AssociationResponseFrameBody Class Reference
Ieee80211AssociationResponseFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211AssociationResponseFrameBody ()
Ieee80211AssociationResponseFrameBody (const Ieee80211AssociationResponseFrameBody &other)
virtual ~Ieee80211AssociationResponseFrameBody ()
Ieee80211AssociationResponseFrameBody & operator= (const Ieee80211AssociationResponseFrameBody &other)
virtual
Ieee80211AssociationResponseFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getStatusCode () const
virtual void setStatusCode (int statusCode_var)
virtual short getAid () const
virtual void setAid (short aid_var)
virtual
Ieee80211SupportedRatesElement & getSupportedRates ()
virtual const
Ieee80211SupportedRatesElement & getSupportedRates () const
virtual void setSupportedRates (const Ieee80211SupportedRatesElement &supportedRates_var)
Protected Member Functions
bool operator== (const Ieee80211AssociationResponseFrameBody &)
Protected Attributes
int statusCode_var
short aid_var
::Ieee80211SupportedRatesElement supportedRates_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211AssociationResponseFrameBody extends Ieee80211FrameBody
 {
     bodyLength = 26;
     int statusCode enum(Ieee80211StatusCode);
     short aid;
     Ieee80211SupportedRatesElement supportedRates;
 }
Definition at line 407 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211AssociationResponseFrameBody::Ieee80211AssociationResponseFrameBody ()
Referenced by dup().
Ieee80211AssociationResponseFrameBody::Ieee80211AssociationResponseFrameBody (const Ieee80211AssociationResponseFrameBody & other)
virtual Ieee80211AssociationResponseFrameBody::~Ieee80211AssociationResponseFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211AssociationResponseFrameBody* Ieee80211AssociationResponseFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationResponseFrameBody.
Definition at line 422 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211AssociationResponseFrameBody(*this);}
virtual short Ieee80211AssociationResponseFrameBody::getAid () const [virtual]
virtual int Ieee80211AssociationResponseFrameBody::getStatusCode () const [virtual]
Referenced by Ieee80211MgmtSTA::handleAssociationResponseFrame().
virtual const Ieee80211SupportedRatesElement& Ieee80211AssociationResponseFrameBody::getSupportedRates () const [inline, virtual]
Definition at line 432 of file Ieee80211MgmtFrames_m.h.
Referenced by getSupportedRates().
{return const_cast<Ieee80211AssociationResponseFrameBody*>(this)->getSupportedRates();}
virtual Ieee80211SupportedRatesElement& Ieee80211AssociationResponseFrameBody::getSupportedRates () [virtual]
Ieee80211AssociationResponseFrameBody& Ieee80211AssociationResponseFrameBody::operator= (const Ieee80211AssociationResponseFrameBody & other)
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationResponseFrameBody.
bool Ieee80211AssociationResponseFrameBody::operator== (const Ieee80211AssociationResponseFrameBody &) [protected]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationResponseFrameBody.
virtual void Ieee80211AssociationResponseFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationResponseFrameBody.
Referenced by doPacking().
virtual void Ieee80211AssociationResponseFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationResponseFrameBody.
Referenced by doUnpacking().
virtual void Ieee80211AssociationResponseFrameBody::setAid (short aid_var) [virtual]
Referenced by Ieee80211MgmtAP::handleAssociationRequestFrame(), and Ieee80211MgmtAP::handleReassociationRequestFrame().
virtual void Ieee80211AssociationResponseFrameBody::setStatusCode (int statusCode_var) [virtual]
Referenced by Ieee80211MgmtAP::handleAssociationRequestFrame(), and Ieee80211MgmtAP::handleReassociationRequestFrame().
virtual void Ieee80211AssociationResponseFrameBody::setSupportedRates (const Ieee80211SupportedRatesElement & supportedRates_var) [virtual]
Referenced by Ieee80211MgmtAP::handleAssociationRequestFrame(), and Ieee80211MgmtAP::handleReassociationRequestFrame().
Member Data Documentation
short Ieee80211AssociationResponseFrameBody::aid_var [protected]
Definition at line 411 of file Ieee80211MgmtFrames_m.h.
int Ieee80211AssociationResponseFrameBody::statusCode_var [protected]
Definition at line 410 of file Ieee80211MgmtFrames_m.h.
::Ieee80211SupportedRatesElement Ieee80211AssociationResponseFrameBody::supportedRates_var [protected]
Definition at line 412 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h