INET Framework for OMNeT++/OMNEST: Ieee80211FrameBody Class Reference
Ieee80211FrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211FrameBody ()
Ieee80211FrameBody (const Ieee80211FrameBody &other)
virtual ~Ieee80211FrameBody ()
Ieee80211FrameBody & operator= (const Ieee80211FrameBody &other)
virtual Ieee80211FrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual short getBodyLength () const
virtual void setBodyLength (short bodyLength_var)
Protected Member Functions
bool operator== (const Ieee80211FrameBody &)
Protected Attributes
short bodyLength_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211FrameBody
 {
     short bodyLength;
 }
Definition at line 141 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211FrameBody::Ieee80211FrameBody ()
Referenced by dup().
Ieee80211FrameBody::Ieee80211FrameBody (const Ieee80211FrameBody & other)
virtual Ieee80211FrameBody::~Ieee80211FrameBody () [virtual]
Member Function Documentation
virtual Ieee80211FrameBody* Ieee80211FrameBody::dup () const [inline, virtual]
Reimplemented in Ieee80211AuthenticationFrameBody, Ieee80211DeauthenticationFrameBody, Ieee80211DisassociationFrameBody, Ieee80211ProbeRequestFrameBody, Ieee80211AssociationRequestFrameBody, Ieee80211ReassociationRequestFrameBody, Ieee80211AssociationResponseFrameBody, Ieee80211ReassociationResponseFrameBody, Ieee80211BeaconFrameBody, and Ieee80211ProbeResponseFrameBody.
Definition at line 154 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211FrameBody(*this);}
virtual short Ieee80211FrameBody::getBodyLength () const [virtual]
Ieee80211FrameBody& Ieee80211FrameBody::operator= (const Ieee80211FrameBody & other)
Reimplemented in Ieee80211AuthenticationFrameBody, Ieee80211DeauthenticationFrameBody, Ieee80211DisassociationFrameBody, Ieee80211ProbeRequestFrameBody, Ieee80211AssociationRequestFrameBody, Ieee80211ReassociationRequestFrameBody, Ieee80211AssociationResponseFrameBody, Ieee80211ReassociationResponseFrameBody, Ieee80211BeaconFrameBody, and Ieee80211ProbeResponseFrameBody.
bool Ieee80211FrameBody::operator== (const Ieee80211FrameBody &) [protected]
Reimplemented in Ieee80211AuthenticationFrameBody, Ieee80211DeauthenticationFrameBody, Ieee80211DisassociationFrameBody, Ieee80211ProbeRequestFrameBody, Ieee80211AssociationRequestFrameBody, Ieee80211ReassociationRequestFrameBody, Ieee80211AssociationResponseFrameBody, Ieee80211ReassociationResponseFrameBody, Ieee80211BeaconFrameBody, and Ieee80211ProbeResponseFrameBody.
virtual void Ieee80211FrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211AuthenticationFrameBody, Ieee80211DeauthenticationFrameBody, Ieee80211DisassociationFrameBody, Ieee80211ProbeRequestFrameBody, Ieee80211AssociationRequestFrameBody, Ieee80211ReassociationRequestFrameBody, Ieee80211AssociationResponseFrameBody, Ieee80211ReassociationResponseFrameBody, Ieee80211BeaconFrameBody, and Ieee80211ProbeResponseFrameBody.
Referenced by doPacking().
virtual void Ieee80211FrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211AuthenticationFrameBody, Ieee80211DeauthenticationFrameBody, Ieee80211DisassociationFrameBody, Ieee80211ProbeRequestFrameBody, Ieee80211AssociationRequestFrameBody, Ieee80211ReassociationRequestFrameBody, Ieee80211AssociationResponseFrameBody, Ieee80211ReassociationResponseFrameBody, Ieee80211BeaconFrameBody, and Ieee80211ProbeResponseFrameBody.
Referenced by doUnpacking().
virtual void Ieee80211FrameBody::setBodyLength (short bodyLength_var) [virtual]
Member Data Documentation
short Ieee80211FrameBody::bodyLength_var [protected]
Definition at line 144 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h