INET Framework for OMNeT++/OMNEST: Ieee80211DeauthenticationFrame Class Reference
Ieee80211DeauthenticationFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211DeauthenticationFrame (const char *name=NULL, int kind=0)
Ieee80211DeauthenticationFrame (const Ieee80211DeauthenticationFrame &other)
virtual ~Ieee80211DeauthenticationFrame ()
Ieee80211DeauthenticationFrame & operator= (const Ieee80211DeauthenticationFrame &other)
virtual
Ieee80211DeauthenticationFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211DeauthenticationFrameBody & getBody ()
virtual const
Ieee80211DeauthenticationFrameBody & getBody () const
virtual void setBody (const Ieee80211DeauthenticationFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211DeauthenticationFrame &)
Protected Attributes
::Ieee80211DeauthenticationFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211DeauthenticationFrame extends Ieee80211ManagementFrame
 {
     type = ST_DEAUTHENTICATION;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211DeauthenticationFrameBody body;
 }
Definition at line 600 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211DeauthenticationFrame::Ieee80211DeauthenticationFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211DeauthenticationFrame::Ieee80211DeauthenticationFrame (const Ieee80211DeauthenticationFrame & other)
virtual Ieee80211DeauthenticationFrame::~Ieee80211DeauthenticationFrame () [virtual]
Member Function Documentation
virtual Ieee80211DeauthenticationFrame* Ieee80211DeauthenticationFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 613 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211DeauthenticationFrame(*this);}
virtual const Ieee80211DeauthenticationFrameBody& Ieee80211DeauthenticationFrame::getBody () const [inline, virtual]
Definition at line 619 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211DeauthenticationFrame*>(this)->getBody();}
virtual Ieee80211DeauthenticationFrameBody& Ieee80211DeauthenticationFrame::getBody () [virtual]
Referenced by Ieee80211MgmtAP::handleAssociationRequestFrame(), Ieee80211MgmtAP::handleReassociationRequestFrame(), and Ieee80211MgmtSTA::processDeauthenticateCommand().
Ieee80211DeauthenticationFrame& Ieee80211DeauthenticationFrame::operator= (const Ieee80211DeauthenticationFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211DeauthenticationFrame::operator== (const Ieee80211DeauthenticationFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211DeauthenticationFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211DeauthenticationFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211DeauthenticationFrame::setBody (const Ieee80211DeauthenticationFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211DeauthenticationFrameBody Ieee80211DeauthenticationFrame::body_var [protected]
Definition at line 603 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h