INET Framework for OMNeT++/OMNEST: HelloTimeoutMsg Class Reference
HelloTimeoutMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
HelloTimeoutMsg (const char *name=NULL, int kind=0)
HelloTimeoutMsg (const HelloTimeoutMsg &other)
virtual ~HelloTimeoutMsg ()
HelloTimeoutMsg & operator= (const HelloTimeoutMsg &other)
virtual HelloTimeoutMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getPeer ()
virtual const IPAddress & getPeer () const
virtual void setPeer (const IPAddress &peer_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const HelloTimeoutMsg &)
Protected Attributes
::IPAddress peer_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message HelloTimeoutMsg extends SignallingMsg
 {
     IPAddress peer;
     int command = MSG_HELLO_TIMEOUT;
 }
Definition at line 322 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
HelloTimeoutMsg::HelloTimeoutMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
HelloTimeoutMsg::HelloTimeoutMsg (const HelloTimeoutMsg & other)
virtual HelloTimeoutMsg::~HelloTimeoutMsg () [virtual]
Member Function Documentation
virtual HelloTimeoutMsg* HelloTimeoutMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 336 of file SignallingMsg_m.h.
{return new HelloTimeoutMsg(*this);}
virtual int HelloTimeoutMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual const IPAddress& HelloTimeoutMsg::getPeer () const [inline, virtual]
Definition at line 342 of file SignallingMsg_m.h.
Referenced by getPeer().
{return const_cast<HelloTimeoutMsg*>(this)->getPeer();}
virtual IPAddress& HelloTimeoutMsg::getPeer () [virtual]
Referenced by RSVP::processHELLO_TIMEOUT().
HelloTimeoutMsg& HelloTimeoutMsg::operator= (const HelloTimeoutMsg & other)
Reimplemented from SignallingMsg.
bool HelloTimeoutMsg::operator== (const HelloTimeoutMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void HelloTimeoutMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void HelloTimeoutMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void HelloTimeoutMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void HelloTimeoutMsg::setPeer (const IPAddress & peer_var) [virtual]
Referenced by RSVP::setupHello().
Member Data Documentation
int HelloTimeoutMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 326 of file SignallingMsg_m.h.
::IPAddress HelloTimeoutMsg::peer_var [protected]
Definition at line 325 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h