INET Framework for OMNeT++/OMNEST: Ieee80211AssociationRequestFrameBody Class Reference
Ieee80211AssociationRequestFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211AssociationRequestFrameBody ()
Ieee80211AssociationRequestFrameBody (const Ieee80211AssociationRequestFrameBody &other)
virtual ~Ieee80211AssociationRequestFrameBody ()
Ieee80211AssociationRequestFrameBody & operator= (const Ieee80211AssociationRequestFrameBody &other)
virtual
Ieee80211AssociationRequestFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getSSID () const
virtual void setSSID (const char *SSID_var)
virtual
Ieee80211SupportedRatesElement & getSupportedRates ()
virtual const
Ieee80211SupportedRatesElement & getSupportedRates () const
virtual void setSupportedRates (const Ieee80211SupportedRatesElement &supportedRates_var)
Protected Member Functions
bool operator== (const Ieee80211AssociationRequestFrameBody &)
Protected Attributes
opp_string SSID_var
::Ieee80211SupportedRatesElement supportedRates_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211AssociationRequestFrameBody extends Ieee80211FrameBody
 {
     bodyLength = 16;
     string SSID;
     Ieee80211SupportedRatesElement supportedRates;
 }
Definition at line 330 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211AssociationRequestFrameBody::Ieee80211AssociationRequestFrameBody ()
Referenced by dup().
Ieee80211AssociationRequestFrameBody::Ieee80211AssociationRequestFrameBody (const Ieee80211AssociationRequestFrameBody & other)
virtual Ieee80211AssociationRequestFrameBody::~Ieee80211AssociationRequestFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211AssociationRequestFrameBody* Ieee80211AssociationRequestFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationRequestFrameBody.
Definition at line 344 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211AssociationRequestFrameBody(*this);}
virtual const char* Ieee80211AssociationRequestFrameBody::getSSID () const [virtual]
virtual const Ieee80211SupportedRatesElement& Ieee80211AssociationRequestFrameBody::getSupportedRates () const [inline, virtual]
Definition at line 352 of file Ieee80211MgmtFrames_m.h.
Referenced by getSupportedRates().
{return const_cast<Ieee80211AssociationRequestFrameBody*>(this)->getSupportedRates();}
virtual Ieee80211SupportedRatesElement& Ieee80211AssociationRequestFrameBody::getSupportedRates () [virtual]
Ieee80211AssociationRequestFrameBody& Ieee80211AssociationRequestFrameBody::operator= (const Ieee80211AssociationRequestFrameBody & other)
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationRequestFrameBody.
bool Ieee80211AssociationRequestFrameBody::operator== (const Ieee80211AssociationRequestFrameBody &) [protected]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationRequestFrameBody.
virtual void Ieee80211AssociationRequestFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationRequestFrameBody.
Referenced by doPacking().
virtual void Ieee80211AssociationRequestFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Reimplemented in Ieee80211ReassociationRequestFrameBody.
Referenced by doUnpacking().
virtual void Ieee80211AssociationRequestFrameBody::setSSID (const char * SSID_var) [virtual]
virtual void Ieee80211AssociationRequestFrameBody::setSupportedRates (const Ieee80211SupportedRatesElement & supportedRates_var) [virtual]
Member Data Documentation
opp_string Ieee80211AssociationRequestFrameBody::SSID_var [protected]
Definition at line 333 of file Ieee80211MgmtFrames_m.h.
::Ieee80211SupportedRatesElement Ieee80211AssociationRequestFrameBody::supportedRates_var [protected]
Definition at line 334 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h