INET Framework for OMNeT++/OMNEST: TCPOption Class Reference
TCPOption Class Reference
#include <TCPSegment_m.h>
Public Member Functions
TCPOption ()
TCPOption (const TCPOption &other)
virtual ~TCPOption ()
TCPOption & operator= (const TCPOption &other)
virtual TCPOption * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned short getKind () const
virtual void setKind (unsigned short kind_var)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length_var)
virtual void setValuesArraySize (unsigned int size)
virtual unsigned int getValuesArraySize () const
virtual unsigned int getValues (unsigned int k) const
virtual void setValues (unsigned int k, unsigned int values_var)
Protected Member Functions
bool operator== (const TCPOption &)
Protected Attributes
unsigned short kind_var
unsigned short length_var
unsigned int * values_var
unsigned int values_arraysize
Detailed Description
Class generated from transport/tcp/TCPSegment.msg by opp_msgc.
 class TCPOption
 {
     unsigned short kind enum(TCPOptionNumbers) = TCPOPTION_END_OF_OPTION_LIST;
     unsigned short length = 1;
     unsigned int values[];
 }
Definition at line 155 of file TCPSegment_m.h.
Constructor & Destructor Documentation
TCPOption::TCPOption ()
Referenced by dup().
TCPOption::TCPOption (const TCPOption & other)
virtual TCPOption::~TCPOption () [virtual]
Member Function Documentation
virtual TCPOption* TCPOption::dup () const [inline, virtual]
Definition at line 171 of file TCPSegment_m.h.
{return new TCPOption(*this);}
virtual unsigned short TCPOption::getKind () const [virtual]
Referenced by TCPConnection::readHeaderOptions(), TCPSerializer::serialize(), and TCPDumper::tcpDump().
virtual unsigned short TCPOption::getLength () const [virtual]
Referenced by TCPConnection::addSacks(), TCPConnection::processMSSOption(), TCPConnection::processSACKOption(), TCPConnection::processSACKPermittedOption(), TCPConnection::readHeaderOptions(), TCPSerializer::serialize(), TCPDumper::tcpDump(), and TCPConnection::writeHeaderOptions().
virtual unsigned int TCPOption::getValues (unsigned int k) const [virtual]
Referenced by TCPConnection::addSacks(), TCPConnection::processMSSOption(), TCPConnection::processSACKOption(), and TCPSerializer::serialize().
virtual unsigned int TCPOption::getValuesArraySize () const [virtual]
Referenced by TCPConnection::processMSSOption(), TCPConnection::processSACKOption(), and TCPSerializer::serialize().
TCPOption& TCPOption::operator= (const TCPOption & other)
bool TCPOption::operator== (const TCPOption &) [protected]
virtual void TCPOption::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TCPOption::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void TCPOption::setKind (unsigned short kind_var) [virtual]
Referenced by TCPConnection::addSacks(), TCPSerializer::parse(), and TCPConnection::writeHeaderOptions().
virtual void TCPOption::setLength (unsigned short length_var) [virtual]
Referenced by TCPConnection::addSacks(), TCPSerializer::parse(), and TCPConnection::writeHeaderOptions().
virtual void TCPOption::setValues (unsigned int k, unsigned int values_var) [virtual]
Referenced by TCPConnection::addSacks(), TCPSerializer::parse(), and TCPConnection::writeHeaderOptions().
virtual void TCPOption::setValuesArraySize (unsigned int size) [virtual]
Referenced by TCPConnection::addSacks(), TCPSerializer::parse(), and TCPConnection::writeHeaderOptions().
Member Data Documentation
unsigned short TCPOption::kind_var [protected]
Definition at line 158 of file TCPSegment_m.h.
unsigned short TCPOption::length_var [protected]
Definition at line 159 of file TCPSegment_m.h.
unsigned int TCPOption::values_arraysize [protected]
Definition at line 161 of file TCPSegment_m.h.
unsigned int* TCPOption::values_var [protected]
Definition at line 160 of file TCPSegment_m.h.
The documentation for this class was generated from the following file:
TCPSegment_m.h