INET Framework for OMNeT++/OMNEST: Ieee80211Prim_BSSDescription Class Reference
Ieee80211Prim_BSSDescription Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_BSSDescription ()
Ieee80211Prim_BSSDescription (const Ieee80211Prim_BSSDescription &other)
virtual ~Ieee80211Prim_BSSDescription ()
Ieee80211Prim_BSSDescription & operator= (const Ieee80211Prim_BSSDescription &other)
virtual
Ieee80211Prim_BSSDescription * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber_var)
virtual MACAddress & getBSSID ()
virtual const MACAddress & getBSSID () const
virtual void setBSSID (const MACAddress &BSSID_var)
virtual const char * getSSID () const
virtual void setSSID (const char *SSID_var)
virtual
Ieee80211SupportedRatesElement & getSupportedRates ()
virtual const
Ieee80211SupportedRatesElement & getSupportedRates () const
virtual void setSupportedRates (const Ieee80211SupportedRatesElement &supportedRates_var)
virtual simtime_t getBeaconInterval () const
virtual void setBeaconInterval (simtime_t beaconInterval_var)
virtual double getRxPower () const
virtual void setRxPower (double rxPower_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_BSSDescription &)
Protected Attributes
int channelNumber_var
::MACAddress BSSID_var
opp_string SSID_var
::Ieee80211SupportedRatesElement supportedRates_var
simtime_t beaconInterval_var
double rxPower_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_BSSDescription
 {
     int channelNumber;
     MACAddress BSSID;
     string SSID;
     Ieee80211SupportedRatesElement supportedRates;
     simtime_t beaconInterval;
     double rxPower;
 }
Definition at line 256 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_BSSDescription::Ieee80211Prim_BSSDescription ()
Referenced by dup().
Ieee80211Prim_BSSDescription::Ieee80211Prim_BSSDescription (const Ieee80211Prim_BSSDescription & other)
virtual Ieee80211Prim_BSSDescription::~Ieee80211Prim_BSSDescription () [virtual]
Member Function Documentation
virtual Ieee80211Prim_BSSDescription* Ieee80211Prim_BSSDescription::dup () const [inline, virtual]
Definition at line 274 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_BSSDescription(*this);}
virtual simtime_t Ieee80211Prim_BSSDescription::getBeaconInterval () const [virtual]
Referenced by Ieee80211AgentSTA::dumpAPList().
virtual const MACAddress& Ieee80211Prim_BSSDescription::getBSSID () const [inline, virtual]
Definition at line 282 of file Ieee80211Primitives_m.h.
Referenced by getBSSID().
{return const_cast<Ieee80211Prim_BSSDescription*>(this)->getBSSID();}
virtual MACAddress& Ieee80211Prim_BSSDescription::getBSSID () [virtual]
Referenced by Ieee80211AgentSTA::dumpAPList(), and Ieee80211AgentSTA::processScanConfirm().
virtual int Ieee80211Prim_BSSDescription::getChannelNumber () const [virtual]
Referenced by Ieee80211AgentSTA::dumpAPList().
virtual double Ieee80211Prim_BSSDescription::getRxPower () const [virtual]
Referenced by Ieee80211AgentSTA::chooseBSS(), and Ieee80211AgentSTA::dumpAPList().
virtual const char* Ieee80211Prim_BSSDescription::getSSID () const [virtual]
Referenced by Ieee80211AgentSTA::dumpAPList().
virtual const Ieee80211SupportedRatesElement& Ieee80211Prim_BSSDescription::getSupportedRates () const [inline, virtual]
Definition at line 287 of file Ieee80211Primitives_m.h.
Referenced by getSupportedRates().
{return const_cast<Ieee80211Prim_BSSDescription*>(this)->getSupportedRates();}
virtual Ieee80211SupportedRatesElement& Ieee80211Prim_BSSDescription::getSupportedRates () [virtual]
Ieee80211Prim_BSSDescription& Ieee80211Prim_BSSDescription::operator= (const Ieee80211Prim_BSSDescription & other)
bool Ieee80211Prim_BSSDescription::operator== (const Ieee80211Prim_BSSDescription &) [protected]
virtual void Ieee80211Prim_BSSDescription::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void Ieee80211Prim_BSSDescription::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void Ieee80211Prim_BSSDescription::setBeaconInterval (simtime_t beaconInterval_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendScanConfirm().
virtual void Ieee80211Prim_BSSDescription::setBSSID (const MACAddress & BSSID_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendScanConfirm().
virtual void Ieee80211Prim_BSSDescription::setChannelNumber (int channelNumber_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendScanConfirm().
virtual void Ieee80211Prim_BSSDescription::setRxPower (double rxPower_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendScanConfirm().
virtual void Ieee80211Prim_BSSDescription::setSSID (const char * SSID_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendScanConfirm().
virtual void Ieee80211Prim_BSSDescription::setSupportedRates (const Ieee80211SupportedRatesElement & supportedRates_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendScanConfirm().
Member Data Documentation
simtime_t Ieee80211Prim_BSSDescription::beaconInterval_var [protected]
Definition at line 263 of file Ieee80211Primitives_m.h.
::MACAddress Ieee80211Prim_BSSDescription::BSSID_var [protected]
Definition at line 260 of file Ieee80211Primitives_m.h.
int Ieee80211Prim_BSSDescription::channelNumber_var [protected]
Definition at line 259 of file Ieee80211Primitives_m.h.
double Ieee80211Prim_BSSDescription::rxPower_var [protected]
Definition at line 264 of file Ieee80211Primitives_m.h.
opp_string Ieee80211Prim_BSSDescription::SSID_var [protected]
Definition at line 261 of file Ieee80211Primitives_m.h.
::Ieee80211SupportedRatesElement Ieee80211Prim_BSSDescription::supportedRates_var [protected]
Definition at line 262 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h