INET Framework for OMNeT++/OMNEST: RSVPResvMsg Class Reference
RSVPResvMsg Class Reference
#include <RSVPResvMsg.h>
Public Member Functions
RSVPResvMsg (const char *name=NULL, int kind=RESV_MESSAGE)
RSVPResvMsg (const RSVPResvMsg &other)
RSVPResvMsg & operator= (const RSVPResvMsg &other)
virtual RSVPResvMsg * dup () const
IPAddress getNHOP ()
IPAddress getLIH ()
Detailed Description
RSVP RESV message
This class adds convenience get() and set() methods to the generated base class, but no extra data.
Definition at line 28 of file RSVPResvMsg.h.
Constructor & Destructor Documentation
RSVPResvMsg::RSVPResvMsg (const char * name = NULL, int kind = RESV_MESSAGE) [inline]
Definition at line 31 of file RSVPResvMsg.h.
Referenced by dup().
: RSVPResvMsg_Base(name,kind) {}
RSVPResvMsg::RSVPResvMsg (const RSVPResvMsg & other) [inline]
Definition at line 32 of file RSVPResvMsg.h.
: RSVPResvMsg_Base(other.getName()) {operator=(other);}
Member Function Documentation
virtual RSVPResvMsg* RSVPResvMsg::dup () const [inline, virtual]
Reimplemented from RSVPResvMsg_Base.
Definition at line 34 of file RSVPResvMsg.h.
{return new RSVPResvMsg(*this);}
IPAddress RSVPResvMsg::getLIH () [inline]
Definition at line 37 of file RSVPResvMsg.h.
Referenced by RSVP::createRSB(), and RSVP::processResvMsg().
{return getHop().Logical_Interface_Handle;}
IPAddress RSVPResvMsg::getNHOP () [inline]
Definition at line 36 of file RSVPResvMsg.h.
Referenced by RSVP::createRSB(), and RSVP::processResvMsg().
{return getHop().Next_Hop_Address;}
RSVPResvMsg& RSVPResvMsg::operator= (const RSVPResvMsg & other) [inline]
Reimplemented from RSVPResvMsg_Base.
Definition at line 33 of file RSVPResvMsg.h.
Referenced by RSVPResvMsg().
{RSVPResvMsg_Base::operator=(other); return *this;}
The documentation for this class was generated from the following file:
RSVPResvMsg.h