INET Framework for OMNeT++/OMNEST: OSPF::NetworkLSA Class Reference
OSPF::NetworkLSA Class Reference
#include <LSA.h>
Public Member Functions
NetworkLSA (void)
NetworkLSA (const OSPFNetworkLSA &lsa)
NetworkLSA (const NetworkLSA &lsa)
virtual ~NetworkLSA (void)
bool ValidateLSChecksum () const
bool Update (const OSPFNetworkLSA *lsa)
bool DiffersFrom (const OSPFNetworkLSA *networkLSA) const
Detailed Description
Definition at line 97 of file LSA.h.
Constructor & Destructor Documentation
OSPF::NetworkLSA::NetworkLSA (void) [inline]
Definition at line 102 of file LSA.h.
: OSPFNetworkLSA(), RoutingInfo(), LSATrackingInfo() {}
OSPF::NetworkLSA::NetworkLSA (const OSPFNetworkLSA & lsa) [inline]
Definition at line 103 of file LSA.h.
: OSPFNetworkLSA(lsa), RoutingInfo(), LSATrackingInfo() {}
OSPF::NetworkLSA::NetworkLSA (const NetworkLSA & lsa) [inline]
Definition at line 104 of file LSA.h.
: OSPFNetworkLSA(lsa), RoutingInfo(lsa), LSATrackingInfo(lsa) {}
virtual OSPF::NetworkLSA::~NetworkLSA (void) [inline, virtual]
Definition at line 105 of file LSA.h.
{}
Member Function Documentation
bool OSPF::NetworkLSA::DiffersFrom (const OSPFNetworkLSA * networkLSA) const
Definition at line 33 of file NetworkLSA.cc.
Referenced by Update().
{
    const OSPFLSAHeader& lsaHeader = networkLSA->getHeader();
    bool differentHeader = ((header_var.getLsOptions() != lsaHeader.getLsOptions()) ||
                            ((header_var.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                            ((header_var.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                            (header_var.getLsaLength() != lsaHeader.getLsaLength()));
    bool differentBody   = false;
    if (!differentHeader) {
        differentBody = ((networkMask_var != networkLSA->getNetworkMask()) ||
                         (attachedRouters_arraysize != networkLSA->getAttachedRoutersArraySize()));
        if (!differentBody) {
            unsigned int routerCount = attachedRouters_arraysize;
            for (unsigned int i = 0; i < routerCount; i++) {
                if (attachedRouters_var[i] != networkLSA->getAttachedRouters(i)) {
                    differentBody = true;
                    break;
                }
            }
        }
    }
    return (differentHeader || differentBody);
}
bool OSPF::NetworkLSA::Update (const OSPFNetworkLSA * lsa)
Definition at line 20 of file NetworkLSA.cc.
Referenced by OSPF::Area::AgeDatabase(), and OSPF::NeighborState::ChangeState().
{
    bool different = DiffersFrom(lsa);
    (*this) = (*lsa);
    ResetInstallTime();
    if (different) {
        ClearNextHops();
        return true;
    } else {
        return false;
    }
}
bool OSPF::NetworkLSA::ValidateLSChecksum () const [inline]
Definition at line 107 of file LSA.h.
Referenced by OSPF::Area::AgeDatabase().
{ return true; } // not implemented
The documentation for this class was generated from the following files:
LSA.h
NetworkLSA.cc