INET Framework for OMNeT++/OMNEST: TransmComplete Class Reference
TransmComplete Class Reference
#include <TransmComplete_m.h>
Public Member Functions
TransmComplete (const char *name=NULL, int kind=0)
TransmComplete (const TransmComplete &other)
virtual ~TransmComplete ()
TransmComplete & operator= (const TransmComplete &other)
virtual TransmComplete * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const TransmComplete &)
Detailed Description
Class generated from linklayer/mfcore/TransmComplete.msg by opp_msgc.
 packet TransmComplete
 {
 }
Definition at line 31 of file TransmComplete_m.h.
Constructor & Destructor Documentation
TransmComplete::TransmComplete (const char * name = NULL, int kind = 0)
Referenced by dup().
TransmComplete::TransmComplete (const TransmComplete & other)
virtual TransmComplete::~TransmComplete () [virtual]
Member Function Documentation
virtual TransmComplete* TransmComplete::dup () const [inline, virtual]
Definition at line 43 of file TransmComplete_m.h.
{return new TransmComplete(*this);}
TransmComplete& TransmComplete::operator= (const TransmComplete & other)
bool TransmComplete::operator== (const TransmComplete &) [protected]
virtual void TransmComplete::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TransmComplete::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TransmComplete_m.h