INET Framework for OMNeT++/OMNEST: OSPFHelloPacket Class Reference
OSPFHelloPacket Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFHelloPacket (const char *name=NULL, int kind=0)
OSPFHelloPacket (const OSPFHelloPacket &other)
virtual ~OSPFHelloPacket ()
OSPFHelloPacket & operator= (const OSPFHelloPacket &other)
virtual OSPFHelloPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getNetworkMask ()
virtual const IPAddress & getNetworkMask () const
virtual void setNetworkMask (const IPAddress &networkMask_var)
virtual short getHelloInterval () const
virtual void setHelloInterval (short helloInterval_var)
virtual OSPFOptions & getOptions ()
virtual const OSPFOptions & getOptions () const
virtual void setOptions (const OSPFOptions &options_var)
virtual char getRouterPriority () const
virtual void setRouterPriority (char routerPriority_var)
virtual long getRouterDeadInterval () const
virtual void setRouterDeadInterval (long routerDeadInterval_var)
virtual IPAddress & getDesignatedRouter ()
virtual const IPAddress & getDesignatedRouter () const
virtual void setDesignatedRouter (const IPAddress &designatedRouter_var)
virtual IPAddress & getBackupDesignatedRouter ()
virtual const IPAddress & getBackupDesignatedRouter () const
virtual void setBackupDesignatedRouter (const IPAddress &backupDesignatedRouter_var)
virtual void setNeighborArraySize (unsigned int size)
virtual unsigned int getNeighborArraySize () const
virtual IPAddress & getNeighbor (unsigned int k)
virtual const IPAddress & getNeighbor (unsigned int k) const
virtual void setNeighbor (unsigned int k, const IPAddress &neighbor_var)
Protected Member Functions
bool operator== (const OSPFHelloPacket &)
Protected Attributes
::IPAddress networkMask_var
short helloInterval_var
::OSPFOptions options_var
char routerPriority_var
long routerDeadInterval_var
::IPAddress designatedRouter_var
::IPAddress backupDesignatedRouter_var
::IPAddress * neighbor_var
unsigned int neighbor_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 packet OSPFHelloPacket extends OSPFPacket
 {
     IPAddress networkMask;
     short helloInterval = 5;
     OSPFOptions options;
     char routerPriority = 0;
     long routerDeadInterval = 0;
     IPAddress designatedRouter;
     IPAddress backupDesignatedRouter;
     IPAddress neighbor[];
 }
Definition at line 193 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFHelloPacket::OSPFHelloPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
OSPFHelloPacket::OSPFHelloPacket (const OSPFHelloPacket & other)
virtual OSPFHelloPacket::~OSPFHelloPacket () [virtual]
Member Function Documentation
virtual OSPFHelloPacket* OSPFHelloPacket::dup () const [inline, virtual]
Reimplemented from OSPFPacket.
Definition at line 214 of file OSPFPacket_m.h.
{return new OSPFHelloPacket(*this);}
virtual const IPAddress& OSPFHelloPacket::getBackupDesignatedRouter () const [inline, virtual]
Definition at line 235 of file OSPFPacket_m.h.
Referenced by getBackupDesignatedRouter().
{return const_cast<OSPFHelloPacket*>(this)->getBackupDesignatedRouter();}
virtual IPAddress& OSPFHelloPacket::getBackupDesignatedRouter () [virtual]
Referenced by OSPF::MessageHandler::PrintHelloPacket(), and OSPF::HelloHandler::ProcessPacket().
virtual const IPAddress& OSPFHelloPacket::getDesignatedRouter () const [inline, virtual]
Definition at line 232 of file OSPFPacket_m.h.
Referenced by getDesignatedRouter().
{return const_cast<OSPFHelloPacket*>(this)->getDesignatedRouter();}
virtual IPAddress& OSPFHelloPacket::getDesignatedRouter () [virtual]
Referenced by OSPF::MessageHandler::PrintHelloPacket(), and OSPF::HelloHandler::ProcessPacket().
virtual short OSPFHelloPacket::getHelloInterval () const [virtual]
Referenced by OSPF::HelloHandler::ProcessPacket().
virtual const IPAddress& OSPFHelloPacket::getNeighbor (unsigned int k) const [inline, virtual]
Definition at line 240 of file OSPFPacket_m.h.
Referenced by getNeighbor().
{return const_cast<OSPFHelloPacket*>(this)->getNeighbor(k);}
virtual IPAddress& OSPFHelloPacket::getNeighbor (unsigned int k) [virtual]
Referenced by OSPF::MessageHandler::PrintHelloPacket(), and OSPF::HelloHandler::ProcessPacket().
virtual unsigned int OSPFHelloPacket::getNeighborArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintHelloPacket(), and OSPF::HelloHandler::ProcessPacket().
virtual const IPAddress& OSPFHelloPacket::getNetworkMask () const [inline, virtual]
Definition at line 220 of file OSPFPacket_m.h.
Referenced by getNetworkMask().
{return const_cast<OSPFHelloPacket*>(this)->getNetworkMask();}
virtual IPAddress& OSPFHelloPacket::getNetworkMask () [virtual]
Referenced by OSPF::MessageHandler::PrintHelloPacket(), and OSPF::HelloHandler::ProcessPacket().
virtual const OSPFOptions& OSPFHelloPacket::getOptions () const [inline, virtual]
Definition at line 225 of file OSPFPacket_m.h.
Referenced by getOptions().
{return const_cast<OSPFHelloPacket*>(this)->getOptions();}
virtual OSPFOptions& OSPFHelloPacket::getOptions () [virtual]
Referenced by OSPF::HelloHandler::ProcessPacket().
virtual long OSPFHelloPacket::getRouterDeadInterval () const [virtual]
Referenced by OSPF::HelloHandler::ProcessPacket().
virtual char OSPFHelloPacket::getRouterPriority () const [virtual]
Referenced by OSPF::HelloHandler::ProcessPacket().
OSPFHelloPacket& OSPFHelloPacket::operator= (const OSPFHelloPacket & other)
Reimplemented from OSPFPacket.
bool OSPFHelloPacket::operator== (const OSPFHelloPacket &) [protected]
Reimplemented from OSPFPacket.
virtual void OSPFHelloPacket::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doPacking().
virtual void OSPFHelloPacket::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doUnpacking().
virtual void OSPFHelloPacket::setBackupDesignatedRouter (const IPAddress & backupDesignatedRouter_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setDesignatedRouter (const IPAddress & designatedRouter_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setHelloInterval (short helloInterval_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setNeighbor (unsigned int k, const IPAddress & neighbor_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setNeighborArraySize (unsigned int size) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setNetworkMask (const IPAddress & networkMask_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setOptions (const OSPFOptions & options_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setRouterDeadInterval (long routerDeadInterval_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
virtual void OSPFHelloPacket::setRouterPriority (char routerPriority_var) [virtual]
Referenced by OSPF::Interface::SendHelloPacket().
Member Data Documentation
::IPAddress OSPFHelloPacket::backupDesignatedRouter_var [protected]
Definition at line 202 of file OSPFPacket_m.h.
::IPAddress OSPFHelloPacket::designatedRouter_var [protected]
Definition at line 201 of file OSPFPacket_m.h.
short OSPFHelloPacket::helloInterval_var [protected]
Definition at line 197 of file OSPFPacket_m.h.
unsigned int OSPFHelloPacket::neighbor_arraysize [protected]
Definition at line 204 of file OSPFPacket_m.h.
::IPAddress* OSPFHelloPacket::neighbor_var [protected]
Definition at line 203 of file OSPFPacket_m.h.
::IPAddress OSPFHelloPacket::networkMask_var [protected]
Definition at line 196 of file OSPFPacket_m.h.
::OSPFOptions OSPFHelloPacket::options_var [protected]
Definition at line 198 of file OSPFPacket_m.h.
long OSPFHelloPacket::routerDeadInterval_var [protected]
Definition at line 200 of file OSPFPacket_m.h.
char OSPFHelloPacket::routerPriority_var [protected]
Definition at line 199 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h