INET Framework for OMNeT++/OMNEST: RSVPResvMsg_Base Class Reference
RSVPResvMsg_Base Class Reference
#include <RSVPResvMsg_m.h>
Public Member Functions
virtual ~RSVPResvMsg_Base ()
virtual RSVPResvMsg_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual RsvpHopObj_t & getHop ()
virtual const RsvpHopObj_t & getHop () const
virtual void setHop (const RsvpHopObj_t &hop_var)
virtual FlowDescriptorVector & getFlowDescriptor ()
virtual const
FlowDescriptorVector & getFlowDescriptor () const
virtual void setFlowDescriptor (const FlowDescriptorVector &flowDescriptor_var)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind_var)
Protected Member Functions
bool operator== (const RSVPResvMsg_Base &)
RSVPResvMsg_Base (const char *name=NULL, int kind=0)
RSVPResvMsg_Base (const RSVPResvMsg_Base &other)
RSVPResvMsg_Base & operator= (const RSVPResvMsg_Base &other)
Protected Attributes
::RsvpHopObj_t hop_var
::FlowDescriptorVector flowDescriptor_var
int rsvpKind_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPResvMsg.msg by opp_msgc.
 packet RSVPResvMsg extends RSVPPacket
 {
     (true);
     RsvpHopObj_t hop;
     FlowDescriptorVector flowDescriptor;
     int rsvpKind = RESV_MESSAGE;
 }
RSVPResvMsg_Base is only useful if it gets subclassed, and RSVPResvMsg is derived from it. The minimum code to be written for RSVPResvMsg is the following:
 class RSVPResvMsg : public RSVPResvMsg_Base
 {
   public:
     RSVPResvMsg(const char *name=NULL, int kind=0) : RSVPResvMsg_Base(name,kind) {}
     RSVPResvMsg(const RSVPResvMsg& other) : RSVPResvMsg_Base(other.getName()) {operator=(other);}
     RSVPResvMsg& operator=(const RSVPResvMsg& other) {RSVPResvMsg_Base::operator=(other); return *this;}
     virtual RSVPResvMsg *dup() const {return new RSVPResvMsg(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPResvMsg_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(RSVPResvMsg);
Definition at line 57 of file RSVPResvMsg_m.h.
Constructor & Destructor Documentation
RSVPResvMsg_Base::RSVPResvMsg_Base (const char * name = NULL, int kind = 0) [protected]
RSVPResvMsg_Base::RSVPResvMsg_Base (const RSVPResvMsg_Base & other) [protected]
virtual RSVPResvMsg_Base::~RSVPResvMsg_Base () [virtual]
Member Function Documentation
virtual RSVPResvMsg_Base* RSVPResvMsg_Base::dup () const [inline, virtual]
Reimplemented from RSVPPacket.
Reimplemented in RSVPResvMsg.
Definition at line 74 of file RSVPResvMsg_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class RSVPResvMsg");}
virtual const FlowDescriptorVector& RSVPResvMsg_Base::getFlowDescriptor () const [inline, virtual]
Definition at line 83 of file RSVPResvMsg_m.h.
Referenced by getFlowDescriptor().
{return const_cast<RSVPResvMsg_Base*>(this)->getFlowDescriptor();}
virtual FlowDescriptorVector& RSVPResvMsg_Base::getFlowDescriptor () [virtual]
Referenced by RSVP::createRSB(), RSVP::print(), RSVP::processResvMsg(), and RSVP::updateRSB().
virtual const RsvpHopObj_t& RSVPResvMsg_Base::getHop () const [inline, virtual]
Definition at line 80 of file RSVPResvMsg_m.h.
Referenced by getHop().
{return const_cast<RSVPResvMsg_Base*>(this)->getHop();}
virtual RsvpHopObj_t& RSVPResvMsg_Base::getHop () [virtual]
Referenced by RSVPResvMsg::getLIH(), and RSVPResvMsg::getNHOP().
virtual int RSVPResvMsg_Base::getRsvpKind () const [virtual]
Reimplemented from RSVPMessage.
RSVPResvMsg_Base& RSVPResvMsg_Base::operator= (const RSVPResvMsg_Base & other) [protected]
Reimplemented from RSVPPacket.
Reimplemented in RSVPResvMsg.
bool RSVPResvMsg_Base::operator== (const RSVPResvMsg_Base &) [protected]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvMsg_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvMsg_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvMsg_Base::setFlowDescriptor (const FlowDescriptorVector & flowDescriptor_var) [virtual]
Referenced by RSVP::refreshResv().
virtual void RSVPResvMsg_Base::setHop (const RsvpHopObj_t & hop_var) [virtual]
Referenced by RSVP::refreshResv().
virtual void RSVPResvMsg_Base::setRsvpKind (int rsvpKind_var) [virtual]
Reimplemented from RSVPMessage.
Member Data Documentation
::FlowDescriptorVector RSVPResvMsg_Base::flowDescriptor_var [protected]
Definition at line 61 of file RSVPResvMsg_m.h.
::RsvpHopObj_t RSVPResvMsg_Base::hop_var [protected]
Definition at line 60 of file RSVPResvMsg_m.h.
int RSVPResvMsg_Base::rsvpKind_var [protected]
Reimplemented from RSVPMessage.
Definition at line 62 of file RSVPResvMsg_m.h.
The documentation for this class was generated from the following file:
RSVPResvMsg_m.h