INET Framework for OMNeT++/OMNEST: OSPFDatabaseDescriptionPacket Class Reference
OSPFDatabaseDescriptionPacket Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFDatabaseDescriptionPacket (const char *name=NULL, int kind=0)
OSPFDatabaseDescriptionPacket (const OSPFDatabaseDescriptionPacket &other)
virtual ~OSPFDatabaseDescriptionPacket ()
OSPFDatabaseDescriptionPacket & operator= (const OSPFDatabaseDescriptionPacket &other)
virtual
OSPFDatabaseDescriptionPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned short getInterfaceMTU () const
virtual void setInterfaceMTU (unsigned short interfaceMTU_var)
virtual OSPFOptions & getOptions ()
virtual const OSPFOptions & getOptions () const
virtual void setOptions (const OSPFOptions &options_var)
virtual OSPFDDOptions & getDdOptions ()
virtual const OSPFDDOptions & getDdOptions () const
virtual void setDdOptions (const OSPFDDOptions &ddOptions_var)
virtual unsigned long getDdSequenceNumber () const
virtual void setDdSequenceNumber (unsigned long ddSequenceNumber_var)
virtual void setLsaHeadersArraySize (unsigned int size)
virtual unsigned int getLsaHeadersArraySize () const
virtual OSPFLSAHeader & getLsaHeaders (unsigned int k)
virtual const OSPFLSAHeader & getLsaHeaders (unsigned int k) const
virtual void setLsaHeaders (unsigned int k, const OSPFLSAHeader &lsaHeaders_var)
Protected Member Functions
bool operator== (const OSPFDatabaseDescriptionPacket &)
Protected Attributes
unsigned short interfaceMTU_var
::OSPFOptions options_var
::OSPFDDOptions ddOptions_var
unsigned long ddSequenceNumber_var
::OSPFLSAHeader * lsaHeaders_var
unsigned int lsaHeaders_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 packet OSPFDatabaseDescriptionPacket extends OSPFPacket
 {
     unsigned short interfaceMTU;
     OSPFOptions options;
     OSPFDDOptions ddOptions;
     unsigned long ddSequenceNumber;
     OSPFLSAHeader lsaHeaders[];
 }
Definition at line 704 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFDatabaseDescriptionPacket::OSPFDatabaseDescriptionPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
OSPFDatabaseDescriptionPacket::OSPFDatabaseDescriptionPacket (const OSPFDatabaseDescriptionPacket & other)
virtual OSPFDatabaseDescriptionPacket::~OSPFDatabaseDescriptionPacket () [virtual]
Member Function Documentation
virtual OSPFDatabaseDescriptionPacket* OSPFDatabaseDescriptionPacket::dup () const [inline, virtual]
Reimplemented from OSPFPacket.
Definition at line 722 of file OSPFPacket_m.h.
{return new OSPFDatabaseDescriptionPacket(*this);}
virtual const OSPFDDOptions& OSPFDatabaseDescriptionPacket::getDdOptions () const [inline, virtual]
Definition at line 733 of file OSPFPacket_m.h.
Referenced by getDdOptions().
{return const_cast<OSPFDatabaseDescriptionPacket*>(this)->getDdOptions();}
virtual OSPFDDOptions& OSPFDatabaseDescriptionPacket::getDdOptions () [virtual]
Referenced by OSPF::MessageHandler::PrintDatabaseDescriptionPacket(), OSPF::DatabaseDescriptionHandler::ProcessDDPacket(), and OSPF::DatabaseDescriptionHandler::ProcessPacket().
virtual unsigned long OSPFDatabaseDescriptionPacket::getDdSequenceNumber () const [virtual]
Referenced by OSPF::MessageHandler::PrintDatabaseDescriptionPacket(), OSPF::DatabaseDescriptionHandler::ProcessDDPacket(), and OSPF::DatabaseDescriptionHandler::ProcessPacket().
virtual unsigned short OSPFDatabaseDescriptionPacket::getInterfaceMTU () const [virtual]
Referenced by OSPF::DatabaseDescriptionHandler::ProcessPacket().
virtual const OSPFLSAHeader& OSPFDatabaseDescriptionPacket::getLsaHeaders (unsigned int k) const [inline, virtual]
Definition at line 740 of file OSPFPacket_m.h.
Referenced by getLsaHeaders().
{return const_cast<OSPFDatabaseDescriptionPacket*>(this)->getLsaHeaders(k);}
virtual OSPFLSAHeader& OSPFDatabaseDescriptionPacket::getLsaHeaders (unsigned int k) [virtual]
Referenced by OSPF::MessageHandler::PrintDatabaseDescriptionPacket(), and OSPF::DatabaseDescriptionHandler::ProcessDDPacket().
virtual unsigned int OSPFDatabaseDescriptionPacket::getLsaHeadersArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintDatabaseDescriptionPacket(), OSPF::DatabaseDescriptionHandler::ProcessDDPacket(), OSPF::DatabaseDescriptionHandler::ProcessPacket(), and OSPF::Neighbor::SendDatabaseDescriptionPacket().
virtual const OSPFOptions& OSPFDatabaseDescriptionPacket::getOptions () const [inline, virtual]
Definition at line 730 of file OSPFPacket_m.h.
Referenced by getOptions().
{return const_cast<OSPFDatabaseDescriptionPacket*>(this)->getOptions();}
virtual OSPFOptions& OSPFDatabaseDescriptionPacket::getOptions () [virtual]
Referenced by OSPF::DatabaseDescriptionHandler::ProcessPacket().
OSPFDatabaseDescriptionPacket& OSPFDatabaseDescriptionPacket::operator= (const OSPFDatabaseDescriptionPacket & other)
Reimplemented from OSPFPacket.
bool OSPFDatabaseDescriptionPacket::operator== (const OSPFDatabaseDescriptionPacket &) [protected]
Reimplemented from OSPFPacket.
virtual void OSPFDatabaseDescriptionPacket::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doPacking().
virtual void OSPFDatabaseDescriptionPacket::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doUnpacking().
virtual void OSPFDatabaseDescriptionPacket::setDdOptions (const OSPFDDOptions & ddOptions_var) [virtual]
Referenced by OSPF::Neighbor::SendDatabaseDescriptionPacket().
virtual void OSPFDatabaseDescriptionPacket::setDdSequenceNumber (unsigned long ddSequenceNumber_var) [virtual]
Referenced by OSPF::Neighbor::SendDatabaseDescriptionPacket().
virtual void OSPFDatabaseDescriptionPacket::setInterfaceMTU (unsigned short interfaceMTU_var) [virtual]
Referenced by OSPF::Neighbor::SendDatabaseDescriptionPacket().
virtual void OSPFDatabaseDescriptionPacket::setLsaHeaders (unsigned int k, const OSPFLSAHeader & lsaHeaders_var) [virtual]
Referenced by OSPF::Neighbor::SendDatabaseDescriptionPacket().
virtual void OSPFDatabaseDescriptionPacket::setLsaHeadersArraySize (unsigned int size) [virtual]
Referenced by OSPF::Neighbor::SendDatabaseDescriptionPacket().
virtual void OSPFDatabaseDescriptionPacket::setOptions (const OSPFOptions & options_var) [virtual]
Referenced by OSPF::Neighbor::SendDatabaseDescriptionPacket().
Member Data Documentation
::OSPFDDOptions OSPFDatabaseDescriptionPacket::ddOptions_var [protected]
Definition at line 709 of file OSPFPacket_m.h.
unsigned long OSPFDatabaseDescriptionPacket::ddSequenceNumber_var [protected]
Definition at line 710 of file OSPFPacket_m.h.
unsigned short OSPFDatabaseDescriptionPacket::interfaceMTU_var [protected]
Definition at line 707 of file OSPFPacket_m.h.
unsigned int OSPFDatabaseDescriptionPacket::lsaHeaders_arraysize [protected]
Definition at line 712 of file OSPFPacket_m.h.
::OSPFLSAHeader* OSPFDatabaseDescriptionPacket::lsaHeaders_var [protected]
Definition at line 711 of file OSPFPacket_m.h.
::OSPFOptions OSPFDatabaseDescriptionPacket::options_var [protected]
Definition at line 708 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h