INET Framework for OMNeT++/OMNEST: Sack Class Reference
Sack Class Reference
#include <TCPSegment_m.h>
Public Member Functions
Sack ()
Sack (const Sack &other)
virtual ~Sack ()
Sack & operator= (const Sack &other)
virtual Sack * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getStart () const
virtual void setStart (unsigned int start_var)
virtual unsigned int getEnd () const
virtual void setEnd (unsigned int end_var)
Protected Member Functions
bool operator== (const Sack &)
Protected Attributes
unsigned int start_var
unsigned int end_var
Detailed Description
Class generated from transport/tcp/TCPSegment.msg by opp_msgc.
 class Sack
 {
     unsigned int start;
     unsigned int end;
 }
Definition at line 116 of file TCPSegment_m.h.
Constructor & Destructor Documentation
Sack::Sack ()
Referenced by dup().
Sack::Sack (const Sack & other)
virtual Sack::~Sack () [virtual]
Member Function Documentation
virtual Sack* Sack::dup () const [inline, virtual]
Definition at line 130 of file TCPSegment_m.h.
{return new Sack(*this);}
virtual unsigned int Sack::getEnd () const [virtual]
Referenced by TCPConnection::addSacks(), and TCPConnection::processSACKOption().
virtual unsigned int Sack::getStart () const [virtual]
Referenced by TCPConnection::addSacks(), and TCPConnection::processSACKOption().
Sack& Sack::operator= (const Sack & other)
bool Sack::operator== (const Sack &) [protected]
virtual void Sack::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void Sack::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void Sack::setEnd (unsigned int end_var) [virtual]
Referenced by TCPConnection::addSacks(), and TCPConnection::processSACKOption().
virtual void Sack::setStart (unsigned int start_var) [virtual]
Referenced by TCPConnection::addSacks(), and TCPConnection::processSACKOption().
Member Data Documentation
unsigned int Sack::end_var [protected]
Definition at line 120 of file TCPSegment_m.h.
unsigned int Sack::start_var [protected]
Definition at line 119 of file TCPSegment_m.h.
The documentation for this class was generated from the following file:
TCPSegment_m.h