INET Framework for OMNeT++/OMNEST: Ieee80211ReassociationResponseFrame Class Reference
Ieee80211ReassociationResponseFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ReassociationResponseFrame (const char *name=NULL, int kind=0)
Ieee80211ReassociationResponseFrame (const Ieee80211ReassociationResponseFrame &other)
virtual ~Ieee80211ReassociationResponseFrame ()
Ieee80211ReassociationResponseFrame & operator= (const Ieee80211ReassociationResponseFrame &other)
virtual
Ieee80211ReassociationResponseFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211ReassociationResponseFrameBody & getBody ()
virtual const
Ieee80211ReassociationResponseFrameBody & getBody () const
virtual void setBody (const Ieee80211ReassociationResponseFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211ReassociationResponseFrame &)
Protected Attributes
::Ieee80211ReassociationResponseFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211ReassociationResponseFrame extends Ieee80211ManagementFrame
 {
     type = ST_REASSOCIATIONRESPONSE;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211ReassociationResponseFrameBody body;
 }
Definition at line 822 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ReassociationResponseFrame::Ieee80211ReassociationResponseFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211ReassociationResponseFrame::Ieee80211ReassociationResponseFrame (const Ieee80211ReassociationResponseFrame & other)
virtual Ieee80211ReassociationResponseFrame::~Ieee80211ReassociationResponseFrame () [virtual]
Member Function Documentation
virtual Ieee80211ReassociationResponseFrame* Ieee80211ReassociationResponseFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 835 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ReassociationResponseFrame(*this);}
virtual const Ieee80211ReassociationResponseFrameBody& Ieee80211ReassociationResponseFrame::getBody () const [inline, virtual]
Definition at line 841 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211ReassociationResponseFrame*>(this)->getBody();}
virtual Ieee80211ReassociationResponseFrameBody& Ieee80211ReassociationResponseFrame::getBody () [virtual]
Referenced by Ieee80211MgmtAP::handleReassociationRequestFrame().
Ieee80211ReassociationResponseFrame& Ieee80211ReassociationResponseFrame::operator= (const Ieee80211ReassociationResponseFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211ReassociationResponseFrame::operator== (const Ieee80211ReassociationResponseFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211ReassociationResponseFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211ReassociationResponseFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211ReassociationResponseFrame::setBody (const Ieee80211ReassociationResponseFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211ReassociationResponseFrameBody Ieee80211ReassociationResponseFrame::body_var [protected]
Definition at line 825 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h