INET Framework for OMNeT++/OMNEST: EtherFrameWithLLC Class Reference
EtherFrameWithLLC Class Reference
#include <EtherFrame_m.h>
Public Member Functions
EtherFrameWithLLC (const char *name=NULL, int kind=0)
EtherFrameWithLLC (const EtherFrameWithLLC &other)
virtual ~EtherFrameWithLLC ()
EtherFrameWithLLC & operator= (const EtherFrameWithLLC &other)
virtual EtherFrameWithLLC * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSsap () const
virtual void setSsap (int ssap_var)
virtual int getDsap () const
virtual void setDsap (int dsap_var)
virtual int getControl () const
virtual void setControl (int control_var)
Protected Member Functions
bool operator== (const EtherFrameWithLLC &)
Protected Attributes
int ssap_var
int dsap_var
int control_var
Detailed Description
Class generated from linklayer/ethernet/EtherFrame.msg by opp_msgc.
 packet EtherFrameWithLLC extends EtherFrame
 {
     int ssap;
     int dsap;
     int control;
 }
Definition at line 141 of file EtherFrame_m.h.
Constructor & Destructor Documentation
EtherFrameWithLLC::EtherFrameWithLLC (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherFrameWithLLC::EtherFrameWithLLC (const EtherFrameWithLLC & other)
virtual EtherFrameWithLLC::~EtherFrameWithLLC () [virtual]
Member Function Documentation
virtual EtherFrameWithLLC* EtherFrameWithLLC::dup () const [inline, virtual]
Reimplemented from EtherFrame.
Definition at line 156 of file EtherFrame_m.h.
{return new EtherFrameWithLLC(*this);}
virtual int EtherFrameWithLLC::getControl () const [virtual]
virtual int EtherFrameWithLLC::getDsap () const [virtual]
Referenced by EtherLLC::processFrameFromMAC().
virtual int EtherFrameWithLLC::getSsap () const [virtual]
Referenced by EtherLLC::processFrameFromMAC().
EtherFrameWithLLC& EtherFrameWithLLC::operator= (const EtherFrameWithLLC & other)
Reimplemented from EtherFrame.
bool EtherFrameWithLLC::operator== (const EtherFrameWithLLC &) [protected]
Reimplemented from EtherFrame.
virtual void EtherFrameWithLLC::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doPacking().
virtual void EtherFrameWithLLC::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doUnpacking().
virtual void EtherFrameWithLLC::setControl (int control_var) [virtual]
virtual void EtherFrameWithLLC::setDsap (int dsap_var) [virtual]
virtual void EtherFrameWithLLC::setSsap (int ssap_var) [virtual]
Member Data Documentation
int EtherFrameWithLLC::control_var [protected]
Definition at line 146 of file EtherFrame_m.h.
int EtherFrameWithLLC::dsap_var [protected]
Definition at line 145 of file EtherFrame_m.h.
int EtherFrameWithLLC::ssap_var [protected]
Definition at line 144 of file EtherFrame_m.h.
The documentation for this class was generated from the following file:
EtherFrame_m.h