INET Framework for OMNeT++/OMNEST: SCTPOpenCommand Class Reference
SCTPOpenCommand Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPOpenCommand (const char *name=NULL)
SCTPOpenCommand (const SCTPOpenCommand &other)
virtual ~SCTPOpenCommand ()
SCTPOpenCommand & operator= (const SCTPOpenCommand &other)
virtual SCTPOpenCommand * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual AddressVector & getLocalAddresses ()
virtual const AddressVector & getLocalAddresses () const
virtual void setLocalAddresses (const AddressVector &localAddresses_var)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual AddressVector & getRemoteAddresses ()
virtual const AddressVector & getRemoteAddresses () const
virtual void setRemoteAddresses (const AddressVector &remoteAddresses_var)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort_var)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort_var)
virtual bool getFork () const
virtual void setFork (bool fork_var)
virtual const char * getQueueClass () const
virtual void setQueueClass (const char *queueClass_var)
virtual const char * getSctpAlgorithmClass () const
virtual void setSctpAlgorithmClass (const char *sctpAlgorithmClass_var)
virtual uint32 getInboundStreams () const
virtual void setInboundStreams (uint32 inboundStreams_var)
virtual uint32 getOutboundStreams () const
virtual void setOutboundStreams (uint32 outboundStreams_var)
virtual uint32 getNumRequests () const
virtual void setNumRequests (uint32 numRequests_var)
virtual uint32 getMessagesToPush () const
virtual void setMessagesToPush (uint32 messagesToPush_var)
Protected Member Functions
bool operator== (const SCTPOpenCommand &)
Protected Attributes
::AddressVector localAddresses_var
::IPvXAddress remoteAddr_var
::AddressVector remoteAddresses_var
int localPort_var
int remotePort_var
bool fork_var
opp_string queueClass_var
opp_string sctpAlgorithmClass_var
uint32 inboundStreams_var
uint32 outboundStreams_var
uint32 numRequests_var
uint32 messagesToPush_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPOpenCommand extends SCTPCommand
 {
     AddressVector localAddresses;
     IPvXAddress remoteAddr;
     AddressVector remoteAddresses;
     int localPort = -1;
     int remotePort = -1;
     bool fork = false;
     string queueClass = "SCTPQueue";
     string sctpAlgorithmClass;
     uint32 inboundStreams;
     uint32 outboundStreams;
     uint32 numRequests;
     uint32 messagesToPush;
 }
Definition at line 164 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPOpenCommand::SCTPOpenCommand (const char * name = NULL)
Referenced by dup().
SCTPOpenCommand::SCTPOpenCommand (const SCTPOpenCommand & other)
virtual SCTPOpenCommand::~SCTPOpenCommand () [virtual]
Member Function Documentation
virtual SCTPOpenCommand* SCTPOpenCommand::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 188 of file SCTPCommand_m.h.
{return new SCTPOpenCommand(*this);}
virtual bool SCTPOpenCommand::getFork () const [virtual]
Referenced by SCTPAssociation::process_OPEN_PASSIVE().
virtual uint32 SCTPOpenCommand::getInboundStreams () const [virtual]
Referenced by SCTPAssociation::process_OPEN_PASSIVE().
virtual const AddressVector& SCTPOpenCommand::getLocalAddresses () const [inline, virtual]
Definition at line 194 of file SCTPCommand_m.h.
Referenced by getLocalAddresses().
{return const_cast<SCTPOpenCommand*>(this)->getLocalAddresses();}
virtual AddressVector& SCTPOpenCommand::getLocalAddresses () [virtual]
Referenced by SCTPAssociation::process_ASSOCIATE(), and SCTPAssociation::process_OPEN_PASSIVE().
virtual int SCTPOpenCommand::getLocalPort () const [virtual]
Referenced by SCTP::handleMessage(), SCTPAssociation::process_ASSOCIATE(), and SCTPAssociation::process_OPEN_PASSIVE().
virtual uint32 SCTPOpenCommand::getMessagesToPush () const [virtual]
Referenced by SCTPAssociation::process_OPEN_PASSIVE().
virtual uint32 SCTPOpenCommand::getNumRequests () const [virtual]
Referenced by SCTPAssociation::process_ASSOCIATE(), and SCTPAssociation::process_OPEN_PASSIVE().
virtual uint32 SCTPOpenCommand::getOutboundStreams () const [virtual]
Referenced by SCTPAssociation::initAssociation(), and SCTPAssociation::process_OPEN_PASSIVE().
virtual const char* SCTPOpenCommand::getQueueClass () const [virtual]
Referenced by SCTPAssociation::initAssociation().
virtual const IPvXAddress& SCTPOpenCommand::getRemoteAddr () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 197 of file SCTPCommand_m.h.
Referenced by getRemoteAddr().
{return const_cast<SCTPOpenCommand*>(this)->getRemoteAddr();}
virtual IPvXAddress& SCTPOpenCommand::getRemoteAddr () [virtual]
Reimplemented from SCTPCommand.
Referenced by SCTP::handleMessage(), and SCTPAssociation::process_ASSOCIATE().
virtual const AddressVector& SCTPOpenCommand::getRemoteAddresses () const [inline, virtual]
Definition at line 200 of file SCTPCommand_m.h.
Referenced by getRemoteAddresses().
{return const_cast<SCTPOpenCommand*>(this)->getRemoteAddresses();}
virtual AddressVector& SCTPOpenCommand::getRemoteAddresses () [virtual]
Referenced by SCTPAssociation::process_ASSOCIATE().
virtual int SCTPOpenCommand::getRemotePort () const [virtual]
Referenced by SCTP::handleMessage(), and SCTPAssociation::process_ASSOCIATE().
virtual const char* SCTPOpenCommand::getSctpAlgorithmClass () const [virtual]
Referenced by SCTPAssociation::initAssociation().
SCTPOpenCommand& SCTPOpenCommand::operator= (const SCTPOpenCommand & other)
Reimplemented from SCTPCommand.
bool SCTPOpenCommand::operator== (const SCTPOpenCommand &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPOpenCommand::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPOpenCommand::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPOpenCommand::setFork (bool fork_var) [virtual]
Referenced by SCTPSocket::listen().
virtual void SCTPOpenCommand::setInboundStreams (uint32 inboundStreams_var) [virtual]
Referenced by SCTPSocket::listen().
virtual void SCTPOpenCommand::setLocalAddresses (const AddressVector & localAddresses_var) [virtual]
Referenced by SCTPSocket::connect(), SCTPSocket::connectx(), and SCTPSocket::listen().
virtual void SCTPOpenCommand::setLocalPort (int localPort_var) [virtual]
Referenced by SCTPSocket::connect(), SCTPSocket::connectx(), and SCTPSocket::listen().
virtual void SCTPOpenCommand::setMessagesToPush (uint32 messagesToPush_var) [virtual]
Referenced by SCTPSocket::listen().
virtual void SCTPOpenCommand::setNumRequests (uint32 numRequests_var) [virtual]
Referenced by SCTPSocket::connect(), SCTPSocket::connectx(), and SCTPSocket::listen().
virtual void SCTPOpenCommand::setOutboundStreams (uint32 outboundStreams_var) [virtual]
Referenced by SCTPSocket::connect(), SCTPSocket::connectx(), and SCTPSocket::listen().
virtual void SCTPOpenCommand::setQueueClass (const char * queueClass_var) [virtual]
virtual void SCTPOpenCommand::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Reimplemented from SCTPCommand.
Referenced by SCTPSocket::connect(), and SCTPSocket::connectx().
virtual void SCTPOpenCommand::setRemoteAddresses (const AddressVector & remoteAddresses_var) [virtual]
Referenced by SCTPSocket::connectx().
virtual void SCTPOpenCommand::setRemotePort (int remotePort_var) [virtual]
Referenced by SCTPSocket::connect(), and SCTPSocket::connectx().
virtual void SCTPOpenCommand::setSctpAlgorithmClass (const char * sctpAlgorithmClass_var) [virtual]
Member Data Documentation
bool SCTPOpenCommand::fork_var [protected]
Definition at line 172 of file SCTPCommand_m.h.
uint32 SCTPOpenCommand::inboundStreams_var [protected]
Definition at line 175 of file SCTPCommand_m.h.
::AddressVector SCTPOpenCommand::localAddresses_var [protected]
Definition at line 167 of file SCTPCommand_m.h.
int SCTPOpenCommand::localPort_var [protected]
Definition at line 170 of file SCTPCommand_m.h.
uint32 SCTPOpenCommand::messagesToPush_var [protected]
Definition at line 178 of file SCTPCommand_m.h.
uint32 SCTPOpenCommand::numRequests_var [protected]
Definition at line 177 of file SCTPCommand_m.h.
uint32 SCTPOpenCommand::outboundStreams_var [protected]
Definition at line 176 of file SCTPCommand_m.h.
opp_string SCTPOpenCommand::queueClass_var [protected]
Definition at line 173 of file SCTPCommand_m.h.
::IPvXAddress SCTPOpenCommand::remoteAddr_var [protected]
Reimplemented from SCTPCommand.
Definition at line 168 of file SCTPCommand_m.h.
::AddressVector SCTPOpenCommand::remoteAddresses_var [protected]
Definition at line 169 of file SCTPCommand_m.h.
int SCTPOpenCommand::remotePort_var [protected]
Definition at line 171 of file SCTPCommand_m.h.
opp_string SCTPOpenCommand::sctpAlgorithmClass_var [protected]
Definition at line 174 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h