INET Framework for OMNeT++/OMNEST: MacPkt Class Reference
MacPkt Class Reference
#include <MacPkt_m.h>
Public Member Functions
MacPkt (const char *name=NULL, int kind=0)
MacPkt (const MacPkt &other)
virtual ~MacPkt ()
MacPkt & operator= (const MacPkt &other)
virtual MacPkt * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getDestAddr ()
virtual const MACAddress & getDestAddr () const
virtual void setDestAddr (const MACAddress &destAddr_var)
virtual MACAddress & getSrcAddr ()
virtual const MACAddress & getSrcAddr () const
virtual void setSrcAddr (const MACAddress &srcAddr_var)
virtual int getChannelId () const
virtual void setChannelId (int channelId_var)
Protected Member Functions
bool operator== (const MacPkt &)
Protected Attributes
::MACAddress destAddr_var
::MACAddress srcAddr_var
int channelId_var
Detailed Description
Class generated from linklayer/mf80211/macLayer/MacPkt.msg by opp_msgc.
 packet MacPkt
 {
     MACAddress destAddr;
     MACAddress srcAddr;
     int channelId = 1;
 }
Definition at line 34 of file MacPkt_m.h.
Constructor & Destructor Documentation
MacPkt::MacPkt (const char * name = NULL, int kind = 0)
Referenced by dup().
MacPkt::MacPkt (const MacPkt & other)
virtual MacPkt::~MacPkt () [virtual]
Member Function Documentation
virtual MacPkt* MacPkt::dup () const [inline, virtual]
Reimplemented in Mac80211Pkt.
Definition at line 49 of file MacPkt_m.h.
{return new MacPkt(*this);}
virtual int MacPkt::getChannelId () const [virtual]
virtual const MACAddress& MacPkt::getDestAddr () const [inline, virtual]
Definition at line 55 of file MacPkt_m.h.
Referenced by getDestAddr().
{return const_cast<MacPkt*>(this)->getDestAddr();}
virtual MACAddress& MacPkt::getDestAddr () [virtual]
Referenced by Mac80211::handleLowerMsg(), CSMAMacLayer::handleLowerMsg(), and Mac80211::handleUpperMsg().
virtual const MACAddress& MacPkt::getSrcAddr () const [inline, virtual]
Definition at line 58 of file MacPkt_m.h.
Referenced by getSrcAddr().
{return const_cast<MacPkt*>(this)->getSrcAddr();}
virtual MACAddress& MacPkt::getSrcAddr () [virtual]
Referenced by Mac80211::buildACKframe(), and Mac80211::buildCTSframe().
MacPkt& MacPkt::operator= (const MacPkt & other)
Reimplemented in Mac80211Pkt.
bool MacPkt::operator== (const MacPkt &) [protected]
Reimplemented in Mac80211Pkt.
virtual void MacPkt::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in Mac80211Pkt.
Referenced by doPacking().
virtual void MacPkt::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in Mac80211Pkt.
Referenced by doUnpacking().
virtual void MacPkt::setChannelId (int channelId_var) [virtual]
virtual void MacPkt::setDestAddr (const MACAddress & destAddr_var) [virtual]
Referenced by Mac80211::buildACKframe(), Mac80211::buildCTSframe(), Mac80211::buildRTSframe(), Mac80211::encapsMsg(), and CSMAMacLayer::encapsMsg().
virtual void MacPkt::setSrcAddr (const MACAddress & srcAddr_var) [virtual]
Referenced by Mac80211::buildACKframe(), Mac80211::buildCTSframe(), Mac80211::buildDATAframe(), Mac80211::buildRTSframe(), Mac80211::encapsMsg(), and CSMAMacLayer::encapsMsg().
Member Data Documentation
int MacPkt::channelId_var [protected]
Definition at line 39 of file MacPkt_m.h.
::MACAddress MacPkt::destAddr_var [protected]
Definition at line 37 of file MacPkt_m.h.
::MACAddress MacPkt::srcAddr_var [protected]
Definition at line 38 of file MacPkt_m.h.
The documentation for this class was generated from the following file:
MacPkt_m.h