INET Framework for OMNeT++/OMNEST: Ieee80211ReassociationResponseFrameBody Class Reference
Ieee80211ReassociationResponseFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ReassociationResponseFrameBody ()
Ieee80211ReassociationResponseFrameBody (const Ieee80211ReassociationResponseFrameBody &other)
virtual ~Ieee80211ReassociationResponseFrameBody ()
Ieee80211ReassociationResponseFrameBody & operator= (const Ieee80211ReassociationResponseFrameBody &other)
virtual
Ieee80211ReassociationResponseFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211ReassociationResponseFrameBody &)
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211ReassociationResponseFrameBody extends Ieee80211AssociationResponseFrameBody
 {
 }
Definition at line 447 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ReassociationResponseFrameBody::Ieee80211ReassociationResponseFrameBody ()
Referenced by dup().
Ieee80211ReassociationResponseFrameBody::Ieee80211ReassociationResponseFrameBody (const Ieee80211ReassociationResponseFrameBody & other)
virtual Ieee80211ReassociationResponseFrameBody::~Ieee80211ReassociationResponseFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211ReassociationResponseFrameBody* Ieee80211ReassociationResponseFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211AssociationResponseFrameBody.
Definition at line 459 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ReassociationResponseFrameBody(*this);}
Ieee80211ReassociationResponseFrameBody& Ieee80211ReassociationResponseFrameBody::operator= (const Ieee80211ReassociationResponseFrameBody & other)
Reimplemented from Ieee80211AssociationResponseFrameBody.
bool Ieee80211ReassociationResponseFrameBody::operator== (const Ieee80211ReassociationResponseFrameBody &) [protected]
Reimplemented from Ieee80211AssociationResponseFrameBody.
virtual void Ieee80211ReassociationResponseFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211AssociationResponseFrameBody.
Referenced by doPacking().
virtual void Ieee80211ReassociationResponseFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211AssociationResponseFrameBody.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h