INET Framework for OMNeT++/OMNEST: IPv6NDPrefixInformation Class Reference
IPv6NDPrefixInformation Class Reference
#include <IPv6NDMessage_m.h>
Public Member Functions
IPv6NDPrefixInformation ()
IPv6NDPrefixInformation (const IPv6NDPrefixInformation &other)
virtual ~IPv6NDPrefixInformation ()
IPv6NDPrefixInformation & operator= (const IPv6NDPrefixInformation &other)
virtual IPv6NDPrefixInformation * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getPrefixLength () const
virtual void setPrefixLength (unsigned int prefixLength_var)
virtual bool getOnlinkFlag () const
virtual void setOnlinkFlag (bool onlinkFlag_var)
virtual bool getAutoAddressConfFlag () const
virtual void setAutoAddressConfFlag (bool autoAddressConfFlag_var)
virtual unsigned int getValidLifetime () const
virtual void setValidLifetime (unsigned int validLifetime_var)
virtual unsigned int getPreferredLifetime () const
virtual void setPreferredLifetime (unsigned int preferredLifetime_var)
virtual IPv6Address & getPrefix ()
virtual const IPv6Address & getPrefix () const
virtual void setPrefix (const IPv6Address &prefix_var)
Protected Member Functions
bool operator== (const IPv6NDPrefixInformation &)
Protected Attributes
unsigned int prefixLength_var
bool onlinkFlag_var
bool autoAddressConfFlag_var
unsigned int validLifetime_var
unsigned int preferredLifetime_var
::IPv6Address prefix_var
Detailed Description
Class generated from networklayer/icmpv6/IPv6NDMessage.msg by opp_msgc.
 class IPv6NDPrefixInformation
 {
     unsigned int prefixLength;
     bool onlinkFlag;
     bool autoAddressConfFlag;
     unsigned int validLifetime;
     unsigned int preferredLifetime;
     IPv6Address prefix;
 }
Definition at line 39 of file IPv6NDMessage_m.h.
Constructor & Destructor Documentation
IPv6NDPrefixInformation::IPv6NDPrefixInformation ()
Referenced by dup().
IPv6NDPrefixInformation::IPv6NDPrefixInformation (const IPv6NDPrefixInformation & other)
virtual IPv6NDPrefixInformation::~IPv6NDPrefixInformation () [virtual]
Member Function Documentation
virtual IPv6NDPrefixInformation* IPv6NDPrefixInformation::dup () const [inline, virtual]
Definition at line 57 of file IPv6NDMessage_m.h.
{return new IPv6NDPrefixInformation(*this);}
virtual bool IPv6NDPrefixInformation::getAutoAddressConfFlag () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPacket().
virtual bool IPv6NDPrefixInformation::getOnlinkFlag () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPrefixInfo().
virtual unsigned int IPv6NDPrefixInformation::getPreferredLifetime () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPrefixInfo(), and IPv6NeighbourDiscovery::processRAPrefixInfoForAddrAutoConf().
virtual const IPv6Address& IPv6NDPrefixInformation::getPrefix () const [inline, virtual]
Definition at line 73 of file IPv6NDMessage_m.h.
Referenced by getPrefix().
{return const_cast<IPv6NDPrefixInformation*>(this)->getPrefix();}
virtual IPv6Address& IPv6NDPrefixInformation::getPrefix () [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPrefixInfo(), and IPv6NeighbourDiscovery::processRAPrefixInfoForAddrAutoConf().
virtual unsigned int IPv6NDPrefixInformation::getPrefixLength () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPrefixInfo(), and IPv6NeighbourDiscovery::processRAPrefixInfoForAddrAutoConf().
virtual unsigned int IPv6NDPrefixInformation::getValidLifetime () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPrefixInfo(), and IPv6NeighbourDiscovery::processRAPrefixInfoForAddrAutoConf().
IPv6NDPrefixInformation& IPv6NDPrefixInformation::operator= (const IPv6NDPrefixInformation & other)
bool IPv6NDPrefixInformation::operator== (const IPv6NDPrefixInformation &) [protected]
virtual void IPv6NDPrefixInformation::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void IPv6NDPrefixInformation::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void IPv6NDPrefixInformation::setAutoAddressConfFlag (bool autoAddressConfFlag_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6NDPrefixInformation::setOnlinkFlag (bool onlinkFlag_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6NDPrefixInformation::setPreferredLifetime (unsigned int preferredLifetime_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6NDPrefixInformation::setPrefix (const IPv6Address & prefix_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6NDPrefixInformation::setPrefixLength (unsigned int prefixLength_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6NDPrefixInformation::setValidLifetime (unsigned int validLifetime_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
Member Data Documentation
bool IPv6NDPrefixInformation::autoAddressConfFlag_var [protected]
Definition at line 44 of file IPv6NDMessage_m.h.
bool IPv6NDPrefixInformation::onlinkFlag_var [protected]
Definition at line 43 of file IPv6NDMessage_m.h.
unsigned int IPv6NDPrefixInformation::preferredLifetime_var [protected]
Definition at line 46 of file IPv6NDMessage_m.h.
::IPv6Address IPv6NDPrefixInformation::prefix_var [protected]
Definition at line 47 of file IPv6NDMessage_m.h.
unsigned int IPv6NDPrefixInformation::prefixLength_var [protected]
Definition at line 42 of file IPv6NDMessage_m.h.
unsigned int IPv6NDPrefixInformation::validLifetime_var [protected]
Definition at line 45 of file IPv6NDMessage_m.h.
The documentation for this class was generated from the following file:
IPv6NDMessage_m.h