INET Framework for OMNeT++/OMNEST: RSVPMessage Class Reference
RSVPMessage Class Reference
#include <RSVPPacket_m.h>
Public Member Functions
RSVPMessage (const char *name=NULL, int kind=0)
RSVPMessage (const RSVPMessage &other)
virtual ~RSVPMessage ()
RSVPMessage & operator= (const RSVPMessage &other)
virtual RSVPMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind_var)
Protected Member Functions
bool operator== (const RSVPMessage &)
Protected Attributes
int rsvpKind_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPPacket.msg by opp_msgc.
 packet RSVPMessage
 {
     int rsvpKind;
 }
Definition at line 40 of file RSVPPacket_m.h.
Constructor & Destructor Documentation
RSVPMessage::RSVPMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
RSVPMessage::RSVPMessage (const RSVPMessage & other)
virtual RSVPMessage::~RSVPMessage () [virtual]
Member Function Documentation
virtual RSVPMessage* RSVPMessage::dup () const [inline, virtual]
Reimplemented in RSVPHelloMsg_Base, RSVPHelloMsg, RSVPPacket, RSVPPacket_Base, RSVPPathMsg, RSVPPathTear, RSVPPathError, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg, RSVPResvTear, RSVPResvError, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Definition at line 53 of file RSVPPacket_m.h.
{return new RSVPMessage(*this);}
virtual int RSVPMessage::getRsvpKind () const [virtual]
Reimplemented in RSVPHelloMsg_Base, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Referenced by RSVP::processRSVPMessage().
RSVPMessage& RSVPMessage::operator= (const RSVPMessage & other)
Reimplemented in RSVPHelloMsg_Base, RSVPHelloMsg, RSVPPacket, RSVPPacket_Base, RSVPPathMsg, RSVPPathTear, RSVPPathError, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg, RSVPResvTear, RSVPResvError, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
bool RSVPMessage::operator== (const RSVPMessage &) [protected]
Reimplemented in RSVPHelloMsg_Base, RSVPPacket_Base, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
virtual void RSVPMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in RSVPHelloMsg_Base, RSVPPacket_Base, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Referenced by doPacking().
virtual void RSVPMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in RSVPHelloMsg_Base, RSVPPacket_Base, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Referenced by doUnpacking().
virtual void RSVPMessage::setRsvpKind (int rsvpKind_var) [virtual]
Reimplemented in RSVPHelloMsg_Base, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Member Data Documentation
int RSVPMessage::rsvpKind_var [protected]
Reimplemented in RSVPHelloMsg_Base, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Definition at line 43 of file RSVPPacket_m.h.
Referenced by RSVPPacket::RSVPPacket().
The documentation for this class was generated from the following file:
RSVPPacket_m.h