INET Framework for OMNeT++/OMNEST: SCTPCookie Class Reference
SCTPCookie Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPCookie (const char *name=NULL, int kind=0)
SCTPCookie (const SCTPCookie &other)
virtual ~SCTPCookie ()
SCTPCookie & operator= (const SCTPCookie &other)
virtual SCTPCookie * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual simtime_t getCreationTime () const
virtual void setCreationTime (simtime_t creationTime_var)
virtual uint32 getLocalTag () const
virtual void setLocalTag (uint32 localTag_var)
virtual uint32 getPeerTag () const
virtual void setPeerTag (uint32 peerTag_var)
virtual void setLocalTieTagArraySize (unsigned int size)
virtual unsigned int getLocalTieTagArraySize () const
virtual uint8 getLocalTieTag (unsigned int k) const
virtual void setLocalTieTag (unsigned int k, uint8 localTieTag_var)
virtual void setPeerTieTagArraySize (unsigned int size)
virtual unsigned int getPeerTieTagArraySize () const
virtual uint8 getPeerTieTag (unsigned int k) const
virtual void setPeerTieTag (unsigned int k, uint8 peerTieTag_var)
Protected Member Functions
bool operator== (const SCTPCookie &)
Protected Attributes
simtime_t creationTime_var
uint32 localTag_var
uint32 peerTag_var
uint8 * localTieTag_var
unsigned int localTieTag_arraysize
uint8 * peerTieTag_var
unsigned int peerTieTag_arraysize
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPCookie extends cPacket
 {
      simtime_t creationTime;
      uint32 localTag;
      uint32 peerTag;
      uint8 localTieTag[];
      uint8 peerTieTag[];
 }
Definition at line 411 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPCookie::SCTPCookie (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPCookie::SCTPCookie (const SCTPCookie & other)
virtual SCTPCookie::~SCTPCookie () [virtual]
Member Function Documentation
virtual SCTPCookie* SCTPCookie::dup () const [inline, virtual]
Definition at line 430 of file SCTPMessage_m.h.
{return new SCTPCookie(*this);}
virtual simtime_t SCTPCookie::getCreationTime () const [virtual]
Referenced by SCTPAssociation::processCookieEchoArrived().
virtual uint32 SCTPCookie::getLocalTag () const [virtual]
Referenced by SCTPAssociation::processCookieEchoArrived().
virtual uint8 SCTPCookie::getLocalTieTag (unsigned int k) const [virtual]
Referenced by SCTPAssociation::processCookieEchoArrived(), and SCTPAssociation::sendInitAck().
virtual unsigned int SCTPCookie::getLocalTieTagArraySize () const [virtual]
virtual uint32 SCTPCookie::getPeerTag () const [virtual]
Referenced by SCTPAssociation::processCookieEchoArrived().
virtual uint8 SCTPCookie::getPeerTieTag (unsigned int k) const [virtual]
Referenced by SCTPAssociation::processCookieEchoArrived(), and SCTPAssociation::sendInitAck().
virtual unsigned int SCTPCookie::getPeerTieTagArraySize () const [virtual]
SCTPCookie& SCTPCookie::operator= (const SCTPCookie & other)
bool SCTPCookie::operator== (const SCTPCookie &) [protected]
virtual void SCTPCookie::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SCTPCookie::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SCTPCookie::setCreationTime (simtime_t creationTime_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPCookie::setLocalTag (uint32 localTag_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPCookie::setLocalTieTag (unsigned int k, uint8 localTieTag_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPCookie::setLocalTieTagArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPCookie::setPeerTag (uint32 peerTag_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPCookie::setPeerTieTag (unsigned int k, uint8 peerTieTag_var) [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual void SCTPCookie::setPeerTieTagArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendInitAck().
Member Data Documentation
simtime_t SCTPCookie::creationTime_var [protected]
Definition at line 414 of file SCTPMessage_m.h.
uint32 SCTPCookie::localTag_var [protected]
Definition at line 415 of file SCTPMessage_m.h.
unsigned int SCTPCookie::localTieTag_arraysize [protected]
Definition at line 418 of file SCTPMessage_m.h.
uint8* SCTPCookie::localTieTag_var [protected]
Definition at line 417 of file SCTPMessage_m.h.
uint32 SCTPCookie::peerTag_var [protected]
Definition at line 416 of file SCTPMessage_m.h.
unsigned int SCTPCookie::peerTieTag_arraysize [protected]
Definition at line 420 of file SCTPMessage_m.h.
uint8* SCTPCookie::peerTieTag_var [protected]
Definition at line 419 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h