INET Framework for OMNeT++/OMNEST: TCPErrorInfo Class Reference
TCPErrorInfo Class Reference
#include <TCPCommand_m.h>
Public Member Functions
TCPErrorInfo ()
TCPErrorInfo (const TCPErrorInfo &other)
virtual ~TCPErrorInfo ()
TCPErrorInfo & operator= (const TCPErrorInfo &other)
virtual TCPErrorInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getErrorCode () const
virtual void setErrorCode (int errorCode_var)
virtual const char * getMessageText () const
virtual void setMessageText (const char *messageText_var)
Protected Member Functions
bool operator== (const TCPErrorInfo &)
Protected Attributes
int errorCode_var
opp_string messageText_var
Detailed Description
Class generated from transport/contract/TCPCommand.msg by opp_msgc.
 class TCPErrorInfo extends TCPCommand
 {
     int errorCode enum(TCPErrorCode);
     string messageText;
 }
Definition at line 137 of file TCPCommand_m.h.
Constructor & Destructor Documentation
TCPErrorInfo::TCPErrorInfo ()
Referenced by dup().
TCPErrorInfo::TCPErrorInfo (const TCPErrorInfo & other)
virtual TCPErrorInfo::~TCPErrorInfo () [virtual]
Member Function Documentation
virtual TCPErrorInfo* TCPErrorInfo::dup () const [inline, virtual]
Reimplemented from TCPCommand.
Definition at line 151 of file TCPCommand_m.h.
{return new TCPErrorInfo(*this);}
virtual int TCPErrorInfo::getErrorCode () const [virtual]
virtual const char* TCPErrorInfo::getMessageText () const [virtual]
TCPErrorInfo& TCPErrorInfo::operator= (const TCPErrorInfo & other)
Reimplemented from TCPCommand.
bool TCPErrorInfo::operator== (const TCPErrorInfo &) [protected]
Reimplemented from TCPCommand.
virtual void TCPErrorInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doPacking().
virtual void TCPErrorInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doUnpacking().
virtual void TCPErrorInfo::setErrorCode (int errorCode_var) [virtual]
virtual void TCPErrorInfo::setMessageText (const char * messageText_var) [virtual]
Member Data Documentation
int TCPErrorInfo::errorCode_var [protected]
Definition at line 140 of file TCPCommand_m.h.
opp_string TCPErrorInfo::messageText_var [protected]
Definition at line 141 of file TCPCommand_m.h.
The documentation for this class was generated from the following file:
TCPCommand_m.h