INET Framework for OMNeT++/OMNEST: IPv6RouterAdvertisement Class Reference
IPv6RouterAdvertisement Class Reference
#include <IPv6NDMessage_m.h>
Public Member Functions
IPv6RouterAdvertisement (const char *name=NULL, int kind=0)
IPv6RouterAdvertisement (const IPv6RouterAdvertisement &other)
virtual ~IPv6RouterAdvertisement ()
IPv6RouterAdvertisement & operator= (const IPv6RouterAdvertisement &other)
virtual IPv6RouterAdvertisement * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getCurHopLimit () const
virtual void setCurHopLimit (unsigned int curHopLimit_var)
virtual bool getManagedAddrConfFlag () const
virtual void setManagedAddrConfFlag (bool managedAddrConfFlag_var)
virtual bool getOtherStatefulConfFlag () const
virtual void setOtherStatefulConfFlag (bool otherStatefulConfFlag_var)
virtual unsigned short getRouterLifetime () const
virtual void setRouterLifetime (unsigned short routerLifetime_var)
virtual unsigned int getReachableTime () const
virtual void setReachableTime (unsigned int reachableTime_var)
virtual unsigned int getRetransTimer () const
virtual void setRetransTimer (unsigned int retransTimer_var)
virtual MACAddress & getSourceLinkLayerAddress ()
virtual const MACAddress & getSourceLinkLayerAddress () const
virtual void setSourceLinkLayerAddress (const MACAddress &sourceLinkLayerAddress_var)
virtual unsigned int getMTU () const
virtual void setMTU (unsigned int MTU_var)
virtual void setPrefixInformationArraySize (unsigned int size)
virtual unsigned int getPrefixInformationArraySize () const
virtual IPv6NDPrefixInformation & getPrefixInformation (unsigned int k)
virtual const
IPv6NDPrefixInformation & getPrefixInformation (unsigned int k) const
virtual void setPrefixInformation (unsigned int k, const IPv6NDPrefixInformation &prefixInformation_var)
Protected Member Functions
bool operator== (const IPv6RouterAdvertisement &)
Protected Attributes
unsigned int curHopLimit_var
bool managedAddrConfFlag_var
bool otherStatefulConfFlag_var
unsigned short routerLifetime_var
unsigned int reachableTime_var
unsigned int retransTimer_var
::MACAddress sourceLinkLayerAddress_var
unsigned int MTU_var
::IPv6NDPrefixInformation * prefixInformation_var
unsigned int prefixInformation_arraysize
Detailed Description
Class generated from networklayer/icmpv6/IPv6NDMessage.msg by opp_msgc.
 packet IPv6RouterAdvertisement extends IPv6NDMessage
 {
     unsigned int curHopLimit;
     bool managedAddrConfFlag;
     bool otherStatefulConfFlag;
     unsigned short routerLifetime;
     unsigned int reachableTime;
     unsigned int retransTimer;
     MACAddress sourceLinkLayerAddress;
     unsigned int MTU;
     IPv6NDPrefixInformation prefixInformation[];
 }
Definition at line 171 of file IPv6NDMessage_m.h.
Constructor & Destructor Documentation
IPv6RouterAdvertisement::IPv6RouterAdvertisement (const char * name = NULL, int kind = 0)
Referenced by dup().
IPv6RouterAdvertisement::IPv6RouterAdvertisement (const IPv6RouterAdvertisement & other)
virtual IPv6RouterAdvertisement::~IPv6RouterAdvertisement () [virtual]
Member Function Documentation
virtual IPv6RouterAdvertisement* IPv6RouterAdvertisement::dup () const [inline, virtual]
Reimplemented from IPv6NDMessage.
Definition at line 193 of file IPv6NDMessage_m.h.
{return new IPv6RouterAdvertisement(*this);}
virtual unsigned int IPv6RouterAdvertisement::getCurHopLimit () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAForRouterUpdates().
virtual bool IPv6RouterAdvertisement::getManagedAddrConfFlag () const [virtual]
virtual unsigned int IPv6RouterAdvertisement::getMTU () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPacket().
virtual bool IPv6RouterAdvertisement::getOtherStatefulConfFlag () const [virtual]
virtual const IPv6NDPrefixInformation& IPv6RouterAdvertisement::getPrefixInformation (unsigned int k) const [inline, virtual]
Definition at line 218 of file IPv6NDMessage_m.h.
Referenced by getPrefixInformation().
{return const_cast<IPv6RouterAdvertisement*>(this)->getPrefixInformation(k);}
virtual IPv6NDPrefixInformation& IPv6RouterAdvertisement::getPrefixInformation (unsigned int k) [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPacket(), and IPv6NeighbourDiscovery::processRAPrefixInfo().
virtual unsigned int IPv6RouterAdvertisement::getPrefixInformationArraySize () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAPacket(), and IPv6NeighbourDiscovery::processRAPrefixInfo().
virtual unsigned int IPv6RouterAdvertisement::getReachableTime () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAForRouterUpdates().
virtual unsigned int IPv6RouterAdvertisement::getRetransTimer () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAForRouterUpdates().
virtual unsigned short IPv6RouterAdvertisement::getRouterLifetime () const [virtual]
Referenced by IPv6NeighbourDiscovery::processRAForRouterUpdates().
virtual const MACAddress& IPv6RouterAdvertisement::getSourceLinkLayerAddress () const [inline, virtual]
Definition at line 211 of file IPv6NDMessage_m.h.
Referenced by getSourceLinkLayerAddress().
{return const_cast<IPv6RouterAdvertisement*>(this)->getSourceLinkLayerAddress();}
virtual MACAddress& IPv6RouterAdvertisement::getSourceLinkLayerAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processRAForRouterUpdates(), and IPv6NeighbourDiscovery::processRAPacket().
IPv6RouterAdvertisement& IPv6RouterAdvertisement::operator= (const IPv6RouterAdvertisement & other)
Reimplemented from IPv6NDMessage.
bool IPv6RouterAdvertisement::operator== (const IPv6RouterAdvertisement &) [protected]
Reimplemented from IPv6NDMessage.
virtual void IPv6RouterAdvertisement::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doPacking().
virtual void IPv6RouterAdvertisement::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doUnpacking().
virtual void IPv6RouterAdvertisement::setCurHopLimit (unsigned int curHopLimit_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setManagedAddrConfFlag (bool managedAddrConfFlag_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setMTU (unsigned int MTU_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setOtherStatefulConfFlag (bool otherStatefulConfFlag_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setPrefixInformation (unsigned int k, const IPv6NDPrefixInformation & prefixInformation_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setPrefixInformationArraySize (unsigned int size) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setReachableTime (unsigned int reachableTime_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setRetransTimer (unsigned int retransTimer_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setRouterLifetime (unsigned short routerLifetime_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
virtual void IPv6RouterAdvertisement::setSourceLinkLayerAddress (const MACAddress & sourceLinkLayerAddress_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRAPacket().
Member Data Documentation
unsigned int IPv6RouterAdvertisement::curHopLimit_var [protected]
Definition at line 174 of file IPv6NDMessage_m.h.
bool IPv6RouterAdvertisement::managedAddrConfFlag_var [protected]
Definition at line 175 of file IPv6NDMessage_m.h.
unsigned int IPv6RouterAdvertisement::MTU_var [protected]
Definition at line 181 of file IPv6NDMessage_m.h.
bool IPv6RouterAdvertisement::otherStatefulConfFlag_var [protected]
Definition at line 176 of file IPv6NDMessage_m.h.
unsigned int IPv6RouterAdvertisement::prefixInformation_arraysize [protected]
Definition at line 183 of file IPv6NDMessage_m.h.
::IPv6NDPrefixInformation* IPv6RouterAdvertisement::prefixInformation_var [protected]
Definition at line 182 of file IPv6NDMessage_m.h.
unsigned int IPv6RouterAdvertisement::reachableTime_var [protected]
Definition at line 178 of file IPv6NDMessage_m.h.
unsigned int IPv6RouterAdvertisement::retransTimer_var [protected]
Definition at line 179 of file IPv6NDMessage_m.h.
unsigned short IPv6RouterAdvertisement::routerLifetime_var [protected]
Definition at line 177 of file IPv6NDMessage_m.h.
::MACAddress IPv6RouterAdvertisement::sourceLinkLayerAddress_var [protected]
Definition at line 180 of file IPv6NDMessage_m.h.
The documentation for this class was generated from the following file:
IPv6NDMessage_m.h