INET Framework for OMNeT++/OMNEST: PsbTimeoutMsg Class Reference
PsbTimeoutMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
PsbTimeoutMsg (const char *name=NULL, int kind=0)
PsbTimeoutMsg (const PsbTimeoutMsg &other)
virtual ~PsbTimeoutMsg ()
PsbTimeoutMsg & operator= (const PsbTimeoutMsg &other)
virtual PsbTimeoutMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getId () const
virtual void setId (int id_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const PsbTimeoutMsg &)
Protected Attributes
int id_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message PsbTimeoutMsg extends SignallingMsg
 {
     int id;
     int command = MSG_PSB_TIMEOUT;
 }
Definition at line 126 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
PsbTimeoutMsg::PsbTimeoutMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
PsbTimeoutMsg::PsbTimeoutMsg (const PsbTimeoutMsg & other)
virtual PsbTimeoutMsg::~PsbTimeoutMsg () [virtual]
Member Function Documentation
virtual PsbTimeoutMsg* PsbTimeoutMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 140 of file SignallingMsg_m.h.
{return new PsbTimeoutMsg(*this);}
virtual int PsbTimeoutMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual int PsbTimeoutMsg::getId () const [virtual]
Referenced by RSVP::processPSB_TIMEOUT().
PsbTimeoutMsg& PsbTimeoutMsg::operator= (const PsbTimeoutMsg & other)
Reimplemented from SignallingMsg.
bool PsbTimeoutMsg::operator== (const PsbTimeoutMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void PsbTimeoutMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void PsbTimeoutMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void PsbTimeoutMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void PsbTimeoutMsg::setId (int id_var) [virtual]
Referenced by RSVP::createIngressPSB(), and RSVP::createPSB().
Member Data Documentation
int PsbTimeoutMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 130 of file SignallingMsg_m.h.
int PsbTimeoutMsg::id_var [protected]
Definition at line 129 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h