INET Framework for OMNeT++/OMNEST: LDPHello Class Reference
LDPHello Class Reference
#include <LDPPacket_m.h>
Public Member Functions
LDPHello (const char *name=NULL, int kind=0)
LDPHello (const LDPHello &other)
virtual ~LDPHello ()
LDPHello & operator= (const LDPHello &other)
virtual LDPHello * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual double getHoldTime () const
virtual void setHoldTime (double holdTime_var)
virtual bool getTbit () const
virtual void setTbit (bool tbit_var)
virtual bool getRbit () const
virtual void setRbit (bool rbit_var)
Protected Member Functions
bool operator== (const LDPHello &)
Protected Attributes
double holdTime_var
bool tbit_var
bool rbit_var
Detailed Description
Class generated from networklayer/ldp/LDPPacket.msg by opp_msgc.
 packet LDPHello extends LDPPacket
 {
     double holdTime;
     bool tbit;
     bool rbit;
 }
Definition at line 220 of file LDPPacket_m.h.
Constructor & Destructor Documentation
LDPHello::LDPHello (const char * name = NULL, int kind = 0)
Referenced by dup().
LDPHello::LDPHello (const LDPHello & other)
virtual LDPHello::~LDPHello () [virtual]
Member Function Documentation
virtual LDPHello* LDPHello::dup () const [inline, virtual]
Reimplemented from LDPPacket.
Definition at line 235 of file LDPPacket_m.h.
{return new LDPHello(*this);}
virtual double LDPHello::getHoldTime () const [virtual]
virtual bool LDPHello::getRbit () const [virtual]
virtual bool LDPHello::getTbit () const [virtual]
LDPHello& LDPHello::operator= (const LDPHello & other)
Reimplemented from LDPPacket.
bool LDPHello::operator== (const LDPHello &) [protected]
Reimplemented from LDPPacket.
virtual void LDPHello::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doPacking().
virtual void LDPHello::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doUnpacking().
virtual void LDPHello::setHoldTime (double holdTime_var) [virtual]
Referenced by LDP::sendHelloTo().
virtual void LDPHello::setRbit (bool rbit_var) [virtual]
virtual void LDPHello::setTbit (bool tbit_var) [virtual]
Member Data Documentation
double LDPHello::holdTime_var [protected]
Definition at line 223 of file LDPPacket_m.h.
bool LDPHello::rbit_var [protected]
Definition at line 225 of file LDPPacket_m.h.
bool LDPHello::tbit_var [protected]
Definition at line 224 of file LDPPacket_m.h.
The documentation for this class was generated from the following file:
LDPPacket_m.h