INET Framework for OMNeT++/OMNEST: OSPFASExternalLSA Class Reference
OSPFASExternalLSA Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFASExternalLSA ()
OSPFASExternalLSA (const OSPFASExternalLSA &other)
virtual ~OSPFASExternalLSA ()
OSPFASExternalLSA & operator= (const OSPFASExternalLSA &other)
virtual OSPFASExternalLSA * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OSPFASExternalLSAContents & getContents ()
virtual const
OSPFASExternalLSAContents & getContents () const
virtual void setContents (const OSPFASExternalLSAContents &contents_var)
Protected Member Functions
bool operator== (const OSPFASExternalLSA &)
Protected Attributes
::OSPFASExternalLSAContents contents_var
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class OSPFASExternalLSA extends OSPFLSA
 {
     OSPFASExternalLSAContents contents;
 }
Definition at line 646 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFASExternalLSA::OSPFASExternalLSA ()
Referenced by dup().
OSPFASExternalLSA::OSPFASExternalLSA (const OSPFASExternalLSA & other)
virtual OSPFASExternalLSA::~OSPFASExternalLSA () [virtual]
Member Function Documentation
virtual OSPFASExternalLSA* OSPFASExternalLSA::dup () const [inline, virtual]
Reimplemented from OSPFLSA.
Definition at line 659 of file OSPFPacket_m.h.
{return new OSPFASExternalLSA(*this);}
virtual const OSPFASExternalLSAContents& OSPFASExternalLSA::getContents () const [inline, virtual]
Definition at line 665 of file OSPFPacket_m.h.
Referenced by getContents().
{return const_cast<OSPFASExternalLSA*>(this)->getContents();}
virtual OSPFASExternalLSAContents& OSPFASExternalLSA::getContents () [virtual]
Referenced by CalculateLSASize(), OSPF::ASExternalLSA::DiffersFrom(), OSPF::Router::GetUniqueLinkStateID(), OSPF::Router::InstallASExternalLSA(), OSPF::Router::IsDestinationUnreachable(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
OSPFASExternalLSA& OSPFASExternalLSA::operator= (const OSPFASExternalLSA & other)
Reimplemented from OSPFLSA.
bool OSPFASExternalLSA::operator== (const OSPFASExternalLSA &) [protected]
Reimplemented from OSPFLSA.
virtual void OSPFASExternalLSA::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doPacking().
virtual void OSPFASExternalLSA::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doUnpacking().
virtual void OSPFASExternalLSA::setContents (const OSPFASExternalLSAContents & contents_var) [virtual]
Referenced by OSPF::Router::UpdateExternalRoute().
Member Data Documentation
::OSPFASExternalLSAContents OSPFASExternalLSA::contents_var [protected]
Definition at line 649 of file OSPFPacket_m.h.
Referenced by OSPF::ASExternalLSA::DiffersFrom().
The documentation for this class was generated from the following file:
OSPFPacket_m.h