INET Framework for OMNeT++/OMNEST: OSPFRouterLSA Class Reference
OSPFRouterLSA Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFRouterLSA ()
OSPFRouterLSA (const OSPFRouterLSA &other)
virtual ~OSPFRouterLSA ()
OSPFRouterLSA & operator= (const OSPFRouterLSA &other)
virtual OSPFRouterLSA * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getV_VirtualLinkEndpoint () const
virtual void setV_VirtualLinkEndpoint (bool V_VirtualLinkEndpoint_var)
virtual bool getE_ASBoundaryRouter () const
virtual void setE_ASBoundaryRouter (bool E_ASBoundaryRouter_var)
virtual bool getB_AreaBorderRouter () const
virtual void setB_AreaBorderRouter (bool B_AreaBorderRouter_var)
virtual unsigned short getNumberOfLinks () const
virtual void setNumberOfLinks (unsigned short numberOfLinks_var)
virtual void setLinksArraySize (unsigned int size)
virtual unsigned int getLinksArraySize () const
virtual Link & getLinks (unsigned int k)
virtual const Link & getLinks (unsigned int k) const
virtual void setLinks (unsigned int k, const Link &links_var)
Protected Member Functions
bool operator== (const OSPFRouterLSA &)
Protected Attributes
bool V_VirtualLinkEndpoint_var
bool E_ASBoundaryRouter_var
bool B_AreaBorderRouter_var
unsigned short numberOfLinks_var
::Link * links_var
unsigned int links_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class OSPFRouterLSA extends OSPFLSA
 {
     bool V_VirtualLinkEndpoint = false;
     bool E_ASBoundaryRouter = false;
     bool B_AreaBorderRouter = false;
     unsigned short numberOfLinks = 0;
     Link links[];
 }
Definition at line 431 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFRouterLSA::OSPFRouterLSA ()
Referenced by dup().
OSPFRouterLSA::OSPFRouterLSA (const OSPFRouterLSA & other)
virtual OSPFRouterLSA::~OSPFRouterLSA () [virtual]
Member Function Documentation
virtual OSPFRouterLSA* OSPFRouterLSA::dup () const [inline, virtual]
Reimplemented from OSPFLSA.
Definition at line 449 of file OSPFPacket_m.h.
{return new OSPFRouterLSA(*this);}
virtual bool OSPFRouterLSA::getB_AreaBorderRouter () const [virtual]
Referenced by OSPF::RouterLSA::DiffersFrom(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual bool OSPFRouterLSA::getE_ASBoundaryRouter () const [virtual]
Referenced by OSPF::RouterLSA::DiffersFrom(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual const Link& OSPFRouterLSA::getLinks (unsigned int k) const [inline, virtual]
Definition at line 465 of file OSPFPacket_m.h.
Referenced by getLinks().
{return const_cast<OSPFRouterLSA*>(this)->getLinks(k);}
virtual Link& OSPFRouterLSA::getLinks (unsigned int k) [virtual]
Referenced by CalculateLSASize(), OSPF::Area::CalculateNextHops(), OSPF::RouterLSA::DiffersFrom(), OSPF::Area::HasLink(), OSPF::Router::IsDestinationUnreachable(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual unsigned int OSPFRouterLSA::getLinksArraySize () const [virtual]
Referenced by CalculateLSASize(), OSPF::Area::CalculateNextHops(), OSPF::RouterLSA::DiffersFrom(), OSPF::Area::HasLink(), OSPF::Router::IsDestinationUnreachable(), OSPF::Area::OriginateRouterLSA(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual unsigned short OSPFRouterLSA::getNumberOfLinks () const [virtual]
Referenced by OSPF::RouterLSA::DiffersFrom().
virtual bool OSPFRouterLSA::getV_VirtualLinkEndpoint () const [virtual]
Referenced by OSPF::RouterLSA::DiffersFrom(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
OSPFRouterLSA& OSPFRouterLSA::operator= (const OSPFRouterLSA & other)
Reimplemented from OSPFLSA.
bool OSPFRouterLSA::operator== (const OSPFRouterLSA &) [protected]
Reimplemented from OSPFLSA.
virtual void OSPFRouterLSA::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doPacking().
virtual void OSPFRouterLSA::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doUnpacking().
virtual void OSPFRouterLSA::setB_AreaBorderRouter (bool B_AreaBorderRouter_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void OSPFRouterLSA::setE_ASBoundaryRouter (bool E_ASBoundaryRouter_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void OSPFRouterLSA::setLinks (unsigned int k, const Link & links_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void OSPFRouterLSA::setLinksArraySize (unsigned int size) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void OSPFRouterLSA::setNumberOfLinks (unsigned short numberOfLinks_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
virtual void OSPFRouterLSA::setV_VirtualLinkEndpoint (bool V_VirtualLinkEndpoint_var) [virtual]
Referenced by OSPF::Area::OriginateRouterLSA().
Member Data Documentation
bool OSPFRouterLSA::B_AreaBorderRouter_var [protected]
Definition at line 436 of file OSPFPacket_m.h.
Referenced by OSPF::RouterLSA::DiffersFrom().
bool OSPFRouterLSA::E_ASBoundaryRouter_var [protected]
Definition at line 435 of file OSPFPacket_m.h.
Referenced by OSPF::RouterLSA::DiffersFrom().
unsigned int OSPFRouterLSA::links_arraysize [protected]
Definition at line 439 of file OSPFPacket_m.h.
Referenced by OSPF::RouterLSA::DiffersFrom().
::Link* OSPFRouterLSA::links_var [protected]
Definition at line 438 of file OSPFPacket_m.h.
Referenced by OSPF::RouterLSA::DiffersFrom().
unsigned short OSPFRouterLSA::numberOfLinks_var [protected]
Definition at line 437 of file OSPFPacket_m.h.
Referenced by OSPF::RouterLSA::DiffersFrom().
bool OSPFRouterLSA::V_VirtualLinkEndpoint_var [protected]
Definition at line 434 of file OSPFPacket_m.h.
Referenced by OSPF::RouterLSA::DiffersFrom().
The documentation for this class was generated from the following file:
OSPFPacket_m.h