INET Framework for OMNeT++/OMNEST: LinkStateMsg Class Reference
LinkStateMsg Class Reference
#include <LinkStatePacket_m.h>
Public Member Functions
LinkStateMsg (const char *name=NULL, int kind=0)
LinkStateMsg (const LinkStateMsg &other)
virtual ~LinkStateMsg ()
LinkStateMsg & operator= (const LinkStateMsg &other)
virtual LinkStateMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setLinkInfoArraySize (unsigned int size)
virtual unsigned int getLinkInfoArraySize () const
virtual TELinkStateInfo & getLinkInfo (unsigned int k)
virtual const TELinkStateInfo & getLinkInfo (unsigned int k) const
virtual void setLinkInfo (unsigned int k, const TELinkStateInfo &linkInfo_var)
virtual bool getRequest () const
virtual void setRequest (bool request_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const LinkStateMsg &)
Protected Attributes
::TELinkStateInfo * linkInfo_var
unsigned int linkInfo_arraysize
bool request_var
int command_var
Detailed Description
Class generated from networklayer/ted/LinkStatePacket.msg by opp_msgc.
 packet LinkStateMsg
 {
     TELinkStateInfo linkInfo[];
     bool request = false;
     int command = LINK_STATE_MESSAGE;
 }
Definition at line 37 of file LinkStatePacket_m.h.
Constructor & Destructor Documentation
LinkStateMsg::LinkStateMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
LinkStateMsg::LinkStateMsg (const LinkStateMsg & other)
virtual LinkStateMsg::~LinkStateMsg () [virtual]
Member Function Documentation
virtual LinkStateMsg* LinkStateMsg::dup () const [inline, virtual]
Definition at line 53 of file LinkStatePacket_m.h.
{return new LinkStateMsg(*this);}
virtual int LinkStateMsg::getCommand () const [virtual]
virtual const TELinkStateInfo& LinkStateMsg::getLinkInfo (unsigned int k) const [inline, virtual]
Definition at line 61 of file LinkStatePacket_m.h.
Referenced by getLinkInfo().
{return const_cast<LinkStateMsg*>(this)->getLinkInfo(k);}
virtual TELinkStateInfo& LinkStateMsg::getLinkInfo (unsigned int k) [virtual]
Referenced by LinkStateRouting::processLINK_STATE_MESSAGE().
virtual unsigned int LinkStateMsg::getLinkInfoArraySize () const [virtual]
Referenced by LinkStateRouting::processLINK_STATE_MESSAGE(), and LinkStateRouting::sendToIP().
virtual bool LinkStateMsg::getRequest () const [virtual]
Referenced by LinkStateRouting::processLINK_STATE_MESSAGE().
LinkStateMsg& LinkStateMsg::operator= (const LinkStateMsg & other)
bool LinkStateMsg::operator== (const LinkStateMsg &) [protected]
virtual void LinkStateMsg::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void LinkStateMsg::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void LinkStateMsg::setCommand (int command_var) [virtual]
virtual void LinkStateMsg::setLinkInfo (unsigned int k, const TELinkStateInfo & linkInfo_var) [virtual]
Referenced by LinkStateRouting::sendToPeer().
virtual void LinkStateMsg::setLinkInfoArraySize (unsigned int size) [virtual]
Referenced by LinkStateRouting::sendToPeer().
virtual void LinkStateMsg::setRequest (bool request_var) [virtual]
Referenced by LinkStateRouting::sendToPeer().
Member Data Documentation
int LinkStateMsg::command_var [protected]
Definition at line 43 of file LinkStatePacket_m.h.
unsigned int LinkStateMsg::linkInfo_arraysize [protected]
Definition at line 41 of file LinkStatePacket_m.h.
::TELinkStateInfo* LinkStateMsg::linkInfo_var [protected]
Definition at line 40 of file LinkStatePacket_m.h.
bool LinkStateMsg::request_var [protected]
Definition at line 42 of file LinkStatePacket_m.h.
The documentation for this class was generated from the following file:
LinkStatePacket_m.h