INET Framework for OMNeT++/OMNEST: ICMPv6EchoReplyMsg Class Reference
ICMPv6EchoReplyMsg Class Reference
#include <ICMPv6Message_m.h>
Public Member Functions
ICMPv6EchoReplyMsg (const char *name=NULL, int kind=0)
ICMPv6EchoReplyMsg (const ICMPv6EchoReplyMsg &other)
virtual ~ICMPv6EchoReplyMsg ()
ICMPv6EchoReplyMsg & operator= (const ICMPv6EchoReplyMsg &other)
virtual ICMPv6EchoReplyMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCode () const
virtual void setCode (int code_var)
virtual int getIdentifier () const
virtual void setIdentifier (int identifier_var)
virtual int getSeqNumber () const
virtual void setSeqNumber (int seqNumber_var)
Protected Member Functions
bool operator== (const ICMPv6EchoReplyMsg &)
Protected Attributes
int code_var
int identifier_var
int seqNumber_var
Detailed Description
Class generated from networklayer/icmpv6/ICMPv6Message.msg by opp_msgc.
 packet ICMPv6EchoReplyMsg extends ICMPv6Message
 {
     int code;
     int identifier;
     int seqNumber;
 }
Definition at line 352 of file ICMPv6Message_m.h.
Constructor & Destructor Documentation
ICMPv6EchoReplyMsg::ICMPv6EchoReplyMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPv6EchoReplyMsg::ICMPv6EchoReplyMsg (const ICMPv6EchoReplyMsg & other)
virtual ICMPv6EchoReplyMsg::~ICMPv6EchoReplyMsg () [virtual]
Member Function Documentation
virtual ICMPv6EchoReplyMsg* ICMPv6EchoReplyMsg::dup () const [inline, virtual]
Reimplemented from ICMPv6Message.
Definition at line 367 of file ICMPv6Message_m.h.
{return new ICMPv6EchoReplyMsg(*this);}
virtual int ICMPv6EchoReplyMsg::getCode () const [virtual]
virtual int ICMPv6EchoReplyMsg::getIdentifier () const [virtual]
virtual int ICMPv6EchoReplyMsg::getSeqNumber () const [virtual]
ICMPv6EchoReplyMsg& ICMPv6EchoReplyMsg::operator= (const ICMPv6EchoReplyMsg & other)
Reimplemented from ICMPv6Message.
bool ICMPv6EchoReplyMsg::operator== (const ICMPv6EchoReplyMsg &) [protected]
Reimplemented from ICMPv6Message.
virtual void ICMPv6EchoReplyMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doPacking().
virtual void ICMPv6EchoReplyMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doUnpacking().
virtual void ICMPv6EchoReplyMsg::setCode (int code_var) [virtual]
virtual void ICMPv6EchoReplyMsg::setIdentifier (int identifier_var) [virtual]
virtual void ICMPv6EchoReplyMsg::setSeqNumber (int seqNumber_var) [virtual]
Member Data Documentation
int ICMPv6EchoReplyMsg::code_var [protected]
Definition at line 355 of file ICMPv6Message_m.h.
int ICMPv6EchoReplyMsg::identifier_var [protected]
Definition at line 356 of file ICMPv6Message_m.h.
int ICMPv6EchoReplyMsg::seqNumber_var [protected]
Definition at line 357 of file ICMPv6Message_m.h.
The documentation for this class was generated from the following file:
ICMPv6Message_m.h