INET Framework for OMNeT++/OMNEST: Ieee80211AssociationResponseFrame Class Reference
Ieee80211AssociationResponseFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211AssociationResponseFrame (const char *name=NULL, int kind=0)
Ieee80211AssociationResponseFrame (const Ieee80211AssociationResponseFrame &other)
virtual ~Ieee80211AssociationResponseFrame ()
Ieee80211AssociationResponseFrame & operator= (const Ieee80211AssociationResponseFrame &other)
virtual
Ieee80211AssociationResponseFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211AssociationResponseFrameBody & getBody ()
virtual const
Ieee80211AssociationResponseFrameBody & getBody () const
virtual void setBody (const Ieee80211AssociationResponseFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211AssociationResponseFrame &)
Protected Attributes
::Ieee80211AssociationResponseFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211AssociationResponseFrame extends Ieee80211ManagementFrame
 {
     type = ST_ASSOCIATIONRESPONSE;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211AssociationResponseFrameBody body;
 }
Definition at line 785 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211AssociationResponseFrame::Ieee80211AssociationResponseFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211AssociationResponseFrame::Ieee80211AssociationResponseFrame (const Ieee80211AssociationResponseFrame & other)
virtual Ieee80211AssociationResponseFrame::~Ieee80211AssociationResponseFrame () [virtual]
Member Function Documentation
virtual Ieee80211AssociationResponseFrame* Ieee80211AssociationResponseFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 798 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211AssociationResponseFrame(*this);}
virtual const Ieee80211AssociationResponseFrameBody& Ieee80211AssociationResponseFrame::getBody () const [inline, virtual]
Definition at line 804 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211AssociationResponseFrame*>(this)->getBody();}
virtual Ieee80211AssociationResponseFrameBody& Ieee80211AssociationResponseFrame::getBody () [virtual]
Referenced by Ieee80211MgmtAP::handleAssociationRequestFrame(), and Ieee80211MgmtSTA::handleAssociationResponseFrame().
Ieee80211AssociationResponseFrame& Ieee80211AssociationResponseFrame::operator= (const Ieee80211AssociationResponseFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211AssociationResponseFrame::operator== (const Ieee80211AssociationResponseFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211AssociationResponseFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211AssociationResponseFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211AssociationResponseFrame::setBody (const Ieee80211AssociationResponseFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211AssociationResponseFrameBody Ieee80211AssociationResponseFrame::body_var [protected]
Definition at line 788 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h