INET Framework for OMNeT++/OMNEST: OSPFLSA Class Reference
OSPFLSA Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFLSA ()
OSPFLSA (const OSPFLSA &other)
virtual ~OSPFLSA ()
OSPFLSA & operator= (const OSPFLSA &other)
virtual OSPFLSA * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OSPFLSAHeader & getHeader ()
virtual const OSPFLSAHeader & getHeader () const
virtual void setHeader (const OSPFLSAHeader &header_var)
Protected Member Functions
bool operator== (const OSPFLSA &)
Protected Attributes
::OSPFLSAHeader header_var
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class OSPFLSA
 {
     OSPFLSAHeader header;
 }
Definition at line 320 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFLSA::OSPFLSA ()
Referenced by dup().
OSPFLSA::OSPFLSA (const OSPFLSA & other)
virtual OSPFLSA::~OSPFLSA () [virtual]
Member Function Documentation
virtual OSPFLSA* OSPFLSA::dup () const [inline, virtual]
Reimplemented in OSPFRouterLSA, OSPFNetworkLSA, OSPFSummaryLSA, and OSPFASExternalLSA.
Definition at line 333 of file OSPFPacket_m.h.
{return new OSPFLSA(*this);}
virtual const OSPFLSAHeader& OSPFLSA::getHeader () const [inline, virtual]
Definition at line 339 of file OSPFPacket_m.h.
Referenced by getHeader().
{return const_cast<OSPFLSA*>(this)->getHeader();}
virtual OSPFLSAHeader& OSPFLSA::getHeader () [virtual]
Referenced by OSPF::Neighbor::AddToRetransmissionList(), OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::Area::CalculateNextHops(), OSPF::NeighborState::ChangeState(), OSPF::InterfaceState::ChangeState(), OSPF::Neighbor::CreateDatabaseSummary(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::SummaryLSA::DiffersFrom(), OSPF::RouterLSA::DiffersFrom(), OSPF::NetworkLSA::DiffersFrom(), OSPF::ASExternalLSA::DiffersFrom(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::FloodLSA(), OSPF::Interface::FloodLSA(), OSPF::Router::GetUniqueLinkStateID(), OSPF::Area::GetUniqueLinkStateID(), OSPF::Area::HasLink(), OSPF::Router::InstallASExternalLSA(), OSPF::Router::InstallLSA(), OSPF::Area::InstallNetworkLSA(), OSPF::Area::InstallRouterLSA(), OSPF::Area::InstallSummaryLSA(), OSPF::Router::IsDestinationUnreachable(), OSPF::Neighbor::IsLSAOnRetransmissionList(), operator<<(), OSPF::Router::OriginateASExternalLSA(), OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), OSPF::Area::OriginateSummaryLSA(), OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::DatabaseDescriptionHandler::ProcessDDPacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), OSPF::LinkStateAcknowledgementHandler::ProcessPacket(), OSPF::HelloHandler::ProcessPacket(), OSPF::Neighbor::RetransmitUpdatePacket(), and OSPF::Router::UpdateExternalRoute().
OSPFLSA& OSPFLSA::operator= (const OSPFLSA & other)
Reimplemented in OSPFRouterLSA, OSPFNetworkLSA, OSPFSummaryLSA, and OSPFASExternalLSA.
bool OSPFLSA::operator== (const OSPFLSA &) [protected]
Reimplemented in OSPFRouterLSA, OSPFNetworkLSA, OSPFSummaryLSA, and OSPFASExternalLSA.
virtual void OSPFLSA::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in OSPFRouterLSA, OSPFNetworkLSA, OSPFSummaryLSA, and OSPFASExternalLSA.
Referenced by doPacking().
virtual void OSPFLSA::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in OSPFRouterLSA, OSPFNetworkLSA, OSPFSummaryLSA, and OSPFASExternalLSA.
Referenced by doUnpacking().
virtual void OSPFLSA::setHeader (const OSPFLSAHeader & header_var) [virtual]
Member Data Documentation
::OSPFLSAHeader OSPFLSA::header_var [protected]
Definition at line 323 of file OSPFPacket_m.h.
Referenced by OSPF::SummaryLSA::DiffersFrom(), OSPF::RouterLSA::DiffersFrom(), OSPF::NetworkLSA::DiffersFrom(), and OSPF::ASExternalLSA::DiffersFrom().
The documentation for this class was generated from the following file:
OSPFPacket_m.h