INET Framework for OMNeT++/OMNEST: Ieee80211ManagementFrame Class Reference
Ieee80211ManagementFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211ManagementFrame (const char *name=NULL, int kind=0)
Ieee80211ManagementFrame (const Ieee80211ManagementFrame &other)
virtual ~Ieee80211ManagementFrame ()
Ieee80211ManagementFrame & operator= (const Ieee80211ManagementFrame &other)
virtual Ieee80211ManagementFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211ManagementFrame &)
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211ManagementFrame extends Ieee80211DataOrMgmtFrame
 {
 }
Definition at line 385 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211ManagementFrame::Ieee80211ManagementFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211ManagementFrame::Ieee80211ManagementFrame (const Ieee80211ManagementFrame & other)
virtual Ieee80211ManagementFrame::~Ieee80211ManagementFrame () [virtual]
Member Function Documentation
virtual Ieee80211ManagementFrame* Ieee80211ManagementFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211DataOrMgmtFrame.
Reimplemented in Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Definition at line 397 of file Ieee80211Frame_m.h.
{return new Ieee80211ManagementFrame(*this);}
Ieee80211ManagementFrame& Ieee80211ManagementFrame::operator= (const Ieee80211ManagementFrame & other)
Reimplemented from Ieee80211DataOrMgmtFrame.
Reimplemented in Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
bool Ieee80211ManagementFrame::operator== (const Ieee80211ManagementFrame &) [protected]
Reimplemented from Ieee80211DataOrMgmtFrame.
Reimplemented in Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
virtual void Ieee80211ManagementFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211DataOrMgmtFrame.
Reimplemented in Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doPacking().
virtual void Ieee80211ManagementFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211DataOrMgmtFrame.
Reimplemented in Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h