INET Framework for OMNeT++/OMNEST: Ieee80211Prim_AssociateRequest Class Reference
Ieee80211Prim_AssociateRequest Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_AssociateRequest ()
Ieee80211Prim_AssociateRequest (const Ieee80211Prim_AssociateRequest &other)
virtual ~Ieee80211Prim_AssociateRequest ()
Ieee80211Prim_AssociateRequest & operator= (const Ieee80211Prim_AssociateRequest &other)
virtual
Ieee80211Prim_AssociateRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getAddress ()
virtual const MACAddress & getAddress () const
virtual void setAddress (const MACAddress &address_var)
virtual simtime_t getTimeout () const
virtual void setTimeout (simtime_t timeout_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_AssociateRequest &)
Protected Attributes
::MACAddress address_var
simtime_t timeout_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_AssociateRequest extends Ieee80211PrimRequest
 {
     MACAddress address;
     simtime_t timeout;
 }
Definition at line 459 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_AssociateRequest::Ieee80211Prim_AssociateRequest ()
Referenced by dup().
Ieee80211Prim_AssociateRequest::Ieee80211Prim_AssociateRequest (const Ieee80211Prim_AssociateRequest & other)
virtual Ieee80211Prim_AssociateRequest::~Ieee80211Prim_AssociateRequest () [virtual]
Member Function Documentation
virtual Ieee80211Prim_AssociateRequest* Ieee80211Prim_AssociateRequest::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimRequest.
Reimplemented in Ieee80211Prim_ReassociateRequest.
Definition at line 473 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_AssociateRequest(*this);}
virtual const MACAddress& Ieee80211Prim_AssociateRequest::getAddress () const [inline, virtual]
Definition at line 479 of file Ieee80211Primitives_m.h.
Referenced by getAddress().
{return const_cast<Ieee80211Prim_AssociateRequest*>(this)->getAddress();}
virtual MACAddress& Ieee80211Prim_AssociateRequest::getAddress () [virtual]
Referenced by Ieee80211MgmtSTA::processAssociateCommand().
virtual simtime_t Ieee80211Prim_AssociateRequest::getTimeout () const [virtual]
Referenced by Ieee80211MgmtSTA::processAssociateCommand().
Ieee80211Prim_AssociateRequest& Ieee80211Prim_AssociateRequest::operator= (const Ieee80211Prim_AssociateRequest & other)
Reimplemented from Ieee80211PrimRequest.
Reimplemented in Ieee80211Prim_ReassociateRequest.
bool Ieee80211Prim_AssociateRequest::operator== (const Ieee80211Prim_AssociateRequest &) [protected]
Reimplemented from Ieee80211PrimRequest.
Reimplemented in Ieee80211Prim_ReassociateRequest.
virtual void Ieee80211Prim_AssociateRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Reimplemented in Ieee80211Prim_ReassociateRequest.
Referenced by doPacking().
virtual void Ieee80211Prim_AssociateRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Reimplemented in Ieee80211Prim_ReassociateRequest.
Referenced by doUnpacking().
virtual void Ieee80211Prim_AssociateRequest::setAddress (const MACAddress & address_var) [virtual]
Referenced by Ieee80211AgentSTA::sendAssociateRequest(), and Ieee80211AgentSTA::sendReassociateRequest().
virtual void Ieee80211Prim_AssociateRequest::setTimeout (simtime_t timeout_var) [virtual]
Referenced by Ieee80211AgentSTA::sendAssociateRequest(), and Ieee80211AgentSTA::sendReassociateRequest().
Member Data Documentation
::MACAddress Ieee80211Prim_AssociateRequest::address_var [protected]
Definition at line 462 of file Ieee80211Primitives_m.h.
simtime_t Ieee80211Prim_AssociateRequest::timeout_var [protected]
Definition at line 463 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h