INET Framework for OMNeT++/OMNEST: SCTPDataMsg Class Reference
SCTPDataMsg Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPDataMsg (const char *name=NULL, int kind=0)
SCTPDataMsg (const SCTPDataMsg &other)
virtual ~SCTPDataMsg ()
SCTPDataMsg & operator= (const SCTPDataMsg &other)
virtual SCTPDataMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getEBit () const
virtual void setEBit (bool eBit_var)
virtual bool getBBit () const
virtual void setBBit (bool bBit_var)
virtual simtime_t getEnqueuingTime () const
virtual void setEnqueuingTime (simtime_t enqueuingTime_var)
virtual simtime_t getExpiryTime () const
virtual void setExpiryTime (simtime_t expiryTime_var)
virtual uint32 getPpid () const
virtual void setPpid (uint32 ppid_var)
virtual IPvXAddress & getInitialDestination ()
virtual const IPvXAddress & getInitialDestination () const
virtual void setInitialDestination (const IPvXAddress &initialDestination_var)
virtual uint32 getMsgNum () const
virtual void setMsgNum (uint32 msgNum_var)
virtual uint16 getSid () const
virtual void setSid (uint16 sid_var)
virtual bool getOrdered () const
virtual void setOrdered (bool ordered_var)
virtual uint32 getBooksize () const
virtual void setBooksize (uint32 booksize_var)
virtual uint32 getRtx () const
virtual void setRtx (uint32 rtx_var)
virtual bool getFragment () const
virtual void setFragment (bool fragment_var)
Protected Member Functions
bool operator== (const SCTPDataMsg &)
Protected Attributes
bool eBit_var
bool bBit_var
simtime_t enqueuingTime_var
simtime_t expiryTime_var
uint32 ppid_var
::IPvXAddress initialDestination_var
uint32 msgNum_var
uint16 sid_var
bool ordered_var
uint32 booksize_var
uint32 rtx_var
bool fragment_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPDataMsg extends cPacket
 {
     bool eBit = 0;
     bool bBit = 0;
     simtime_t enqueuingTime;
     simtime_t expiryTime;
     uint32 ppid;
     IPvXAddress initialDestination;
     uint32 msgNum;
     uint16 sid;
     bool ordered;
     uint32 booksize;
     uint32 rtx;
     bool fragment;
 }
Definition at line 505 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPDataMsg::SCTPDataMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPDataMsg::SCTPDataMsg (const SCTPDataMsg & other)
virtual SCTPDataMsg::~SCTPDataMsg () [virtual]
Member Function Documentation
virtual SCTPDataMsg* SCTPDataMsg::dup () const [inline, virtual]
Definition at line 529 of file SCTPMessage_m.h.
{return new SCTPDataMsg(*this);}
virtual bool SCTPDataMsg::getBBit () const [virtual]
Referenced by SCTPAssociation::makeDataVarFromDataMsg().
virtual uint32 SCTPDataMsg::getBooksize () const [virtual]
Referenced by SCTPAssociation::calculateBytesToSendOnPath(), SCTPAssociation::dequeueOutboundDataMsg(), SCTPAssociation::makeDataVarFromDataMsg(), and SCTPAssociation::process_SEND().
virtual bool SCTPDataMsg::getEBit () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::makeDataVarFromDataMsg().
virtual simtime_t SCTPDataMsg::getEnqueuingTime () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::makeDataVarFromDataMsg().
virtual simtime_t SCTPDataMsg::getExpiryTime () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::makeDataVarFromDataMsg().
virtual bool SCTPDataMsg::getFragment () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg().
virtual const IPvXAddress& SCTPDataMsg::getInitialDestination () const [inline, virtual]
Definition at line 545 of file SCTPMessage_m.h.
Referenced by getInitialDestination().
{return const_cast<SCTPDataMsg*>(this)->getInitialDestination();}
virtual IPvXAddress& SCTPDataMsg::getInitialDestination () [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::process_SEND().
virtual uint32 SCTPDataMsg::getMsgNum () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg().
virtual bool SCTPDataMsg::getOrdered () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::makeDataVarFromDataMsg().
virtual uint32 SCTPDataMsg::getPpid () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::makeDataVarFromDataMsg().
virtual uint32 SCTPDataMsg::getRtx () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::makeDataVarFromDataMsg().
virtual uint16 SCTPDataMsg::getSid () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::makeDataVarFromDataMsg().
SCTPDataMsg& SCTPDataMsg::operator= (const SCTPDataMsg & other)
bool SCTPDataMsg::operator== (const SCTPDataMsg &) [protected]
virtual void SCTPDataMsg::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SCTPDataMsg::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SCTPDataMsg::setBBit (bool bBit_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg().
virtual void SCTPDataMsg::setBooksize (uint32 booksize_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::process_SEND().
virtual void SCTPDataMsg::setEBit (bool eBit_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg().
virtual void SCTPDataMsg::setEnqueuingTime (simtime_t enqueuingTime_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::process_SEND().
virtual void SCTPDataMsg::setExpiryTime (simtime_t expiryTime_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg().
virtual void SCTPDataMsg::setFragment (bool fragment_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg().
virtual void SCTPDataMsg::setInitialDestination (const IPvXAddress & initialDestination_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPAssociation::makeDataVarFromDataMsg(), and SCTPAssociation::process_SEND().
virtual void SCTPDataMsg::setMsgNum (uint32 msgNum_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::process_SEND().
virtual void SCTPDataMsg::setOrdered (bool ordered_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::process_SEND().
virtual void SCTPDataMsg::setPpid (uint32 ppid_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::process_SEND().
virtual void SCTPDataMsg::setRtx (uint32 rtx_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg().
virtual void SCTPDataMsg::setSid (uint16 sid_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPAssociation::process_SEND().
Member Data Documentation
bool SCTPDataMsg::bBit_var [protected]
Definition at line 509 of file SCTPMessage_m.h.
uint32 SCTPDataMsg::booksize_var [protected]
Definition at line 517 of file SCTPMessage_m.h.
bool SCTPDataMsg::eBit_var [protected]
Definition at line 508 of file SCTPMessage_m.h.
simtime_t SCTPDataMsg::enqueuingTime_var [protected]
Definition at line 510 of file SCTPMessage_m.h.
simtime_t SCTPDataMsg::expiryTime_var [protected]
Definition at line 511 of file SCTPMessage_m.h.
bool SCTPDataMsg::fragment_var [protected]
Definition at line 519 of file SCTPMessage_m.h.
::IPvXAddress SCTPDataMsg::initialDestination_var [protected]
Definition at line 513 of file SCTPMessage_m.h.
uint32 SCTPDataMsg::msgNum_var [protected]
Definition at line 514 of file SCTPMessage_m.h.
bool SCTPDataMsg::ordered_var [protected]
Definition at line 516 of file SCTPMessage_m.h.
uint32 SCTPDataMsg::ppid_var [protected]
Definition at line 512 of file SCTPMessage_m.h.
uint32 SCTPDataMsg::rtx_var [protected]
Definition at line 518 of file SCTPMessage_m.h.
uint16 SCTPDataMsg::sid_var [protected]
Definition at line 515 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h