INET Framework for OMNeT++/OMNEST: HelloTimerMsg Class Reference
HelloTimerMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
HelloTimerMsg (const char *name=NULL, int kind=0)
HelloTimerMsg (const HelloTimerMsg &other)
virtual ~HelloTimerMsg ()
HelloTimerMsg & operator= (const HelloTimerMsg &other)
virtual HelloTimerMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getPeer ()
virtual const IPAddress & getPeer () const
virtual void setPeer (const IPAddress &peer_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const HelloTimerMsg &)
Protected Attributes
::IPAddress peer_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message HelloTimerMsg extends SignallingMsg
 {
     IPAddress peer;
     int command = MSG_HELLO_TIMER;
 }
Definition at line 282 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
HelloTimerMsg::HelloTimerMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
HelloTimerMsg::HelloTimerMsg (const HelloTimerMsg & other)
virtual HelloTimerMsg::~HelloTimerMsg () [virtual]
Member Function Documentation
virtual HelloTimerMsg* HelloTimerMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 296 of file SignallingMsg_m.h.
{return new HelloTimerMsg(*this);}
virtual int HelloTimerMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual const IPAddress& HelloTimerMsg::getPeer () const [inline, virtual]
Definition at line 302 of file SignallingMsg_m.h.
Referenced by getPeer().
{return const_cast<HelloTimerMsg*>(this)->getPeer();}
virtual IPAddress& HelloTimerMsg::getPeer () [virtual]
Referenced by RSVP::processHELLO_TIMER().
HelloTimerMsg& HelloTimerMsg::operator= (const HelloTimerMsg & other)
Reimplemented from SignallingMsg.
bool HelloTimerMsg::operator== (const HelloTimerMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void HelloTimerMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void HelloTimerMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void HelloTimerMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void HelloTimerMsg::setPeer (const IPAddress & peer_var) [virtual]
Referenced by RSVP::setupHello().
Member Data Documentation
int HelloTimerMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 286 of file SignallingMsg_m.h.
::IPAddress HelloTimerMsg::peer_var [protected]
Definition at line 285 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h