INET Framework for OMNeT++/OMNEST: IPv6RoutingHeader Class Reference
IPv6RoutingHeader Class Reference
#include <IPv6ExtensionHeaders_m.h>
Public Member Functions
IPv6RoutingHeader ()
IPv6RoutingHeader (const IPv6RoutingHeader &other)
virtual ~IPv6RoutingHeader ()
IPv6RoutingHeader & operator= (const IPv6RoutingHeader &other)
virtual IPv6RoutingHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned char getRoutingType () const
virtual void setRoutingType (unsigned char routingType_var)
virtual unsigned char getSegmentsLeft () const
virtual void setSegmentsLeft (unsigned char segmentsLeft_var)
virtual void setAddressArraySize (unsigned int size)
virtual unsigned int getAddressArraySize () const
virtual IPv6Address & getAddress (unsigned int k)
virtual const IPv6Address & getAddress (unsigned int k) const
virtual void setAddress (unsigned int k, const IPv6Address &address_var)
Protected Member Functions
bool operator== (const IPv6RoutingHeader &)
Protected Attributes
unsigned char routingType_var
unsigned char segmentsLeft_var
::IPv6Address * address_var
unsigned int address_arraysize
Detailed Description
Class generated from networklayer/ipv6/IPv6ExtensionHeaders.msg by opp_msgc.
 class IPv6RoutingHeader extends IPv6ExtensionHeader
 {
     unsigned char routingType;
     unsigned char segmentsLeft;
     IPv6Address address[];
 }
Definition at line 65 of file IPv6ExtensionHeaders_m.h.
Constructor & Destructor Documentation
IPv6RoutingHeader::IPv6RoutingHeader ()
Referenced by dup().
IPv6RoutingHeader::IPv6RoutingHeader (const IPv6RoutingHeader & other)
virtual IPv6RoutingHeader::~IPv6RoutingHeader () [virtual]
Member Function Documentation
virtual IPv6RoutingHeader* IPv6RoutingHeader::dup () const [inline, virtual]
Reimplemented from IPv6ExtensionHeader.
Definition at line 81 of file IPv6ExtensionHeaders_m.h.
{return new IPv6RoutingHeader(*this);}
virtual const IPv6Address& IPv6RoutingHeader::getAddress (unsigned int k) const [inline, virtual]
Definition at line 93 of file IPv6ExtensionHeaders_m.h.
Referenced by getAddress().
{return const_cast<IPv6RoutingHeader*>(this)->getAddress(k);}
virtual IPv6Address& IPv6RoutingHeader::getAddress (unsigned int k) [virtual]
virtual unsigned int IPv6RoutingHeader::getAddressArraySize () const [virtual]
virtual unsigned char IPv6RoutingHeader::getRoutingType () const [virtual]
virtual unsigned char IPv6RoutingHeader::getSegmentsLeft () const [virtual]
IPv6RoutingHeader& IPv6RoutingHeader::operator= (const IPv6RoutingHeader & other)
Reimplemented from IPv6ExtensionHeader.
bool IPv6RoutingHeader::operator== (const IPv6RoutingHeader &) [protected]
Reimplemented from IPv6ExtensionHeader_Base.
virtual void IPv6RoutingHeader::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doPacking().
virtual void IPv6RoutingHeader::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doUnpacking().
virtual void IPv6RoutingHeader::setAddress (unsigned int k, const IPv6Address & address_var) [virtual]
virtual void IPv6RoutingHeader::setAddressArraySize (unsigned int size) [virtual]
virtual void IPv6RoutingHeader::setRoutingType (unsigned char routingType_var) [virtual]
virtual void IPv6RoutingHeader::setSegmentsLeft (unsigned char segmentsLeft_var) [virtual]
Member Data Documentation
unsigned int IPv6RoutingHeader::address_arraysize [protected]
Definition at line 71 of file IPv6ExtensionHeaders_m.h.
::IPv6Address* IPv6RoutingHeader::address_var [protected]
Definition at line 70 of file IPv6ExtensionHeaders_m.h.
unsigned char IPv6RoutingHeader::routingType_var [protected]
Definition at line 68 of file IPv6ExtensionHeaders_m.h.
unsigned char IPv6RoutingHeader::segmentsLeft_var [protected]
Definition at line 69 of file IPv6ExtensionHeaders_m.h.
The documentation for this class was generated from the following file:
IPv6ExtensionHeaders_m.h