INET Framework for OMNeT++/OMNEST: OSPFASExternalLSAContents Class Reference
OSPFASExternalLSAContents Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFASExternalLSAContents ()
OSPFASExternalLSAContents (const OSPFASExternalLSAContents &other)
virtual ~OSPFASExternalLSAContents ()
OSPFASExternalLSAContents & operator= (const OSPFASExternalLSAContents &other)
virtual OSPFASExternalLSAContents * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getNetworkMask ()
virtual const IPAddress & getNetworkMask () const
virtual void setNetworkMask (const IPAddress &networkMask_var)
virtual bool getE_ExternalMetricType () const
virtual void setE_ExternalMetricType (bool E_ExternalMetricType_var)
virtual unsigned long getRouteCost () const
virtual void setRouteCost (unsigned long routeCost_var)
virtual IPAddress & getForwardingAddress ()
virtual const IPAddress & getForwardingAddress () const
virtual void setForwardingAddress (const IPAddress &forwardingAddress_var)
virtual long getExternalRouteTag () const
virtual void setExternalRouteTag (long externalRouteTag_var)
virtual void setExternalTOSInfoArraySize (unsigned int size)
virtual unsigned int getExternalTOSInfoArraySize () const
virtual ExternalTOSInfo & getExternalTOSInfo (unsigned int k)
virtual const ExternalTOSInfo & getExternalTOSInfo (unsigned int k) const
virtual void setExternalTOSInfo (unsigned int k, const ExternalTOSInfo &externalTOSInfo_var)
Protected Member Functions
bool operator== (const OSPFASExternalLSAContents &)
Protected Attributes
::IPAddress networkMask_var
bool E_ExternalMetricType_var
unsigned long routeCost_var
::IPAddress forwardingAddress_var
long externalRouteTag_var
::ExternalTOSInfo * externalTOSInfo_var
unsigned int externalTOSInfo_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class OSPFASExternalLSAContents
 {
     IPAddress networkMask;
     bool E_ExternalMetricType = false;
     unsigned long routeCost = 1;
     IPAddress forwardingAddress;
     long externalRouteTag = 0;
     ExternalTOSInfo externalTOSInfo[];
 }
Definition at line 591 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFASExternalLSAContents::OSPFASExternalLSAContents ()
Referenced by dup().
OSPFASExternalLSAContents::OSPFASExternalLSAContents (const OSPFASExternalLSAContents & other)
virtual OSPFASExternalLSAContents::~OSPFASExternalLSAContents () [virtual]
Member Function Documentation
virtual OSPFASExternalLSAContents* OSPFASExternalLSAContents::dup () const [inline, virtual]
Definition at line 610 of file OSPFPacket_m.h.
{return new OSPFASExternalLSAContents(*this);}
virtual bool OSPFASExternalLSAContents::getE_ExternalMetricType () const [virtual]
Referenced by OSPF::ASExternalLSA::DiffersFrom(), OSPF::Router::InstallASExternalLSA(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual long OSPFASExternalLSAContents::getExternalRouteTag () const [virtual]
Referenced by OSPF::ASExternalLSA::DiffersFrom().
virtual const ExternalTOSInfo& OSPFASExternalLSAContents::getExternalTOSInfo (unsigned int k) const [inline, virtual]
Definition at line 630 of file OSPFPacket_m.h.
Referenced by getExternalTOSInfo().
{return const_cast<OSPFASExternalLSAContents*>(this)->getExternalTOSInfo(k);}
virtual ExternalTOSInfo& OSPFASExternalLSAContents::getExternalTOSInfo (unsigned int k) [virtual]
Referenced by OSPF::ASExternalLSA::DiffersFrom().
virtual unsigned int OSPFASExternalLSAContents::getExternalTOSInfoArraySize () const [virtual]
Referenced by CalculateLSASize(), and OSPF::ASExternalLSA::DiffersFrom().
virtual const IPAddress& OSPFASExternalLSAContents::getForwardingAddress () const [inline, virtual]
Definition at line 623 of file OSPFPacket_m.h.
Referenced by getForwardingAddress().
{return const_cast<OSPFASExternalLSAContents*>(this)->getForwardingAddress();}
virtual IPAddress& OSPFASExternalLSAContents::getForwardingAddress () [virtual]
Referenced by OSPF::ASExternalLSA::DiffersFrom(), OSPF::Router::InstallASExternalLSA(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual const IPAddress& OSPFASExternalLSAContents::getNetworkMask () const [inline, virtual]
Definition at line 616 of file OSPFPacket_m.h.
Referenced by getNetworkMask().
{return const_cast<OSPFASExternalLSAContents*>(this)->getNetworkMask();}
virtual IPAddress& OSPFASExternalLSAContents::getNetworkMask () [virtual]
Referenced by OSPF::ASExternalLSA::DiffersFrom(), OSPF::Router::GetUniqueLinkStateID(), OSPF::Router::IsDestinationUnreachable(), OSPF::MessageHandler::PrintLinkStateUpdatePacket(), and OSPF::Router::UpdateExternalRoute().
virtual unsigned long OSPFASExternalLSAContents::getRouteCost () const [virtual]
Referenced by OSPF::ASExternalLSA::DiffersFrom(), OSPF::Router::InstallASExternalLSA(), OSPF::MessageHandler::PrintLinkStateUpdatePacket(), and OSPF::Router::UpdateExternalRoute().
OSPFASExternalLSAContents& OSPFASExternalLSAContents::operator= (const OSPFASExternalLSAContents & other)
bool OSPFASExternalLSAContents::operator== (const OSPFASExternalLSAContents &) [protected]
virtual void OSPFASExternalLSAContents::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void OSPFASExternalLSAContents::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void OSPFASExternalLSAContents::setE_ExternalMetricType (bool E_ExternalMetricType_var) [virtual]
Referenced by OSPF::Router::GetUniqueLinkStateID(), and OSPFRouting::LoadExternalRoute().
virtual void OSPFASExternalLSAContents::setExternalRouteTag (long externalRouteTag_var) [virtual]
Referenced by OSPFRouting::LoadExternalRoute().
virtual void OSPFASExternalLSAContents::setExternalTOSInfo (unsigned int k, const ExternalTOSInfo & externalTOSInfo_var) [virtual]
virtual void OSPFASExternalLSAContents::setExternalTOSInfoArraySize (unsigned int size) [virtual]
virtual void OSPFASExternalLSAContents::setForwardingAddress (const IPAddress & forwardingAddress_var) [virtual]
Referenced by OSPFRouting::LoadExternalRoute().
virtual void OSPFASExternalLSAContents::setNetworkMask (const IPAddress & networkMask_var) [virtual]
Referenced by OSPF::Router::GetUniqueLinkStateID(), and OSPFRouting::LoadExternalRoute().
virtual void OSPFASExternalLSAContents::setRouteCost (unsigned long routeCost_var) [virtual]
Referenced by OSPF::Router::GetUniqueLinkStateID(), and OSPFRouting::LoadExternalRoute().
Member Data Documentation
bool OSPFASExternalLSAContents::E_ExternalMetricType_var [protected]
Definition at line 595 of file OSPFPacket_m.h.
long OSPFASExternalLSAContents::externalRouteTag_var [protected]
Definition at line 598 of file OSPFPacket_m.h.
unsigned int OSPFASExternalLSAContents::externalTOSInfo_arraysize [protected]
Definition at line 600 of file OSPFPacket_m.h.
::ExternalTOSInfo* OSPFASExternalLSAContents::externalTOSInfo_var [protected]
Definition at line 599 of file OSPFPacket_m.h.
::IPAddress OSPFASExternalLSAContents::forwardingAddress_var [protected]
Definition at line 597 of file OSPFPacket_m.h.
::IPAddress OSPFASExternalLSAContents::networkMask_var [protected]
Definition at line 594 of file OSPFPacket_m.h.
unsigned long OSPFASExternalLSAContents::routeCost_var [protected]
Definition at line 596 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h