INET Framework for OMNeT++/OMNEST: EtherAutoconfig Class Reference
EtherAutoconfig Class Reference
#include <EtherFrame_m.h>
Public Member Functions
EtherAutoconfig (const char *name=NULL, int kind=0)
EtherAutoconfig (const EtherAutoconfig &other)
virtual ~EtherAutoconfig ()
EtherAutoconfig & operator= (const EtherAutoconfig &other)
virtual EtherAutoconfig * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual double getTxrate () const
virtual void setTxrate (double txrate_var)
virtual bool getHalfDuplex () const
virtual void setHalfDuplex (bool halfDuplex_var)
Protected Member Functions
bool operator== (const EtherAutoconfig &)
Protected Attributes
double txrate_var
bool halfDuplex_var
Detailed Description
Class generated from linklayer/ethernet/EtherFrame.msg by opp_msgc.
 packet EtherAutoconfig
 {
     double txrate = 0;
     bool halfDuplex = false;
 }
Definition at line 254 of file EtherFrame_m.h.
Constructor & Destructor Documentation
EtherAutoconfig::EtherAutoconfig (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherAutoconfig::EtherAutoconfig (const EtherAutoconfig & other)
virtual EtherAutoconfig::~EtherAutoconfig () [virtual]
Member Function Documentation
virtual EtherAutoconfig* EtherAutoconfig::dup () const [inline, virtual]
Definition at line 268 of file EtherFrame_m.h.
{return new EtherAutoconfig(*this);}
virtual bool EtherAutoconfig::getHalfDuplex () const [virtual]
Referenced by EtherMAC::handleAutoconfigMessage().
virtual double EtherAutoconfig::getTxrate () const [virtual]
Referenced by EtherMAC::handleAutoconfigMessage().
EtherAutoconfig& EtherAutoconfig::operator= (const EtherAutoconfig & other)
bool EtherAutoconfig::operator== (const EtherAutoconfig &) [protected]
virtual void EtherAutoconfig::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void EtherAutoconfig::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void EtherAutoconfig::setHalfDuplex (bool halfDuplex_var) [virtual]
Referenced by EtherHub::initialize(), EtherBus::initialize(), and EtherMAC::startAutoconfig().
virtual void EtherAutoconfig::setTxrate (double txrate_var) [virtual]
Referenced by EtherBus::initialize(), and EtherMAC::startAutoconfig().
Member Data Documentation
bool EtherAutoconfig::halfDuplex_var [protected]
Definition at line 258 of file EtherFrame_m.h.
double EtherAutoconfig::txrate_var [protected]
Definition at line 257 of file EtherFrame_m.h.
The documentation for this class was generated from the following file:
EtherFrame_m.h