INET Framework for OMNeT++/OMNEST: IPv6EncapsulatingSecurityPayloadHeader Class Reference
IPv6EncapsulatingSecurityPayloadHeader Class Reference
#include <IPv6ExtensionHeaders_m.h>
Public Member Functions
IPv6EncapsulatingSecurityPayloadHeader ()
IPv6EncapsulatingSecurityPayloadHeader (const IPv6EncapsulatingSecurityPayloadHeader &other)
virtual ~IPv6EncapsulatingSecurityPayloadHeader ()
IPv6EncapsulatingSecurityPayloadHeader & operator= (const IPv6EncapsulatingSecurityPayloadHeader &other)
virtual
IPv6EncapsulatingSecurityPayloadHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const IPv6EncapsulatingSecurityPayloadHeader &)
Detailed Description
Class generated from networklayer/ipv6/IPv6ExtensionHeaders.msg by opp_msgc.
 class IPv6EncapsulatingSecurityPayloadHeader extends IPv6ExtensionHeader
 {
 }
Definition at line 210 of file IPv6ExtensionHeaders_m.h.
Constructor & Destructor Documentation
IPv6EncapsulatingSecurityPayloadHeader::IPv6EncapsulatingSecurityPayloadHeader ()
Referenced by dup().
IPv6EncapsulatingSecurityPayloadHeader::IPv6EncapsulatingSecurityPayloadHeader (const IPv6EncapsulatingSecurityPayloadHeader & other)
virtual IPv6EncapsulatingSecurityPayloadHeader::~IPv6EncapsulatingSecurityPayloadHeader () [virtual]
Member Function Documentation
virtual IPv6EncapsulatingSecurityPayloadHeader* IPv6EncapsulatingSecurityPayloadHeader::dup () const [inline, virtual]
Reimplemented from IPv6ExtensionHeader.
Definition at line 222 of file IPv6ExtensionHeaders_m.h.
{return new IPv6EncapsulatingSecurityPayloadHeader(*this);}
IPv6EncapsulatingSecurityPayloadHeader& IPv6EncapsulatingSecurityPayloadHeader::operator= (const IPv6EncapsulatingSecurityPayloadHeader & other)
Reimplemented from IPv6ExtensionHeader.
bool IPv6EncapsulatingSecurityPayloadHeader::operator== (const IPv6EncapsulatingSecurityPayloadHeader &) [protected]
Reimplemented from IPv6ExtensionHeader_Base.
virtual void IPv6EncapsulatingSecurityPayloadHeader::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doPacking().
virtual void IPv6EncapsulatingSecurityPayloadHeader::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
IPv6ExtensionHeaders_m.h