INET Framework for OMNeT++/OMNEST: SCTPShutdownCompleteChunk Class Reference
SCTPShutdownCompleteChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPShutdownCompleteChunk (const char *name=NULL, int kind=0)
SCTPShutdownCompleteChunk (const SCTPShutdownCompleteChunk &other)
virtual ~SCTPShutdownCompleteChunk ()
SCTPShutdownCompleteChunk & operator= (const SCTPShutdownCompleteChunk &other)
virtual SCTPShutdownCompleteChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getTBit () const
virtual void setTBit (bool TBit_var)
Protected Member Functions
bool operator== (const SCTPShutdownCompleteChunk &)
Protected Attributes
bool TBit_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPShutdownCompleteChunk extends SCTPChunk
 {
      bool TBit = 0;
 }
Definition at line 955 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPShutdownCompleteChunk::SCTPShutdownCompleteChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPShutdownCompleteChunk::SCTPShutdownCompleteChunk (const SCTPShutdownCompleteChunk & other)
virtual SCTPShutdownCompleteChunk::~SCTPShutdownCompleteChunk () [virtual]
Member Function Documentation
virtual SCTPShutdownCompleteChunk* SCTPShutdownCompleteChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 968 of file SCTPMessage_m.h.
{return new SCTPShutdownCompleteChunk(*this);}
virtual bool SCTPShutdownCompleteChunk::getTBit () const [virtual]
SCTPShutdownCompleteChunk& SCTPShutdownCompleteChunk::operator= (const SCTPShutdownCompleteChunk & other)
Reimplemented from SCTPChunk.
bool SCTPShutdownCompleteChunk::operator== (const SCTPShutdownCompleteChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPShutdownCompleteChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPShutdownCompleteChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPShutdownCompleteChunk::setTBit (bool TBit_var) [virtual]
Referenced by SCTPAssociation::sendShutdownComplete(), and SCTP::sendShutdownCompleteFromMain().
Member Data Documentation
bool SCTPShutdownCompleteChunk::TBit_var [protected]
Definition at line 958 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h