INET Framework for OMNeT++/OMNEST: ICMPv6ParamProblemMsg Class Reference
ICMPv6ParamProblemMsg Class Reference
#include <ICMPv6Message_m.h>
Public Member Functions
ICMPv6ParamProblemMsg (const char *name=NULL, int kind=0)
ICMPv6ParamProblemMsg (const ICMPv6ParamProblemMsg &other)
virtual ~ICMPv6ParamProblemMsg ()
ICMPv6ParamProblemMsg & operator= (const ICMPv6ParamProblemMsg &other)
virtual ICMPv6ParamProblemMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCode () const
virtual void setCode (int code_var)
Protected Member Functions
bool operator== (const ICMPv6ParamProblemMsg &)
Protected Attributes
int code_var
Detailed Description
Class generated from networklayer/icmpv6/ICMPv6Message.msg by opp_msgc.
 packet ICMPv6ParamProblemMsg extends ICMPv6Message
 {
     int code enum(ICMPv6_PARAMETER_PROB);
 }
Definition at line 273 of file ICMPv6Message_m.h.
Constructor & Destructor Documentation
ICMPv6ParamProblemMsg::ICMPv6ParamProblemMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPv6ParamProblemMsg::ICMPv6ParamProblemMsg (const ICMPv6ParamProblemMsg & other)
virtual ICMPv6ParamProblemMsg::~ICMPv6ParamProblemMsg () [virtual]
Member Function Documentation
virtual ICMPv6ParamProblemMsg* ICMPv6ParamProblemMsg::dup () const [inline, virtual]
Reimplemented from ICMPv6Message.
Definition at line 286 of file ICMPv6Message_m.h.
{return new ICMPv6ParamProblemMsg(*this);}
virtual int ICMPv6ParamProblemMsg::getCode () const [virtual]
Referenced by IPv6ErrorHandling::handleMessage().
ICMPv6ParamProblemMsg& ICMPv6ParamProblemMsg::operator= (const ICMPv6ParamProblemMsg & other)
Reimplemented from ICMPv6Message.
bool ICMPv6ParamProblemMsg::operator== (const ICMPv6ParamProblemMsg &) [protected]
Reimplemented from ICMPv6Message.
virtual void ICMPv6ParamProblemMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doPacking().
virtual void ICMPv6ParamProblemMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doUnpacking().
virtual void ICMPv6ParamProblemMsg::setCode (int code_var) [virtual]
Referenced by ICMPv6::createParamProblemMsg().
Member Data Documentation
int ICMPv6ParamProblemMsg::code_var [protected]
Definition at line 276 of file ICMPv6Message_m.h.
The documentation for this class was generated from the following file:
ICMPv6Message_m.h