INET Framework for OMNeT++/OMNEST: SCTPRcvCommand Class Reference
SCTPRcvCommand Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPRcvCommand (const char *name=NULL)
SCTPRcvCommand (const SCTPRcvCommand &other)
virtual ~SCTPRcvCommand ()
SCTPRcvCommand & operator= (const SCTPRcvCommand &other)
virtual SCTPRcvCommand * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32 getPpid () const
virtual void setPpid (uint32 ppid_var)
virtual uint32 getTsn () const
virtual void setTsn (uint32 tsn_var)
virtual uint32 getCumTsn () const
virtual void setCumTsn (uint32 cumTsn_var)
Protected Member Functions
bool operator== (const SCTPRcvCommand &)
Protected Attributes
uint32 ppid_var
uint32 tsn_var
uint32 cumTsn_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPRcvCommand extends SCTPCommand
 {
     uint32 ppid;
     uint32 tsn;
     uint32 cumTsn;
 }
Definition at line 497 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPRcvCommand::SCTPRcvCommand (const char * name = NULL)
Referenced by dup().
SCTPRcvCommand::SCTPRcvCommand (const SCTPRcvCommand & other)
virtual SCTPRcvCommand::~SCTPRcvCommand () [virtual]
Member Function Documentation
virtual SCTPRcvCommand* SCTPRcvCommand::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 512 of file SCTPCommand_m.h.
{return new SCTPRcvCommand(*this);}
virtual uint32 SCTPRcvCommand::getCumTsn () const [virtual]
virtual uint32 SCTPRcvCommand::getPpid () const [virtual]
virtual uint32 SCTPRcvCommand::getTsn () const [virtual]
SCTPRcvCommand& SCTPRcvCommand::operator= (const SCTPRcvCommand & other)
Reimplemented from SCTPCommand.
bool SCTPRcvCommand::operator== (const SCTPRcvCommand &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPRcvCommand::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPRcvCommand::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPRcvCommand::setCumTsn (uint32 cumTsn_var) [virtual]
Referenced by SCTPAssociation::pushUlp().
virtual void SCTPRcvCommand::setPpid (uint32 ppid_var) [virtual]
Referenced by SCTPAssociation::pushUlp().
virtual void SCTPRcvCommand::setTsn (uint32 tsn_var) [virtual]
Referenced by SCTPAssociation::pushUlp().
Member Data Documentation
uint32 SCTPRcvCommand::cumTsn_var [protected]
Definition at line 502 of file SCTPCommand_m.h.
uint32 SCTPRcvCommand::ppid_var [protected]
Definition at line 500 of file SCTPCommand_m.h.
uint32 SCTPRcvCommand::tsn_var [protected]
Definition at line 501 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h