INET Framework for OMNeT++/OMNEST: SnrControlInfo Class Reference
SnrControlInfo Class Reference
#include <SnrControlInfo_m.h>
Public Member Functions
SnrControlInfo ()
SnrControlInfo (const SnrControlInfo &other)
virtual ~SnrControlInfo ()
SnrControlInfo & operator= (const SnrControlInfo &other)
virtual SnrControlInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual SnrList & getSnrList ()
virtual const SnrList & getSnrList () const
virtual void setSnrList (const SnrList &snrList_var)
Protected Member Functions
bool operator== (const SnrControlInfo &)
Protected Attributes
::SnrList snrList_var
Detailed Description
Class generated from linklayer/mfcore/SnrControlInfo.msg by opp_msgc.
 class SnrControlInfo
 {
     SnrList snrList;
 }
Definition at line 33 of file SnrControlInfo_m.h.
Constructor & Destructor Documentation
SnrControlInfo::SnrControlInfo ()
Referenced by dup().
SnrControlInfo::SnrControlInfo (const SnrControlInfo & other)
virtual SnrControlInfo::~SnrControlInfo () [virtual]
Member Function Documentation
virtual SnrControlInfo* SnrControlInfo::dup () const [inline, virtual]
Definition at line 46 of file SnrControlInfo_m.h.
{return new SnrControlInfo(*this);}
virtual const SnrList& SnrControlInfo::getSnrList () const [inline, virtual]
Definition at line 52 of file SnrControlInfo_m.h.
Referenced by getSnrList().
{return const_cast<SnrControlInfo*>(this)->getSnrList();}
virtual SnrList& SnrControlInfo::getSnrList () [virtual]
Referenced by BasicDecider::handleMessage().
SnrControlInfo& SnrControlInfo::operator= (const SnrControlInfo & other)
bool SnrControlInfo::operator== (const SnrControlInfo &) [protected]
virtual void SnrControlInfo::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SnrControlInfo::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SnrControlInfo::setSnrList (const SnrList & snrList_var) [virtual]
Referenced by BasicSnrEval::sendUp().
Member Data Documentation
::SnrList SnrControlInfo::snrList_var [protected]
Definition at line 36 of file SnrControlInfo_m.h.
The documentation for this class was generated from the following file:
SnrControlInfo_m.h