INET Framework for OMNeT++/OMNEST: SCTPPathInfo Class Reference
SCTPPathInfo Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPPathInfo (const char *name=NULL)
SCTPPathInfo (const SCTPPathInfo &other)
virtual ~SCTPPathInfo ()
SCTPPathInfo & operator= (const SCTPPathInfo &other)
virtual SCTPPathInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPvXAddress & getRemoteAddress ()
virtual const IPvXAddress & getRemoteAddress () const
virtual void setRemoteAddress (const IPvXAddress &remoteAddress_var)
Protected Member Functions
bool operator== (const SCTPPathInfo &)
Protected Attributes
::IPvXAddress remoteAddress_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPPathInfo extends SCTPCommand
 {
     IPvXAddress remoteAddress;
 }
Definition at line 380 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPPathInfo::SCTPPathInfo (const char * name = NULL)
Referenced by dup().
SCTPPathInfo::SCTPPathInfo (const SCTPPathInfo & other)
virtual SCTPPathInfo::~SCTPPathInfo () [virtual]
Member Function Documentation
virtual SCTPPathInfo* SCTPPathInfo::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 393 of file SCTPCommand_m.h.
Referenced by SCTPAssociation::SCTPAssociation(), and SCTPPathVariables::SCTPPathVariables().
{return new SCTPPathInfo(*this);}
virtual const IPvXAddress& SCTPPathInfo::getRemoteAddress () const [inline, virtual]
Definition at line 399 of file SCTPCommand_m.h.
Referenced by getRemoteAddress().
{return const_cast<SCTPPathInfo*>(this)->getRemoteAddress();}
virtual IPvXAddress& SCTPPathInfo::getRemoteAddress () [virtual]
Referenced by SCTPAssociation::process_PRIMARY(), and SCTPAssociation::processTimer().
SCTPPathInfo& SCTPPathInfo::operator= (const SCTPPathInfo & other)
Reimplemented from SCTPCommand.
bool SCTPPathInfo::operator== (const SCTPPathInfo &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPPathInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPPathInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPPathInfo::setRemoteAddress (const IPvXAddress & remoteAddress_var) [virtual]
Referenced by SCTPAssociation::SCTPAssociation(), SCTPPathVariables::SCTPPathVariables(), and SCTPClient::setPrimaryPath().
Member Data Documentation
::IPvXAddress SCTPPathInfo::remoteAddress_var [protected]
Definition at line 383 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h