INET Framework for OMNeT++/OMNEST: IPRecordRouteOption Class Reference
IPRecordRouteOption Class Reference
#include <IPDatagram_m.h>
Public Member Functions
IPRecordRouteOption ()
IPRecordRouteOption (const IPRecordRouteOption &other)
virtual ~IPRecordRouteOption ()
IPRecordRouteOption & operator= (const IPRecordRouteOption &other)
virtual IPRecordRouteOption * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getRecordAddressArraySize () const
virtual IPAddress & getRecordAddress (unsigned int k)
virtual const IPAddress & getRecordAddress (unsigned int k) const
virtual void setRecordAddress (unsigned int k, const IPAddress &recordAddress_var)
virtual short getNextAddressPtr () const
virtual void setNextAddressPtr (short nextAddressPtr_var)
Protected Member Functions
bool operator== (const IPRecordRouteOption &)
Protected Attributes
::IPAddress recordAddress_var [MAX_IPADDR_OPTION_ENTRIES]
short nextAddressPtr_var
Detailed Description
Class generated from networklayer/ipv4/IPDatagram.msg by opp_msgc.
 class IPRecordRouteOption
 {
     IPAddress recordAddress[MAX_IPADDR_OPTION_ENTRIES];
     short nextAddressPtr;
 }
Definition at line 109 of file IPDatagram_m.h.
Constructor & Destructor Documentation
IPRecordRouteOption::IPRecordRouteOption ()
Referenced by dup().
IPRecordRouteOption::IPRecordRouteOption (const IPRecordRouteOption & other)
virtual IPRecordRouteOption::~IPRecordRouteOption () [virtual]
Member Function Documentation
virtual IPRecordRouteOption* IPRecordRouteOption::dup () const [inline, virtual]
Definition at line 123 of file IPDatagram_m.h.
{return new IPRecordRouteOption(*this);}
virtual short IPRecordRouteOption::getNextAddressPtr () const [virtual]
virtual const IPAddress& IPRecordRouteOption::getRecordAddress (unsigned int k) const [inline, virtual]
Definition at line 130 of file IPDatagram_m.h.
Referenced by getRecordAddress().
{return const_cast<IPRecordRouteOption*>(this)->getRecordAddress(k);}
virtual IPAddress& IPRecordRouteOption::getRecordAddress (unsigned int k) [virtual]
virtual unsigned int IPRecordRouteOption::getRecordAddressArraySize () const [virtual]
IPRecordRouteOption& IPRecordRouteOption::operator= (const IPRecordRouteOption & other)
bool IPRecordRouteOption::operator== (const IPRecordRouteOption &) [protected]
virtual void IPRecordRouteOption::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void IPRecordRouteOption::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void IPRecordRouteOption::setNextAddressPtr (short nextAddressPtr_var) [virtual]
virtual void IPRecordRouteOption::setRecordAddress (unsigned int k, const IPAddress & recordAddress_var) [virtual]
Member Data Documentation
short IPRecordRouteOption::nextAddressPtr_var [protected]
Definition at line 113 of file IPDatagram_m.h.
::IPAddress IPRecordRouteOption::recordAddress_var[MAX_IPADDR_OPTION_ENTRIES] [protected]
Definition at line 112 of file IPDatagram_m.h.
The documentation for this class was generated from the following file:
IPDatagram_m.h