INET Framework for OMNeT++/OMNEST: OSPFNetworkLSA Class Reference
OSPFNetworkLSA Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFNetworkLSA ()
OSPFNetworkLSA (const OSPFNetworkLSA &other)
virtual ~OSPFNetworkLSA ()
OSPFNetworkLSA & operator= (const OSPFNetworkLSA &other)
virtual OSPFNetworkLSA * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getNetworkMask ()
virtual const IPAddress & getNetworkMask () const
virtual void setNetworkMask (const IPAddress &networkMask_var)
virtual void setAttachedRoutersArraySize (unsigned int size)
virtual unsigned int getAttachedRoutersArraySize () const
virtual IPAddress & getAttachedRouters (unsigned int k)
virtual const IPAddress & getAttachedRouters (unsigned int k) const
virtual void setAttachedRouters (unsigned int k, const IPAddress &attachedRouters_var)
Protected Member Functions
bool operator== (const OSPFNetworkLSA &)
Protected Attributes
::IPAddress networkMask_var
::IPAddress * attachedRouters_var
unsigned int attachedRouters_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class OSPFNetworkLSA extends OSPFLSA
 {
     IPAddress networkMask;
     IPAddress attachedRouters[];
 }
Definition at line 482 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFNetworkLSA::OSPFNetworkLSA ()
Referenced by dup().
OSPFNetworkLSA::OSPFNetworkLSA (const OSPFNetworkLSA & other)
virtual OSPFNetworkLSA::~OSPFNetworkLSA () [virtual]
Member Function Documentation
virtual OSPFNetworkLSA* OSPFNetworkLSA::dup () const [inline, virtual]
Reimplemented from OSPFLSA.
Definition at line 497 of file OSPFPacket_m.h.
{return new OSPFNetworkLSA(*this);}
virtual const IPAddress& OSPFNetworkLSA::getAttachedRouters (unsigned int k) const [inline, virtual]
Definition at line 508 of file OSPFPacket_m.h.
Referenced by getAttachedRouters().
{return const_cast<OSPFNetworkLSA*>(this)->getAttachedRouters(k);}
virtual IPAddress& OSPFNetworkLSA::getAttachedRouters (unsigned int k) [virtual]
Referenced by OSPF::NetworkLSA::DiffersFrom(), OSPF::Area::HasLink(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual unsigned int OSPFNetworkLSA::getAttachedRoutersArraySize () const [virtual]
Referenced by CalculateLSASize(), OSPF::NetworkLSA::DiffersFrom(), OSPF::Area::HasLink(), OSPF::Area::OriginateNetworkLSA(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual const IPAddress& OSPFNetworkLSA::getNetworkMask () const [inline, virtual]
Definition at line 503 of file OSPFPacket_m.h.
Referenced by getNetworkMask().
{return const_cast<OSPFNetworkLSA*>(this)->getNetworkMask();}
virtual IPAddress& OSPFNetworkLSA::getNetworkMask () [virtual]
Referenced by OSPF::Area::CalculateNextHops(), OSPF::NetworkLSA::DiffersFrom(), OSPF::Area::HasLink(), OSPF::Router::IsDestinationUnreachable(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
OSPFNetworkLSA& OSPFNetworkLSA::operator= (const OSPFNetworkLSA & other)
Reimplemented from OSPFLSA.
bool OSPFNetworkLSA::operator== (const OSPFNetworkLSA &) [protected]
Reimplemented from OSPFLSA.
virtual void OSPFNetworkLSA::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doPacking().
virtual void OSPFNetworkLSA::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doUnpacking().
virtual void OSPFNetworkLSA::setAttachedRouters (unsigned int k, const IPAddress & attachedRouters_var) [virtual]
Referenced by OSPF::Area::OriginateNetworkLSA().
virtual void OSPFNetworkLSA::setAttachedRoutersArraySize (unsigned int size) [virtual]
Referenced by OSPF::Area::OriginateNetworkLSA().
virtual void OSPFNetworkLSA::setNetworkMask (const IPAddress & networkMask_var) [virtual]
Referenced by OSPF::Area::OriginateNetworkLSA().
Member Data Documentation
unsigned int OSPFNetworkLSA::attachedRouters_arraysize [protected]
Definition at line 487 of file OSPFPacket_m.h.
Referenced by OSPF::NetworkLSA::DiffersFrom().
::IPAddress* OSPFNetworkLSA::attachedRouters_var [protected]
Definition at line 486 of file OSPFPacket_m.h.
Referenced by OSPF::NetworkLSA::DiffersFrom().
::IPAddress OSPFNetworkLSA::networkMask_var [protected]
Definition at line 485 of file OSPFPacket_m.h.
Referenced by OSPF::NetworkLSA::DiffersFrom().
The documentation for this class was generated from the following file:
OSPFPacket_m.h