INET Framework for OMNeT++/OMNEST: SCTPConnectInfo Class Reference
SCTPConnectInfo Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPConnectInfo (const char *name=NULL)
SCTPConnectInfo (const SCTPConnectInfo &other)
virtual ~SCTPConnectInfo ()
SCTPConnectInfo & operator= (const SCTPConnectInfo &other)
virtual SCTPConnectInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual AddressVector & getRemoteAddresses ()
virtual const AddressVector & getRemoteAddresses () const
virtual void setRemoteAddresses (const AddressVector &remoteAddresses_var)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort_var)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort_var)
virtual int getStatus () const
virtual void setStatus (int status_var)
virtual int getInboundStreams () const
virtual void setInboundStreams (int inboundStreams_var)
virtual int getOutboundStreams () const
virtual void setOutboundStreams (int outboundStreams_var)
Protected Member Functions
bool operator== (const SCTPConnectInfo &)
Protected Attributes
::AddressVector remoteAddresses_var
int localPort_var
int remotePort_var
int status_var
int inboundStreams_var
int outboundStreams_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPConnectInfo extends SCTPCommand
 {
     AddressVector remoteAddresses;
     int localPort;
     int remotePort;
     int status;
     int inboundStreams;
     int outboundStreams;
 }
Definition at line 283 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPConnectInfo::SCTPConnectInfo (const char * name = NULL)
Referenced by dup().
SCTPConnectInfo::SCTPConnectInfo (const SCTPConnectInfo & other)
virtual SCTPConnectInfo::~SCTPConnectInfo () [virtual]
Member Function Documentation
virtual SCTPConnectInfo* SCTPConnectInfo::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 301 of file SCTPCommand_m.h.
{return new SCTPConnectInfo(*this);}
virtual int SCTPConnectInfo::getInboundStreams () const [virtual]
Referenced by SCTPServer::handleMessage(), and SCTPSocket::processMessage().
virtual int SCTPConnectInfo::getLocalPort () const [virtual]
Referenced by SCTPSocket::processMessage().
virtual int SCTPConnectInfo::getOutboundStreams () const [virtual]
Referenced by SCTPServer::handleMessage(), SCTPPeer::handleMessage(), and SCTPSocket::processMessage().
virtual const AddressVector& SCTPConnectInfo::getRemoteAddresses () const [inline, virtual]
Definition at line 307 of file SCTPCommand_m.h.
Referenced by getRemoteAddresses().
{return const_cast<SCTPConnectInfo*>(this)->getRemoteAddresses();}
virtual AddressVector& SCTPConnectInfo::getRemoteAddresses () [virtual]
virtual int SCTPConnectInfo::getRemotePort () const [virtual]
Referenced by SCTPSocket::processMessage().
virtual int SCTPConnectInfo::getStatus () const [virtual]
Referenced by SCTPSocket::processMessage().
SCTPConnectInfo& SCTPConnectInfo::operator= (const SCTPConnectInfo & other)
Reimplemented from SCTPCommand.
bool SCTPConnectInfo::operator== (const SCTPConnectInfo &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPConnectInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPConnectInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPConnectInfo::setInboundStreams (int inboundStreams_var) [virtual]
Referenced by SCTPAssociation::sendEstabIndicationToApp().
virtual void SCTPConnectInfo::setLocalPort (int localPort_var) [virtual]
Referenced by SCTPAssociation::sendEstabIndicationToApp().
virtual void SCTPConnectInfo::setOutboundStreams (int outboundStreams_var) [virtual]
Referenced by SCTPAssociation::sendEstabIndicationToApp().
virtual void SCTPConnectInfo::setRemoteAddresses (const AddressVector & remoteAddresses_var) [virtual]
Referenced by SCTPAssociation::sendEstabIndicationToApp().
virtual void SCTPConnectInfo::setRemotePort (int remotePort_var) [virtual]
Referenced by SCTPAssociation::sendEstabIndicationToApp().
virtual void SCTPConnectInfo::setStatus (int status_var) [virtual]
Member Data Documentation
int SCTPConnectInfo::inboundStreams_var [protected]
Definition at line 290 of file SCTPCommand_m.h.
int SCTPConnectInfo::localPort_var [protected]
Definition at line 287 of file SCTPCommand_m.h.
int SCTPConnectInfo::outboundStreams_var [protected]
Definition at line 291 of file SCTPCommand_m.h.
::AddressVector SCTPConnectInfo::remoteAddresses_var [protected]
Definition at line 286 of file SCTPCommand_m.h.
int SCTPConnectInfo::remotePort_var [protected]
Definition at line 288 of file SCTPCommand_m.h.
int SCTPConnectInfo::status_var [protected]
Definition at line 289 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h