INET Framework for OMNeT++/OMNEST: IPv6ControlInfo_Base Class Reference
IPv6ControlInfo_Base Class Reference
#include <IPv6ControlInfo_m.h>
Public Member Functions
virtual ~IPv6ControlInfo_Base ()
virtual IPv6ControlInfo_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getProtocol () const
virtual void setProtocol (int protocol_var)
virtual IPv6Address & getDestAddr ()
virtual const IPv6Address & getDestAddr () const
virtual void setDestAddr (const IPv6Address &destAddr_var)
virtual IPv6Address & getSrcAddr ()
virtual const IPv6Address & getSrcAddr () const
virtual void setSrcAddr (const IPv6Address &srcAddr_var)
virtual short getHopLimit () const
virtual void setHopLimit (short hopLimit_var)
virtual int getInterfaceId () const
virtual void setInterfaceId (int interfaceId_var)
Protected Member Functions
bool operator== (const IPv6ControlInfo_Base &)
IPv6ControlInfo_Base ()
IPv6ControlInfo_Base (const IPv6ControlInfo_Base &other)
IPv6ControlInfo_Base & operator= (const IPv6ControlInfo_Base &other)
Protected Attributes
int protocol_var
::IPv6Address destAddr_var
::IPv6Address srcAddr_var
short hopLimit_var
int interfaceId_var
Detailed Description
Class generated from networklayer/contract/IPv6ControlInfo.msg by opp_msgc.
 class IPv6ControlInfo
 {
     (true);
     int protocol enum(IPProtocolId);
     IPv6Address destAddr;
     IPv6Address srcAddr;
     short hopLimit;
     int interfaceId = -1;
 }
IPv6ControlInfo_Base is only useful if it gets subclassed, and IPv6ControlInfo is derived from it. The minimum code to be written for IPv6ControlInfo is the following:
 class IPv6ControlInfo : public IPv6ControlInfo_Base
 {
   public:
     IPv6ControlInfo() : IPv6ControlInfo_Base() {}
     IPv6ControlInfo(const IPv6ControlInfo& other) : IPv6ControlInfo_Base() {operator=(other);}
     IPv6ControlInfo& operator=(const IPv6ControlInfo& other) {IPv6ControlInfo_Base::operator=(other); return *this;}
     virtual IPv6ControlInfo *dup() const {return new IPv6ControlInfo(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from IPv6ControlInfo_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(IPv6ControlInfo);
Definition at line 60 of file IPv6ControlInfo_m.h.
Constructor & Destructor Documentation
IPv6ControlInfo_Base::IPv6ControlInfo_Base () [protected]
IPv6ControlInfo_Base::IPv6ControlInfo_Base (const IPv6ControlInfo_Base & other) [protected]
virtual IPv6ControlInfo_Base::~IPv6ControlInfo_Base () [virtual]
Member Function Documentation
virtual IPv6ControlInfo_Base* IPv6ControlInfo_Base::dup () const [inline, virtual]
Definition at line 79 of file IPv6ControlInfo_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class IPv6ControlInfo");}
virtual const IPv6Address& IPv6ControlInfo_Base::getDestAddr () const [inline, virtual]
Definition at line 87 of file IPv6ControlInfo_m.h.
Referenced by getDestAddr().
{return const_cast<IPv6ControlInfo_Base*>(this)->getDestAddr();}
virtual IPv6Address& IPv6ControlInfo_Base::getDestAddr () [virtual]
Referenced by IPv6::encapsulate(), tcp_old::TCP::handleMessage(), TCP::handleMessage(), SCTP::handleMessage(), UDP::matchesSocket(), IPTrafSink::printPacket(), ICMPv6::processEchoRequest(), IPv6NeighbourDiscovery::processNSForTentativeAddress(), PingApp::processPingResponse(), UDP::processUndeliverablePacket(), UDP::sendUp(), IPv6NeighbourDiscovery::validateNAPacket(), and IPv6NeighbourDiscovery::validateNSPacket().
virtual short IPv6ControlInfo_Base::getHopLimit () const [virtual]
Referenced by IPv6::encapsulate(), PingApp::processPingResponse(), IPv6NeighbourDiscovery::validateNAPacket(), IPv6NeighbourDiscovery::validateNSPacket(), IPv6NeighbourDiscovery::validateRAPacket(), and IPv6NeighbourDiscovery::validateRSPacket().
virtual int IPv6ControlInfo_Base::getInterfaceId () const [virtual]
Referenced by IPv6::encapsulate(), UDP::matchesSocket(), IPv6NeighbourDiscovery::processNAPacket(), IPv6NeighbourDiscovery::processNSPacket(), IPv6NeighbourDiscovery::processRAForRouterUpdates(), IPv6NeighbourDiscovery::processRAPacket(), IPv6NeighbourDiscovery::processRSPacket(), and UDP::sendUp().
virtual int IPv6ControlInfo_Base::getProtocol () const [virtual]
Referenced by IPv6::encapsulate(), IPTrafSink::printPacket(), IPv6NeighbourDiscovery::validateRAPacket(), and IPv6NeighbourDiscovery::validateRSPacket().
virtual const IPv6Address& IPv6ControlInfo_Base::getSrcAddr () const [inline, virtual]
Definition at line 90 of file IPv6ControlInfo_m.h.
Referenced by getSrcAddr().
{return const_cast<IPv6ControlInfo_Base*>(this)->getSrcAddr();}
virtual IPv6Address& IPv6ControlInfo_Base::getSrcAddr () [virtual]
Referenced by IPv6::encapsulate(), tcp_old::TCP::handleMessage(), TCP::handleMessage(), SCTP::handleMessage(), UDP::matchesSocket(), IPTrafSink::printPacket(), ICMPv6::processEchoRequest(), IPv6NeighbourDiscovery::processNSForNonTentativeAddress(), IPv6NeighbourDiscovery::processNSForTentativeAddress(), IPv6NeighbourDiscovery::processNSWithSpecifiedSrcAddr(), PingApp::processPingResponse(), IPv6NeighbourDiscovery::processRAForRouterUpdates(), IPv6NeighbourDiscovery::sendSolicitedNA(), UDP::sendUp(), IPv6NeighbourDiscovery::validateNSPacket(), IPv6NeighbourDiscovery::validateRAPacket(), and IPv6NeighbourDiscovery::validateRSPacket().
IPv6ControlInfo_Base& IPv6ControlInfo_Base::operator= (const IPv6ControlInfo_Base & other) [protected]
Reimplemented in IPv6ControlInfo.
Referenced by IPv6ControlInfo::IPv6ControlInfo(), and IPv6ControlInfo::operator=().
bool IPv6ControlInfo_Base::operator== (const IPv6ControlInfo_Base &) [protected]
virtual void IPv6ControlInfo_Base::parsimPack (cCommBuffer * b) [virtual]
virtual void IPv6ControlInfo_Base::parsimUnpack (cCommBuffer * b) [virtual]
virtual void IPv6ControlInfo_Base::setDestAddr (const IPv6Address & destAddr_var) [virtual]
Referenced by IPv6::decapsulate(), UDP::processMsgFromApp(), IPTrafGen::sendPacket(), IPv6NeighbourDiscovery::sendPacketToIPv6Module(), PingApp::sendToICMP(), TCPSpoof::sendToIP(), tcp_old::TCPConnection::sendToIP(), TCPConnection::sendToIP(), SCTPAssociation::sendToIP(), and ICMPv6::sendToIP().
virtual void IPv6ControlInfo_Base::setHopLimit (short hopLimit_var) [virtual]
Referenced by IPv6::decapsulate(), IPv6NeighbourDiscovery::sendPacketToIPv6Module(), and PingApp::sendToICMP().
virtual void IPv6ControlInfo_Base::setInterfaceId (int interfaceId_var) [virtual]
Referenced by IPv6::decapsulate(), and IPv6NeighbourDiscovery::sendPacketToIPv6Module().
virtual void IPv6ControlInfo_Base::setProtocol (int protocol_var) [virtual]
Referenced by IPv6::decapsulate(), UDP::processMsgFromApp(), ICMPv6::sendEchoRequest(), ICMPv6::sendErrorMessage(), IPTrafGen::sendPacket(), IPv6NeighbourDiscovery::sendPacketToIPv6Module(), TCPSpoof::sendToIP(), tcp_old::TCPConnection::sendToIP(), TCPConnection::sendToIP(), SCTPAssociation::sendToIP(), and ICMPv6::sendToIP().
virtual void IPv6ControlInfo_Base::setSrcAddr (const IPv6Address & srcAddr_var) [virtual]
Referenced by IPv6::decapsulate(), UDP::processMsgFromApp(), ICMPv6::sendErrorMessage(), IPv6NeighbourDiscovery::sendPacketToIPv6Module(), PingApp::sendToICMP(), TCPSpoof::sendToIP(), tcp_old::TCPConnection::sendToIP(), TCPConnection::sendToIP(), and SCTPAssociation::sendToIP().
Member Data Documentation
::IPv6Address IPv6ControlInfo_Base::destAddr_var [protected]
Definition at line 64 of file IPv6ControlInfo_m.h.
short IPv6ControlInfo_Base::hopLimit_var [protected]
Definition at line 66 of file IPv6ControlInfo_m.h.
int IPv6ControlInfo_Base::interfaceId_var [protected]
Definition at line 67 of file IPv6ControlInfo_m.h.
int IPv6ControlInfo_Base::protocol_var [protected]
Definition at line 63 of file IPv6ControlInfo_m.h.
::IPv6Address IPv6ControlInfo_Base::srcAddr_var [protected]
Definition at line 65 of file IPv6ControlInfo_m.h.
The documentation for this class was generated from the following file:
IPv6ControlInfo_m.h