INET Framework for OMNeT++/OMNEST: Ieee80211DeauthenticationFrameBody Class Reference
Ieee80211DeauthenticationFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211DeauthenticationFrameBody ()
Ieee80211DeauthenticationFrameBody (const Ieee80211DeauthenticationFrameBody &other)
virtual ~Ieee80211DeauthenticationFrameBody ()
Ieee80211DeauthenticationFrameBody & operator= (const Ieee80211DeauthenticationFrameBody &other)
virtual
Ieee80211DeauthenticationFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getReasonCode () const
virtual void setReasonCode (int reasonCode_var)
Protected Member Functions
bool operator== (const Ieee80211DeauthenticationFrameBody &)
Protected Attributes
int reasonCode_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211DeauthenticationFrameBody extends Ieee80211FrameBody
 {
     bodyLength = 2;
     int reasonCode enum(Ieee80211ReasonCode);
 }
Definition at line 219 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211DeauthenticationFrameBody::Ieee80211DeauthenticationFrameBody ()
Referenced by dup().
Ieee80211DeauthenticationFrameBody::Ieee80211DeauthenticationFrameBody (const Ieee80211DeauthenticationFrameBody & other)
virtual Ieee80211DeauthenticationFrameBody::~Ieee80211DeauthenticationFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211DeauthenticationFrameBody* Ieee80211DeauthenticationFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211FrameBody.
Definition at line 232 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211DeauthenticationFrameBody(*this);}
virtual int Ieee80211DeauthenticationFrameBody::getReasonCode () const [virtual]
Ieee80211DeauthenticationFrameBody& Ieee80211DeauthenticationFrameBody::operator= (const Ieee80211DeauthenticationFrameBody & other)
Reimplemented from Ieee80211FrameBody.
bool Ieee80211DeauthenticationFrameBody::operator== (const Ieee80211DeauthenticationFrameBody &) [protected]
Reimplemented from Ieee80211FrameBody.
virtual void Ieee80211DeauthenticationFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doPacking().
virtual void Ieee80211DeauthenticationFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doUnpacking().
virtual void Ieee80211DeauthenticationFrameBody::setReasonCode (int reasonCode_var) [virtual]
Referenced by Ieee80211MgmtAP::handleAssociationRequestFrame(), Ieee80211MgmtAP::handleReassociationRequestFrame(), and Ieee80211MgmtSTA::processDeauthenticateCommand().
Member Data Documentation
int Ieee80211DeauthenticationFrameBody::reasonCode_var [protected]
Definition at line 222 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h