INET Framework for OMNeT++/OMNEST: OSPFSummaryLSA Class Reference
OSPFSummaryLSA Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFSummaryLSA ()
OSPFSummaryLSA (const OSPFSummaryLSA &other)
virtual ~OSPFSummaryLSA ()
OSPFSummaryLSA & operator= (const OSPFSummaryLSA &other)
virtual OSPFSummaryLSA * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getNetworkMask ()
virtual const IPAddress & getNetworkMask () const
virtual void setNetworkMask (const IPAddress &networkMask_var)
virtual unsigned long getRouteCost () const
virtual void setRouteCost (unsigned long routeCost_var)
virtual void setTosDataArraySize (unsigned int size)
virtual unsigned int getTosDataArraySize () const
virtual TOSData & getTosData (unsigned int k)
virtual const TOSData & getTosData (unsigned int k) const
virtual void setTosData (unsigned int k, const TOSData &tosData_var)
Protected Member Functions
bool operator== (const OSPFSummaryLSA &)
Protected Attributes
::IPAddress networkMask_var
unsigned long routeCost_var
::TOSData * tosData_var
unsigned int tosData_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class OSPFSummaryLSA extends OSPFLSA
 {
     IPAddress networkMask;
     unsigned long routeCost = 1;
     TOSData tosData[];
 }
Definition at line 526 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFSummaryLSA::OSPFSummaryLSA ()
Referenced by dup().
OSPFSummaryLSA::OSPFSummaryLSA (const OSPFSummaryLSA & other)
virtual OSPFSummaryLSA::~OSPFSummaryLSA () [virtual]
Member Function Documentation
virtual OSPFSummaryLSA* OSPFSummaryLSA::dup () const [inline, virtual]
Reimplemented from OSPFLSA.
Definition at line 542 of file OSPFPacket_m.h.
{return new OSPFSummaryLSA(*this);}
virtual const IPAddress& OSPFSummaryLSA::getNetworkMask () const [inline, virtual]
Definition at line 548 of file OSPFPacket_m.h.
Referenced by getNetworkMask().
{return const_cast<OSPFSummaryLSA*>(this)->getNetworkMask();}
virtual IPAddress& OSPFSummaryLSA::getNetworkMask () [virtual]
Referenced by OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), OSPF::SummaryLSA::DiffersFrom(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Area::GetUniqueLinkStateID(), OSPF::Router::IsDestinationUnreachable(), OSPF::Area::OriginateSummaryLSA(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual unsigned long OSPFSummaryLSA::getRouteCost () const [virtual]
Referenced by OSPF::SummaryLSA::DiffersFrom(), and OSPF::MessageHandler::PrintLinkStateUpdatePacket().
virtual const TOSData& OSPFSummaryLSA::getTosData (unsigned int k) const [inline, virtual]
Definition at line 555 of file OSPFPacket_m.h.
Referenced by getTosData().
{return const_cast<OSPFSummaryLSA*>(this)->getTosData(k);}
virtual TOSData& OSPFSummaryLSA::getTosData (unsigned int k) [virtual]
Referenced by OSPF::SummaryLSA::DiffersFrom().
virtual unsigned int OSPFSummaryLSA::getTosDataArraySize () const [virtual]
Referenced by CalculateLSASize(), and OSPF::SummaryLSA::DiffersFrom().
OSPFSummaryLSA& OSPFSummaryLSA::operator= (const OSPFSummaryLSA & other)
Reimplemented from OSPFLSA.
bool OSPFSummaryLSA::operator== (const OSPFSummaryLSA &) [protected]
Reimplemented from OSPFLSA.
virtual void OSPFSummaryLSA::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doPacking().
virtual void OSPFSummaryLSA::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFLSA.
Referenced by doUnpacking().
virtual void OSPFSummaryLSA::setNetworkMask (const IPAddress & networkMask_var) [virtual]
Referenced by OSPF::Area::GetUniqueLinkStateID().
virtual void OSPFSummaryLSA::setRouteCost (unsigned long routeCost_var) [virtual]
Referenced by OSPF::Area::GetUniqueLinkStateID().
virtual void OSPFSummaryLSA::setTosData (unsigned int k, const TOSData & tosData_var) [virtual]
virtual void OSPFSummaryLSA::setTosDataArraySize (unsigned int size) [virtual]
Member Data Documentation
::IPAddress OSPFSummaryLSA::networkMask_var [protected]
Definition at line 529 of file OSPFPacket_m.h.
Referenced by OSPF::SummaryLSA::DiffersFrom().
unsigned long OSPFSummaryLSA::routeCost_var [protected]
Definition at line 530 of file OSPFPacket_m.h.
Referenced by OSPF::SummaryLSA::DiffersFrom().
unsigned int OSPFSummaryLSA::tosData_arraysize [protected]
Definition at line 532 of file OSPFPacket_m.h.
Referenced by OSPF::SummaryLSA::DiffersFrom().
::TOSData* OSPFSummaryLSA::tosData_var [protected]
Definition at line 531 of file OSPFPacket_m.h.
Referenced by OSPF::SummaryLSA::DiffersFrom().
The documentation for this class was generated from the following file:
OSPFPacket_m.h