INET Framework for OMNeT++/OMNEST: Ieee80211PrimRequest Class Reference
Ieee80211PrimRequest Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211PrimRequest ()
Ieee80211PrimRequest (const Ieee80211PrimRequest &other)
virtual ~Ieee80211PrimRequest ()
Ieee80211PrimRequest & operator= (const Ieee80211PrimRequest &other)
virtual Ieee80211PrimRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211PrimRequest &)
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211PrimRequest
 {
 }
Definition at line 119 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211PrimRequest::Ieee80211PrimRequest ()
Referenced by dup().
Ieee80211PrimRequest::Ieee80211PrimRequest (const Ieee80211PrimRequest & other)
virtual Ieee80211PrimRequest::~Ieee80211PrimRequest () [virtual]
Member Function Documentation
virtual Ieee80211PrimRequest* Ieee80211PrimRequest::dup () const [inline, virtual]
Reimplemented in Ieee80211Prim_ScanRequest, Ieee80211Prim_AuthenticateRequest, Ieee80211Prim_DeauthenticateRequest, Ieee80211Prim_AssociateRequest, Ieee80211Prim_ReassociateRequest, and Ieee80211Prim_DisassociateRequest.
Definition at line 131 of file Ieee80211Primitives_m.h.
{return new Ieee80211PrimRequest(*this);}
Ieee80211PrimRequest& Ieee80211PrimRequest::operator= (const Ieee80211PrimRequest & other)
Reimplemented in Ieee80211Prim_ScanRequest, Ieee80211Prim_AuthenticateRequest, Ieee80211Prim_DeauthenticateRequest, Ieee80211Prim_AssociateRequest, Ieee80211Prim_ReassociateRequest, and Ieee80211Prim_DisassociateRequest.
bool Ieee80211PrimRequest::operator== (const Ieee80211PrimRequest &) [protected]
Reimplemented in Ieee80211Prim_ScanRequest, Ieee80211Prim_AuthenticateRequest, Ieee80211Prim_DeauthenticateRequest, Ieee80211Prim_AssociateRequest, Ieee80211Prim_ReassociateRequest, and Ieee80211Prim_DisassociateRequest.
virtual void Ieee80211PrimRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211Prim_ScanRequest, Ieee80211Prim_AuthenticateRequest, Ieee80211Prim_DeauthenticateRequest, Ieee80211Prim_AssociateRequest, Ieee80211Prim_ReassociateRequest, and Ieee80211Prim_DisassociateRequest.
Referenced by doPacking().
virtual void Ieee80211PrimRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211Prim_ScanRequest, Ieee80211Prim_AuthenticateRequest, Ieee80211Prim_DeauthenticateRequest, Ieee80211Prim_AssociateRequest, Ieee80211Prim_ReassociateRequest, and Ieee80211Prim_DisassociateRequest.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h