INET Framework for OMNeT++/OMNEST: Ieee80211DisassociationFrameBody Class Reference
Ieee80211DisassociationFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211DisassociationFrameBody ()
Ieee80211DisassociationFrameBody (const Ieee80211DisassociationFrameBody &other)
virtual ~Ieee80211DisassociationFrameBody ()
Ieee80211DisassociationFrameBody & operator= (const Ieee80211DisassociationFrameBody &other)
virtual
Ieee80211DisassociationFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getReasonCode () const
virtual void setReasonCode (int reasonCode_var)
Protected Member Functions
bool operator== (const Ieee80211DisassociationFrameBody &)
Protected Attributes
int reasonCode_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211DisassociationFrameBody extends Ieee80211FrameBody
 {
     bodyLength = 2;
     int reasonCode enum(Ieee80211ReasonCode);
 }
Definition at line 254 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211DisassociationFrameBody::Ieee80211DisassociationFrameBody ()
Referenced by dup().
Ieee80211DisassociationFrameBody::Ieee80211DisassociationFrameBody (const Ieee80211DisassociationFrameBody & other)
virtual Ieee80211DisassociationFrameBody::~Ieee80211DisassociationFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211DisassociationFrameBody* Ieee80211DisassociationFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211FrameBody.
Definition at line 267 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211DisassociationFrameBody(*this);}
virtual int Ieee80211DisassociationFrameBody::getReasonCode () const [virtual]
Ieee80211DisassociationFrameBody& Ieee80211DisassociationFrameBody::operator= (const Ieee80211DisassociationFrameBody & other)
Reimplemented from Ieee80211FrameBody.
bool Ieee80211DisassociationFrameBody::operator== (const Ieee80211DisassociationFrameBody &) [protected]
Reimplemented from Ieee80211FrameBody.
virtual void Ieee80211DisassociationFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doPacking().
virtual void Ieee80211DisassociationFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doUnpacking().
virtual void Ieee80211DisassociationFrameBody::setReasonCode (int reasonCode_var) [virtual]
Referenced by Ieee80211MgmtSTA::processDisassociateCommand().
Member Data Documentation
int Ieee80211DisassociationFrameBody::reasonCode_var [protected]
Definition at line 257 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h