INET Framework for OMNeT++/OMNEST: GenericAppMsg Class Reference
GenericAppMsg Class Reference
#include <GenericAppMsg_m.h>
Public Member Functions
GenericAppMsg (const char *name=NULL, int kind=0)
GenericAppMsg (const GenericAppMsg &other)
virtual ~GenericAppMsg ()
GenericAppMsg & operator= (const GenericAppMsg &other)
virtual GenericAppMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getExpectedReplyLength () const
virtual void setExpectedReplyLength (int expectedReplyLength_var)
virtual double getReplyDelay () const
virtual void setReplyDelay (double replyDelay_var)
virtual bool getServerClose () const
virtual void setServerClose (bool serverClose_var)
Protected Member Functions
bool operator== (const GenericAppMsg &)
Protected Attributes
int expectedReplyLength_var
double replyDelay_var
bool serverClose_var
Detailed Description
Class generated from applications/tcpapp/GenericAppMsg.msg by opp_msgc.
 packet GenericAppMsg
 {
     int expectedReplyLength;
     double replyDelay;
     bool serverClose;
 }
Definition at line 35 of file GenericAppMsg_m.h.
Constructor & Destructor Documentation
GenericAppMsg::GenericAppMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
GenericAppMsg::GenericAppMsg (const GenericAppMsg & other)
virtual GenericAppMsg::~GenericAppMsg () [virtual]
Member Function Documentation
virtual GenericAppMsg* GenericAppMsg::dup () const [inline, virtual]
Definition at line 50 of file GenericAppMsg_m.h.
{return new GenericAppMsg(*this);}
virtual int GenericAppMsg::getExpectedReplyLength () const [virtual]
Referenced by TCPGenericSrvThread::dataArrived(), and TCPGenericSrvApp::handleMessage().
virtual double GenericAppMsg::getReplyDelay () const [virtual]
Referenced by TCPGenericSrvThread::dataArrived(), and TCPGenericSrvApp::handleMessage().
virtual bool GenericAppMsg::getServerClose () const [virtual]
Referenced by TCPGenericSrvThread::dataArrived(), and TCPGenericSrvApp::handleMessage().
GenericAppMsg& GenericAppMsg::operator= (const GenericAppMsg & other)
bool GenericAppMsg::operator== (const GenericAppMsg &) [protected]
virtual void GenericAppMsg::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void GenericAppMsg::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void GenericAppMsg::setExpectedReplyLength (int expectedReplyLength_var) [virtual]
virtual void GenericAppMsg::setReplyDelay (double replyDelay_var) [virtual]
virtual void GenericAppMsg::setServerClose (bool serverClose_var) [virtual]
Member Data Documentation
int GenericAppMsg::expectedReplyLength_var [protected]
Definition at line 38 of file GenericAppMsg_m.h.
double GenericAppMsg::replyDelay_var [protected]
Definition at line 39 of file GenericAppMsg_m.h.
bool GenericAppMsg::serverClose_var [protected]
Definition at line 40 of file GenericAppMsg_m.h.
The documentation for this class was generated from the following file:
GenericAppMsg_m.h