INET Framework for OMNeT++/OMNEST: SCTPHeartbeatChunk Class Reference
SCTPHeartbeatChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPHeartbeatChunk (const char *name=NULL, int kind=0)
SCTPHeartbeatChunk (const SCTPHeartbeatChunk &other)
virtual ~SCTPHeartbeatChunk ()
SCTPHeartbeatChunk & operator= (const SCTPHeartbeatChunk &other)
virtual SCTPHeartbeatChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual simtime_t getTimeField () const
virtual void setTimeField (simtime_t timeField_var)
virtual void setInfoArraySize (unsigned int size)
virtual unsigned int getInfoArraySize () const
virtual char getInfo (unsigned int k) const
virtual void setInfo (unsigned int k, char info_var)
Protected Member Functions
bool operator== (const SCTPHeartbeatChunk &)
Protected Attributes
::IPvXAddress remoteAddr_var
simtime_t timeField_var
char * info_var
unsigned int info_arraysize
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPHeartbeatChunk extends SCTPChunk
 {
      IPvXAddress remoteAddr;
      simtime_t timeField;
      char info[];
 }
Definition at line 801 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPHeartbeatChunk::SCTPHeartbeatChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPHeartbeatChunk::SCTPHeartbeatChunk (const SCTPHeartbeatChunk & other)
virtual SCTPHeartbeatChunk::~SCTPHeartbeatChunk () [virtual]
Member Function Documentation
virtual SCTPHeartbeatChunk* SCTPHeartbeatChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 817 of file SCTPMessage_m.h.
{return new SCTPHeartbeatChunk(*this);}
virtual char SCTPHeartbeatChunk::getInfo (unsigned int k) const [virtual]
Referenced by SCTPAssociation::sendHeartbeatAck().
virtual unsigned int SCTPHeartbeatChunk::getInfoArraySize () const [virtual]
Referenced by SCTPAssociation::sendHeartbeatAck().
virtual const IPvXAddress& SCTPHeartbeatChunk::getRemoteAddr () const [inline, virtual]
Definition at line 823 of file SCTPMessage_m.h.
Referenced by getRemoteAddr().
{return const_cast<SCTPHeartbeatChunk*>(this)->getRemoteAddr();}
virtual IPvXAddress& SCTPHeartbeatChunk::getRemoteAddr () [virtual]
Referenced by SCTPAssociation::sendHeartbeatAck().
virtual simtime_t SCTPHeartbeatChunk::getTimeField () const [virtual]
Referenced by TCPDumper::sctpDump(), and SCTPAssociation::sendHeartbeatAck().
SCTPHeartbeatChunk& SCTPHeartbeatChunk::operator= (const SCTPHeartbeatChunk & other)
Reimplemented from SCTPChunk.
bool SCTPHeartbeatChunk::operator== (const SCTPHeartbeatChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPHeartbeatChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPHeartbeatChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPHeartbeatChunk::setInfo (unsigned int k, char info_var) [virtual]
virtual void SCTPHeartbeatChunk::setInfoArraySize (unsigned int size) [virtual]
virtual void SCTPHeartbeatChunk::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Referenced by SCTPAssociation::sendHeartbeat().
virtual void SCTPHeartbeatChunk::setTimeField (simtime_t timeField_var) [virtual]
Referenced by SCTPAssociation::sendHeartbeat().
Member Data Documentation
unsigned int SCTPHeartbeatChunk::info_arraysize [protected]
Definition at line 807 of file SCTPMessage_m.h.
char* SCTPHeartbeatChunk::info_var [protected]
Definition at line 806 of file SCTPMessage_m.h.
::IPvXAddress SCTPHeartbeatChunk::remoteAddr_var [protected]
Definition at line 804 of file SCTPMessage_m.h.
simtime_t SCTPHeartbeatChunk::timeField_var [protected]
Definition at line 805 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h