INET Framework for OMNeT++/OMNEST: SCTPSocket::CallbackInterface Class Reference
SCTPSocket::CallbackInterface Class Reference
#include <SCTPSocket.h>
Public Member Functions
virtual ~CallbackInterface ()
virtual void socketDataArrived (int assocId, void *yourPtr, cPacket *msg, bool urgent)=0
virtual void socketDataNotificationArrived (int assocId, void *yourPtr, cPacket *msg)=0
virtual void socketEstablished (int assocId, void *yourPtr, uint64 buffer)
virtual void socketPeerClosed (int assocId, void *yourPtr)
virtual void socketClosed (int assocId, void *yourPtr)
virtual void socketFailure (int assocId, void *yourPtr, int code)
virtual void socketStatusArrived (int assocId, void *yourPtr, SCTPStatusInfo *status)
virtual void sendRequestArrived ()
virtual void shutdownReceivedArrived (int connId)
virtual void sendqueueFullArrived (int connId)
virtual void sendqueueAbatedArrived (int connId, uint64 buffer)
virtual void addressAddedArrived (int assocId, IPvXAddress localAddr, IPvXAddress remoteAddr)
Detailed Description
Abstract base class for your callback objects. See setCallbackObject() and processMessage() for more info.
Note: this class is not subclassed from cPolymorphic, because classes may have both this class and cSimpleModule as base class, and cSimpleModule is already a cPolymorphic.
Definition at line 46 of file SCTPSocket.h.
Constructor & Destructor Documentation
virtual SCTPSocket::CallbackInterface::~CallbackInterface () [inline, virtual]
Definition at line 49 of file SCTPSocket.h.
{}
Member Function Documentation
virtual void SCTPSocket::CallbackInterface::addressAddedArrived (int assocId, IPvXAddress localAddr, IPvXAddress remoteAddr) [inline, virtual]
Definition at line 61 of file SCTPSocket.h.
{}
virtual void SCTPSocket::CallbackInterface::sendqueueAbatedArrived (int connId, uint64 buffer) [inline, virtual]
Definition at line 60 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::sendqueueFullArrived (int connId) [inline, virtual]
Definition at line 59 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::sendRequestArrived () [inline, virtual]
Reimplemented in SCTPClient, and SCTPPeer.
Definition at line 57 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::shutdownReceivedArrived (int connId) [inline, virtual]
Definition at line 58 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::socketClosed (int assocId, void * yourPtr) [inline, virtual]
Definition at line 54 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::socketDataArrived (int assocId, void * yourPtr, cPacket * msg, bool urgent) [pure virtual]
Referenced by SCTPSocket::processMessage().
virtual void SCTPSocket::CallbackInterface::socketDataNotificationArrived (int assocId, void * yourPtr, cPacket * msg) [pure virtual]
Referenced by SCTPSocket::processMessage().
virtual void SCTPSocket::CallbackInterface::socketEstablished (int assocId, void * yourPtr, uint64 buffer) [inline, virtual]
Definition at line 52 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::socketFailure (int assocId, void * yourPtr, int code) [inline, virtual]
Definition at line 55 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::socketPeerClosed (int assocId, void * yourPtr) [inline, virtual]
Definition at line 53 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}
virtual void SCTPSocket::CallbackInterface::socketStatusArrived (int assocId, void * yourPtr, SCTPStatusInfo * status) [inline, virtual]
Definition at line 56 of file SCTPSocket.h.
Referenced by SCTPSocket::processMessage().
{}// {delete status;}
The documentation for this class was generated from the following file:
SCTPSocket.h