INET Framework for OMNeT++/OMNEST: UDPEchoAppMsg Class Reference
UDPEchoAppMsg Class Reference
#include <UDPEchoAppMsg_m.h>
Public Member Functions
UDPEchoAppMsg (const char *name=NULL, int kind=0)
UDPEchoAppMsg (const UDPEchoAppMsg &other)
virtual ~UDPEchoAppMsg ()
UDPEchoAppMsg & operator= (const UDPEchoAppMsg &other)
virtual UDPEchoAppMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getIsRequest () const
virtual void setIsRequest (bool isRequest_var)
Protected Member Functions
bool operator== (const UDPEchoAppMsg &)
Protected Attributes
bool isRequest_var
Detailed Description
Class generated from applications/udpapp/UDPEchoAppMsg.msg by opp_msgc.
 packet UDPEchoAppMsg
 {
     bool isRequest = true;
 }
Definition at line 32 of file UDPEchoAppMsg_m.h.
Constructor & Destructor Documentation
UDPEchoAppMsg::UDPEchoAppMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
UDPEchoAppMsg::UDPEchoAppMsg (const UDPEchoAppMsg & other)
virtual UDPEchoAppMsg::~UDPEchoAppMsg () [virtual]
Member Function Documentation
virtual UDPEchoAppMsg* UDPEchoAppMsg::dup () const [inline, virtual]
Definition at line 45 of file UDPEchoAppMsg_m.h.
{return new UDPEchoAppMsg(*this);}
virtual bool UDPEchoAppMsg::getIsRequest () const [virtual]
Referenced by UDPEchoApp::processPacket().
UDPEchoAppMsg& UDPEchoAppMsg::operator= (const UDPEchoAppMsg & other)
bool UDPEchoAppMsg::operator== (const UDPEchoAppMsg &) [protected]
virtual void UDPEchoAppMsg::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void UDPEchoAppMsg::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void UDPEchoAppMsg::setIsRequest (bool isRequest_var) [virtual]
Referenced by UDPEchoApp::processPacket().
Member Data Documentation
bool UDPEchoAppMsg::isRequest_var [protected]
Definition at line 35 of file UDPEchoAppMsg_m.h.
The documentation for this class was generated from the following file:
UDPEchoAppMsg_m.h