INET Framework for OMNeT++/OMNEST: IPv6RouterSolicitation Class Reference
IPv6RouterSolicitation Class Reference
#include <IPv6NDMessage_m.h>
Public Member Functions
IPv6RouterSolicitation (const char *name=NULL, int kind=0)
IPv6RouterSolicitation (const IPv6RouterSolicitation &other)
virtual ~IPv6RouterSolicitation ()
IPv6RouterSolicitation & operator= (const IPv6RouterSolicitation &other)
virtual IPv6RouterSolicitation * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getSourceLinkLayerAddress ()
virtual const MACAddress & getSourceLinkLayerAddress () const
virtual void setSourceLinkLayerAddress (const MACAddress &sourceLinkLayerAddress_var)
Protected Member Functions
bool operator== (const IPv6RouterSolicitation &)
Protected Attributes
::MACAddress sourceLinkLayerAddress_var
Detailed Description
Class generated from networklayer/icmpv6/IPv6NDMessage.msg by opp_msgc.
 packet IPv6RouterSolicitation extends IPv6NDMessage
 {
     MACAddress sourceLinkLayerAddress;
 }
Definition at line 125 of file IPv6NDMessage_m.h.
Constructor & Destructor Documentation
IPv6RouterSolicitation::IPv6RouterSolicitation (const char * name = NULL, int kind = 0)
Referenced by dup().
IPv6RouterSolicitation::IPv6RouterSolicitation (const IPv6RouterSolicitation & other)
virtual IPv6RouterSolicitation::~IPv6RouterSolicitation () [virtual]
Member Function Documentation
virtual IPv6RouterSolicitation* IPv6RouterSolicitation::dup () const [inline, virtual]
Reimplemented from IPv6NDMessage.
Definition at line 138 of file IPv6NDMessage_m.h.
{return new IPv6RouterSolicitation(*this);}
virtual const MACAddress& IPv6RouterSolicitation::getSourceLinkLayerAddress () const [inline, virtual]
Definition at line 144 of file IPv6NDMessage_m.h.
Referenced by getSourceLinkLayerAddress().
{return const_cast<IPv6RouterSolicitation*>(this)->getSourceLinkLayerAddress();}
virtual MACAddress& IPv6RouterSolicitation::getSourceLinkLayerAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processRSPacket(), and IPv6NeighbourDiscovery::validateRSPacket().
IPv6RouterSolicitation& IPv6RouterSolicitation::operator= (const IPv6RouterSolicitation & other)
Reimplemented from IPv6NDMessage.
bool IPv6RouterSolicitation::operator== (const IPv6RouterSolicitation &) [protected]
Reimplemented from IPv6NDMessage.
virtual void IPv6RouterSolicitation::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doPacking().
virtual void IPv6RouterSolicitation::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doUnpacking().
virtual void IPv6RouterSolicitation::setSourceLinkLayerAddress (const MACAddress & sourceLinkLayerAddress_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendRSPacket().
Member Data Documentation
::MACAddress IPv6RouterSolicitation::sourceLinkLayerAddress_var [protected]
Definition at line 128 of file IPv6NDMessage_m.h.
The documentation for this class was generated from the following file:
IPv6NDMessage_m.h