INET Framework for OMNeT++/OMNEST: OSPFLinkStateAcknowledgementPacket Class Reference
OSPFLinkStateAcknowledgementPacket Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFLinkStateAcknowledgementPacket (const char *name=NULL, int kind=0)
OSPFLinkStateAcknowledgementPacket (const OSPFLinkStateAcknowledgementPacket &other)
virtual ~OSPFLinkStateAcknowledgementPacket ()
OSPFLinkStateAcknowledgementPacket & operator= (const OSPFLinkStateAcknowledgementPacket &other)
virtual
OSPFLinkStateAcknowledgementPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setLsaHeadersArraySize (unsigned int size)
virtual unsigned int getLsaHeadersArraySize () const
virtual OSPFLSAHeader & getLsaHeaders (unsigned int k)
virtual const OSPFLSAHeader & getLsaHeaders (unsigned int k) const
virtual void setLsaHeaders (unsigned int k, const OSPFLSAHeader &lsaHeaders_var)
Protected Member Functions
bool operator== (const OSPFLinkStateAcknowledgementPacket &)
Protected Attributes
::OSPFLSAHeader * lsaHeaders_var
unsigned int lsaHeaders_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 packet OSPFLinkStateAcknowledgementPacket extends OSPFPacket
 {
     OSPFLSAHeader lsaHeaders[];
 }
Definition at line 874 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFLinkStateAcknowledgementPacket::OSPFLinkStateAcknowledgementPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
OSPFLinkStateAcknowledgementPacket::OSPFLinkStateAcknowledgementPacket (const OSPFLinkStateAcknowledgementPacket & other)
virtual OSPFLinkStateAcknowledgementPacket::~OSPFLinkStateAcknowledgementPacket () [virtual]
Member Function Documentation
virtual OSPFLinkStateAcknowledgementPacket* OSPFLinkStateAcknowledgementPacket::dup () const [inline, virtual]
Reimplemented from OSPFPacket.
Definition at line 888 of file OSPFPacket_m.h.
{return new OSPFLinkStateAcknowledgementPacket(*this);}
virtual const OSPFLSAHeader& OSPFLinkStateAcknowledgementPacket::getLsaHeaders (unsigned int k) const [inline, virtual]
Definition at line 896 of file OSPFPacket_m.h.
Referenced by getLsaHeaders().
{return const_cast<OSPFLinkStateAcknowledgementPacket*>(this)->getLsaHeaders(k);}
virtual OSPFLSAHeader& OSPFLinkStateAcknowledgementPacket::getLsaHeaders (unsigned int k) [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateAcknowledgementPacket(), and OSPF::LinkStateAcknowledgementHandler::ProcessPacket().
virtual unsigned int OSPFLinkStateAcknowledgementPacket::getLsaHeadersArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateAcknowledgementPacket(), OSPF::LinkStateAcknowledgementHandler::ProcessPacket(), and OSPF::Interface::SendDelayedAcknowledgements().
OSPFLinkStateAcknowledgementPacket& OSPFLinkStateAcknowledgementPacket::operator= (const OSPFLinkStateAcknowledgementPacket & other)
Reimplemented from OSPFPacket.
bool OSPFLinkStateAcknowledgementPacket::operator== (const OSPFLinkStateAcknowledgementPacket &) [protected]
Reimplemented from OSPFPacket.
virtual void OSPFLinkStateAcknowledgementPacket::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doPacking().
virtual void OSPFLinkStateAcknowledgementPacket::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doUnpacking().
virtual void OSPFLinkStateAcknowledgementPacket::setLsaHeaders (unsigned int k, const OSPFLSAHeader & lsaHeaders_var) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::SendDelayedAcknowledgements(), and OSPF::Interface::SendLSAcknowledgement().
virtual void OSPFLinkStateAcknowledgementPacket::setLsaHeadersArraySize (unsigned int size) [virtual]
Referenced by OSPF::LinkStateUpdateHandler::AcknowledgeLSA(), OSPF::Interface::SendDelayedAcknowledgements(), and OSPF::Interface::SendLSAcknowledgement().
Member Data Documentation
unsigned int OSPFLinkStateAcknowledgementPacket::lsaHeaders_arraysize [protected]
Definition at line 878 of file OSPFPacket_m.h.
::OSPFLSAHeader* OSPFLinkStateAcknowledgementPacket::lsaHeaders_var [protected]
Definition at line 877 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h