INET Framework for OMNeT++/OMNEST: TCPSendCommand Class Reference
TCPSendCommand Class Reference
#include <TCPCommand_m.h>
Public Member Functions
TCPSendCommand ()
TCPSendCommand (const TCPSendCommand &other)
virtual ~TCPSendCommand ()
TCPSendCommand & operator= (const TCPSendCommand &other)
virtual TCPSendCommand * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const TCPSendCommand &)
Detailed Description
Class generated from transport/contract/TCPCommand.msg by opp_msgc.
 class TCPSendCommand extends TCPCommand
 {
 }
Definition at line 237 of file TCPCommand_m.h.
Constructor & Destructor Documentation
TCPSendCommand::TCPSendCommand ()
Referenced by dup().
TCPSendCommand::TCPSendCommand (const TCPSendCommand & other)
virtual TCPSendCommand::~TCPSendCommand () [virtual]
Member Function Documentation
virtual TCPSendCommand* TCPSendCommand::dup () const [inline, virtual]
Reimplemented from TCPCommand.
Definition at line 249 of file TCPCommand_m.h.
{return new TCPSendCommand(*this);}
TCPSendCommand& TCPSendCommand::operator= (const TCPSendCommand & other)
Reimplemented from TCPCommand.
bool TCPSendCommand::operator== (const TCPSendCommand &) [protected]
Reimplemented from TCPCommand.
virtual void TCPSendCommand::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doPacking().
virtual void TCPSendCommand::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TCPCommand_m.h