INET Framework for OMNeT++/OMNEST: LDPLabelRequest Class Reference
LDPLabelRequest Class Reference
#include <LDPPacket_m.h>
Public Member Functions
LDPLabelRequest (const char *name=NULL, int kind=0)
LDPLabelRequest (const LDPLabelRequest &other)
virtual ~LDPLabelRequest ()
LDPLabelRequest & operator= (const LDPLabelRequest &other)
virtual LDPLabelRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual FEC_TLV & getFec ()
virtual const FEC_TLV & getFec () const
virtual void setFec (const FEC_TLV &fec_var)
Protected Member Functions
bool operator== (const LDPLabelRequest &)
Protected Attributes
::FEC_TLV fec_var
Detailed Description
Class generated from networklayer/ldp/LDPPacket.msg by opp_msgc.
 packet LDPLabelRequest extends LDPPacket
 {
     FEC_TLV fec;
 }
Definition at line 183 of file LDPPacket_m.h.
Constructor & Destructor Documentation
LDPLabelRequest::LDPLabelRequest (const char * name = NULL, int kind = 0)
Referenced by dup().
LDPLabelRequest::LDPLabelRequest (const LDPLabelRequest & other)
virtual LDPLabelRequest::~LDPLabelRequest () [virtual]
Member Function Documentation
virtual LDPLabelRequest* LDPLabelRequest::dup () const [inline, virtual]
Reimplemented from LDPPacket.
Definition at line 196 of file LDPPacket_m.h.
{return new LDPLabelRequest(*this);}
virtual const FEC_TLV& LDPLabelRequest::getFec () const [inline, virtual]
Definition at line 202 of file LDPPacket_m.h.
Referenced by getFec().
{return const_cast<LDPLabelRequest*>(this)->getFec();}
virtual FEC_TLV& LDPLabelRequest::getFec () [virtual]
Referenced by LDP::processLABEL_REQUEST().
LDPLabelRequest& LDPLabelRequest::operator= (const LDPLabelRequest & other)
Reimplemented from LDPPacket.
bool LDPLabelRequest::operator== (const LDPLabelRequest &) [protected]
Reimplemented from LDPPacket.
virtual void LDPLabelRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doPacking().
virtual void LDPLabelRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doUnpacking().
virtual void LDPLabelRequest::setFec (const FEC_TLV & fec_var) [virtual]
Referenced by LDP::sendMappingRequest().
Member Data Documentation
::FEC_TLV LDPLabelRequest::fec_var [protected]
Definition at line 186 of file LDPPacket_m.h.
The documentation for this class was generated from the following file:
LDPPacket_m.h