INET Framework for OMNeT++/OMNEST: RSVPPacket_Base Class Reference
RSVPPacket_Base Class Reference
#include <RSVPPacket_m.h>
Public Member Functions
virtual ~RSVPPacket_Base ()
virtual RSVPPacket_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual SessionObj_t & getSession ()
virtual const SessionObj_t & getSession () const
virtual void setSession (const SessionObj_t &session_var)
virtual bool getChecksumValid () const
virtual void setChecksumValid (bool checksumValid_var)
Protected Member Functions
bool operator== (const RSVPPacket_Base &)
RSVPPacket_Base (const char *name=NULL, int kind=0)
RSVPPacket_Base (const RSVPPacket_Base &other)
RSVPPacket_Base & operator= (const RSVPPacket_Base &other)
Protected Attributes
::SessionObj_t session_var
bool checksumValid_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPPacket.msg by opp_msgc.
 packet RSVPPacket extends RSVPMessage
 {
     (true);
     SessionObj_t session;
     bool checksumValid = true;
 }
RSVPPacket_Base is only useful if it gets subclassed, and RSVPPacket is derived from it. The minimum code to be written for RSVPPacket is the following:
 class RSVPPacket : public RSVPPacket_Base
 {
   public:
     RSVPPacket(const char *name=NULL, int kind=0) : RSVPPacket_Base(name,kind) {}
     RSVPPacket(const RSVPPacket& other) : RSVPPacket_Base(other.getName()) {operator=(other);}
     RSVPPacket& operator=(const RSVPPacket& other) {RSVPPacket_Base::operator=(other); return *this;}
     virtual RSVPPacket *dup() const {return new RSVPPacket(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPPacket_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(RSVPPacket);
Definition at line 97 of file RSVPPacket_m.h.
Constructor & Destructor Documentation
RSVPPacket_Base::RSVPPacket_Base (const char * name = NULL, int kind = 0) [protected]
RSVPPacket_Base::RSVPPacket_Base (const RSVPPacket_Base & other) [protected]
virtual RSVPPacket_Base::~RSVPPacket_Base () [virtual]
Member Function Documentation
virtual RSVPPacket_Base* RSVPPacket_Base::dup () const [inline, virtual]
Reimplemented from RSVPMessage.
Reimplemented in RSVPPacket, RSVPPathMsg, RSVPPathTear, RSVPPathError, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg, RSVPResvTear, RSVPResvError, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
Definition at line 113 of file RSVPPacket_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class RSVPPacket");}
virtual bool RSVPPacket_Base::getChecksumValid () const [virtual]
virtual const SessionObj_t& RSVPPacket_Base::getSession () const [inline, virtual]
Definition at line 119 of file RSVPPacket_m.h.
Referenced by getSession().
{return const_cast<RSVPPacket_Base*>(this)->getSession();}
virtual SessionObj_t& RSVPPacket_Base::getSession () [virtual]
Referenced by RSVP::createPSB(), RSVP::createRSB(), RSVPPacket::getDestAddress(), RSVPPacket::getExTunnelId(), RSVPPacket::getHoldingPri(), RSVPPacket::getSetupPri(), RSVPPacket::getTunnelId(), RSVPPacket::isInSession(), RSVP::processPathErrMsg(), RSVP::processPathMsg(), RSVP::processPathTearMsg(), and RSVP::processResvMsg().
RSVPPacket_Base& RSVPPacket_Base::operator= (const RSVPPacket_Base & other) [protected]
Reimplemented from RSVPMessage.
Reimplemented in RSVPPacket, RSVPPathMsg, RSVPPathTear, RSVPPathError, RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg, RSVPResvTear, RSVPResvError, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
bool RSVPPacket_Base::operator== (const RSVPPacket_Base &) [protected]
Reimplemented from RSVPMessage.
Reimplemented in RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
virtual void RSVPPacket_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from RSVPMessage.
Reimplemented in RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
virtual void RSVPPacket_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from RSVPMessage.
Reimplemented in RSVPPathMsg_Base, RSVPPathTear_Base, RSVPPathError_Base, RSVPResvMsg_Base, RSVPResvTear_Base, and RSVPResvError_Base.
virtual void RSVPPacket_Base::setChecksumValid (bool checksumValid_var) [virtual]
virtual void RSVPPacket_Base::setSession (const SessionObj_t & session_var) [virtual]
Referenced by RSVP::refreshResv(), RSVP::sendPathErrorMessage(), and RSVP::sendPathTearMessage().
Member Data Documentation
bool RSVPPacket_Base::checksumValid_var [protected]
Definition at line 101 of file RSVPPacket_m.h.
::SessionObj_t RSVPPacket_Base::session_var [protected]
Definition at line 100 of file RSVPPacket_m.h.
The documentation for this class was generated from the following file:
RSVPPacket_m.h