INET Framework for OMNeT++/OMNEST: EtherFrameWithSNAP Class Reference
EtherFrameWithSNAP Class Reference
#include <EtherFrame_m.h>
Public Member Functions
EtherFrameWithSNAP (const char *name=NULL, int kind=0)
EtherFrameWithSNAP (const EtherFrameWithSNAP &other)
virtual ~EtherFrameWithSNAP ()
EtherFrameWithSNAP & operator= (const EtherFrameWithSNAP &other)
virtual EtherFrameWithSNAP * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual long getOrgCode () const
virtual void setOrgCode (long orgCode_var)
virtual int getLocalcode () const
virtual void setLocalcode (int localcode_var)
Protected Member Functions
bool operator== (const EtherFrameWithSNAP &)
Protected Attributes
long orgCode_var
int localcode_var
Detailed Description
Class generated from linklayer/ethernet/EtherFrame.msg by opp_msgc.
 packet EtherFrameWithSNAP extends EtherFrame
 {
     long orgCode;
     int localcode;
 }
Definition at line 182 of file EtherFrame_m.h.
Constructor & Destructor Documentation
EtherFrameWithSNAP::EtherFrameWithSNAP (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherFrameWithSNAP::EtherFrameWithSNAP (const EtherFrameWithSNAP & other)
virtual EtherFrameWithSNAP::~EtherFrameWithSNAP () [virtual]
Member Function Documentation
virtual EtherFrameWithSNAP* EtherFrameWithSNAP::dup () const [inline, virtual]
Reimplemented from EtherFrame.
Definition at line 196 of file EtherFrame_m.h.
{return new EtherFrameWithSNAP(*this);}
virtual int EtherFrameWithSNAP::getLocalcode () const [virtual]
virtual long EtherFrameWithSNAP::getOrgCode () const [virtual]
EtherFrameWithSNAP& EtherFrameWithSNAP::operator= (const EtherFrameWithSNAP & other)
Reimplemented from EtherFrame.
bool EtherFrameWithSNAP::operator== (const EtherFrameWithSNAP &) [protected]
Reimplemented from EtherFrame.
virtual void EtherFrameWithSNAP::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doPacking().
virtual void EtherFrameWithSNAP::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from EtherFrame.
Referenced by doUnpacking().
virtual void EtherFrameWithSNAP::setLocalcode (int localcode_var) [virtual]
virtual void EtherFrameWithSNAP::setOrgCode (long orgCode_var) [virtual]
Member Data Documentation
int EtherFrameWithSNAP::localcode_var [protected]
Definition at line 186 of file EtherFrame_m.h.
long EtherFrameWithSNAP::orgCode_var [protected]
Definition at line 185 of file EtherFrame_m.h.
The documentation for this class was generated from the following file:
EtherFrame_m.h