INET Framework for OMNeT++/OMNEST: UDPPacket Class Reference
UDPPacket Class Reference
#include <UDPPacket_m.h>
Public Member Functions
UDPPacket (const char *name=NULL, int kind=0)
UDPPacket (const UDPPacket &other)
virtual ~UDPPacket ()
UDPPacket & operator= (const UDPPacket &other)
virtual UDPPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSourcePort () const
virtual void setSourcePort (int sourcePort_var)
virtual int getDestinationPort () const
virtual void setDestinationPort (int destinationPort_var)
Protected Member Functions
bool operator== (const UDPPacket &)
Protected Attributes
int sourcePort_var
int destinationPort_var
Detailed Description
Class generated from transport/udp/UDPPacket.msg by opp_msgc.
 packet UDPPacket
 {
     int sourcePort = -1;
     int destinationPort = -1;
 }
Definition at line 33 of file UDPPacket_m.h.
Constructor & Destructor Documentation
UDPPacket::UDPPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
UDPPacket::UDPPacket (const UDPPacket & other)
virtual UDPPacket::~UDPPacket () [virtual]
Member Function Documentation
virtual UDPPacket* UDPPacket::dup () const [inline, virtual]
Definition at line 47 of file UDPPacket_m.h.
{return new UDPPacket(*this);}
virtual int UDPPacket::getDestinationPort () const [virtual]
Referenced by UDP::processUDPPacket(), UDP::sendUp(), UDPSerializer::serialize(), and TCPDumper::udpDump().
virtual int UDPPacket::getSourcePort () const [virtual]
Referenced by UDP::matchesSocket(), UDP::sendUp(), UDPSerializer::serialize(), and TCPDumper::udpDump().
UDPPacket& UDPPacket::operator= (const UDPPacket & other)
bool UDPPacket::operator== (const UDPPacket &) [protected]
virtual void UDPPacket::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void UDPPacket::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void UDPPacket::setDestinationPort (int destinationPort_var) [virtual]
Referenced by UDPSerializer::parse().
virtual void UDPPacket::setSourcePort (int sourcePort_var) [virtual]
Referenced by UDPSerializer::parse(), and UDP::processMsgFromApp().
Member Data Documentation
int UDPPacket::destinationPort_var [protected]
Definition at line 37 of file UDPPacket_m.h.
int UDPPacket::sourcePort_var [protected]
Definition at line 36 of file UDPPacket_m.h.
The documentation for this class was generated from the following file:
UDPPacket_m.h