INET Framework for OMNeT++/OMNEST: Ieee80211ReassociationRequestFrameBody Class Reference
Ieee80211ReassociationRequestFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ReassociationRequestFrameBody ()
Ieee80211ReassociationRequestFrameBody (const Ieee80211ReassociationRequestFrameBody &other)
virtual ~Ieee80211ReassociationRequestFrameBody ()
Ieee80211ReassociationRequestFrameBody & operator= (const Ieee80211ReassociationRequestFrameBody &other)
virtual
Ieee80211ReassociationRequestFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getCurrentAP ()
virtual const MACAddress & getCurrentAP () const
virtual void setCurrentAP (const MACAddress &currentAP_var)
Protected Member Functions
bool operator== (const Ieee80211ReassociationRequestFrameBody &)
Protected Attributes
::MACAddress currentAP_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211ReassociationRequestFrameBody extends Ieee80211AssociationRequestFrameBody
 {
     bodyLength = 26;
     MACAddress currentAP;
 }
Definition at line 369 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ReassociationRequestFrameBody::Ieee80211ReassociationRequestFrameBody ()
Referenced by dup().
Ieee80211ReassociationRequestFrameBody::Ieee80211ReassociationRequestFrameBody (const Ieee80211ReassociationRequestFrameBody & other)
virtual Ieee80211ReassociationRequestFrameBody::~Ieee80211ReassociationRequestFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211ReassociationRequestFrameBody* Ieee80211ReassociationRequestFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211AssociationRequestFrameBody.
Definition at line 382 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ReassociationRequestFrameBody(*this);}
virtual const MACAddress& Ieee80211ReassociationRequestFrameBody::getCurrentAP () const [inline, virtual]
Definition at line 388 of file Ieee80211MgmtFrames_m.h.
Referenced by getCurrentAP().
{return const_cast<Ieee80211ReassociationRequestFrameBody*>(this)->getCurrentAP();}
virtual MACAddress& Ieee80211ReassociationRequestFrameBody::getCurrentAP () [virtual]
Ieee80211ReassociationRequestFrameBody& Ieee80211ReassociationRequestFrameBody::operator= (const Ieee80211ReassociationRequestFrameBody & other)
Reimplemented from Ieee80211AssociationRequestFrameBody.
bool Ieee80211ReassociationRequestFrameBody::operator== (const Ieee80211ReassociationRequestFrameBody &) [protected]
Reimplemented from Ieee80211AssociationRequestFrameBody.
virtual void Ieee80211ReassociationRequestFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211AssociationRequestFrameBody.
Referenced by doPacking().
virtual void Ieee80211ReassociationRequestFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211AssociationRequestFrameBody.
Referenced by doUnpacking().
virtual void Ieee80211ReassociationRequestFrameBody::setCurrentAP (const MACAddress & currentAP_var) [virtual]
Member Data Documentation
::MACAddress Ieee80211ReassociationRequestFrameBody::currentAP_var [protected]
Definition at line 372 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h