INET Framework for OMNeT++/OMNEST: SCTPForwardTsnChunk Class Reference
SCTPForwardTsnChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPForwardTsnChunk (const char *name=NULL, int kind=0)
SCTPForwardTsnChunk (const SCTPForwardTsnChunk &other)
virtual ~SCTPForwardTsnChunk ()
SCTPForwardTsnChunk & operator= (const SCTPForwardTsnChunk &other)
virtual SCTPForwardTsnChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32 getNewCumTsn () const
virtual void setNewCumTsn (uint32 newCumTsn_var)
virtual void setSidArraySize (unsigned int size)
virtual unsigned int getSidArraySize () const
virtual uint16 getSid (unsigned int k) const
virtual void setSid (unsigned int k, uint16 sid_var)
virtual void setSsnArraySize (unsigned int size)
virtual unsigned int getSsnArraySize () const
virtual short getSsn (unsigned int k) const
virtual void setSsn (unsigned int k, short ssn_var)
Protected Member Functions
bool operator== (const SCTPForwardTsnChunk &)
Protected Attributes
uint32 newCumTsn_var
uint16 * sid_var
unsigned int sid_arraysize
short * ssn_var
unsigned int ssn_arraysize
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPForwardTsnChunk extends SCTPChunk
 {
      uint32 newCumTsn;
      uint16 sid[];
      short ssn[];
 }
Definition at line 642 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPForwardTsnChunk::SCTPForwardTsnChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPForwardTsnChunk::SCTPForwardTsnChunk (const SCTPForwardTsnChunk & other)
virtual SCTPForwardTsnChunk::~SCTPForwardTsnChunk () [virtual]
Member Function Documentation
virtual SCTPForwardTsnChunk* SCTPForwardTsnChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 659 of file SCTPMessage_m.h.
{return new SCTPForwardTsnChunk(*this);}
virtual uint32 SCTPForwardTsnChunk::getNewCumTsn () const [virtual]
virtual uint16 SCTPForwardTsnChunk::getSid (unsigned int k) const [virtual]
virtual unsigned int SCTPForwardTsnChunk::getSidArraySize () const [virtual]
virtual short SCTPForwardTsnChunk::getSsn (unsigned int k) const [virtual]
virtual unsigned int SCTPForwardTsnChunk::getSsnArraySize () const [virtual]
SCTPForwardTsnChunk& SCTPForwardTsnChunk::operator= (const SCTPForwardTsnChunk & other)
Reimplemented from SCTPChunk.
bool SCTPForwardTsnChunk::operator== (const SCTPForwardTsnChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPForwardTsnChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPForwardTsnChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPForwardTsnChunk::setNewCumTsn (uint32 newCumTsn_var) [virtual]
virtual void SCTPForwardTsnChunk::setSid (unsigned int k, uint16 sid_var) [virtual]
virtual void SCTPForwardTsnChunk::setSidArraySize (unsigned int size) [virtual]
virtual void SCTPForwardTsnChunk::setSsn (unsigned int k, short ssn_var) [virtual]
virtual void SCTPForwardTsnChunk::setSsnArraySize (unsigned int size) [virtual]
Member Data Documentation
uint32 SCTPForwardTsnChunk::newCumTsn_var [protected]
Definition at line 645 of file SCTPMessage_m.h.
unsigned int SCTPForwardTsnChunk::sid_arraysize [protected]
Definition at line 647 of file SCTPMessage_m.h.
uint16* SCTPForwardTsnChunk::sid_var [protected]
Definition at line 646 of file SCTPMessage_m.h.
unsigned int SCTPForwardTsnChunk::ssn_arraysize [protected]
Definition at line 649 of file SCTPMessage_m.h.
short* SCTPForwardTsnChunk::ssn_var [protected]
Definition at line 648 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h