INET Framework for OMNeT++/OMNEST: PPPFrame Class Reference
PPPFrame Class Reference
#include <PPPFrame_m.h>
Public Member Functions
PPPFrame (const char *name=NULL, int kind=0)
PPPFrame (const PPPFrame &other)
virtual ~PPPFrame ()
PPPFrame & operator= (const PPPFrame &other)
virtual PPPFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const PPPFrame &)
Detailed Description
Class generated from linklayer/ppp/PPPFrame.msg by opp_msgc.
 packet PPPFrame
 {
 }
Definition at line 32 of file PPPFrame_m.h.
Constructor & Destructor Documentation
PPPFrame::PPPFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
PPPFrame::PPPFrame (const PPPFrame & other)
virtual PPPFrame::~PPPFrame () [virtual]
Member Function Documentation
virtual PPPFrame* PPPFrame::dup () const [inline, virtual]
Definition at line 44 of file PPPFrame_m.h.
{return new PPPFrame(*this);}
PPPFrame& PPPFrame::operator= (const PPPFrame & other)
bool PPPFrame::operator== (const PPPFrame &) [protected]
virtual void PPPFrame::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void PPPFrame::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PPPFrame_m.h