INET Framework for OMNeT++/OMNEST: SCTPSimpleMessage Class Reference
SCTPSimpleMessage Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPSimpleMessage (const char *name=NULL, int kind=0)
SCTPSimpleMessage (const SCTPSimpleMessage &other)
virtual ~SCTPSimpleMessage ()
SCTPSimpleMessage & operator= (const SCTPSimpleMessage &other)
virtual SCTPSimpleMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32 getDataLen () const
virtual void setDataLen (uint32 dataLen_var)
virtual void setDataArraySize (unsigned int size)
virtual unsigned int getDataArraySize () const
virtual char getData (unsigned int k) const
virtual void setData (unsigned int k, char data_var)
virtual simtime_t getCreationTime () const
virtual void setCreationTime (simtime_t creationTime_var)
virtual bool getEncaps () const
virtual void setEncaps (bool encaps_var)
Protected Member Functions
bool operator== (const SCTPSimpleMessage &)
Protected Attributes
uint32 dataLen_var
char * data_var
unsigned int data_arraysize
simtime_t creationTime_var
bool encaps_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPSimpleMessage extends cPacket
 {
      uint32 dataLen;
      char data[];
      simtime_t creationTime = 0;
      bool encaps = false;
 }
Definition at line 40 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPSimpleMessage::SCTPSimpleMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPSimpleMessage::SCTPSimpleMessage (const SCTPSimpleMessage & other)
virtual SCTPSimpleMessage::~SCTPSimpleMessage () [virtual]
Member Function Documentation
virtual SCTPSimpleMessage* SCTPSimpleMessage::dup () const [inline, virtual]
Definition at line 57 of file SCTPMessage_m.h.
{return new SCTPSimpleMessage(*this);}
virtual simtime_t SCTPSimpleMessage::getCreationTime () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPServer::handleMessage(), and SCTPPeer::handleMessage().
virtual char SCTPSimpleMessage::getData (unsigned int k) const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), and SCTPReceiveStream::reassemble().
virtual unsigned int SCTPSimpleMessage::getDataArraySize () const [virtual]
Referenced by SCTPReceiveStream::reassemble().
virtual uint32 SCTPSimpleMessage::getDataLen () const [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPAssociation::makeVarFromMsg(), and SCTPReceiveStream::reassemble().
virtual bool SCTPSimpleMessage::getEncaps () const [virtual]
SCTPSimpleMessage& SCTPSimpleMessage::operator= (const SCTPSimpleMessage & other)
bool SCTPSimpleMessage::operator== (const SCTPSimpleMessage &) [protected]
virtual void SCTPSimpleMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SCTPSimpleMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SCTPSimpleMessage::setCreationTime (simtime_t creationTime_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPPeer::sendRequest(), and SCTPClient::sendRequest().
virtual void SCTPSimpleMessage::setData (unsigned int k, char data_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPServer::generateAndSend(), SCTPPeer::generateAndSend(), SCTPReceiveStream::reassemble(), SCTPPeer::sendRequest(), and SCTPClient::sendRequest().
virtual void SCTPSimpleMessage::setDataArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPServer::generateAndSend(), SCTPPeer::generateAndSend(), SCTPReceiveStream::reassemble(), SCTPPeer::sendRequest(), and SCTPClient::sendRequest().
virtual void SCTPSimpleMessage::setDataLen (uint32 dataLen_var) [virtual]
Referenced by SCTPAssociation::dequeueOutboundDataMsg(), SCTPServer::generateAndSend(), SCTPPeer::generateAndSend(), SCTPReceiveStream::reassemble(), SCTPPeer::sendRequest(), and SCTPClient::sendRequest().
virtual void SCTPSimpleMessage::setEncaps (bool encaps_var) [virtual]
Member Data Documentation
simtime_t SCTPSimpleMessage::creationTime_var [protected]
Definition at line 46 of file SCTPMessage_m.h.
unsigned int SCTPSimpleMessage::data_arraysize [protected]
Definition at line 45 of file SCTPMessage_m.h.
char* SCTPSimpleMessage::data_var [protected]
Definition at line 44 of file SCTPMessage_m.h.
uint32 SCTPSimpleMessage::dataLen_var [protected]
Definition at line 43 of file SCTPMessage_m.h.
bool SCTPSimpleMessage::encaps_var [protected]
Definition at line 47 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h