INET Framework for OMNeT++/OMNEST: Ieee80211AssociationRequestFrame Class Reference
Ieee80211AssociationRequestFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211AssociationRequestFrame (const char *name=NULL, int kind=0)
Ieee80211AssociationRequestFrame (const Ieee80211AssociationRequestFrame &other)
virtual ~Ieee80211AssociationRequestFrame ()
Ieee80211AssociationRequestFrame & operator= (const Ieee80211AssociationRequestFrame &other)
virtual
Ieee80211AssociationRequestFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211AssociationRequestFrameBody & getBody ()
virtual const
Ieee80211AssociationRequestFrameBody & getBody () const
virtual void setBody (const Ieee80211AssociationRequestFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211AssociationRequestFrame &)
Protected Attributes
::Ieee80211AssociationRequestFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211AssociationRequestFrame extends Ieee80211ManagementFrame
 {
     type = ST_ASSOCIATIONREQUEST;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211AssociationRequestFrameBody body;
 }
Definition at line 711 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211AssociationRequestFrame::Ieee80211AssociationRequestFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211AssociationRequestFrame::Ieee80211AssociationRequestFrame (const Ieee80211AssociationRequestFrame & other)
virtual Ieee80211AssociationRequestFrame::~Ieee80211AssociationRequestFrame () [virtual]
Member Function Documentation
virtual Ieee80211AssociationRequestFrame* Ieee80211AssociationRequestFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 724 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211AssociationRequestFrame(*this);}
virtual const Ieee80211AssociationRequestFrameBody& Ieee80211AssociationRequestFrame::getBody () const [inline, virtual]
Definition at line 730 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211AssociationRequestFrame*>(this)->getBody();}
virtual Ieee80211AssociationRequestFrameBody& Ieee80211AssociationRequestFrame::getBody () [virtual]
Ieee80211AssociationRequestFrame& Ieee80211AssociationRequestFrame::operator= (const Ieee80211AssociationRequestFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211AssociationRequestFrame::operator== (const Ieee80211AssociationRequestFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211AssociationRequestFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211AssociationRequestFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211AssociationRequestFrame::setBody (const Ieee80211AssociationRequestFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211AssociationRequestFrameBody Ieee80211AssociationRequestFrame::body_var [protected]
Definition at line 714 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h