INET Framework for OMNeT++/OMNEST: SCTPMessage_Base Class Reference
SCTPMessage_Base Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
virtual ~SCTPMessage_Base ()
virtual SCTPMessage_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint16 getSrcPort () const
virtual void setSrcPort (uint16 srcPort_var)
virtual uint16 getDestPort () const
virtual void setDestPort (uint16 destPort_var)
virtual uint32 getTag () const
virtual void setTag (uint32 tag_var)
virtual bool getChecksumOk () const
virtual void setChecksumOk (bool checksumOk_var)
virtual void setChunksArraySize (unsigned int size)=0
virtual unsigned int getChunksArraySize () const =0
virtual cPacketPtr & getChunks (unsigned int k)=0
virtual const cPacketPtr & getChunks (unsigned int k) const
virtual void setChunks (unsigned int k, const cPacketPtr &chunks_var)=0
Protected Member Functions
bool operator== (const SCTPMessage_Base &)
SCTPMessage_Base (const char *name=NULL, int kind=0)
SCTPMessage_Base (const SCTPMessage_Base &other)
SCTPMessage_Base & operator= (const SCTPMessage_Base &other)
Protected Attributes
uint16 srcPort_var
uint16 destPort_var
uint32 tag_var
bool checksumOk_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPMessage extends cPacket
 {
      (true);
      uint16 srcPort;
      uint16 destPort;
      uint32 tag;
      bool checksumOk;
      abstract cPacketPtr chunks[];
 }
SCTPMessage_Base is only useful if it gets subclassed, and SCTPMessage is derived from it. The minimum code to be written for SCTPMessage is the following:
 class SCTPMessage : public SCTPMessage_Base
 {
   public:
     SCTPMessage(const char *name=NULL, int kind=0) : SCTPMessage_Base(name,kind) {}
     SCTPMessage(const SCTPMessage& other) : SCTPMessage_Base(other.getName()) {operator=(other);}
     SCTPMessage& operator=(const SCTPMessage& other) {SCTPMessage_Base::operator=(other); return *this;}
     virtual SCTPMessage *dup() const {return new SCTPMessage(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from SCTPMessage_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(SCTPMessage);
Definition at line 115 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPMessage_Base::SCTPMessage_Base (const char * name = NULL, int kind = 0) [protected]
SCTPMessage_Base::SCTPMessage_Base (const SCTPMessage_Base & other) [protected]
virtual SCTPMessage_Base::~SCTPMessage_Base () [virtual]
Member Function Documentation
virtual SCTPMessage_Base* SCTPMessage_Base::dup () const [inline, virtual]
Reimplemented in SCTPMessage.
Definition at line 133 of file SCTPMessage_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class SCTPMessage");}
virtual bool SCTPMessage_Base::getChecksumOk () const [virtual]
Referenced by SCTP::handleMessage(), and SCTPAssociation::process_RCV_Message().
virtual const cPacketPtr& SCTPMessage_Base::getChunks (unsigned int k) const [inline, virtual]
Definition at line 149 of file SCTPMessage_m.h.
Referenced by getChunks().
{return const_cast<SCTPMessage_Base*>(this)->getChunks(k);}
virtual cPacketPtr& SCTPMessage_Base::getChunks (unsigned int k) [pure virtual]
virtual unsigned int SCTPMessage_Base::getChunksArraySize () const [pure virtual]
Implemented in SCTPMessage.
virtual uint16 SCTPMessage_Base::getDestPort () const [virtual]
Referenced by SCTP::handleMessage(), SCTPAssociation::printSegmentBrief(), SCTPAssociation::process_RCV_Message(), SCTPAssociation::processSCTPMessage(), TCPDumper::sctpDump(), SCTP::sendAbortFromMain(), and SCTP::sendShutdownCompleteFromMain().
virtual uint16 SCTPMessage_Base::getSrcPort () const [virtual]
Referenced by SCTP::handleMessage(), SCTPAssociation::printSegmentBrief(), SCTPAssociation::process_RCV_Message(), SCTPAssociation::processSCTPMessage(), TCPDumper::sctpDump(), SCTP::sendAbortFromMain(), and SCTP::sendShutdownCompleteFromMain().
virtual uint32 SCTPMessage_Base::getTag () const [virtual]
Referenced by SCTP::handleMessage(), SCTPMessage::operator=(), SCTPAssociation::printSegmentBrief(), SCTPAssociation::process_RCV_Message(), TCPDumper::sctpDump(), SCTP::sendAbortFromMain(), SCTPAssociation::sendInitAck(), SCTP::sendShutdownCompleteFromMain(), and SCTPAssociation::sendToIP().
SCTPMessage_Base& SCTPMessage_Base::operator= (const SCTPMessage_Base & other) [protected]
Reimplemented in SCTPMessage.
Referenced by SCTPMessage::SCTPMessage().
bool SCTPMessage_Base::operator== (const SCTPMessage_Base &) [protected]
virtual void SCTPMessage_Base::parsimPack (cCommBuffer * b) [virtual]
virtual void SCTPMessage_Base::parsimUnpack (cCommBuffer * b) [virtual]
virtual void SCTPMessage_Base::setChecksumOk (bool checksumOk_var) [virtual]
Referenced by TCPDumper::sctpDump(), SCTP::sendAbortFromMain(), SCTP::sendShutdownCompleteFromMain(), and SCTPAssociation::sendToIP().
virtual void SCTPMessage_Base::setChunks (unsigned int k, const cPacketPtr & chunks_var) [pure virtual]
virtual void SCTPMessage_Base::setChunksArraySize (unsigned int size) [pure virtual]
virtual void SCTPMessage_Base::setDestPort (uint16 destPort_var) [virtual]
Referenced by SCTPAssociation::sendAbort(), SCTP::sendAbortFromMain(), SCTPAssociation::sendCookieAck(), SCTPAssociation::sendCookieEcho(), SCTPAssociation::sendHeartbeat(), SCTPAssociation::sendHeartbeatAck(), SCTPAssociation::sendInitAck(), SCTPAssociation::sendShutdown(), SCTPAssociation::sendShutdownAck(), SCTPAssociation::sendShutdownComplete(), SCTP::sendShutdownCompleteFromMain(), and SCTPAssociation::sendToIP().
virtual void SCTPMessage_Base::setSrcPort (uint16 srcPort_var) [virtual]
Referenced by SCTPAssociation::sendAbort(), SCTP::sendAbortFromMain(), SCTPAssociation::sendCookieAck(), SCTPAssociation::sendCookieEcho(), SCTPAssociation::sendHeartbeat(), SCTPAssociation::sendHeartbeatAck(), SCTPAssociation::sendInitAck(), SCTPAssociation::sendShutdown(), SCTPAssociation::sendShutdownAck(), SCTPAssociation::sendShutdownComplete(), SCTP::sendShutdownCompleteFromMain(), and SCTPAssociation::sendToIP().
virtual void SCTPMessage_Base::setTag (uint32 tag_var) [virtual]
Referenced by SCTPMessage::operator=(), SCTP::sendAbortFromMain(), SCTPAssociation::sendInitAck(), SCTP::sendShutdownCompleteFromMain(), and SCTPAssociation::sendToIP().
Member Data Documentation
bool SCTPMessage_Base::checksumOk_var [protected]
Definition at line 121 of file SCTPMessage_m.h.
uint16 SCTPMessage_Base::destPort_var [protected]
Definition at line 119 of file SCTPMessage_m.h.
uint16 SCTPMessage_Base::srcPort_var [protected]
Definition at line 118 of file SCTPMessage_m.h.
uint32 SCTPMessage_Base::tag_var [protected]
Definition at line 120 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h