INET Framework for OMNeT++/OMNEST: EtherAppReq Class Reference
EtherAppReq Class Reference
#include <EtherApp_m.h>
Public Member Functions
EtherAppReq (const char *name=NULL, int kind=0)
EtherAppReq (const EtherAppReq &other)
virtual ~EtherAppReq ()
EtherAppReq & operator= (const EtherAppReq &other)
virtual EtherAppReq * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual long getRequestId () const
virtual void setRequestId (long requestId_var)
virtual long getResponseBytes () const
virtual void setResponseBytes (long responseBytes_var)
Protected Member Functions
bool operator== (const EtherAppReq &)
Protected Attributes
long requestId_var
long responseBytes_var
Detailed Description
Class generated from applications/ethernet/EtherApp.msg by opp_msgc.
 packet EtherAppReq
 {
     long requestId;
     long responseBytes;
 }
Definition at line 35 of file EtherApp_m.h.
Constructor & Destructor Documentation
EtherAppReq::EtherAppReq (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherAppReq::EtherAppReq (const EtherAppReq & other)
virtual EtherAppReq::~EtherAppReq () [virtual]
Member Function Documentation
virtual EtherAppReq* EtherAppReq::dup () const [inline, virtual]
Definition at line 49 of file EtherApp_m.h.
{return new EtherAppReq(*this);}
virtual long EtherAppReq::getRequestId () const [virtual]
Referenced by EtherAppSrv::handleMessage().
virtual long EtherAppReq::getResponseBytes () const [virtual]
Referenced by EtherAppSrv::handleMessage().
EtherAppReq& EtherAppReq::operator= (const EtherAppReq & other)
bool EtherAppReq::operator== (const EtherAppReq &) [protected]
virtual void EtherAppReq::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void EtherAppReq::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void EtherAppReq::setRequestId (long requestId_var) [virtual]
Referenced by EtherAppCli::sendPacket().
virtual void EtherAppReq::setResponseBytes (long responseBytes_var) [virtual]
Referenced by EtherAppCli::sendPacket().
Member Data Documentation
long EtherAppReq::requestId_var [protected]
Definition at line 38 of file EtherApp_m.h.
long EtherAppReq::responseBytes_var [protected]
Definition at line 39 of file EtherApp_m.h.
The documentation for this class was generated from the following file:
EtherApp_m.h