INET Framework for OMNeT++/OMNEST: SCTPCookieAckChunk Class Reference
SCTPCookieAckChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPCookieAckChunk (const char *name=NULL, int kind=0)
SCTPCookieAckChunk (const SCTPCookieAckChunk &other)
virtual ~SCTPCookieAckChunk ()
SCTPCookieAckChunk & operator= (const SCTPCookieAckChunk &other)
virtual SCTPCookieAckChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const SCTPCookieAckChunk &)
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPCookieAckChunk extends SCTPChunk
 {
 }
Definition at line 462 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPCookieAckChunk::SCTPCookieAckChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPCookieAckChunk::SCTPCookieAckChunk (const SCTPCookieAckChunk & other)
virtual SCTPCookieAckChunk::~SCTPCookieAckChunk () [virtual]
Member Function Documentation
virtual SCTPCookieAckChunk* SCTPCookieAckChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 474 of file SCTPMessage_m.h.
{return new SCTPCookieAckChunk(*this);}
SCTPCookieAckChunk& SCTPCookieAckChunk::operator= (const SCTPCookieAckChunk & other)
Reimplemented from SCTPChunk.
bool SCTPCookieAckChunk::operator== (const SCTPCookieAckChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPCookieAckChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPCookieAckChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
SCTPMessage_m.h