INET Framework for OMNeT++/OMNEST: Ieee80211Prim_ReassociateConfirm Class Reference
Ieee80211Prim_ReassociateConfirm Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_ReassociateConfirm ()
Ieee80211Prim_ReassociateConfirm (const Ieee80211Prim_ReassociateConfirm &other)
virtual ~Ieee80211Prim_ReassociateConfirm ()
Ieee80211Prim_ReassociateConfirm & operator= (const Ieee80211Prim_ReassociateConfirm &other)
virtual
Ieee80211Prim_ReassociateConfirm * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211Prim_ReassociateConfirm &)
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_ReassociateConfirm extends Ieee80211Prim_AssociateConfirm
 {
 }
Definition at line 556 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_ReassociateConfirm::Ieee80211Prim_ReassociateConfirm ()
Referenced by dup().
Ieee80211Prim_ReassociateConfirm::Ieee80211Prim_ReassociateConfirm (const Ieee80211Prim_ReassociateConfirm & other)
virtual Ieee80211Prim_ReassociateConfirm::~Ieee80211Prim_ReassociateConfirm () [virtual]
Member Function Documentation
virtual Ieee80211Prim_ReassociateConfirm* Ieee80211Prim_ReassociateConfirm::dup () const [inline, virtual]
Reimplemented from Ieee80211Prim_AssociateConfirm.
Definition at line 568 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_ReassociateConfirm(*this);}
Ieee80211Prim_ReassociateConfirm& Ieee80211Prim_ReassociateConfirm::operator= (const Ieee80211Prim_ReassociateConfirm & other)
Reimplemented from Ieee80211Prim_AssociateConfirm.
bool Ieee80211Prim_ReassociateConfirm::operator== (const Ieee80211Prim_ReassociateConfirm &) [protected]
Reimplemented from Ieee80211Prim_AssociateConfirm.
virtual void Ieee80211Prim_ReassociateConfirm::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211Prim_AssociateConfirm.
Referenced by doPacking().
virtual void Ieee80211Prim_ReassociateConfirm::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211Prim_AssociateConfirm.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h