INET Framework for OMNeT++/OMNEST: Ieee80211Prim_ScanRequest Class Reference
Ieee80211Prim_ScanRequest Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_ScanRequest ()
Ieee80211Prim_ScanRequest (const Ieee80211Prim_ScanRequest &other)
virtual ~Ieee80211Prim_ScanRequest ()
Ieee80211Prim_ScanRequest & operator= (const Ieee80211Prim_ScanRequest &other)
virtual Ieee80211Prim_ScanRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getBSSType () const
virtual void setBSSType (int BSSType_var)
virtual MACAddress & getBSSID ()
virtual const MACAddress & getBSSID () const
virtual void setBSSID (const MACAddress &BSSID_var)
virtual const char * getSSID () const
virtual void setSSID (const char *SSID_var)
virtual bool getActiveScan () const
virtual void setActiveScan (bool activeScan_var)
virtual simtime_t getProbeDelay () const
virtual void setProbeDelay (simtime_t probeDelay_var)
virtual void setChannelListArraySize (unsigned int size)
virtual unsigned int getChannelListArraySize () const
virtual int getChannelList (unsigned int k) const
virtual void setChannelList (unsigned int k, int channelList_var)
virtual simtime_t getMinChannelTime () const
virtual void setMinChannelTime (simtime_t minChannelTime_var)
virtual simtime_t getMaxChannelTime () const
virtual void setMaxChannelTime (simtime_t maxChannelTime_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_ScanRequest &)
Protected Attributes
int BSSType_var
::MACAddress BSSID_var
opp_string SSID_var
bool activeScan_var
simtime_t probeDelay_var
int * channelList_var
unsigned int channelList_arraysize
simtime_t minChannelTime_var
simtime_t maxChannelTime_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_ScanRequest extends Ieee80211PrimRequest
 {
     int BSSType enum(Ieee80211BSSType);
     MACAddress BSSID;
     string SSID;
     bool activeScan;
     simtime_t probeDelay;
     int channelList[];
     simtime_t minChannelTime;
     simtime_t maxChannelTime;
 }
Definition at line 191 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_ScanRequest::Ieee80211Prim_ScanRequest ()
Referenced by dup().
Ieee80211Prim_ScanRequest::Ieee80211Prim_ScanRequest (const Ieee80211Prim_ScanRequest & other)
virtual Ieee80211Prim_ScanRequest::~Ieee80211Prim_ScanRequest () [virtual]
Member Function Documentation
virtual Ieee80211Prim_ScanRequest* Ieee80211Prim_ScanRequest::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimRequest.
Definition at line 212 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_ScanRequest(*this);}
virtual bool Ieee80211Prim_ScanRequest::getActiveScan () const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual const MACAddress& Ieee80211Prim_ScanRequest::getBSSID () const [inline, virtual]
Definition at line 220 of file Ieee80211Primitives_m.h.
Referenced by getBSSID().
{return const_cast<Ieee80211Prim_ScanRequest*>(this)->getBSSID();}
virtual MACAddress& Ieee80211Prim_ScanRequest::getBSSID () [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual int Ieee80211Prim_ScanRequest::getBSSType () const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual int Ieee80211Prim_ScanRequest::getChannelList (unsigned int k) const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual unsigned int Ieee80211Prim_ScanRequest::getChannelListArraySize () const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual simtime_t Ieee80211Prim_ScanRequest::getMaxChannelTime () const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual simtime_t Ieee80211Prim_ScanRequest::getMinChannelTime () const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual simtime_t Ieee80211Prim_ScanRequest::getProbeDelay () const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
virtual const char* Ieee80211Prim_ScanRequest::getSSID () const [virtual]
Referenced by Ieee80211MgmtSTA::processScanCommand().
Ieee80211Prim_ScanRequest& Ieee80211Prim_ScanRequest::operator= (const Ieee80211Prim_ScanRequest & other)
Reimplemented from Ieee80211PrimRequest.
bool Ieee80211Prim_ScanRequest::operator== (const Ieee80211Prim_ScanRequest &) [protected]
Reimplemented from Ieee80211PrimRequest.
virtual void Ieee80211Prim_ScanRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doPacking().
virtual void Ieee80211Prim_ScanRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doUnpacking().
virtual void Ieee80211Prim_ScanRequest::setActiveScan (bool activeScan_var) [virtual]
Referenced by Ieee80211AgentSTA::sendScanRequest().
virtual void Ieee80211Prim_ScanRequest::setBSSID (const MACAddress & BSSID_var) [virtual]
virtual void Ieee80211Prim_ScanRequest::setBSSType (int BSSType_var) [virtual]
Referenced by Ieee80211AgentSTA::sendScanRequest().
virtual void Ieee80211Prim_ScanRequest::setChannelList (unsigned int k, int channelList_var) [virtual]
Referenced by Ieee80211AgentSTA::sendScanRequest().
virtual void Ieee80211Prim_ScanRequest::setChannelListArraySize (unsigned int size) [virtual]
Referenced by Ieee80211AgentSTA::sendScanRequest().
virtual void Ieee80211Prim_ScanRequest::setMaxChannelTime (simtime_t maxChannelTime_var) [virtual]
Referenced by Ieee80211AgentSTA::sendScanRequest().
virtual void Ieee80211Prim_ScanRequest::setMinChannelTime (simtime_t minChannelTime_var) [virtual]
Referenced by Ieee80211AgentSTA::sendScanRequest().
virtual void Ieee80211Prim_ScanRequest::setProbeDelay (simtime_t probeDelay_var) [virtual]
Referenced by Ieee80211AgentSTA::sendScanRequest().
virtual void Ieee80211Prim_ScanRequest::setSSID (const char * SSID_var) [virtual]
Member Data Documentation
bool Ieee80211Prim_ScanRequest::activeScan_var [protected]
Definition at line 197 of file Ieee80211Primitives_m.h.
::MACAddress Ieee80211Prim_ScanRequest::BSSID_var [protected]
Definition at line 195 of file Ieee80211Primitives_m.h.
int Ieee80211Prim_ScanRequest::BSSType_var [protected]
Definition at line 194 of file Ieee80211Primitives_m.h.
unsigned int Ieee80211Prim_ScanRequest::channelList_arraysize [protected]
Definition at line 200 of file Ieee80211Primitives_m.h.
int* Ieee80211Prim_ScanRequest::channelList_var [protected]
Definition at line 199 of file Ieee80211Primitives_m.h.
simtime_t Ieee80211Prim_ScanRequest::maxChannelTime_var [protected]
Definition at line 202 of file Ieee80211Primitives_m.h.
simtime_t Ieee80211Prim_ScanRequest::minChannelTime_var [protected]
Definition at line 201 of file Ieee80211Primitives_m.h.
simtime_t Ieee80211Prim_ScanRequest::probeDelay_var [protected]
Definition at line 198 of file Ieee80211Primitives_m.h.
opp_string Ieee80211Prim_ScanRequest::SSID_var [protected]
Definition at line 196 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h