INET Framework for OMNeT++/OMNEST: SCTPInitChunk Class Reference
SCTPInitChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPInitChunk (const char *name=NULL, int kind=0)
SCTPInitChunk (const SCTPInitChunk &other)
virtual ~SCTPInitChunk ()
SCTPInitChunk & operator= (const SCTPInitChunk &other)
virtual SCTPInitChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32 getInitTag () const
virtual void setInitTag (uint32 initTag_var)
virtual uint32 getA_rwnd () const
virtual void setA_rwnd (uint32 a_rwnd_var)
virtual uint16 getNoOutStreams () const
virtual void setNoOutStreams (uint16 noOutStreams_var)
virtual uint16 getNoInStreams () const
virtual void setNoInStreams (uint16 noInStreams_var)
virtual uint32 getInitTSN () const
virtual void setInitTSN (uint32 initTSN_var)
virtual bool getForwardTsn () const
virtual void setForwardTsn (bool forwardTsn_var)
virtual void setAddressesArraySize (unsigned int size)
virtual unsigned int getAddressesArraySize () const
virtual IPvXAddress & getAddresses (unsigned int k)
virtual const IPvXAddress & getAddresses (unsigned int k) const
virtual void setAddresses (unsigned int k, const IPvXAddress &addresses_var)
virtual void setUnrecognizedParametersArraySize (unsigned int size)
virtual unsigned int getUnrecognizedParametersArraySize () const
virtual uint8 getUnrecognizedParameters (unsigned int k) const
virtual void setUnrecognizedParameters (unsigned int k, uint8 unrecognizedParameters_var)
Protected Member Functions
bool operator== (const SCTPInitChunk &)
Protected Attributes
uint32 initTag_var
uint32 a_rwnd_var
uint16 noOutStreams_var
uint16 noInStreams_var
uint32 initTSN_var
bool forwardTsn_var
::IPvXAddress * addresses_var
unsigned int addresses_arraysize
uint8 * unrecognizedParameters_var
unsigned int unrecognizedParameters_arraysize
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPInitChunk extends SCTPChunk
 {
      uint32 initTag;
      uint32 a_rwnd;
      uint16 noOutStreams;
      uint16 noInStreams;
      uint32 initTSN;
      bool forwardTsn;
      IPvXAddress addresses[];
      uint8 unrecognizedParameters[];
 }
Definition at line 210 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPInitChunk::SCTPInitChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPInitChunk::SCTPInitChunk (const SCTPInitChunk & other)
virtual SCTPInitChunk::~SCTPInitChunk () [virtual]
Member Function Documentation
virtual SCTPInitChunk* SCTPInitChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 232 of file SCTPMessage_m.h.
Referenced by SCTPAssociation::retransmitInit(), and SCTPAssociation::sendInit().
{return new SCTPInitChunk(*this);}
virtual uint32 SCTPInitChunk::getA_rwnd () const [virtual]
Referenced by SCTPAssociation::processInitArrived(), and TCPDumper::sctpDump().
virtual const IPvXAddress& SCTPInitChunk::getAddresses (unsigned int k) const [inline, virtual]
Definition at line 252 of file SCTPMessage_m.h.
Referenced by getAddresses().
{return const_cast<SCTPInitChunk*>(this)->getAddresses(k);}
virtual IPvXAddress& SCTPInitChunk::getAddresses (unsigned int k) [virtual]
Referenced by SCTPAssociation::processInitArrived(), and TCPDumper::sctpDump().
virtual unsigned int SCTPInitChunk::getAddressesArraySize () const [virtual]
Referenced by SCTPAssociation::processInitArrived(), and TCPDumper::sctpDump().
virtual bool SCTPInitChunk::getForwardTsn () const [virtual]
virtual uint32 SCTPInitChunk::getInitTag () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), SCTPAssociation::processInitArrived(), TCPDumper::sctpDump(), SCTP::sendAbortFromMain(), SCTPAssociation::sendInit(), and SCTPAssociation::sendInitAck().
virtual uint32 SCTPInitChunk::getInitTSN () const [virtual]
Referenced by SCTPAssociation::processInitArrived(), TCPDumper::sctpDump(), SCTPAssociation::sendInit(), and SCTPAssociation::sendInitAck().
virtual uint16 SCTPInitChunk::getNoInStreams () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), TCPDumper::sctpDump(), and SCTPAssociation::sendInitAck().
virtual uint16 SCTPInitChunk::getNoOutStreams () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), TCPDumper::sctpDump(), and SCTPAssociation::sendInitAck().
virtual uint8 SCTPInitChunk::getUnrecognizedParameters (unsigned int k) const [virtual]
Referenced by SCTPAssociation::sendInitAck().
virtual unsigned int SCTPInitChunk::getUnrecognizedParametersArraySize () const [virtual]
Referenced by SCTPAssociation::sendInitAck().
SCTPInitChunk& SCTPInitChunk::operator= (const SCTPInitChunk & other)
Reimplemented from SCTPChunk.
bool SCTPInitChunk::operator== (const SCTPInitChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPInitChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPInitChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPInitChunk::setA_rwnd (uint32 a_rwnd_var) [virtual]
Referenced by SCTPAssociation::sendInit().
virtual void SCTPInitChunk::setAddresses (unsigned int k, const IPvXAddress & addresses_var) [virtual]
Referenced by SCTPAssociation::sendInit().
virtual void SCTPInitChunk::setAddressesArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::sendInit().
virtual void SCTPInitChunk::setForwardTsn (bool forwardTsn_var) [virtual]
virtual void SCTPInitChunk::setInitTag (uint32 initTag_var) [virtual]
Referenced by SCTPAssociation::sendInit().
virtual void SCTPInitChunk::setInitTSN (uint32 initTSN_var) [virtual]
Referenced by SCTPAssociation::sendInit().
virtual void SCTPInitChunk::setNoInStreams (uint16 noInStreams_var) [virtual]
Referenced by SCTPAssociation::sendInit().
virtual void SCTPInitChunk::setNoOutStreams (uint16 noOutStreams_var) [virtual]
Referenced by SCTPAssociation::sendInit().
virtual void SCTPInitChunk::setUnrecognizedParameters (unsigned int k, uint8 unrecognizedParameters_var) [virtual]
virtual void SCTPInitChunk::setUnrecognizedParametersArraySize (unsigned int size) [virtual]
Member Data Documentation
uint32 SCTPInitChunk::a_rwnd_var [protected]
Definition at line 214 of file SCTPMessage_m.h.
unsigned int SCTPInitChunk::addresses_arraysize [protected]
Definition at line 220 of file SCTPMessage_m.h.
::IPvXAddress* SCTPInitChunk::addresses_var [protected]
Definition at line 219 of file SCTPMessage_m.h.
bool SCTPInitChunk::forwardTsn_var [protected]
Definition at line 218 of file SCTPMessage_m.h.
uint32 SCTPInitChunk::initTag_var [protected]
Definition at line 213 of file SCTPMessage_m.h.
uint32 SCTPInitChunk::initTSN_var [protected]
Definition at line 217 of file SCTPMessage_m.h.
uint16 SCTPInitChunk::noInStreams_var [protected]
Definition at line 216 of file SCTPMessage_m.h.
uint16 SCTPInitChunk::noOutStreams_var [protected]
Definition at line 215 of file SCTPMessage_m.h.
unsigned int SCTPInitChunk::unrecognizedParameters_arraysize [protected]
Definition at line 222 of file SCTPMessage_m.h.
uint8* SCTPInitChunk::unrecognizedParameters_var [protected]
Definition at line 221 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h