INET Framework for OMNeT++/OMNEST: SCTPSendCommand Class Reference
SCTPSendCommand Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPSendCommand (const char *name=NULL)
SCTPSendCommand (const SCTPSendCommand &other)
virtual ~SCTPSendCommand ()
SCTPSendCommand & operator= (const SCTPSendCommand &other)
virtual SCTPSendCommand * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getLast () const
virtual void setLast (bool last_var)
virtual unsigned int getPpid () const
virtual void setPpid (unsigned int ppid_var)
virtual bool getPrimary () const
virtual void setPrimary (bool primary_var)
Protected Member Functions
bool operator== (const SCTPSendCommand &)
Protected Attributes
bool last_var
unsigned int ppid_var
bool primary_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPSendCommand extends SCTPCommand
 {
     bool last;
     unsigned int ppid = 0;
     bool primary = true;
 }
Definition at line 236 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPSendCommand::SCTPSendCommand (const char * name = NULL)
Referenced by dup().
SCTPSendCommand::SCTPSendCommand (const SCTPSendCommand & other)
virtual SCTPSendCommand::~SCTPSendCommand () [virtual]
Member Function Documentation
virtual SCTPSendCommand* SCTPSendCommand::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 251 of file SCTPCommand_m.h.
{return new SCTPSendCommand(*this);}
virtual bool SCTPSendCommand::getLast () const [virtual]
Referenced by SCTPAssociation::process_SEND().
virtual unsigned int SCTPSendCommand::getPpid () const [virtual]
Referenced by SCTPAssociation::process_SEND().
virtual bool SCTPSendCommand::getPrimary () const [virtual]
Referenced by SCTPAssociation::process_SEND().
SCTPSendCommand& SCTPSendCommand::operator= (const SCTPSendCommand & other)
Reimplemented from SCTPCommand.
bool SCTPSendCommand::operator== (const SCTPSendCommand &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPSendCommand::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPSendCommand::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPSendCommand::setLast (bool last_var) [virtual]
Referenced by SCTPServer::generateAndSend(), SCTPPeer::generateAndSend(), SCTPServer::handleMessage(), SCTPPeer::handleMessage(), and SCTPSocket::send().
virtual void SCTPSendCommand::setPpid (unsigned int ppid_var) [virtual]
virtual void SCTPSendCommand::setPrimary (bool primary_var) [virtual]
Referenced by SCTPSocket::send().
Member Data Documentation
bool SCTPSendCommand::last_var [protected]
Definition at line 239 of file SCTPCommand_m.h.
unsigned int SCTPSendCommand::ppid_var [protected]
Definition at line 240 of file SCTPCommand_m.h.
bool SCTPSendCommand::primary_var [protected]
Definition at line 241 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h