INET Framework for OMNeT++/OMNEST: AirFrame Class Reference
AirFrame Class Reference
#include <AirFrame_m.h>
Public Member Functions
AirFrame (const char *name=NULL, int kind=0)
AirFrame (const AirFrame &other)
virtual ~AirFrame ()
AirFrame & operator= (const AirFrame &other)
virtual AirFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual double getPSend () const
virtual void setPSend (double pSend_var)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber_var)
virtual simtime_t getDuration () const
virtual void setDuration (simtime_t duration_var)
virtual double getBitrate () const
virtual void setBitrate (double bitrate_var)
virtual Coord & getSenderPos ()
virtual const Coord & getSenderPos () const
virtual void setSenderPos (const Coord &senderPos_var)
Protected Member Functions
bool operator== (const AirFrame &)
Protected Attributes
double pSend_var
int channelNumber_var
simtime_t duration_var
double bitrate_var
::Coord senderPos_var
Detailed Description
Class generated from linklayer/mfcore/AirFrame.msg by opp_msgc.
 packet AirFrame
 {
     double pSend;
     int channelNumber;
     simtime_t duration;
     double bitrate;
     Coord senderPos;
 }
Definition at line 37 of file AirFrame_m.h.
Constructor & Destructor Documentation
AirFrame::AirFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
AirFrame::AirFrame (const AirFrame & other)
virtual AirFrame::~AirFrame () [virtual]
Member Function Documentation
virtual AirFrame* AirFrame::dup () const [inline, virtual]
Definition at line 54 of file AirFrame_m.h.
Referenced by SnrEval::changeChannel(), AbstractRadio::changeChannel(), and ChannelControl::sendToChannel().
{return new AirFrame(*this);}
virtual double AirFrame::getBitrate () const [virtual]
Referenced by Ieee80211RadioModel::calculateDuration(), GenericRadioModel::calculateDuration(), Ieee80211RadioModel::isReceivedCorrectly(), and GenericRadioModel::isReceivedCorrectly().
virtual int AirFrame::getChannelNumber () const [virtual]
Referenced by ChannelControl::addOngoingTransmission(), SnrEval::changeChannel(), AbstractRadio::changeChannel(), and ChannelControl::sendToChannel().
virtual simtime_t AirFrame::getDuration () const [virtual]
Referenced by BasicSnrEval::bufferMsg(), AbstractRadio::bufferMsg(), SnrEval::changeChannel(), AbstractRadio::changeChannel(), SnrEval::handleUpperMsg(), AbstractRadio::handleUpperMsg(), ChannelControl::purgeOngoingTransmissions(), and ChannelControl::sendToChannel().
virtual double AirFrame::getPSend () const [virtual]
Referenced by SnrEval::handleLowerMsgStart(), GilbertElliotSnr::handleLowerMsgStart(), and AbstractRadio::handleLowerMsgStart().
virtual const Coord& AirFrame::getSenderPos () const [inline, virtual]
Definition at line 68 of file AirFrame_m.h.
Referenced by getSenderPos().
{return const_cast<AirFrame*>(this)->getSenderPos();}
virtual Coord& AirFrame::getSenderPos () [virtual]
Referenced by SnrEval::changeChannel(), AbstractRadio::changeChannel(), SnrEval::handleLowerMsgStart(), GilbertElliotSnr::handleLowerMsgStart(), and AbstractRadio::handleLowerMsgStart().
AirFrame& AirFrame::operator= (const AirFrame & other)
bool AirFrame::operator== (const AirFrame &) [protected]
virtual void AirFrame::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void AirFrame::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void AirFrame::setBitrate (double bitrate_var) [virtual]
virtual void AirFrame::setChannelNumber (int channelNumber_var) [virtual]
Referenced by BasicSnrEval::encapsMsg().
virtual void AirFrame::setDuration (simtime_t duration_var) [virtual]
Referenced by BasicSnrEval::encapsMsg().
virtual void AirFrame::setPSend (double pSend_var) [virtual]
Referenced by BasicSnrEval::encapsMsg().
virtual void AirFrame::setSenderPos (const Coord & senderPos_var) [virtual]
Referenced by BasicSnrEval::encapsMsg().
Member Data Documentation
double AirFrame::bitrate_var [protected]
Definition at line 43 of file AirFrame_m.h.
int AirFrame::channelNumber_var [protected]
Definition at line 41 of file AirFrame_m.h.
simtime_t AirFrame::duration_var [protected]
Definition at line 42 of file AirFrame_m.h.
double AirFrame::pSend_var [protected]
Definition at line 40 of file AirFrame_m.h.
::Coord AirFrame::senderPos_var [protected]
Definition at line 44 of file AirFrame_m.h.
The documentation for this class was generated from the following file:
AirFrame_m.h