INET Framework for OMNeT++/OMNEST: OSPF::RoutingInfo Class Reference
OSPF::RoutingInfo Class Reference
#include <LSA.h>
Public Member Functions
RoutingInfo (void)
RoutingInfo (const RoutingInfo &routingInfo)
virtual ~RoutingInfo (void)
void AddNextHop (NextHop nextHop)
void ClearNextHops (void)
unsigned int GetNextHopCount (void) const
NextHop GetNextHop (unsigned int index) const
void SetDistance (unsigned long d)
unsigned long GetDistance (void) const
void SetParent (OSPFLSA *p)
OSPFLSA * GetParent (void) const
Private Attributes
std::vector< NextHop > nextHops
unsigned long distance
OSPFLSA * parent
Detailed Description
Definition at line 34 of file LSA.h.
Constructor & Destructor Documentation
OSPF::RoutingInfo::RoutingInfo (void) [inline]
Definition at line 42 of file LSA.h.
: distance(0), parent(NULL) {}
OSPF::RoutingInfo::RoutingInfo (const RoutingInfo & routingInfo) [inline]
Definition at line 44 of file LSA.h.
: nextHops(routingInfo.nextHops), distance(routingInfo.distance), parent(routingInfo.parent) {}
virtual OSPF::RoutingInfo::~RoutingInfo (void) [inline, virtual]
Definition at line 46 of file LSA.h.
{}
Member Function Documentation
void OSPF::RoutingInfo::AddNextHop (NextHop nextHop) [inline]
Definition at line 48 of file LSA.h.
{ nextHops.push_back(nextHop); }
void OSPF::RoutingInfo::ClearNextHops (void) [inline]
Definition at line 49 of file LSA.h.
Referenced by OSPF::SummaryLSA::Update(), OSPF::RouterLSA::Update(), OSPF::NetworkLSA::Update(), and OSPF::ASExternalLSA::Update().
{ nextHops.clear(); }
unsigned long OSPF::RoutingInfo::GetDistance (void) const [inline]
Definition at line 53 of file LSA.h.
{ return distance; }
NextHop OSPF::RoutingInfo::GetNextHop (unsigned int index) const [inline]
Definition at line 51 of file LSA.h.
Referenced by OSPF::Area::CalculateNextHops().
{ return nextHops[index]; }
unsigned int OSPF::RoutingInfo::GetNextHopCount (void) const [inline]
Definition at line 50 of file LSA.h.
Referenced by OSPF::Area::CalculateNextHops().
{ return nextHops.size(); }
OSPFLSA* OSPF::RoutingInfo::GetParent (void) const [inline]
Definition at line 55 of file LSA.h.
Referenced by OSPF::Area::CalculateNextHops(), and OSPF::Router::IsDestinationUnreachable().
{ return parent; }
void OSPF::RoutingInfo::SetDistance (unsigned long d) [inline]
Definition at line 52 of file LSA.h.
{ distance = d; }
void OSPF::RoutingInfo::SetParent (OSPFLSA * p) [inline]
Definition at line 54 of file LSA.h.
{ parent = p; }
Member Data Documentation
unsigned long OSPF::RoutingInfo::distance [private]
Definition at line 38 of file LSA.h.
Referenced by GetDistance(), and SetDistance().
std::vector<NextHop> OSPF::RoutingInfo::nextHops [private]
Definition at line 37 of file LSA.h.
Referenced by AddNextHop(), ClearNextHops(), GetNextHop(), and GetNextHopCount().
OSPFLSA* OSPF::RoutingInfo::parent [private]
Definition at line 39 of file LSA.h.
Referenced by GetParent(), and SetParent().
The documentation for this class was generated from the following file:
LSA.h