INET Framework for OMNeT++/OMNEST: PingPayload Class Reference
PingPayload Class Reference
#include <PingPayload_m.h>
Public Member Functions
PingPayload (const char *name=NULL, int kind=0)
PingPayload (const PingPayload &other)
virtual ~PingPayload ()
PingPayload & operator= (const PingPayload &other)
virtual PingPayload * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual long getOriginatorId () const
virtual void setOriginatorId (long originatorId_var)
virtual long getSeqNo () const
virtual void setSeqNo (long seqNo_var)
virtual void setDataArraySize (unsigned int size)
virtual unsigned int getDataArraySize () const
virtual unsigned char getData (unsigned int k) const
virtual void setData (unsigned int k, unsigned char data_var)
Protected Member Functions
bool operator== (const PingPayload &)
Protected Attributes
long originatorId_var
long seqNo_var
unsigned char * data_var
unsigned int data_arraysize
Detailed Description
Class generated from applications/pingapp/PingPayload.msg by opp_msgc.
 packet PingPayload
 {
     long originatorId;
     long seqNo;
     unsigned char data[];
 }
Definition at line 34 of file PingPayload_m.h.
Constructor & Destructor Documentation
PingPayload::PingPayload (const char * name = NULL, int kind = 0)
Referenced by dup().
PingPayload::PingPayload (const PingPayload & other)
virtual PingPayload::~PingPayload () [virtual]
Member Function Documentation
virtual PingPayload* PingPayload::dup () const [inline, virtual]
Definition at line 50 of file PingPayload_m.h.
{return new PingPayload(*this);}
virtual unsigned char PingPayload::getData (unsigned int k) const [virtual]
virtual unsigned int PingPayload::getDataArraySize () const [virtual]
virtual long PingPayload::getOriginatorId () const [virtual]
virtual long PingPayload::getSeqNo () const [virtual]
Referenced by PingApp::processPingResponse().
PingPayload& PingPayload::operator= (const PingPayload & other)
bool PingPayload::operator== (const PingPayload &) [protected]
virtual void PingPayload::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void PingPayload::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void PingPayload::setData (unsigned int k, unsigned char data_var) [virtual]
virtual void PingPayload::setDataArraySize (unsigned int size) [virtual]
virtual void PingPayload::setOriginatorId (long originatorId_var) [virtual]
Referenced by PingApp::sendPing().
virtual void PingPayload::setSeqNo (long seqNo_var) [virtual]
Referenced by PingApp::sendPing().
Member Data Documentation
unsigned int PingPayload::data_arraysize [protected]
Definition at line 40 of file PingPayload_m.h.
unsigned char* PingPayload::data_var [protected]
Definition at line 39 of file PingPayload_m.h.
long PingPayload::originatorId_var [protected]
Definition at line 37 of file PingPayload_m.h.
long PingPayload::seqNo_var [protected]
Definition at line 38 of file PingPayload_m.h.
The documentation for this class was generated from the following file:
PingPayload_m.h