INET Framework for OMNeT++/OMNEST: IPControlInfo_Base Class Reference
IPControlInfo_Base Class Reference
#include <IPControlInfo_m.h>
Public Member Functions
virtual ~IPControlInfo_Base ()
virtual IPControlInfo_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getDestAddr ()
virtual const IPAddress & getDestAddr () const
virtual void setDestAddr (const IPAddress &destAddr_var)
virtual IPAddress & getSrcAddr ()
virtual const IPAddress & getSrcAddr () const
virtual void setSrcAddr (const IPAddress &srcAddr_var)
virtual int getInterfaceId () const
virtual void setInterfaceId (int interfaceId_var)
virtual short getProtocol () const
virtual void setProtocol (short protocol_var)
virtual unsigned char getDiffServCodePoint () const
virtual void setDiffServCodePoint (unsigned char diffServCodePoint_var)
virtual short getTimeToLive () const
virtual void setTimeToLive (short timeToLive_var)
virtual bool getDontFragment () const
virtual void setDontFragment (bool dontFragment_var)
Protected Member Functions
bool operator== (const IPControlInfo_Base &)
IPControlInfo_Base ()
IPControlInfo_Base (const IPControlInfo_Base &other)
IPControlInfo_Base & operator= (const IPControlInfo_Base &other)
Protected Attributes
::IPAddress destAddr_var
::IPAddress srcAddr_var
int interfaceId_var
short protocol_var
unsigned char diffServCodePoint_var
short timeToLive_var
bool dontFragment_var
Detailed Description
Class generated from networklayer/contract/IPControlInfo.msg by opp_msgc.
 class IPControlInfo
 {
     (true);
     IPAddress destAddr;
     IPAddress srcAddr;
     int interfaceId = -1;
     short protocol enum(IPProtocolId);
     unsigned char diffServCodePoint;
     short timeToLive;
     bool dontFragment;
 }
IPControlInfo_Base is only useful if it gets subclassed, and IPControlInfo is derived from it. The minimum code to be written for IPControlInfo is the following:
 class IPControlInfo : public IPControlInfo_Base
 {
   public:
     IPControlInfo() : IPControlInfo_Base() {}
     IPControlInfo(const IPControlInfo& other) : IPControlInfo_Base() {operator=(other);}
     IPControlInfo& operator=(const IPControlInfo& other) {IPControlInfo_Base::operator=(other); return *this;}
     virtual IPControlInfo *dup() const {return new IPControlInfo(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from IPControlInfo_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(IPControlInfo);
Definition at line 62 of file IPControlInfo_m.h.
Constructor & Destructor Documentation
IPControlInfo_Base::IPControlInfo_Base () [protected]
IPControlInfo_Base::IPControlInfo_Base (const IPControlInfo_Base & other) [protected]
virtual IPControlInfo_Base::~IPControlInfo_Base () [virtual]
Member Function Documentation
virtual IPControlInfo_Base* IPControlInfo_Base::dup () const [inline, virtual]
Definition at line 83 of file IPControlInfo_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class IPControlInfo");}
virtual const IPAddress& IPControlInfo_Base::getDestAddr () const [inline, virtual]
Definition at line 89 of file IPControlInfo_m.h.
Referenced by getDestAddr().
{return const_cast<IPControlInfo_Base*>(this)->getDestAddr();}
virtual IPAddress& IPControlInfo_Base::getDestAddr () [virtual]
Referenced by IP::encapsulate(), tcp_old::TCP::handleMessage(), TCP::handleMessage(), SCTP::handleMessage(), UDP::matchesSocket(), IPTrafSink::printPacket(), ICMP::processEchoRequest(), OSPF::MessageHandler::ProcessPacket(), PingApp::processPingResponse(), UDP::processUndeliverablePacket(), and UDP::sendUp().
virtual unsigned char IPControlInfo_Base::getDiffServCodePoint () const [virtual]
Referenced by IP::encapsulate().
virtual bool IPControlInfo_Base::getDontFragment () const [virtual]
Referenced by IP::encapsulate().
virtual int IPControlInfo_Base::getInterfaceId () const [virtual]
Referenced by IP::encapsulate(), UDP::matchesSocket(), OSPF::MessageHandler::ProcessPacket(), and UDP::sendUp().
virtual short IPControlInfo_Base::getProtocol () const [virtual]
Referenced by IP::encapsulate(), and IPTrafSink::printPacket().
virtual const IPAddress& IPControlInfo_Base::getSrcAddr () const [inline, virtual]
Definition at line 92 of file IPControlInfo_m.h.
Referenced by getSrcAddr().
{return const_cast<IPControlInfo_Base*>(this)->getSrcAddr();}
virtual IPAddress& IPControlInfo_Base::getSrcAddr () [virtual]
Referenced by IP::encapsulate(), tcp_old::TCP::handleMessage(), TCP::handleMessage(), SCTP::handleMessage(), LinkStateRouting::handleMessage(), UDP::matchesSocket(), IPTrafSink::printPacket(), ICMP::processEchoRequest(), RSVP::processHelloMsg(), OSPF::MessageHandler::ProcessPacket(), OSPF::HelloHandler::ProcessPacket(), PingApp::processPingResponse(), and UDP::sendUp().
virtual short IPControlInfo_Base::getTimeToLive () const [virtual]
Referenced by IP::encapsulate(), and PingApp::processPingResponse().
IPControlInfo_Base& IPControlInfo_Base::operator= (const IPControlInfo_Base & other) [protected]
Reimplemented in IPControlInfo.
Referenced by IPControlInfo::IPControlInfo(), and IPControlInfo::operator=().
bool IPControlInfo_Base::operator== (const IPControlInfo_Base &) [protected]
virtual void IPControlInfo_Base::parsimPack (cCommBuffer * b) [virtual]
virtual void IPControlInfo_Base::parsimUnpack (cCommBuffer * b) [virtual]
virtual void IPControlInfo_Base::setDestAddr (const IPAddress & destAddr_var) [virtual]
Referenced by IP::decapsulateIP(), ICMP::processEchoRequest(), UDP::processMsgFromApp(), SCTP::sendAbortFromMain(), OSPF::MessageHandler::SendPacket(), IPTrafGen::sendPacket(), SCTP::sendShutdownCompleteFromMain(), PingApp::sendToICMP(), TCPSpoof::sendToIP(), tcp_old::TCPConnection::sendToIP(), TCPConnection::sendToIP(), SCTPAssociation::sendToIP(), RSVP::sendToIP(), LinkStateRouting::sendToIP(), and ICMP::sendToIP().
virtual void IPControlInfo_Base::setDiffServCodePoint (unsigned char diffServCodePoint_var) [virtual]
Referenced by IP::decapsulateIP().
virtual void IPControlInfo_Base::setDontFragment (bool dontFragment_var) [virtual]
virtual void IPControlInfo_Base::setInterfaceId (int interfaceId_var) [virtual]
Referenced by IP::decapsulateIP(), UDP::processMsgFromApp(), and OSPF::MessageHandler::SendPacket().
virtual void IPControlInfo_Base::setProtocol (short protocol_var) [virtual]
Referenced by IP::decapsulateIP(), UDP::processMsgFromApp(), SCTP::sendAbortFromMain(), ICMP::sendEchoRequest(), ICMP::sendErrorMessage(), OSPF::MessageHandler::SendPacket(), IPTrafGen::sendPacket(), SCTP::sendShutdownCompleteFromMain(), TCPSpoof::sendToIP(), tcp_old::TCPConnection::sendToIP(), TCPConnection::sendToIP(), SCTPAssociation::sendToIP(), RSVP::sendToIP(), LinkStateRouting::sendToIP(), and ICMP::sendToIP().
virtual void IPControlInfo_Base::setSrcAddr (const IPAddress & srcAddr_var) [virtual]
Referenced by IP::decapsulateIP(), ICMP::processEchoRequest(), UDP::processMsgFromApp(), SCTP::sendAbortFromMain(), ICMP::sendErrorMessage(), SCTP::sendShutdownCompleteFromMain(), PingApp::sendToICMP(), TCPSpoof::sendToIP(), tcp_old::TCPConnection::sendToIP(), TCPConnection::sendToIP(), SCTPAssociation::sendToIP(), and LinkStateRouting::sendToIP().
virtual void IPControlInfo_Base::setTimeToLive (short timeToLive_var) [virtual]
Referenced by OSPF::MessageHandler::SendPacket(), and PingApp::sendToICMP().
Member Data Documentation
::IPAddress IPControlInfo_Base::destAddr_var [protected]
Definition at line 65 of file IPControlInfo_m.h.
unsigned char IPControlInfo_Base::diffServCodePoint_var [protected]
Definition at line 69 of file IPControlInfo_m.h.
bool IPControlInfo_Base::dontFragment_var [protected]
Definition at line 71 of file IPControlInfo_m.h.
int IPControlInfo_Base::interfaceId_var [protected]
Definition at line 67 of file IPControlInfo_m.h.
short IPControlInfo_Base::protocol_var [protected]
Definition at line 68 of file IPControlInfo_m.h.
::IPAddress IPControlInfo_Base::srcAddr_var [protected]
Definition at line 66 of file IPControlInfo_m.h.
short IPControlInfo_Base::timeToLive_var [protected]
Definition at line 70 of file IPControlInfo_m.h.
The documentation for this class was generated from the following file:
IPControlInfo_m.h