INET Framework for OMNeT++/OMNEST: Ieee80211OneAddressFrame Class Reference
Ieee80211OneAddressFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211OneAddressFrame (const char *name=NULL, int kind=0)
Ieee80211OneAddressFrame (const Ieee80211OneAddressFrame &other)
virtual ~Ieee80211OneAddressFrame ()
Ieee80211OneAddressFrame & operator= (const Ieee80211OneAddressFrame &other)
virtual Ieee80211OneAddressFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211OneAddressFrame &)
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211OneAddressFrame extends Ieee80211Frame
 {
 }
Definition at line 145 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211OneAddressFrame::Ieee80211OneAddressFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211OneAddressFrame::Ieee80211OneAddressFrame (const Ieee80211OneAddressFrame & other)
virtual Ieee80211OneAddressFrame::~Ieee80211OneAddressFrame () [virtual]
Member Function Documentation
virtual Ieee80211OneAddressFrame* Ieee80211OneAddressFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211Frame.
Reimplemented in Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Definition at line 157 of file Ieee80211Frame_m.h.
{return new Ieee80211OneAddressFrame(*this);}
Ieee80211OneAddressFrame& Ieee80211OneAddressFrame::operator= (const Ieee80211OneAddressFrame & other)
Reimplemented from Ieee80211Frame.
Reimplemented in Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
bool Ieee80211OneAddressFrame::operator== (const Ieee80211OneAddressFrame &) [protected]
Reimplemented from Ieee80211Frame.
Reimplemented in Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
virtual void Ieee80211OneAddressFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211Frame.
Reimplemented in Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doPacking().
virtual void Ieee80211OneAddressFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211Frame.
Reimplemented in Ieee80211ACKFrame, Ieee80211TwoAddressFrame, Ieee80211RTSFrame, Ieee80211CTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h