INET Framework for OMNeT++/OMNEST: OSPFLSAHeader Class Reference
OSPFLSAHeader Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFLSAHeader ()
OSPFLSAHeader (const OSPFLSAHeader &other)
virtual ~OSPFLSAHeader ()
OSPFLSAHeader & operator= (const OSPFLSAHeader &other)
virtual OSPFLSAHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned short getLsAge () const
virtual void setLsAge (unsigned short lsAge_var)
virtual OSPFOptions & getLsOptions ()
virtual const OSPFOptions & getLsOptions () const
virtual void setLsOptions (const OSPFOptions &lsOptions_var)
virtual char getLsType () const
virtual void setLsType (char lsType_var)
virtual unsigned long getLinkStateID () const
virtual void setLinkStateID (unsigned long linkStateID_var)
virtual IPAddress & getAdvertisingRouter ()
virtual const IPAddress & getAdvertisingRouter () const
virtual void setAdvertisingRouter (const IPAddress &advertisingRouter_var)
virtual long getLsSequenceNumber () const
virtual void setLsSequenceNumber (long lsSequenceNumber_var)
virtual short getLsChecksum () const
virtual void setLsChecksum (short lsChecksum_var)
virtual unsigned short getLsaLength () const
virtual void setLsaLength (unsigned short lsaLength_var)
Protected Member Functions
bool operator== (const OSPFLSAHeader &)
Protected Attributes
unsigned short lsAge_var
::OSPFOptions lsOptions_var
char lsType_var
unsigned long linkStateID_var
::IPAddress advertisingRouter_var
long lsSequenceNumber_var
short lsChecksum_var
unsigned short lsaLength_var
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 class OSPFLSAHeader
 {
     unsigned short lsAge = 0;
     OSPFOptions lsOptions;
     char lsType enum(LSAType) = RouterLSAType;
     unsigned long linkStateID;
     IPAddress advertisingRouter;
     long lsSequenceNumber = 0;
     short lsChecksum = 0;
     unsigned short lsaLength = 0;
 }
Definition at line 263 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFLSAHeader::OSPFLSAHeader ()
Referenced by dup().
OSPFLSAHeader::OSPFLSAHeader (const OSPFLSAHeader & other)
virtual OSPFLSAHeader::~OSPFLSAHeader () [virtual]
Member Function Documentation
virtual OSPFLSAHeader* OSPFLSAHeader::dup () const [inline, virtual]
Definition at line 283 of file OSPFPacket_m.h.
{return new OSPFLSAHeader(*this);}
virtual const IPAddress& OSPFLSAHeader::getAdvertisingRouter () const [inline, virtual]
Definition at line 298 of file OSPFPacket_m.h.
Referenced by getAdvertisingRouter().
{return const_cast<OSPFLSAHeader*>(this)->getAdvertisingRouter();}
virtual IPAddress& OSPFLSAHeader::getAdvertisingRouter () [virtual]
Referenced by OSPF::Neighbor::AddToRetransmissionList(), OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::Area::CalculateNextHops(), OSPF::Interface::FloodLSA(), OSPF::Router::InstallASExternalLSA(), OSPF::Area::InstallNetworkLSA(), OSPF::Area::InstallRouterLSA(), OSPF::Area::InstallSummaryLSA(), OSPF::Neighbor::IsLSAOnRequestList(), OSPF::Neighbor::IsLSAOnRetransmissionList(), PrintLSAHeader(), OSPF::DatabaseDescriptionHandler::ProcessDDPacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), OSPF::LinkStateAcknowledgementHandler::ProcessPacket(), and OSPF::Neighbor::SendLinkStateRequestPacket().
virtual unsigned long OSPFLSAHeader::getLinkStateID () const [virtual]
Referenced by OSPF::Neighbor::AddToRetransmissionList(), OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::Area::CalculateNextHops(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Interface::FloodLSA(), OSPF::Area::HasLink(), OSPF::Router::InstallASExternalLSA(), OSPF::Area::InstallNetworkLSA(), OSPF::Area::InstallRouterLSA(), OSPF::Area::InstallSummaryLSA(), OSPF::Router::IsDestinationUnreachable(), OSPF::Neighbor::IsLSAOnRequestList(), OSPF::Neighbor::IsLSAOnRetransmissionList(), OSPF::Area::OriginateSummaryLSA(), PrintLSAHeader(), OSPF::DatabaseDescriptionHandler::ProcessDDPacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), OSPF::LinkStateAcknowledgementHandler::ProcessPacket(), and OSPF::Neighbor::SendLinkStateRequestPacket().
virtual unsigned short OSPFLSAHeader::getLsAge () const [virtual]
Referenced by OSPF::Neighbor::CreateDatabaseSummary(), OSPF::Interface::CreateUpdatePacket(), OSPF::SummaryLSA::DiffersFrom(), OSPF::RouterLSA::DiffersFrom(), OSPF::NetworkLSA::DiffersFrom(), OSPF::ASExternalLSA::DiffersFrom(), operator<(), operator==(), PrintLSAHeader(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual unsigned short OSPFLSAHeader::getLsaLength () const [virtual]
Referenced by OSPF::SummaryLSA::DiffersFrom(), OSPF::RouterLSA::DiffersFrom(), OSPF::NetworkLSA::DiffersFrom(), and OSPF::ASExternalLSA::DiffersFrom().
virtual short OSPFLSAHeader::getLsChecksum () const [virtual]
Referenced by operator<(), and operator==().
virtual const OSPFOptions& OSPFLSAHeader::getLsOptions () const [inline, virtual]
Definition at line 291 of file OSPFPacket_m.h.
Referenced by getLsOptions().
{return const_cast<OSPFLSAHeader*>(this)->getLsOptions();}
virtual OSPFOptions& OSPFLSAHeader::getLsOptions () [virtual]
Referenced by OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), OSPF::SummaryLSA::DiffersFrom(), OSPF::RouterLSA::DiffersFrom(), OSPF::NetworkLSA::DiffersFrom(), and OSPF::ASExternalLSA::DiffersFrom().
virtual long OSPFLSAHeader::getLsSequenceNumber () const [virtual]
Referenced by OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::NeighborState::ChangeState(), OSPF::InterfaceState::ChangeState(), OSPF::Router::GetUniqueLinkStateID(), OSPF::Area::GetUniqueLinkStateID(), operator<(), operator==(), PrintLSAHeader(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::HelloHandler::ProcessPacket().
virtual char OSPFLSAHeader::getLsType () const [virtual]
Referenced by OSPF::Neighbor::AddToRetransmissionList(), OSPF::Area::CreateRoutingTableEntryFromSummaryLSA(), OSPF::Interface::CreateUpdatePacket(), OSPF::Area::FindSameOrWorseCostRoute(), OSPF::Router::FloodLSA(), OSPF::Interface::FloodLSA(), OSPF::Router::InstallLSA(), OSPF::Router::IsDestinationUnreachable(), OSPF::Area::OriginateSummaryLSA(), PrintLSAHeader(), OSPF::DatabaseDescriptionHandler::ProcessDDPacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::SendLinkStateRequestPacket().
OSPFLSAHeader& OSPFLSAHeader::operator= (const OSPFLSAHeader & other)
bool OSPFLSAHeader::operator== (const OSPFLSAHeader &) [protected]
virtual void OSPFLSAHeader::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void OSPFLSAHeader::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void OSPFLSAHeader::setAdvertisingRouter (const IPAddress & advertisingRouter_var) [virtual]
Referenced by OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), and OSPF::Router::UpdateExternalRoute().
virtual void OSPFLSAHeader::setLinkStateID (unsigned long linkStateID_var) [virtual]
Referenced by OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), and OSPF::Router::UpdateExternalRoute().
virtual void OSPFLSAHeader::setLsAge (unsigned short lsAge_var) [virtual]
Referenced by OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::NeighborState::ChangeState(), OSPF::InterfaceState::ChangeState(), OSPF::Interface::CreateUpdatePacket(), OSPF::Router::GetUniqueLinkStateID(), OSPF::Area::GetUniqueLinkStateID(), OSPF::Router::OriginateASExternalLSA(), OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), OSPF::LinkStateUpdateHandler::ProcessPacket(), OSPF::HelloHandler::ProcessPacket(), OSPF::Neighbor::RetransmitUpdatePacket(), and OSPF::Router::UpdateExternalRoute().
virtual void OSPFLSAHeader::setLsaLength (unsigned short lsaLength_var) [virtual]
virtual void OSPFLSAHeader::setLsChecksum (short lsChecksum_var) [virtual]
Referenced by OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::NeighborState::ChangeState(), OSPF::InterfaceState::ChangeState(), OSPF::Router::GetUniqueLinkStateID(), OSPF::Area::GetUniqueLinkStateID(), OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), OSPF::HelloHandler::ProcessPacket(), and OSPF::Router::UpdateExternalRoute().
virtual void OSPFLSAHeader::setLsOptions (const OSPFOptions & lsOptions_var) [virtual]
Referenced by OSPF::Router::OriginateASExternalLSA(), OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), and OSPF::Router::UpdateExternalRoute().
virtual void OSPFLSAHeader::setLsSequenceNumber (long lsSequenceNumber_var) [virtual]
Referenced by OSPF::Router::AgeDatabase(), OSPF::Area::AgeDatabase(), OSPF::NeighborState::ChangeState(), OSPF::InterfaceState::ChangeState(), OSPF::Router::GetUniqueLinkStateID(), OSPF::Area::GetUniqueLinkStateID(), OSPF::Router::OriginateASExternalLSA(), OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), OSPF::LinkStateUpdateHandler::ProcessPacket(), OSPF::HelloHandler::ProcessPacket(), and OSPF::Router::UpdateExternalRoute().
virtual void OSPFLSAHeader::setLsType (char lsType_var) [virtual]
Referenced by OSPF::Area::OriginateNetworkLSA(), OSPF::Area::OriginateRouterLSA(), and OSPF::Router::UpdateExternalRoute().
Member Data Documentation
::IPAddress OSPFLSAHeader::advertisingRouter_var [protected]
Definition at line 270 of file OSPFPacket_m.h.
unsigned long OSPFLSAHeader::linkStateID_var [protected]
Definition at line 269 of file OSPFPacket_m.h.
unsigned short OSPFLSAHeader::lsAge_var [protected]
Definition at line 266 of file OSPFPacket_m.h.
unsigned short OSPFLSAHeader::lsaLength_var [protected]
Definition at line 273 of file OSPFPacket_m.h.
short OSPFLSAHeader::lsChecksum_var [protected]
Definition at line 272 of file OSPFPacket_m.h.
::OSPFOptions OSPFLSAHeader::lsOptions_var [protected]
Definition at line 267 of file OSPFPacket_m.h.
long OSPFLSAHeader::lsSequenceNumber_var [protected]
Definition at line 271 of file OSPFPacket_m.h.
char OSPFLSAHeader::lsType_var [protected]
Definition at line 268 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h