INET Framework for OMNeT++/OMNEST: ICMPv6DestUnreachableMsg Class Reference
ICMPv6DestUnreachableMsg Class Reference
#include <ICMPv6Message_m.h>
Public Member Functions
ICMPv6DestUnreachableMsg (const char *name=NULL, int kind=0)
ICMPv6DestUnreachableMsg (const ICMPv6DestUnreachableMsg &other)
virtual ~ICMPv6DestUnreachableMsg ()
ICMPv6DestUnreachableMsg & operator= (const ICMPv6DestUnreachableMsg &other)
virtual ICMPv6DestUnreachableMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCode () const
virtual void setCode (int code_var)
Protected Member Functions
bool operator== (const ICMPv6DestUnreachableMsg &)
Protected Attributes
int code_var
Detailed Description
Class generated from networklayer/icmpv6/ICMPv6Message.msg by opp_msgc.
 packet ICMPv6DestUnreachableMsg extends ICMPv6Message
 {
     int code enum(ICMPv6DEST_UN);
 }
Definition at line 167 of file ICMPv6Message_m.h.
Constructor & Destructor Documentation
ICMPv6DestUnreachableMsg::ICMPv6DestUnreachableMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPv6DestUnreachableMsg::ICMPv6DestUnreachableMsg (const ICMPv6DestUnreachableMsg & other)
virtual ICMPv6DestUnreachableMsg::~ICMPv6DestUnreachableMsg () [virtual]
Member Function Documentation
virtual ICMPv6DestUnreachableMsg* ICMPv6DestUnreachableMsg::dup () const [inline, virtual]
Reimplemented from ICMPv6Message.
Definition at line 180 of file ICMPv6Message_m.h.
{return new ICMPv6DestUnreachableMsg(*this);}
virtual int ICMPv6DestUnreachableMsg::getCode () const [virtual]
Referenced by IPv6ErrorHandling::handleMessage().
ICMPv6DestUnreachableMsg& ICMPv6DestUnreachableMsg::operator= (const ICMPv6DestUnreachableMsg & other)
Reimplemented from ICMPv6Message.
bool ICMPv6DestUnreachableMsg::operator== (const ICMPv6DestUnreachableMsg &) [protected]
Reimplemented from ICMPv6Message.
virtual void ICMPv6DestUnreachableMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doPacking().
virtual void ICMPv6DestUnreachableMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doUnpacking().
virtual void ICMPv6DestUnreachableMsg::setCode (int code_var) [virtual]
Referenced by ICMPv6::createDestUnreachableMsg().
Member Data Documentation
int ICMPv6DestUnreachableMsg::code_var [protected]
Definition at line 170 of file ICMPv6Message_m.h.
The documentation for this class was generated from the following file:
ICMPv6Message_m.h