INET Framework for OMNeT++/OMNEST: RSVPPathMsg_Base Class Reference
RSVPPathMsg_Base Class Reference
#include <RSVPPathMsg_m.h>
Public Member Functions
virtual ~RSVPPathMsg_Base ()
virtual RSVPPathMsg_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual RsvpHopObj_t & getHop ()
virtual const RsvpHopObj_t & getHop () const
virtual void setHop (const RsvpHopObj_t &hop_var)
virtual LabelRequestObj_t & getLabel_request ()
virtual const LabelRequestObj_t & getLabel_request () const
virtual void setLabel_request (const LabelRequestObj_t &label_request_var)
virtual SenderDescriptor_t & getSender_descriptor ()
virtual const SenderDescriptor_t & getSender_descriptor () const
virtual void setSender_descriptor (const SenderDescriptor_t &sender_descriptor_var)
virtual EroVector & getERO ()
virtual const EroVector & getERO () const
virtual void setERO (const EroVector &ERO_var)
virtual int getColor () const
virtual void setColor (int color_var)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind_var)
Protected Member Functions
bool operator== (const RSVPPathMsg_Base &)
RSVPPathMsg_Base (const char *name=NULL, int kind=0)
RSVPPathMsg_Base (const RSVPPathMsg_Base &other)
RSVPPathMsg_Base & operator= (const RSVPPathMsg_Base &other)
Protected Attributes
::RsvpHopObj_t hop_var
::LabelRequestObj_t label_request_var
::SenderDescriptor_t sender_descriptor_var
::EroVector ERO_var
int color_var
int rsvpKind_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPPathMsg.msg by opp_msgc.
 packet RSVPPathMsg extends RSVPPacket
 {
     (true);
     RsvpHopObj_t hop;
     LabelRequestObj_t label_request;
     SenderDescriptor_t sender_descriptor;
     EroVector ERO;
     int color;
     int rsvpKind = PATH_MESSAGE;
 }
RSVPPathMsg_Base is only useful if it gets subclassed, and RSVPPathMsg is derived from it. The minimum code to be written for RSVPPathMsg is the following:
 class RSVPPathMsg : public RSVPPathMsg_Base
 {
   public:
     RSVPPathMsg(const char *name=NULL, int kind=0) : RSVPPathMsg_Base(name,kind) {}
     RSVPPathMsg(const RSVPPathMsg& other) : RSVPPathMsg_Base(other.getName()) {operator=(other);}
     RSVPPathMsg& operator=(const RSVPPathMsg& other) {RSVPPathMsg_Base::operator=(other); return *this;}
     virtual RSVPPathMsg *dup() const {return new RSVPPathMsg(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPPathMsg_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(RSVPPathMsg);
Definition at line 61 of file RSVPPathMsg_m.h.
Constructor & Destructor Documentation
RSVPPathMsg_Base::RSVPPathMsg_Base (const char * name = NULL, int kind = 0) [protected]
RSVPPathMsg_Base::RSVPPathMsg_Base (const RSVPPathMsg_Base & other) [protected]
virtual RSVPPathMsg_Base::~RSVPPathMsg_Base () [virtual]
Member Function Documentation
virtual RSVPPathMsg_Base* RSVPPathMsg_Base::dup () const [inline, virtual]
Reimplemented from RSVPPacket.
Reimplemented in RSVPPathMsg.
Definition at line 81 of file RSVPPathMsg_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class RSVPPathMsg");}
virtual int RSVPPathMsg_Base::getColor () const [virtual]
Referenced by RSVP::createPSB().
virtual const EroVector& RSVPPathMsg_Base::getERO () const [inline, virtual]
Definition at line 96 of file RSVPPathMsg_m.h.
Referenced by getERO().
{return const_cast<RSVPPathMsg_Base*>(this)->getERO();}
virtual EroVector& RSVPPathMsg_Base::getERO () [virtual]
Referenced by RSVP::createPSB(), RSVP::print(), and RSVP::processPathMsg().
virtual const RsvpHopObj_t& RSVPPathMsg_Base::getHop () const [inline, virtual]
Definition at line 87 of file RSVPPathMsg_m.h.
Referenced by getHop().
{return const_cast<RSVPPathMsg_Base*>(this)->getHop();}
virtual RsvpHopObj_t& RSVPPathMsg_Base::getHop () [virtual]
Referenced by RSVPPathMsg::getLIH(), and RSVPPathMsg::getNHOP().
virtual const LabelRequestObj_t& RSVPPathMsg_Base::getLabel_request () const [inline, virtual]
Definition at line 90 of file RSVPPathMsg_m.h.
Referenced by getLabel_request().
{return const_cast<RSVPPathMsg_Base*>(this)->getLabel_request();}
virtual LabelRequestObj_t& RSVPPathMsg_Base::getLabel_request () [virtual]
virtual int RSVPPathMsg_Base::getRsvpKind () const [virtual]
Reimplemented from RSVPMessage.
virtual const SenderDescriptor_t& RSVPPathMsg_Base::getSender_descriptor () const [inline, virtual]
Definition at line 93 of file RSVPPathMsg_m.h.
Referenced by getSender_descriptor().
{return const_cast<RSVPPathMsg_Base*>(this)->getSender_descriptor();}
virtual SenderDescriptor_t& RSVPPathMsg_Base::getSender_descriptor () [virtual]
Referenced by RSVPPathMsg::getBW(), RSVPPathMsg::getLspId(), RSVPPathMsg::getSenderTemplate(), RSVPPathMsg::getSenderTspec(), RSVPPathMsg::getSrcAddress(), RSVPPathMsg::setSenderTemplate(), and RSVPPathMsg::setSenderTspec().
RSVPPathMsg_Base& RSVPPathMsg_Base::operator= (const RSVPPathMsg_Base & other) [protected]
Reimplemented from RSVPPacket.
Reimplemented in RSVPPathMsg.
bool RSVPPathMsg_Base::operator== (const RSVPPathMsg_Base &) [protected]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathMsg_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathMsg_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathMsg_Base::setColor (int color_var) [virtual]
virtual void RSVPPathMsg_Base::setERO (const EroVector & ERO_var) [virtual]
Referenced by RSVP::processPathMsg().
virtual void RSVPPathMsg_Base::setHop (const RsvpHopObj_t & hop_var) [virtual]
virtual void RSVPPathMsg_Base::setLabel_request (const LabelRequestObj_t & label_request_var) [virtual]
virtual void RSVPPathMsg_Base::setRsvpKind (int rsvpKind_var) [virtual]
Reimplemented from RSVPMessage.
virtual void RSVPPathMsg_Base::setSender_descriptor (const SenderDescriptor_t & sender_descriptor_var) [virtual]
Member Data Documentation
int RSVPPathMsg_Base::color_var [protected]
Definition at line 68 of file RSVPPathMsg_m.h.
::EroVector RSVPPathMsg_Base::ERO_var [protected]
Definition at line 67 of file RSVPPathMsg_m.h.
::RsvpHopObj_t RSVPPathMsg_Base::hop_var [protected]
Definition at line 64 of file RSVPPathMsg_m.h.
::LabelRequestObj_t RSVPPathMsg_Base::label_request_var [protected]
Definition at line 65 of file RSVPPathMsg_m.h.
int RSVPPathMsg_Base::rsvpKind_var [protected]
Reimplemented from RSVPMessage.
Definition at line 69 of file RSVPPathMsg_m.h.
::SenderDescriptor_t RSVPPathMsg_Base::sender_descriptor_var [protected]
Definition at line 66 of file RSVPPathMsg_m.h.
The documentation for this class was generated from the following file:
RSVPPathMsg_m.h