INET Framework for OMNeT++/OMNEST: SCTPErrorInfo Class Reference
SCTPErrorInfo Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPErrorInfo (const char *name=NULL)
SCTPErrorInfo (const SCTPErrorInfo &other)
virtual ~SCTPErrorInfo ()
SCTPErrorInfo & operator= (const SCTPErrorInfo &other)
virtual SCTPErrorInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getErrorCode () const
virtual void setErrorCode (int errorCode_var)
virtual const char * getMessageText () const
virtual void setMessageText (const char *messageText_var)
Protected Member Functions
bool operator== (const SCTPErrorInfo &)
Protected Attributes
int errorCode_var
opp_string messageText_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPErrorInfo extends SCTPCommand
 {
     int errorCode enum(SCTPErrorCode);
     string messageText;
 }
Definition at line 115 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPErrorInfo::SCTPErrorInfo (const char * name = NULL)
Referenced by dup().
SCTPErrorInfo::SCTPErrorInfo (const SCTPErrorInfo & other)
virtual SCTPErrorInfo::~SCTPErrorInfo () [virtual]
Member Function Documentation
virtual SCTPErrorInfo* SCTPErrorInfo::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 129 of file SCTPCommand_m.h.
{return new SCTPErrorInfo(*this);}
virtual int SCTPErrorInfo::getErrorCode () const [virtual]
virtual const char* SCTPErrorInfo::getMessageText () const [virtual]
SCTPErrorInfo& SCTPErrorInfo::operator= (const SCTPErrorInfo & other)
Reimplemented from SCTPCommand.
bool SCTPErrorInfo::operator== (const SCTPErrorInfo &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPErrorInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPErrorInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPErrorInfo::setErrorCode (int errorCode_var) [virtual]
virtual void SCTPErrorInfo::setMessageText (const char * messageText_var) [virtual]
Member Data Documentation
int SCTPErrorInfo::errorCode_var [protected]
Definition at line 118 of file SCTPCommand_m.h.
opp_string SCTPErrorInfo::messageText_var [protected]
Definition at line 119 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h