INET Framework for OMNeT++/OMNEST: Ieee80211DataOrMgmtFrame Class Reference
Ieee80211DataOrMgmtFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211DataOrMgmtFrame (const char *name=NULL, int kind=0)
Ieee80211DataOrMgmtFrame (const Ieee80211DataOrMgmtFrame &other)
virtual ~Ieee80211DataOrMgmtFrame ()
Ieee80211DataOrMgmtFrame & operator= (const Ieee80211DataOrMgmtFrame &other)
virtual Ieee80211DataOrMgmtFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getAddress3 ()
virtual const MACAddress & getAddress3 () const
virtual void setAddress3 (const MACAddress &address3_var)
virtual short getFragmentNumber () const
virtual void setFragmentNumber (short fragmentNumber_var)
virtual short getSequenceNumber () const
virtual void setSequenceNumber (short sequenceNumber_var)
Protected Member Functions
bool operator== (const Ieee80211DataOrMgmtFrame &)
Protected Attributes
::MACAddress address3_var
short fragmentNumber_var
short sequenceNumber_var
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211DataOrMgmtFrame extends Ieee80211TwoAddressFrame
 {
     byteLength = 28;
     MACAddress address3;
     short fragmentNumber;
     short sequenceNumber;
 }
Definition at line 308 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211DataOrMgmtFrame::Ieee80211DataOrMgmtFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211DataOrMgmtFrame::Ieee80211DataOrMgmtFrame (const Ieee80211DataOrMgmtFrame & other)
virtual Ieee80211DataOrMgmtFrame::~Ieee80211DataOrMgmtFrame () [virtual]
Member Function Documentation
virtual Ieee80211DataOrMgmtFrame* Ieee80211DataOrMgmtFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211TwoAddressFrame.
Reimplemented in Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Definition at line 323 of file Ieee80211Frame_m.h.
Referenced by Ieee80211Mac::buildBroadcastFrame(), and Ieee80211Mac::buildDataFrame().
{return new Ieee80211DataOrMgmtFrame(*this);}
virtual const MACAddress& Ieee80211DataOrMgmtFrame::getAddress3 () const [inline, virtual]
Definition at line 329 of file Ieee80211Frame_m.h.
Referenced by getAddress3().
{return const_cast<Ieee80211DataOrMgmtFrame*>(this)->getAddress3();}
virtual MACAddress& Ieee80211DataOrMgmtFrame::getAddress3 () [virtual]
Referenced by Ieee80211MgmtAPBase::convertToEtherFrame(), Ieee80211MgmtBase::decapsulate(), Ieee80211MgmtAPBase::distributeReceivedDataFrame(), Ieee80211MgmtAP::handleDataFrame(), Ieee80211MgmtSTA::handleDeauthenticationFrame(), and Ieee80211MgmtSTA::handleDisassociationFrame().
virtual short Ieee80211DataOrMgmtFrame::getFragmentNumber () const [virtual]
virtual short Ieee80211DataOrMgmtFrame::getSequenceNumber () const [virtual]
Ieee80211DataOrMgmtFrame& Ieee80211DataOrMgmtFrame::operator= (const Ieee80211DataOrMgmtFrame & other)
Reimplemented from Ieee80211TwoAddressFrame.
Reimplemented in Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
bool Ieee80211DataOrMgmtFrame::operator== (const Ieee80211DataOrMgmtFrame &) [protected]
Reimplemented from Ieee80211TwoAddressFrame.
Reimplemented in Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
virtual void Ieee80211DataOrMgmtFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211TwoAddressFrame.
Reimplemented in Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doPacking().
virtual void Ieee80211DataOrMgmtFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211TwoAddressFrame.
Reimplemented in Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doUnpacking().
virtual void Ieee80211DataOrMgmtFrame::setAddress3 (const MACAddress & address3_var) [virtual]
Referenced by Ieee80211MgmtAPBase::convertFromEtherFrame(), Ieee80211MgmtAPBase::distributeReceivedDataFrame(), Ieee80211MgmtSTASimplified::encapsulate(), Ieee80211MgmtSTA::encapsulate(), and Ieee80211MgmtAP::sendManagementFrame().
virtual void Ieee80211DataOrMgmtFrame::setFragmentNumber (short fragmentNumber_var) [virtual]
virtual void Ieee80211DataOrMgmtFrame::setSequenceNumber (short sequenceNumber_var) [virtual]
Referenced by Ieee80211Mac::handleUpperMsg().
Member Data Documentation
::MACAddress Ieee80211DataOrMgmtFrame::address3_var [protected]
Definition at line 311 of file Ieee80211Frame_m.h.
short Ieee80211DataOrMgmtFrame::fragmentNumber_var [protected]
Definition at line 312 of file Ieee80211Frame_m.h.
short Ieee80211DataOrMgmtFrame::sequenceNumber_var [protected]
Definition at line 313 of file Ieee80211Frame_m.h.
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h