INET Framework for OMNeT++/OMNEST: SCTPStatusInfo Class Reference
SCTPStatusInfo Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPStatusInfo (const char *name=NULL)
SCTPStatusInfo (const SCTPStatusInfo &other)
virtual ~SCTPStatusInfo ()
SCTPStatusInfo & operator= (const SCTPStatusInfo &other)
virtual SCTPStatusInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getState () const
virtual void setState (int state_var)
virtual const char * getStateName () const
virtual void setStateName (const char *stateName_var)
virtual IPvXAddress & getPathId ()
virtual const IPvXAddress & getPathId () const
virtual void setPathId (const IPvXAddress &pathId_var)
virtual bool getActive () const
virtual void setActive (bool active_var)
Protected Member Functions
bool operator== (const SCTPStatusInfo &)
Protected Attributes
int state_var
opp_string stateName_var
::IPvXAddress pathId_var
bool active_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPStatusInfo extends SCTPCommand
 {
     int state;
     string stateName;
     IPvXAddress pathId;
     bool active;
 }
Definition at line 336 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPStatusInfo::SCTPStatusInfo (const char * name = NULL)
Referenced by dup().
SCTPStatusInfo::SCTPStatusInfo (const SCTPStatusInfo & other)
virtual SCTPStatusInfo::~SCTPStatusInfo () [virtual]
Member Function Documentation
virtual SCTPStatusInfo* SCTPStatusInfo::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 352 of file SCTPCommand_m.h.
{return new SCTPStatusInfo(*this);}
virtual bool SCTPStatusInfo::getActive () const [virtual]
Referenced by SCTPPeer::socketStatusArrived(), and SCTPClient::socketStatusArrived().
virtual const IPvXAddress& SCTPStatusInfo::getPathId () const [inline, virtual]
Definition at line 362 of file SCTPCommand_m.h.
Referenced by getPathId().
{return const_cast<SCTPStatusInfo*>(this)->getPathId();}
virtual IPvXAddress& SCTPStatusInfo::getPathId () [virtual]
Referenced by SCTPPeer::socketStatusArrived(), and SCTPClient::socketStatusArrived().
virtual int SCTPStatusInfo::getState () const [virtual]
virtual const char* SCTPStatusInfo::getStateName () const [virtual]
SCTPStatusInfo& SCTPStatusInfo::operator= (const SCTPStatusInfo & other)
Reimplemented from SCTPCommand.
bool SCTPStatusInfo::operator== (const SCTPStatusInfo &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPStatusInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPStatusInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPStatusInfo::setActive (bool active_var) [virtual]
Referenced by SCTPAssociation::pathStatusIndication(), and SCTPAssociation::process_STATUS().
virtual void SCTPStatusInfo::setPathId (const IPvXAddress & pathId_var) [virtual]
Referenced by SCTPAssociation::pathStatusIndication(), and SCTPAssociation::process_STATUS().
virtual void SCTPStatusInfo::setState (int state_var) [virtual]
Referenced by SCTPAssociation::process_STATUS().
virtual void SCTPStatusInfo::setStateName (const char * stateName_var) [virtual]
Referenced by SCTPAssociation::process_STATUS().
Member Data Documentation
bool SCTPStatusInfo::active_var [protected]
Definition at line 342 of file SCTPCommand_m.h.
::IPvXAddress SCTPStatusInfo::pathId_var [protected]
Definition at line 341 of file SCTPCommand_m.h.
int SCTPStatusInfo::state_var [protected]
Definition at line 339 of file SCTPCommand_m.h.
opp_string SCTPStatusInfo::stateName_var [protected]
Definition at line 340 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h