INET Framework for OMNeT++/OMNEST: RTPMpegPacket Class Reference
RTPMpegPacket Class Reference
#include <RTPMpegPacket_m.h>
Public Member Functions
RTPMpegPacket (const char *name=NULL, int kind=0)
RTPMpegPacket (const RTPMpegPacket &other)
virtual ~RTPMpegPacket ()
RTPMpegPacket & operator= (const RTPMpegPacket &other)
virtual RTPMpegPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getHeaderLength () const
virtual void setHeaderLength (int headerLength_var)
virtual int getPayloadLength () const
virtual void setPayloadLength (int payloadLength_var)
virtual int getPictureType () const
virtual void setPictureType (int pictureType_var)
Protected Member Functions
bool operator== (const RTPMpegPacket &)
Protected Attributes
int headerLength_var
int payloadLength_var
int pictureType_var
Detailed Description
Class generated from transport/rtp/profiles/avprofile/RTPMpegPacket.msg by opp_msgc.
 packet RTPMpegPacket
 {
     int headerLength = 4;
     int payloadLength;
     int pictureType;
 }
Definition at line 48 of file RTPMpegPacket_m.h.
Constructor & Destructor Documentation
RTPMpegPacket::RTPMpegPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
RTPMpegPacket::RTPMpegPacket (const RTPMpegPacket & other)
virtual RTPMpegPacket::~RTPMpegPacket () [virtual]
Member Function Documentation
virtual RTPMpegPacket* RTPMpegPacket::dup () const [inline, virtual]
Definition at line 63 of file RTPMpegPacket_m.h.
{return new RTPMpegPacket(*this);}
virtual int RTPMpegPacket::getHeaderLength () const [virtual]
virtual int RTPMpegPacket::getPayloadLength () const [virtual]
Referenced by RTPAVProfilePayload32Receiver::processPacket().
virtual int RTPMpegPacket::getPictureType () const [virtual]
Referenced by RTPAVProfilePayload32Receiver::processPacket().
RTPMpegPacket& RTPMpegPacket::operator= (const RTPMpegPacket & other)
bool RTPMpegPacket::operator== (const RTPMpegPacket &) [protected]
virtual void RTPMpegPacket::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void RTPMpegPacket::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void RTPMpegPacket::setHeaderLength (int headerLength_var) [virtual]
virtual void RTPMpegPacket::setPayloadLength (int payloadLength_var) [virtual]
virtual void RTPMpegPacket::setPictureType (int pictureType_var) [virtual]
Referenced by RTPAVProfilePayload32Sender::sendPacket().
Member Data Documentation
int RTPMpegPacket::headerLength_var [protected]
Definition at line 51 of file RTPMpegPacket_m.h.
int RTPMpegPacket::payloadLength_var [protected]
Definition at line 52 of file RTPMpegPacket_m.h.
int RTPMpegPacket::pictureType_var [protected]
Definition at line 53 of file RTPMpegPacket_m.h.
The documentation for this class was generated from the following file:
RTPMpegPacket_m.h