INET Framework for OMNeT++/OMNEST: RSVPResvError_Base Class Reference
RSVPResvError_Base Class Reference
#include <RSVPResvMsg_m.h>
Public Member Functions
virtual ~RSVPResvError_Base ()
virtual RSVPResvError_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual RsvpHopObj_t & getHop ()
virtual const RsvpHopObj_t & getHop () const
virtual void setHop (const RsvpHopObj_t &hop_var)
virtual IPAddress & getErrorNode ()
virtual const IPAddress & getErrorNode () const
virtual void setErrorNode (const IPAddress &errorNode_var)
virtual int getErrorCode () const
virtual void setErrorCode (int errorCode_var)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind_var)
Protected Member Functions
bool operator== (const RSVPResvError_Base &)
RSVPResvError_Base (const char *name=NULL, int kind=0)
RSVPResvError_Base (const RSVPResvError_Base &other)
RSVPResvError_Base & operator= (const RSVPResvError_Base &other)
Protected Attributes
::RsvpHopObj_t hop_var
::IPAddress errorNode_var
int errorCode_var
int rsvpKind_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPResvMsg.msg by opp_msgc.
 packet RSVPResvError extends RSVPPacket
 {
     (true);
     RsvpHopObj_t hop;
     IPAddress errorNode;
     int errorCode;
     int rsvpKind = RERROR_MESSAGE;
 }
RSVPResvError_Base is only useful if it gets subclassed, and RSVPResvError is derived from it. The minimum code to be written for RSVPResvError is the following:
 class RSVPResvError : public RSVPResvError_Base
 {
   public:
     RSVPResvError(const char *name=NULL, int kind=0) : RSVPResvError_Base(name,kind) {}
     RSVPResvError(const RSVPResvError& other) : RSVPResvError_Base(other.getName()) {operator=(other);}
     RSVPResvError& operator=(const RSVPResvError& other) {RSVPResvError_Base::operator=(other); return *this;}
     virtual RSVPResvError *dup() const {return new RSVPResvError(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPResvError_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(RSVPResvError);
Definition at line 188 of file RSVPResvMsg_m.h.
Constructor & Destructor Documentation
RSVPResvError_Base::RSVPResvError_Base (const char * name = NULL, int kind = 0) [protected]
RSVPResvError_Base::RSVPResvError_Base (const RSVPResvError_Base & other) [protected]
virtual RSVPResvError_Base::~RSVPResvError_Base () [virtual]
Member Function Documentation
virtual RSVPResvError_Base* RSVPResvError_Base::dup () const [inline, virtual]
Reimplemented from RSVPPacket.
Reimplemented in RSVPResvError.
Definition at line 206 of file RSVPResvMsg_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class RSVPResvError");}
virtual int RSVPResvError_Base::getErrorCode () const [virtual]
virtual const IPAddress& RSVPResvError_Base::getErrorNode () const [inline, virtual]
Definition at line 215 of file RSVPResvMsg_m.h.
Referenced by getErrorNode().
{return const_cast<RSVPResvError_Base*>(this)->getErrorNode();}
virtual IPAddress& RSVPResvError_Base::getErrorNode () [virtual]
virtual const RsvpHopObj_t& RSVPResvError_Base::getHop () const [inline, virtual]
Definition at line 212 of file RSVPResvMsg_m.h.
Referenced by getHop().
{return const_cast<RSVPResvError_Base*>(this)->getHop();}
virtual RsvpHopObj_t& RSVPResvError_Base::getHop () [virtual]
Referenced by RSVPResvError::getLIH(), and RSVPResvError::getNHOP().
virtual int RSVPResvError_Base::getRsvpKind () const [virtual]
Reimplemented from RSVPMessage.
RSVPResvError_Base& RSVPResvError_Base::operator= (const RSVPResvError_Base & other) [protected]
Reimplemented from RSVPPacket.
Reimplemented in RSVPResvError.
bool RSVPResvError_Base::operator== (const RSVPResvError_Base &) [protected]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvError_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvError_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPResvError_Base::setErrorCode (int errorCode_var) [virtual]
virtual void RSVPResvError_Base::setErrorNode (const IPAddress & errorNode_var) [virtual]
virtual void RSVPResvError_Base::setHop (const RsvpHopObj_t & hop_var) [virtual]
virtual void RSVPResvError_Base::setRsvpKind (int rsvpKind_var) [virtual]
Reimplemented from RSVPMessage.
Member Data Documentation
int RSVPResvError_Base::errorCode_var [protected]
Definition at line 193 of file RSVPResvMsg_m.h.
::IPAddress RSVPResvError_Base::errorNode_var [protected]
Definition at line 192 of file RSVPResvMsg_m.h.
::RsvpHopObj_t RSVPResvError_Base::hop_var [protected]
Definition at line 191 of file RSVPResvMsg_m.h.
int RSVPResvError_Base::rsvpKind_var [protected]
Reimplemented from RSVPMessage.
Definition at line 194 of file RSVPResvMsg_m.h.
The documentation for this class was generated from the following file:
RSVPResvMsg_m.h