INET Framework for OMNeT++/OMNEST: SCTPAbortChunk Class Reference
SCTPAbortChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPAbortChunk (const char *name=NULL, int kind=0)
SCTPAbortChunk (const SCTPAbortChunk &other)
virtual ~SCTPAbortChunk ()
SCTPAbortChunk & operator= (const SCTPAbortChunk &other)
virtual SCTPAbortChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getT_Bit () const
virtual void setT_Bit (bool T_Bit_var)
Protected Member Functions
bool operator== (const SCTPAbortChunk &)
Protected Attributes
bool T_Bit_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPAbortChunk extends SCTPChunk
 {
      bool T_Bit = 0;
 }
Definition at line 765 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPAbortChunk::SCTPAbortChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPAbortChunk::SCTPAbortChunk (const SCTPAbortChunk & other)
virtual SCTPAbortChunk::~SCTPAbortChunk () [virtual]
Member Function Documentation
virtual SCTPAbortChunk* SCTPAbortChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 778 of file SCTPMessage_m.h.
{return new SCTPAbortChunk(*this);}
virtual bool SCTPAbortChunk::getT_Bit () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), TCPDumper::sctpDump(), and SCTPAssociation::sendToIP().
SCTPAbortChunk& SCTPAbortChunk::operator= (const SCTPAbortChunk & other)
Reimplemented from SCTPChunk.
bool SCTPAbortChunk::operator== (const SCTPAbortChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPAbortChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPAbortChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPAbortChunk::setT_Bit (bool T_Bit_var) [virtual]
Referenced by SCTPAssociation::sendAbort(), and SCTP::sendAbortFromMain().
Member Data Documentation
bool SCTPAbortChunk::T_Bit_var [protected]
Definition at line 768 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h