INET Framework for OMNeT++/OMNEST: RTPSenderControlMessage Class Reference
RTPSenderControlMessage Class Reference
#include <RTPSenderControlMessage_m.h>
Public Member Functions
RTPSenderControlMessage (const char *name=NULL, int kind=0)
RTPSenderControlMessage (const RTPSenderControlMessage &other)
virtual ~RTPSenderControlMessage ()
RTPSenderControlMessage & operator= (const RTPSenderControlMessage &other)
virtual RTPSenderControlMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getCommand () const
virtual void setCommand (const char *command_var)
virtual float getCommandParameter1 () const
virtual void setCommandParameter1 (float commandParameter1_var)
virtual float getCommandParameter2 () const
virtual void setCommandParameter2 (float commandParameter2_var)
Protected Member Functions
bool operator== (const RTPSenderControlMessage &)
Protected Attributes
opp_string command_var
float commandParameter1_var
float commandParameter2_var
Detailed Description
Class generated from transport/rtp/RTPSenderControlMessage.msg by opp_msgc.
 packet RTPSenderControlMessage
 {
     string command;
     float commandParameter1;
     float commandParameter2;
 };
Definition at line 34 of file RTPSenderControlMessage_m.h.
Constructor & Destructor Documentation
RTPSenderControlMessage::RTPSenderControlMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
RTPSenderControlMessage::RTPSenderControlMessage (const RTPSenderControlMessage & other)
virtual RTPSenderControlMessage::~RTPSenderControlMessage () [virtual]
Member Function Documentation
virtual RTPSenderControlMessage* RTPSenderControlMessage::dup () const [inline, virtual]
Definition at line 49 of file RTPSenderControlMessage_m.h.
{return new RTPSenderControlMessage(*this);}
virtual const char* RTPSenderControlMessage::getCommand () const [virtual]
Referenced by RTPPayloadSender::activity().
virtual float RTPSenderControlMessage::getCommandParameter1 () const [virtual]
Referenced by RTPPayloadSender::activity().
virtual float RTPSenderControlMessage::getCommandParameter2 () const [virtual]
RTPSenderControlMessage& RTPSenderControlMessage::operator= (const RTPSenderControlMessage & other)
bool RTPSenderControlMessage::operator== (const RTPSenderControlMessage &) [protected]
virtual void RTPSenderControlMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void RTPSenderControlMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void RTPSenderControlMessage::setCommand (const char * command_var) [virtual]
Referenced by RTPApplication::activity().
virtual void RTPSenderControlMessage::setCommandParameter1 (float commandParameter1_var) [virtual]
virtual void RTPSenderControlMessage::setCommandParameter2 (float commandParameter2_var) [virtual]
Member Data Documentation
opp_string RTPSenderControlMessage::command_var [protected]
Definition at line 37 of file RTPSenderControlMessage_m.h.
float RTPSenderControlMessage::commandParameter1_var [protected]
Definition at line 38 of file RTPSenderControlMessage_m.h.
float RTPSenderControlMessage::commandParameter2_var [protected]
Definition at line 39 of file RTPSenderControlMessage_m.h.
The documentation for this class was generated from the following file:
RTPSenderControlMessage_m.h