INET Framework for OMNeT++/OMNEST: LDPIni Class Reference
LDPIni Class Reference
#include <LDPPacket_m.h>
Public Member Functions
LDPIni (const char *name=NULL, int kind=0)
LDPIni (const LDPIni &other)
virtual ~LDPIni ()
LDPIni & operator= (const LDPIni &other)
virtual LDPIni * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual double getKeepAliveTime () const
virtual void setKeepAliveTime (double keepAliveTime_var)
virtual bool getAbit () const
virtual void setAbit (bool abit_var)
virtual bool getDbit () const
virtual void setDbit (bool dbit_var)
virtual int getPvLim () const
virtual void setPvLim (int pvLim_var)
virtual const char * getReceiverLDPIdentifier () const
virtual void setReceiverLDPIdentifier (const char *receiverLDPIdentifier_var)
Protected Member Functions
bool operator== (const LDPIni &)
Protected Attributes
double keepAliveTime_var
bool abit_var
bool dbit_var
int pvLim_var
opp_string receiverLDPIdentifier_var
Detailed Description
Class generated from networklayer/ldp/LDPPacket.msg by opp_msgc.
 packet LDPIni extends LDPPacket
 {
     double keepAliveTime;
     bool abit;
     bool dbit;
     int pvLim;
     string receiverLDPIdentifier;
 }
Definition at line 303 of file LDPPacket_m.h.
Constructor & Destructor Documentation
LDPIni::LDPIni (const char * name = NULL, int kind = 0)
Referenced by dup().
LDPIni::LDPIni (const LDPIni & other)
virtual LDPIni::~LDPIni () [virtual]
Member Function Documentation
virtual LDPIni* LDPIni::dup () const [inline, virtual]
Reimplemented from LDPPacket.
Definition at line 320 of file LDPPacket_m.h.
{return new LDPIni(*this);}
virtual bool LDPIni::getAbit () const [virtual]
virtual bool LDPIni::getDbit () const [virtual]
virtual double LDPIni::getKeepAliveTime () const [virtual]
virtual int LDPIni::getPvLim () const [virtual]
virtual const char* LDPIni::getReceiverLDPIdentifier () const [virtual]
LDPIni& LDPIni::operator= (const LDPIni & other)
Reimplemented from LDPPacket.
bool LDPIni::operator== (const LDPIni &) [protected]
Reimplemented from LDPPacket.
virtual void LDPIni::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doPacking().
virtual void LDPIni::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doUnpacking().
virtual void LDPIni::setAbit (bool abit_var) [virtual]
virtual void LDPIni::setDbit (bool dbit_var) [virtual]
virtual void LDPIni::setKeepAliveTime (double keepAliveTime_var) [virtual]
virtual void LDPIni::setPvLim (int pvLim_var) [virtual]
virtual void LDPIni::setReceiverLDPIdentifier (const char * receiverLDPIdentifier_var) [virtual]
Member Data Documentation
bool LDPIni::abit_var [protected]
Definition at line 307 of file LDPPacket_m.h.
bool LDPIni::dbit_var [protected]
Definition at line 308 of file LDPPacket_m.h.
double LDPIni::keepAliveTime_var [protected]
Definition at line 306 of file LDPPacket_m.h.
int LDPIni::pvLim_var [protected]
Definition at line 309 of file LDPPacket_m.h.
opp_string LDPIni::receiverLDPIdentifier_var [protected]
Definition at line 310 of file LDPPacket_m.h.
The documentation for this class was generated from the following file:
LDPPacket_m.h