INET Framework for OMNeT++/OMNEST: OSPF::SummaryLSA Class Reference
OSPF::SummaryLSA Class Reference
#include <LSA.h>
Public Member Functions
SummaryLSA (void)
SummaryLSA (const OSPFSummaryLSA &lsa)
SummaryLSA (const SummaryLSA &lsa)
virtual ~SummaryLSA (void)
bool GetPurgeable (void) const
void SetPurgeable (bool purge=true)
bool ValidateLSChecksum () const
bool Update (const OSPFSummaryLSA *lsa)
bool DiffersFrom (const OSPFSummaryLSA *summaryLSA) const
Protected Attributes
bool purgeable
Detailed Description
Definition at line 113 of file LSA.h.
Constructor & Destructor Documentation
OSPF::SummaryLSA::SummaryLSA (void) [inline]
Definition at line 120 of file LSA.h.
: OSPFSummaryLSA(), RoutingInfo(), LSATrackingInfo(), purgeable(false) {}
OSPF::SummaryLSA::SummaryLSA (const OSPFSummaryLSA & lsa) [inline]
Definition at line 121 of file LSA.h.
: OSPFSummaryLSA(lsa), RoutingInfo(), LSATrackingInfo(), purgeable(false) {}
OSPF::SummaryLSA::SummaryLSA (const SummaryLSA & lsa) [inline]
Definition at line 122 of file LSA.h.
: OSPFSummaryLSA(lsa), RoutingInfo(lsa), LSATrackingInfo(lsa), purgeable(lsa.purgeable) {}
virtual OSPF::SummaryLSA::~SummaryLSA (void) [inline, virtual]
Definition at line 123 of file LSA.h.
{}
Member Function Documentation
bool OSPF::SummaryLSA::DiffersFrom (const OSPFSummaryLSA * summaryLSA) const
Definition at line 33 of file SummaryLSA.cc.
Referenced by Update().
{
    const OSPFLSAHeader& lsaHeader = summaryLSA->getHeader();
    bool differentHeader = ((header_var.getLsOptions() != lsaHeader.getLsOptions()) ||
                            ((header_var.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                            ((header_var.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                            (header_var.getLsaLength() != lsaHeader.getLsaLength()));
    bool differentBody   = false;
    if (!differentHeader) {
        differentBody = ((networkMask_var != summaryLSA->getNetworkMask()) ||
                         (routeCost_var != summaryLSA->getRouteCost()) ||
                         (tosData_arraysize != summaryLSA->getTosDataArraySize()));
        if (!differentBody) {
            unsigned int tosCount = tosData_arraysize;
            for (unsigned int i = 0; i < tosCount; i++) {
                if ((tosData_var[i].tos != summaryLSA->getTosData(i).tos) ||
                    (tosData_var[i].tosMetric[0] != summaryLSA->getTosData(i).tosMetric[0]) ||
                    (tosData_var[i].tosMetric[1] != summaryLSA->getTosData(i).tosMetric[1]) ||
                    (tosData_var[i].tosMetric[2] != summaryLSA->getTosData(i).tosMetric[2]))
                {
                    differentBody = true;
                    break;
                }
            }
        }
    }
    return (differentHeader || differentBody);
}
bool OSPF::SummaryLSA::GetPurgeable (void) const [inline]
Definition at line 125 of file LSA.h.
{ return purgeable; }
void OSPF::SummaryLSA::SetPurgeable (bool purge = true) [inline]
Definition at line 126 of file LSA.h.
{ purgeable = purge; }
bool OSPF::SummaryLSA::Update (const OSPFSummaryLSA * lsa)
Definition at line 20 of file SummaryLSA.cc.
Referenced by OSPF::Area::AgeDatabase().
{
    bool different = DiffersFrom(lsa);
    (*this) = (*lsa);
    ResetInstallTime();
    if (different) {
        ClearNextHops();
        return true;
    } else {
        return false;
    }
}
bool OSPF::SummaryLSA::ValidateLSChecksum () const [inline]
Definition at line 128 of file LSA.h.
Referenced by OSPF::Area::AgeDatabase().
{ return true; } // not implemented
Member Data Documentation
bool OSPF::SummaryLSA::purgeable [protected]
Definition at line 118 of file LSA.h.
Referenced by GetPurgeable(), and SetPurgeable().
The documentation for this class was generated from the following files:
LSA.h
SummaryLSA.cc