INET Framework for OMNeT++/OMNEST: ICMPv6Message Class Reference
ICMPv6Message Class Reference
#include <ICMPv6Message_m.h>
Public Member Functions
ICMPv6Message (const char *name=NULL, int kind=0)
ICMPv6Message (const ICMPv6Message &other)
virtual ~ICMPv6Message ()
ICMPv6Message & operator= (const ICMPv6Message &other)
virtual ICMPv6Message * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type_var)
Protected Member Functions
bool operator== (const ICMPv6Message &)
Protected Attributes
int type_var
Detailed Description
Class generated from networklayer/icmpv6/ICMPv6Message.msg by opp_msgc.
 packet ICMPv6Message
 {
     int type enum(ICMPv6Type);
 }
Definition at line 133 of file ICMPv6Message_m.h.
Constructor & Destructor Documentation
ICMPv6Message::ICMPv6Message (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPv6Message::ICMPv6Message (const ICMPv6Message & other)
virtual ICMPv6Message::~ICMPv6Message () [virtual]
Member Function Documentation
virtual ICMPv6Message* ICMPv6Message::dup () const [inline, virtual]
Reimplemented in ICMPv6DestUnreachableMsg, ICMPv6PacketTooBigMsg, ICMPv6TimeExceededMsg, ICMPv6ParamProblemMsg, ICMPv6EchoRequestMsg, ICMPv6EchoReplyMsg, IPv6NDMessage, IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
Definition at line 146 of file ICMPv6Message_m.h.
{return new ICMPv6Message(*this);}
virtual int ICMPv6Message::getType () const [virtual]
Referenced by IPv6ErrorHandling::handleMessage(), IPv6::handleReceivedICMP(), UDP::processICMPError(), and ICMPv6::validateDatagramPromptingError().
ICMPv6Message& ICMPv6Message::operator= (const ICMPv6Message & other)
Reimplemented in ICMPv6DestUnreachableMsg, ICMPv6PacketTooBigMsg, ICMPv6TimeExceededMsg, ICMPv6ParamProblemMsg, ICMPv6EchoRequestMsg, ICMPv6EchoReplyMsg, IPv6NDMessage, IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
bool ICMPv6Message::operator== (const ICMPv6Message &) [protected]
Reimplemented in ICMPv6DestUnreachableMsg, ICMPv6PacketTooBigMsg, ICMPv6TimeExceededMsg, ICMPv6ParamProblemMsg, ICMPv6EchoRequestMsg, ICMPv6EchoReplyMsg, IPv6NDMessage, IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
virtual void ICMPv6Message::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in ICMPv6DestUnreachableMsg, ICMPv6PacketTooBigMsg, ICMPv6TimeExceededMsg, ICMPv6ParamProblemMsg, ICMPv6EchoRequestMsg, ICMPv6EchoReplyMsg, IPv6NDMessage, IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
Referenced by doPacking().
virtual void ICMPv6Message::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in ICMPv6DestUnreachableMsg, ICMPv6PacketTooBigMsg, ICMPv6TimeExceededMsg, ICMPv6ParamProblemMsg, ICMPv6EchoRequestMsg, ICMPv6EchoReplyMsg, IPv6NDMessage, IPv6RouterSolicitation, IPv6RouterAdvertisement, IPv6NeighbourSolicitation, IPv6NeighbourAdvertisement, and IPv6Redirect.
Referenced by doUnpacking().
virtual void ICMPv6Message::setType (int type_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendNSPacket(), IPv6NeighbourDiscovery::createAndSendRAPacket(), IPv6NeighbourDiscovery::createAndSendRedirectPacket(), IPv6NeighbourDiscovery::createAndSendRSPacket(), ICMPv6::createDestUnreachableMsg(), ICMPv6::createPacketTooBigMsg(), ICMPv6::createParamProblemMsg(), ICMPv6::createTimeExceededMsg(), ICMPv6::processEchoRequest(), and ICMPv6::sendEchoRequest().
Member Data Documentation
int ICMPv6Message::type_var [protected]
Definition at line 136 of file ICMPv6Message_m.h.
The documentation for this class was generated from the following file:
ICMPv6Message_m.h