INET Framework for OMNeT++/OMNEST: SCTPSackChunk Class Reference
SCTPSackChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPSackChunk (const char *name=NULL, int kind=0)
SCTPSackChunk (const SCTPSackChunk &other)
virtual ~SCTPSackChunk ()
SCTPSackChunk & operator= (const SCTPSackChunk &other)
virtual SCTPSackChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32 getCumTsnAck () const
virtual void setCumTsnAck (uint32 cumTsnAck_var)
virtual uint32 getA_rwnd () const
virtual void setA_rwnd (uint32 a_rwnd_var)
virtual uint16 getNumGaps () const
virtual void setNumGaps (uint16 numGaps_var)
virtual uint16 getNumDupTsns () const
virtual void setNumDupTsns (uint16 numDupTsns_var)
virtual void setGapStartArraySize (unsigned int size)
virtual unsigned int getGapStartArraySize () const
virtual uint32 getGapStart (unsigned int k) const
virtual void setGapStart (unsigned int k, uint32 gapStart_var)
virtual void setGapStopArraySize (unsigned int size)
virtual unsigned int getGapStopArraySize () const
virtual uint32 getGapStop (unsigned int k) const
virtual void setGapStop (unsigned int k, uint32 gapStop_var)
virtual void setDupTsnsArraySize (unsigned int size)
virtual unsigned int getDupTsnsArraySize () const
virtual uint32 getDupTsns (unsigned int k) const
virtual void setDupTsns (unsigned int k, uint32 dupTsns_var)
virtual uint32 getSackSeqNum () const
virtual void setSackSeqNum (uint32 sackSeqNum_var)
Protected Member Functions
bool operator== (const SCTPSackChunk &)
Protected Attributes
uint32 cumTsnAck_var
uint32 a_rwnd_var
uint16 numGaps_var
uint16 numDupTsns_var
uint32 * gapStart_var
unsigned int gapStart_arraysize
uint32 * gapStop_var
unsigned int gapStop_arraysize
uint32 * dupTsns_var
unsigned int dupTsns_arraysize
uint32 sackSeqNum_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPSackChunk extends SCTPChunk
 {
     uint32 cumTsnAck;
     uint32 a_rwnd;
     uint16 numGaps;
     uint16 numDupTsns;
     uint32 gapStart[];
     uint32 gapStop[];
     uint32 dupTsns[];
     uint32 sackSeqNum        = 0;
 }
Definition at line 700 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPSackChunk::SCTPSackChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPSackChunk::SCTPSackChunk (const SCTPSackChunk & other)
virtual SCTPSackChunk::~SCTPSackChunk () [virtual]
Member Function Documentation
virtual SCTPSackChunk* SCTPSackChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 723 of file SCTPMessage_m.h.
{return new SCTPSackChunk(*this);}
virtual uint32 SCTPSackChunk::getA_rwnd () const [virtual]
Referenced by SCTPAssociation::createSack(), SCTPAssociation::processSackArrived(), and TCPDumper::sctpDump().
virtual uint32 SCTPSackChunk::getCumTsnAck () const [virtual]
Referenced by SCTPAssociation::processSackArrived(), and TCPDumper::sctpDump().
virtual uint32 SCTPSackChunk::getDupTsns (unsigned int k) const [virtual]
Referenced by TCPDumper::sctpDump().
virtual unsigned int SCTPSackChunk::getDupTsnsArraySize () const [virtual]
Referenced by TCPDumper::sctpDump().
virtual uint32 SCTPSackChunk::getGapStart (unsigned int k) const [virtual]
Referenced by SCTPAssociation::createSack(), SCTPAssociation::processSackArrived(), and TCPDumper::sctpDump().
virtual unsigned int SCTPSackChunk::getGapStartArraySize () const [virtual]
Referenced by TCPDumper::sctpDump().
virtual uint32 SCTPSackChunk::getGapStop (unsigned int k) const [virtual]
Referenced by SCTPAssociation::createSack(), SCTPAssociation::processSackArrived(), and TCPDumper::sctpDump().
virtual unsigned int SCTPSackChunk::getGapStopArraySize () const [virtual]
virtual uint16 SCTPSackChunk::getNumDupTsns () const [virtual]
virtual uint16 SCTPSackChunk::getNumGaps () const [virtual]
Referenced by SCTPAssociation::processSackArrived().
virtual uint32 SCTPSackChunk::getSackSeqNum () const [virtual]
SCTPSackChunk& SCTPSackChunk::operator= (const SCTPSackChunk & other)
Reimplemented from SCTPChunk.
bool SCTPSackChunk::operator== (const SCTPSackChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPSackChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPSackChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPSackChunk::setA_rwnd (uint32 a_rwnd_var) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setCumTsnAck (uint32 cumTsnAck_var) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setDupTsns (unsigned int k, uint32 dupTsns_var) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setDupTsnsArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setGapStart (unsigned int k, uint32 gapStart_var) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setGapStartArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setGapStop (unsigned int k, uint32 gapStop_var) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setGapStopArraySize (unsigned int size) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setNumDupTsns (uint16 numDupTsns_var) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setNumGaps (uint16 numGaps_var) [virtual]
Referenced by SCTPAssociation::createSack().
virtual void SCTPSackChunk::setSackSeqNum (uint32 sackSeqNum_var) [virtual]
Member Data Documentation
uint32 SCTPSackChunk::a_rwnd_var [protected]
Definition at line 704 of file SCTPMessage_m.h.
uint32 SCTPSackChunk::cumTsnAck_var [protected]
Definition at line 703 of file SCTPMessage_m.h.
unsigned int SCTPSackChunk::dupTsns_arraysize [protected]
Definition at line 712 of file SCTPMessage_m.h.
uint32* SCTPSackChunk::dupTsns_var [protected]
Definition at line 711 of file SCTPMessage_m.h.
unsigned int SCTPSackChunk::gapStart_arraysize [protected]
Definition at line 708 of file SCTPMessage_m.h.
uint32* SCTPSackChunk::gapStart_var [protected]
Definition at line 707 of file SCTPMessage_m.h.
unsigned int SCTPSackChunk::gapStop_arraysize [protected]
Definition at line 710 of file SCTPMessage_m.h.
uint32* SCTPSackChunk::gapStop_var [protected]
Definition at line 709 of file SCTPMessage_m.h.
uint16 SCTPSackChunk::numDupTsns_var [protected]
Definition at line 706 of file SCTPMessage_m.h.
uint16 SCTPSackChunk::numGaps_var [protected]
Definition at line 705 of file SCTPMessage_m.h.
uint32 SCTPSackChunk::sackSeqNum_var [protected]
Definition at line 713 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h