INET Framework for OMNeT++/OMNEST: Ieee80211Prim_DeauthenticateRequest Class Reference
Ieee80211Prim_DeauthenticateRequest Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_DeauthenticateRequest ()
Ieee80211Prim_DeauthenticateRequest (const Ieee80211Prim_DeauthenticateRequest &other)
virtual ~Ieee80211Prim_DeauthenticateRequest ()
Ieee80211Prim_DeauthenticateRequest & operator= (const Ieee80211Prim_DeauthenticateRequest &other)
virtual
Ieee80211Prim_DeauthenticateRequest * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getAddress ()
virtual const MACAddress & getAddress () const
virtual void setAddress (const MACAddress &address_var)
virtual int getReasonCode () const
virtual void setReasonCode (int reasonCode_var)
Protected Member Functions
bool operator== (const Ieee80211Prim_DeauthenticateRequest &)
Protected Attributes
::MACAddress address_var
int reasonCode_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211Prim_DeauthenticateRequest extends Ieee80211PrimRequest
 {
     MACAddress address;
     int reasonCode enum(Ieee80211ReasonCode);
 }
Definition at line 420 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211Prim_DeauthenticateRequest::Ieee80211Prim_DeauthenticateRequest ()
Referenced by dup().
Ieee80211Prim_DeauthenticateRequest::Ieee80211Prim_DeauthenticateRequest (const Ieee80211Prim_DeauthenticateRequest & other)
virtual Ieee80211Prim_DeauthenticateRequest::~Ieee80211Prim_DeauthenticateRequest () [virtual]
Member Function Documentation
virtual Ieee80211Prim_DeauthenticateRequest* Ieee80211Prim_DeauthenticateRequest::dup () const [inline, virtual]
Reimplemented from Ieee80211PrimRequest.
Definition at line 434 of file Ieee80211Primitives_m.h.
{return new Ieee80211Prim_DeauthenticateRequest(*this);}
virtual const MACAddress& Ieee80211Prim_DeauthenticateRequest::getAddress () const [inline, virtual]
Definition at line 440 of file Ieee80211Primitives_m.h.
Referenced by getAddress().
{return const_cast<Ieee80211Prim_DeauthenticateRequest*>(this)->getAddress();}
virtual MACAddress& Ieee80211Prim_DeauthenticateRequest::getAddress () [virtual]
Referenced by Ieee80211MgmtSTA::processDeauthenticateCommand().
virtual int Ieee80211Prim_DeauthenticateRequest::getReasonCode () const [virtual]
Referenced by Ieee80211MgmtSTA::processDeauthenticateCommand().
Ieee80211Prim_DeauthenticateRequest& Ieee80211Prim_DeauthenticateRequest::operator= (const Ieee80211Prim_DeauthenticateRequest & other)
Reimplemented from Ieee80211PrimRequest.
bool Ieee80211Prim_DeauthenticateRequest::operator== (const Ieee80211Prim_DeauthenticateRequest &) [protected]
Reimplemented from Ieee80211PrimRequest.
virtual void Ieee80211Prim_DeauthenticateRequest::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doPacking().
virtual void Ieee80211Prim_DeauthenticateRequest::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211PrimRequest.
Referenced by doUnpacking().
virtual void Ieee80211Prim_DeauthenticateRequest::setAddress (const MACAddress & address_var) [virtual]
Referenced by Ieee80211AgentSTA::sendDeauthenticateRequest().
virtual void Ieee80211Prim_DeauthenticateRequest::setReasonCode (int reasonCode_var) [virtual]
Referenced by Ieee80211AgentSTA::sendDeauthenticateRequest().
Member Data Documentation
::MACAddress Ieee80211Prim_DeauthenticateRequest::address_var [protected]
Definition at line 423 of file Ieee80211Primitives_m.h.
int Ieee80211Prim_DeauthenticateRequest::reasonCode_var [protected]
Definition at line 424 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h