INET Framework for OMNeT++/OMNEST: SCTPResetInfo Class Reference
SCTPResetInfo Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPResetInfo (const char *name=NULL)
SCTPResetInfo (const SCTPResetInfo &other)
virtual ~SCTPResetInfo ()
SCTPResetInfo & operator= (const SCTPResetInfo &other)
virtual SCTPResetInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual unsigned short getRequestType () const
virtual void setRequestType (unsigned short requestType_var)
virtual void setStreamsArraySize (unsigned int size)
virtual unsigned int getStreamsArraySize () const
virtual char getStreams (unsigned int k) const
virtual void setStreams (unsigned int k, char streams_var)
Protected Member Functions
bool operator== (const SCTPResetInfo &)
Protected Attributes
::IPvXAddress remoteAddr_var
unsigned short requestType_var
char * streams_var
unsigned int streams_arraysize
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPResetInfo extends SCTPCommand
 {
     IPvXAddress remoteAddr;
     unsigned short requestType = 0;
     char streams[];
 }
Definition at line 417 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPResetInfo::SCTPResetInfo (const char * name = NULL)
Referenced by dup().
SCTPResetInfo::SCTPResetInfo (const SCTPResetInfo & other)
virtual SCTPResetInfo::~SCTPResetInfo () [virtual]
Member Function Documentation
virtual SCTPResetInfo* SCTPResetInfo::dup () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 433 of file SCTPCommand_m.h.
{return new SCTPResetInfo(*this);}
virtual const IPvXAddress& SCTPResetInfo::getRemoteAddr () const [inline, virtual]
Reimplemented from SCTPCommand.
Definition at line 439 of file SCTPCommand_m.h.
Referenced by getRemoteAddr().
{return const_cast<SCTPResetInfo*>(this)->getRemoteAddr();}
virtual IPvXAddress& SCTPResetInfo::getRemoteAddr () [virtual]
Reimplemented from SCTPCommand.
virtual unsigned short SCTPResetInfo::getRequestType () const [virtual]
virtual char SCTPResetInfo::getStreams (unsigned int k) const [virtual]
virtual unsigned int SCTPResetInfo::getStreamsArraySize () const [virtual]
SCTPResetInfo& SCTPResetInfo::operator= (const SCTPResetInfo & other)
Reimplemented from SCTPCommand.
bool SCTPResetInfo::operator== (const SCTPResetInfo &) [protected]
Reimplemented from SCTPCommand.
virtual void SCTPResetInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doPacking().
virtual void SCTPResetInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPCommand.
Referenced by doUnpacking().
virtual void SCTPResetInfo::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Reimplemented from SCTPCommand.
virtual void SCTPResetInfo::setRequestType (unsigned short requestType_var) [virtual]
virtual void SCTPResetInfo::setStreams (unsigned int k, char streams_var) [virtual]
virtual void SCTPResetInfo::setStreamsArraySize (unsigned int size) [virtual]
Member Data Documentation
::IPvXAddress SCTPResetInfo::remoteAddr_var [protected]
Reimplemented from SCTPCommand.
Definition at line 420 of file SCTPCommand_m.h.
unsigned short SCTPResetInfo::requestType_var [protected]
Definition at line 421 of file SCTPCommand_m.h.
unsigned int SCTPResetInfo::streams_arraysize [protected]
Definition at line 423 of file SCTPCommand_m.h.
char* SCTPResetInfo::streams_var [protected]
Definition at line 422 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h