INET Framework for OMNeT++/OMNEST: TCPConnectInfo Class Reference
TCPConnectInfo Class Reference
#include <TCPCommand_m.h>
Public Member Functions
TCPConnectInfo ()
TCPConnectInfo (const TCPConnectInfo &other)
virtual ~TCPConnectInfo ()
TCPConnectInfo & operator= (const TCPConnectInfo &other)
virtual TCPConnectInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPvXAddress & getLocalAddr ()
virtual const IPvXAddress & getLocalAddr () const
virtual void setLocalAddr (const IPvXAddress &localAddr_var)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort_var)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort_var)
Protected Member Functions
bool operator== (const TCPConnectInfo &)
Protected Attributes
::IPvXAddress localAddr_var
::IPvXAddress remoteAddr_var
int localPort_var
int remotePort_var
Detailed Description
Class generated from transport/contract/TCPCommand.msg by opp_msgc.
 class TCPConnectInfo extends TCPCommand
 {
     IPvXAddress localAddr;
     IPvXAddress remoteAddr;
     int localPort;
     int remotePort;
 }
Definition at line 271 of file TCPCommand_m.h.
Constructor & Destructor Documentation
TCPConnectInfo::TCPConnectInfo ()
Referenced by dup().
TCPConnectInfo::TCPConnectInfo (const TCPConnectInfo & other)
virtual TCPConnectInfo::~TCPConnectInfo () [virtual]
Member Function Documentation
virtual TCPConnectInfo* TCPConnectInfo::dup () const [inline, virtual]
Reimplemented from TCPCommand.
Definition at line 287 of file TCPCommand_m.h.
{return new TCPConnectInfo(*this);}
virtual const IPvXAddress& TCPConnectInfo::getLocalAddr () const [inline, virtual]
Definition at line 293 of file TCPCommand_m.h.
Referenced by getLocalAddr().
{return const_cast<TCPConnectInfo*>(this)->getLocalAddr();}
virtual IPvXAddress& TCPConnectInfo::getLocalAddr () [virtual]
Referenced by TCPSocket::processMessage(), and TCPSocket::TCPSocket().
virtual int TCPConnectInfo::getLocalPort () const [virtual]
Referenced by TCPSocket::processMessage(), and TCPSocket::TCPSocket().
virtual const IPvXAddress& TCPConnectInfo::getRemoteAddr () const [inline, virtual]
Definition at line 296 of file TCPCommand_m.h.
Referenced by getRemoteAddr().
{return const_cast<TCPConnectInfo*>(this)->getRemoteAddr();}
virtual IPvXAddress& TCPConnectInfo::getRemoteAddr () [virtual]
Referenced by TCPSocket::processMessage(), and TCPSocket::TCPSocket().
virtual int TCPConnectInfo::getRemotePort () const [virtual]
Referenced by TCPSocket::processMessage(), and TCPSocket::TCPSocket().
TCPConnectInfo& TCPConnectInfo::operator= (const TCPConnectInfo & other)
Reimplemented from TCPCommand.
bool TCPConnectInfo::operator== (const TCPConnectInfo &) [protected]
Reimplemented from TCPCommand.
virtual void TCPConnectInfo::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doPacking().
virtual void TCPConnectInfo::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doUnpacking().
virtual void TCPConnectInfo::setLocalAddr (const IPvXAddress & localAddr_var) [virtual]
Referenced by tcp_old::TCPConnection::sendEstabIndicationToApp(), and TCPConnection::sendEstabIndicationToApp().
virtual void TCPConnectInfo::setLocalPort (int localPort_var) [virtual]
Referenced by tcp_old::TCPConnection::sendEstabIndicationToApp(), and TCPConnection::sendEstabIndicationToApp().
virtual void TCPConnectInfo::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Referenced by tcp_old::TCPConnection::sendEstabIndicationToApp(), and TCPConnection::sendEstabIndicationToApp().
virtual void TCPConnectInfo::setRemotePort (int remotePort_var) [virtual]
Referenced by tcp_old::TCPConnection::sendEstabIndicationToApp(), and TCPConnection::sendEstabIndicationToApp().
Member Data Documentation
::IPvXAddress TCPConnectInfo::localAddr_var [protected]
Definition at line 274 of file TCPCommand_m.h.
int TCPConnectInfo::localPort_var [protected]
Definition at line 276 of file TCPCommand_m.h.
::IPvXAddress TCPConnectInfo::remoteAddr_var [protected]
Definition at line 275 of file TCPCommand_m.h.
int TCPConnectInfo::remotePort_var [protected]
Definition at line 277 of file TCPCommand_m.h.
The documentation for this class was generated from the following file:
TCPCommand_m.h