INET Framework for OMNeT++/OMNEST: SignallingMsg Class Reference
SignallingMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
SignallingMsg (const char *name=NULL, int kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual SignallingMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const SignallingMsg &)
Protected Attributes
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message SignallingMsg
 {
     int command = 0;
 }
Definition at line 51 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
SignallingMsg::SignallingMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
SignallingMsg::SignallingMsg (const SignallingMsg & other)
virtual SignallingMsg::~SignallingMsg () [virtual]
Member Function Documentation
virtual SignallingMsg* SignallingMsg::dup () const [inline, virtual]
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
Definition at line 64 of file SignallingMsg_m.h.
{return new SignallingMsg(*this);}
virtual int SignallingMsg::getCommand () const [virtual]
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
Referenced by RSVP::processSignallingMessage().
SignallingMsg& SignallingMsg::operator= (const SignallingMsg & other)
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
bool SignallingMsg::operator== (const SignallingMsg &) [protected]
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
virtual void SignallingMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
Referenced by doPacking().
virtual void SignallingMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
Referenced by doUnpacking().
virtual void SignallingMsg::setCommand (int command_var) [virtual]
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
Member Data Documentation
int SignallingMsg::command_var [protected]
Reimplemented in PsbTimerMsg, PsbTimeoutMsg, RsbRefreshTimerMsg, RsbCommitTimerMsg, RsbTimeoutMsg, HelloTimerMsg, HelloTimeoutMsg, and PathNotifyMsg.
Definition at line 54 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h