INET Framework for OMNeT++/OMNEST: LDPPacket Class Reference
LDPPacket Class Reference
#include <LDPPacket_m.h>
Public Member Functions
LDPPacket (const char *name=NULL, int kind=0)
LDPPacket (const LDPPacket &other)
virtual ~LDPPacket ()
LDPPacket & operator= (const LDPPacket &other)
virtual LDPPacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type_var)
virtual IPAddress & getSenderAddress ()
virtual const IPAddress & getSenderAddress () const
virtual void setSenderAddress (const IPAddress &senderAddress_var)
virtual IPAddress & getReceiverAddress ()
virtual const IPAddress & getReceiverAddress () const
virtual void setReceiverAddress (const IPAddress &receiverAddress_var)
Protected Member Functions
bool operator== (const LDPPacket &)
Protected Attributes
int type_var
::IPAddress senderAddress_var
::IPAddress receiverAddress_var
Detailed Description
Class generated from networklayer/ldp/LDPPacket.msg by opp_msgc.
 packet LDPPacket
 {
     int type;
     IPAddress senderAddress;
     IPAddress receiverAddress;
 }
Definition at line 102 of file LDPPacket_m.h.
Constructor & Destructor Documentation
LDPPacket::LDPPacket (const char * name = NULL, int kind = 0)
Referenced by dup().
LDPPacket::LDPPacket (const LDPPacket & other)
virtual LDPPacket::~LDPPacket () [virtual]
Member Function Documentation
virtual LDPPacket* LDPPacket::dup () const [inline, virtual]
Reimplemented in LDPLabelMapping, LDPLabelRequest, LDPHello, LDPNotify, LDPIni, and LDPAddress.
Definition at line 117 of file LDPPacket_m.h.
{return new LDPPacket(*this);}
virtual const IPAddress& LDPPacket::getReceiverAddress () const [inline, virtual]
Definition at line 128 of file LDPPacket_m.h.
Referenced by getReceiverAddress().
{return const_cast<LDPPacket*>(this)->getReceiverAddress();}
virtual IPAddress& LDPPacket::getReceiverAddress () [virtual]
virtual const IPAddress& LDPPacket::getSenderAddress () const [inline, virtual]
Definition at line 125 of file LDPPacket_m.h.
Referenced by getSenderAddress().
{return const_cast<LDPPacket*>(this)->getSenderAddress();}
virtual IPAddress& LDPPacket::getSenderAddress () [virtual]
Referenced by LDP::processLABEL_MAPPING(), LDP::processLABEL_RELEASE(), LDP::processLABEL_REQUEST(), LDP::processLABEL_WITHDRAW(), LDP::processLDPHello(), and LDP::processNOTIFICATION().
virtual int LDPPacket::getType () const [virtual]
Referenced by LDP::processLDPPacketFromTCP().
LDPPacket& LDPPacket::operator= (const LDPPacket & other)
Reimplemented in LDPLabelMapping, LDPLabelRequest, LDPHello, LDPNotify, LDPIni, and LDPAddress.
bool LDPPacket::operator== (const LDPPacket &) [protected]
Reimplemented in LDPLabelMapping, LDPLabelRequest, LDPHello, LDPNotify, LDPIni, and LDPAddress.
virtual void LDPPacket::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in LDPLabelMapping, LDPLabelRequest, LDPHello, LDPNotify, LDPIni, and LDPAddress.
Referenced by doPacking().
virtual void LDPPacket::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in LDPLabelMapping, LDPLabelRequest, LDPHello, LDPNotify, LDPIni, and LDPAddress.
Referenced by doUnpacking().
virtual void LDPPacket::setReceiverAddress (const IPAddress & receiverAddress_var) [virtual]
Referenced by LDP::sendMapping(), LDP::sendMappingRequest(), and LDP::sendNotify().
virtual void LDPPacket::setSenderAddress (const IPAddress & senderAddress_var) [virtual]
Referenced by LDP::sendHelloTo(), LDP::sendMapping(), LDP::sendMappingRequest(), and LDP::sendNotify().
virtual void LDPPacket::setType (int type_var) [virtual]
Referenced by LDP::processLABEL_WITHDRAW(), LDP::sendHelloTo(), LDP::sendMapping(), LDP::sendMappingRequest(), and LDP::sendNotify().
Member Data Documentation
::IPAddress LDPPacket::receiverAddress_var [protected]
Definition at line 107 of file LDPPacket_m.h.
::IPAddress LDPPacket::senderAddress_var [protected]
Definition at line 106 of file LDPPacket_m.h.
int LDPPacket::type_var [protected]
Definition at line 105 of file LDPPacket_m.h.
The documentation for this class was generated from the following file:
LDPPacket_m.h