INET Framework for OMNeT++/OMNEST: Ieee80211TwoAddressFrame Class Reference
Ieee80211TwoAddressFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211TwoAddressFrame (const char *name=NULL, int kind=0)
Ieee80211TwoAddressFrame (const Ieee80211TwoAddressFrame &other)
virtual ~Ieee80211TwoAddressFrame ()
Ieee80211TwoAddressFrame & operator= (const Ieee80211TwoAddressFrame &other)
virtual Ieee80211TwoAddressFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getTransmitterAddress ()
virtual const MACAddress & getTransmitterAddress () const
virtual void setTransmitterAddress (const MACAddress &transmitterAddress_var)
Protected Member Functions
bool operator== (const Ieee80211TwoAddressFrame &)
Protected Attributes
::MACAddress transmitterAddress_var
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211TwoAddressFrame extends Ieee80211OneAddressFrame
 {
     byteLength = 20;
     MACAddress transmitterAddress;
 }
Definition at line 208 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211TwoAddressFrame::Ieee80211TwoAddressFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211TwoAddressFrame::Ieee80211TwoAddressFrame (const Ieee80211TwoAddressFrame & other)
virtual Ieee80211TwoAddressFrame::~Ieee80211TwoAddressFrame () [virtual]
Member Function Documentation
virtual Ieee80211TwoAddressFrame* Ieee80211TwoAddressFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211OneAddressFrame.
Reimplemented in Ieee80211RTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Definition at line 221 of file Ieee80211Frame_m.h.
{return new Ieee80211TwoAddressFrame(*this);}
virtual const MACAddress& Ieee80211TwoAddressFrame::getTransmitterAddress () const [inline, virtual]
Definition at line 227 of file Ieee80211Frame_m.h.
Referenced by getTransmitterAddress().
{return const_cast<Ieee80211TwoAddressFrame*>(this)->getTransmitterAddress();}
virtual MACAddress& Ieee80211TwoAddressFrame::getTransmitterAddress () [virtual]
Referenced by Ieee80211Mac::buildACKFrame(), Ieee80211Mac::buildCTSFrame(), Ieee80211MgmtAPBase::convertToEtherFrame(), Ieee80211MgmtAPBase::distributeReceivedDataFrame(), Ieee80211MgmtAP::handleAssociationRequestFrame(), Ieee80211MgmtSTA::handleAssociationResponseFrame(), Ieee80211MgmtSTA::handleAuthenticationFrame(), Ieee80211MgmtAP::handleAuthenticationFrame(), Ieee80211MgmtSTA::handleBeaconFrame(), Ieee80211Mac::handleLowerMsg(), Ieee80211MgmtAP::handleProbeRequestFrame(), Ieee80211MgmtSTA::handleProbeResponseFrame(), Ieee80211MgmtAP::handleReassociationRequestFrame(), and Ieee80211MgmtAP::lookupSenderSTA().
Ieee80211TwoAddressFrame& Ieee80211TwoAddressFrame::operator= (const Ieee80211TwoAddressFrame & other)
Reimplemented from Ieee80211OneAddressFrame.
Reimplemented in Ieee80211RTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
bool Ieee80211TwoAddressFrame::operator== (const Ieee80211TwoAddressFrame &) [protected]
Reimplemented from Ieee80211OneAddressFrame.
Reimplemented in Ieee80211RTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
virtual void Ieee80211TwoAddressFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211OneAddressFrame.
Reimplemented in Ieee80211RTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doPacking().
virtual void Ieee80211TwoAddressFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211OneAddressFrame.
Reimplemented in Ieee80211RTSFrame, Ieee80211DataOrMgmtFrame, Ieee80211DataFrame, Ieee80211ManagementFrame, Ieee80211AuthenticationFrame, Ieee80211DeauthenticationFrame, Ieee80211DisassociationFrame, Ieee80211ProbeRequestFrame, Ieee80211AssociationRequestFrame, Ieee80211ReassociationRequestFrame, Ieee80211AssociationResponseFrame, Ieee80211ReassociationResponseFrame, Ieee80211BeaconFrame, and Ieee80211ProbeResponseFrame.
Referenced by doUnpacking().
virtual void Ieee80211TwoAddressFrame::setTransmitterAddress (const MACAddress & transmitterAddress_var) [virtual]
Referenced by Ieee80211Mac::buildRTSFrame(), and Ieee80211Mac::handleUpperMsg().
Member Data Documentation
::MACAddress Ieee80211TwoAddressFrame::transmitterAddress_var [protected]
Definition at line 211 of file Ieee80211Frame_m.h.
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h