INET Framework for OMNeT++/OMNEST: IPv6Redirect Class Reference
IPv6Redirect Class Reference
#include <IPv6NDMessage_m.h>
Public Member Functions
IPv6Redirect (const char *name=NULL, int kind=0)
IPv6Redirect (const IPv6Redirect &other)
virtual ~IPv6Redirect ()
IPv6Redirect & operator= (const IPv6Redirect &other)
virtual IPv6Redirect * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPv6Address & getTargetAddress ()
virtual const IPv6Address & getTargetAddress () const
virtual void setTargetAddress (const IPv6Address &targetAddress_var)
virtual IPv6Address & getDestinationAddress ()
virtual const IPv6Address & getDestinationAddress () const
virtual void setDestinationAddress (const IPv6Address &destinationAddress_var)
virtual MACAddress & getTargetLinkLayerAddress ()
virtual const MACAddress & getTargetLinkLayerAddress () const
virtual void setTargetLinkLayerAddress (const MACAddress &targetLinkLayerAddress_var)
Protected Member Functions
bool operator== (const IPv6Redirect &)
Protected Attributes
::IPv6Address targetAddress_var
::IPv6Address destinationAddress_var
::MACAddress targetLinkLayerAddress_var
Detailed Description
Class generated from networklayer/icmpv6/IPv6NDMessage.msg by opp_msgc.
 packet IPv6Redirect extends IPv6NDMessage
 {
     IPv6Address targetAddress;
     IPv6Address destinationAddress;
     MACAddress targetLinkLayerAddress;
 }
Definition at line 338 of file IPv6NDMessage_m.h.
Constructor & Destructor Documentation
IPv6Redirect::IPv6Redirect (const char * name = NULL, int kind = 0)
Referenced by dup().
IPv6Redirect::IPv6Redirect (const IPv6Redirect & other)
virtual IPv6Redirect::~IPv6Redirect () [virtual]
Member Function Documentation
virtual IPv6Redirect* IPv6Redirect::dup () const [inline, virtual]
Reimplemented from IPv6NDMessage.
Definition at line 353 of file IPv6NDMessage_m.h.
{return new IPv6Redirect(*this);}
virtual const IPv6Address& IPv6Redirect::getDestinationAddress () const [inline, virtual]
Definition at line 362 of file IPv6NDMessage_m.h.
Referenced by getDestinationAddress().
{return const_cast<IPv6Redirect*>(this)->getDestinationAddress();}
virtual IPv6Address& IPv6Redirect::getDestinationAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processRedirectPacket().
virtual const IPv6Address& IPv6Redirect::getTargetAddress () const [inline, virtual]
Definition at line 359 of file IPv6NDMessage_m.h.
Referenced by getTargetAddress().
{return const_cast<IPv6Redirect*>(this)->getTargetAddress();}
virtual IPv6Address& IPv6Redirect::getTargetAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processRedirectPacket().
virtual const MACAddress& IPv6Redirect::getTargetLinkLayerAddress () const [inline, virtual]
Definition at line 365 of file IPv6NDMessage_m.h.
Referenced by getTargetLinkLayerAddress().
{return const_cast<IPv6Redirect*>(this)->getTargetLinkLayerAddress();}
virtual MACAddress& IPv6Redirect::getTargetLinkLayerAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processRedirectPacket().
IPv6Redirect& IPv6Redirect::operator= (const IPv6Redirect & other)
Reimplemented from IPv6NDMessage.
bool IPv6Redirect::operator== (const IPv6Redirect &) [protected]
Reimplemented from IPv6NDMessage.
virtual void IPv6Redirect::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doPacking().
virtual void IPv6Redirect::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doUnpacking().
virtual void IPv6Redirect::setDestinationAddress (const IPv6Address & destinationAddress_var) [virtual]
virtual void IPv6Redirect::setTargetAddress (const IPv6Address & targetAddress_var) [virtual]
virtual void IPv6Redirect::setTargetLinkLayerAddress (const MACAddress & targetLinkLayerAddress_var) [virtual]
Member Data Documentation
::IPv6Address IPv6Redirect::destinationAddress_var [protected]
Definition at line 342 of file IPv6NDMessage_m.h.
::IPv6Address IPv6Redirect::targetAddress_var [protected]
Definition at line 341 of file IPv6NDMessage_m.h.
::MACAddress IPv6Redirect::targetLinkLayerAddress_var [protected]
Definition at line 343 of file IPv6NDMessage_m.h.
The documentation for this class was generated from the following file:
IPv6NDMessage_m.h