INET Framework for OMNeT++/OMNEST: Ieee80211AuthenticationFrameBody Class Reference
Ieee80211AuthenticationFrameBody Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211AuthenticationFrameBody ()
Ieee80211AuthenticationFrameBody (const Ieee80211AuthenticationFrameBody &other)
virtual ~Ieee80211AuthenticationFrameBody ()
Ieee80211AuthenticationFrameBody & operator= (const Ieee80211AuthenticationFrameBody &other)
virtual
Ieee80211AuthenticationFrameBody * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned short getSequenceNumber () const
virtual void setSequenceNumber (unsigned short sequenceNumber_var)
virtual int getStatusCode () const
virtual void setStatusCode (int statusCode_var)
virtual bool getIsLast () const
virtual void setIsLast (bool isLast_var)
Protected Member Functions
bool operator== (const Ieee80211AuthenticationFrameBody &)
Protected Attributes
unsigned short sequenceNumber_var
int statusCode_var
bool isLast_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 class Ieee80211AuthenticationFrameBody extends Ieee80211FrameBody
 {
     bodyLength = 6;
     unsigned short sequenceNumber;
     int statusCode enum(Ieee80211StatusCode);
     bool isLast;
 }
Definition at line 178 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211AuthenticationFrameBody::Ieee80211AuthenticationFrameBody ()
Referenced by dup().
Ieee80211AuthenticationFrameBody::Ieee80211AuthenticationFrameBody (const Ieee80211AuthenticationFrameBody & other)
virtual Ieee80211AuthenticationFrameBody::~Ieee80211AuthenticationFrameBody () [virtual]
Member Function Documentation
virtual Ieee80211AuthenticationFrameBody* Ieee80211AuthenticationFrameBody::dup () const [inline, virtual]
Reimplemented from Ieee80211FrameBody.
Definition at line 193 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211AuthenticationFrameBody(*this);}
virtual bool Ieee80211AuthenticationFrameBody::getIsLast () const [virtual]
Referenced by Ieee80211MgmtSTA::handleAuthenticationFrame().
virtual unsigned short Ieee80211AuthenticationFrameBody::getSequenceNumber () const [virtual]
Referenced by Ieee80211MgmtSTA::handleAuthenticationFrame(), and Ieee80211MgmtAP::handleAuthenticationFrame().
virtual int Ieee80211AuthenticationFrameBody::getStatusCode () const [virtual]
Referenced by Ieee80211MgmtSTA::handleAuthenticationFrame().
Ieee80211AuthenticationFrameBody& Ieee80211AuthenticationFrameBody::operator= (const Ieee80211AuthenticationFrameBody & other)
Reimplemented from Ieee80211FrameBody.
bool Ieee80211AuthenticationFrameBody::operator== (const Ieee80211AuthenticationFrameBody &) [protected]
Reimplemented from Ieee80211FrameBody.
virtual void Ieee80211AuthenticationFrameBody::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doPacking().
virtual void Ieee80211AuthenticationFrameBody::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211FrameBody.
Referenced by doUnpacking().
virtual void Ieee80211AuthenticationFrameBody::setIsLast (bool isLast_var) [virtual]
virtual void Ieee80211AuthenticationFrameBody::setSequenceNumber (unsigned short sequenceNumber_var) [virtual]
Referenced by Ieee80211MgmtSTA::handleAuthenticationFrame(), and Ieee80211MgmtSTA::startAuthentication().
virtual void Ieee80211AuthenticationFrameBody::setStatusCode (int statusCode_var) [virtual]
Referenced by Ieee80211MgmtSTA::handleAuthenticationFrame(), and Ieee80211MgmtAP::handleAuthenticationFrame().
Member Data Documentation
bool Ieee80211AuthenticationFrameBody::isLast_var [protected]
Definition at line 183 of file Ieee80211MgmtFrames_m.h.
unsigned short Ieee80211AuthenticationFrameBody::sequenceNumber_var [protected]
Definition at line 181 of file Ieee80211MgmtFrames_m.h.
int Ieee80211AuthenticationFrameBody::statusCode_var [protected]
Definition at line 182 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h