INET Framework for OMNeT++/OMNEST: LDPAddress Class Reference
LDPAddress Class Reference
#include <LDPPacket_m.h>
Public Member Functions
LDPAddress (const char *name=NULL, int kind=0)
LDPAddress (const LDPAddress &other)
virtual ~LDPAddress ()
LDPAddress & operator= (const LDPAddress &other)
virtual LDPAddress * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getIsWithdraw () const
virtual void setIsWithdraw (bool isWithdraw_var)
virtual const char * getFamily () const
virtual void setFamily (const char *family_var)
virtual void setAddressesArraySize (unsigned int size)
virtual unsigned int getAddressesArraySize () const
virtual const char * getAddresses (unsigned int k) const
virtual void setAddresses (unsigned int k, const char *addresses_var)
Protected Member Functions
bool operator== (const LDPAddress &)
Protected Attributes
bool isWithdraw_var
opp_string family_var
opp_string * addresses_var
unsigned int addresses_arraysize
Detailed Description
Class generated from networklayer/ldp/LDPPacket.msg by opp_msgc.
 packet LDPAddress extends LDPPacket
 {
     bool isWithdraw;
     string family;
     string addresses[];
 }
Definition at line 351 of file LDPPacket_m.h.
Constructor & Destructor Documentation
LDPAddress::LDPAddress (const char * name = NULL, int kind = 0)
Referenced by dup().
LDPAddress::LDPAddress (const LDPAddress & other)
virtual LDPAddress::~LDPAddress () [virtual]
Member Function Documentation
virtual LDPAddress* LDPAddress::dup () const [inline, virtual]
Reimplemented from LDPPacket.
Definition at line 367 of file LDPPacket_m.h.
{return new LDPAddress(*this);}
virtual const char* LDPAddress::getAddresses (unsigned int k) const [virtual]
virtual unsigned int LDPAddress::getAddressesArraySize () const [virtual]
virtual const char* LDPAddress::getFamily () const [virtual]
virtual bool LDPAddress::getIsWithdraw () const [virtual]
LDPAddress& LDPAddress::operator= (const LDPAddress & other)
Reimplemented from LDPPacket.
bool LDPAddress::operator== (const LDPAddress &) [protected]
Reimplemented from LDPPacket.
virtual void LDPAddress::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doPacking().
virtual void LDPAddress::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doUnpacking().
virtual void LDPAddress::setAddresses (unsigned int k, const char * addresses_var) [virtual]
virtual void LDPAddress::setAddressesArraySize (unsigned int size) [virtual]
virtual void LDPAddress::setFamily (const char * family_var) [virtual]
virtual void LDPAddress::setIsWithdraw (bool isWithdraw_var) [virtual]
Member Data Documentation
unsigned int LDPAddress::addresses_arraysize [protected]
Definition at line 357 of file LDPPacket_m.h.
opp_string* LDPAddress::addresses_var [protected]
Definition at line 356 of file LDPPacket_m.h.
opp_string LDPAddress::family_var [protected]
Definition at line 355 of file LDPPacket_m.h.
bool LDPAddress::isWithdraw_var [protected]
Definition at line 354 of file LDPPacket_m.h.
The documentation for this class was generated from the following file:
LDPPacket_m.h