INET Framework for OMNeT++/OMNEST: EtherAppResp Class Reference
EtherAppResp Class Reference
#include <EtherApp_m.h>
Public Member Functions
EtherAppResp (const char *name=NULL, int kind=0)
EtherAppResp (const EtherAppResp &other)
virtual ~EtherAppResp ()
EtherAppResp & operator= (const EtherAppResp &other)
virtual EtherAppResp * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getRequestId () const
virtual void setRequestId (int requestId_var)
virtual int getNumFrames () const
virtual void setNumFrames (int numFrames_var)
Protected Member Functions
bool operator== (const EtherAppResp &)
Protected Attributes
int requestId_var
int numFrames_var
Detailed Description
Class generated from applications/ethernet/EtherApp.msg by opp_msgc.
 packet EtherAppResp
 {
     int requestId;
     int numFrames;
 }
Definition at line 73 of file EtherApp_m.h.
Constructor & Destructor Documentation
EtherAppResp::EtherAppResp (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherAppResp::EtherAppResp (const EtherAppResp & other)
virtual EtherAppResp::~EtherAppResp () [virtual]
Member Function Documentation
virtual EtherAppResp* EtherAppResp::dup () const [inline, virtual]
Definition at line 87 of file EtherApp_m.h.
{return new EtherAppResp(*this);}
virtual int EtherAppResp::getNumFrames () const [virtual]
virtual int EtherAppResp::getRequestId () const [virtual]
EtherAppResp& EtherAppResp::operator= (const EtherAppResp & other)
bool EtherAppResp::operator== (const EtherAppResp &) [protected]
virtual void EtherAppResp::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void EtherAppResp::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void EtherAppResp::setNumFrames (int numFrames_var) [virtual]
virtual void EtherAppResp::setRequestId (int requestId_var) [virtual]
Referenced by EtherAppSrv::handleMessage().
Member Data Documentation
int EtherAppResp::numFrames_var [protected]
Definition at line 77 of file EtherApp_m.h.
int EtherAppResp::requestId_var [protected]
Definition at line 76 of file EtherApp_m.h.
The documentation for this class was generated from the following file:
EtherApp_m.h