INET Framework for OMNeT++/OMNEST: Ieee80211PrimConfirm Class Reference
Ieee80211PrimConfirm Class Reference
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211PrimConfirm ()
Ieee80211PrimConfirm (const Ieee80211PrimConfirm &other)
virtual ~Ieee80211PrimConfirm ()
Ieee80211PrimConfirm & operator= (const Ieee80211PrimConfirm &other)
virtual Ieee80211PrimConfirm * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getResultCode () const
virtual void setResultCode (int resultCode_var)
Protected Member Functions
bool operator== (const Ieee80211PrimConfirm &)
Protected Attributes
int resultCode_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211Primitives.msg by opp_msgc.
 class Ieee80211PrimConfirm
 {
     int resultCode enum(Ieee80211PrimResultCode);
 }
Definition at line 150 of file Ieee80211Primitives_m.h.
Constructor & Destructor Documentation
Ieee80211PrimConfirm::Ieee80211PrimConfirm ()
Referenced by dup().
Ieee80211PrimConfirm::Ieee80211PrimConfirm (const Ieee80211PrimConfirm & other)
virtual Ieee80211PrimConfirm::~Ieee80211PrimConfirm () [virtual]
Member Function Documentation
virtual Ieee80211PrimConfirm* Ieee80211PrimConfirm::dup () const [inline, virtual]
Reimplemented in Ieee80211Prim_ScanConfirm, Ieee80211Prim_AuthenticateConfirm, Ieee80211Prim_AssociateConfirm, and Ieee80211Prim_ReassociateConfirm.
Definition at line 163 of file Ieee80211Primitives_m.h.
{return new Ieee80211PrimConfirm(*this);}
virtual int Ieee80211PrimConfirm::getResultCode () const [virtual]
Referenced by Ieee80211AgentSTA::processAssociateConfirm(), Ieee80211AgentSTA::processAuthenticateConfirm(), and Ieee80211AgentSTA::processReassociateConfirm().
Ieee80211PrimConfirm& Ieee80211PrimConfirm::operator= (const Ieee80211PrimConfirm & other)
Reimplemented in Ieee80211Prim_ScanConfirm, Ieee80211Prim_AuthenticateConfirm, Ieee80211Prim_AssociateConfirm, and Ieee80211Prim_ReassociateConfirm.
bool Ieee80211PrimConfirm::operator== (const Ieee80211PrimConfirm &) [protected]
Reimplemented in Ieee80211Prim_ScanConfirm, Ieee80211Prim_AuthenticateConfirm, Ieee80211Prim_AssociateConfirm, and Ieee80211Prim_ReassociateConfirm.
virtual void Ieee80211PrimConfirm::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211Prim_ScanConfirm, Ieee80211Prim_AuthenticateConfirm, Ieee80211Prim_AssociateConfirm, and Ieee80211Prim_ReassociateConfirm.
Referenced by doPacking().
virtual void Ieee80211PrimConfirm::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in Ieee80211Prim_ScanConfirm, Ieee80211Prim_AuthenticateConfirm, Ieee80211Prim_AssociateConfirm, and Ieee80211Prim_ReassociateConfirm.
Referenced by doUnpacking().
virtual void Ieee80211PrimConfirm::setResultCode (int resultCode_var) [virtual]
Referenced by Ieee80211MgmtSTA::sendConfirm().
Member Data Documentation
int Ieee80211PrimConfirm::resultCode_var [protected]
Definition at line 153 of file Ieee80211Primitives_m.h.
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h