INET Framework for OMNeT++/OMNEST: RsbRefreshTimerMsg Class Reference
RsbRefreshTimerMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
RsbRefreshTimerMsg (const char *name=NULL, int kind=0)
RsbRefreshTimerMsg (const RsbRefreshTimerMsg &other)
virtual ~RsbRefreshTimerMsg ()
RsbRefreshTimerMsg & operator= (const RsbRefreshTimerMsg &other)
virtual RsbRefreshTimerMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getId () const
virtual void setId (int id_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const RsbRefreshTimerMsg &)
Protected Attributes
int id_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message RsbRefreshTimerMsg extends SignallingMsg
 {
     int id;
     int command = MSG_RSB_REFRESH_TIMER;
 }
Definition at line 165 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
RsbRefreshTimerMsg::RsbRefreshTimerMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
RsbRefreshTimerMsg::RsbRefreshTimerMsg (const RsbRefreshTimerMsg & other)
virtual RsbRefreshTimerMsg::~RsbRefreshTimerMsg () [virtual]
Member Function Documentation
virtual RsbRefreshTimerMsg* RsbRefreshTimerMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 179 of file SignallingMsg_m.h.
{return new RsbRefreshTimerMsg(*this);}
virtual int RsbRefreshTimerMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual int RsbRefreshTimerMsg::getId () const [virtual]
Referenced by RSVP::processRSB_REFRESH_TIMER().
RsbRefreshTimerMsg& RsbRefreshTimerMsg::operator= (const RsbRefreshTimerMsg & other)
Reimplemented from SignallingMsg.
bool RsbRefreshTimerMsg::operator== (const RsbRefreshTimerMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void RsbRefreshTimerMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void RsbRefreshTimerMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void RsbRefreshTimerMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void RsbRefreshTimerMsg::setId (int id_var) [virtual]
Referenced by RSVP::createEgressRSB(), and RSVP::createRSB().
Member Data Documentation
int RsbRefreshTimerMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 169 of file SignallingMsg_m.h.
int RsbRefreshTimerMsg::id_var [protected]
Definition at line 168 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h