INET Framework for OMNeT++/OMNEST: Ieee80211DataFrame Class Reference
Ieee80211DataFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211DataFrame (const char *name=NULL, int kind=0)
Ieee80211DataFrame (const Ieee80211DataFrame &other)
virtual ~Ieee80211DataFrame ()
Ieee80211DataFrame & operator= (const Ieee80211DataFrame &other)
virtual Ieee80211DataFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual MACAddress & getAddress4 ()
virtual const MACAddress & getAddress4 () const
virtual void setAddress4 (const MACAddress &address4_var)
Protected Member Functions
bool operator== (const Ieee80211DataFrame &)
Protected Attributes
::MACAddress address4_var
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211DataFrame extends Ieee80211DataOrMgmtFrame
 {
     type = ST_DATA;
     byteLength = 34;
     MACAddress address4;
 }
Definition at line 351 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211DataFrame::Ieee80211DataFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211DataFrame::Ieee80211DataFrame (const Ieee80211DataFrame & other)
virtual Ieee80211DataFrame::~Ieee80211DataFrame () [virtual]
Member Function Documentation
virtual Ieee80211DataFrame* Ieee80211DataFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211DataOrMgmtFrame.
Definition at line 364 of file Ieee80211Frame_m.h.
Referenced by Ieee80211MgmtAP::handleDataFrame().
{return new Ieee80211DataFrame(*this);}
virtual const MACAddress& Ieee80211DataFrame::getAddress4 () const [inline, virtual]
Definition at line 370 of file Ieee80211Frame_m.h.
Referenced by getAddress4().
{return const_cast<Ieee80211DataFrame*>(this)->getAddress4();}
virtual MACAddress& Ieee80211DataFrame::getAddress4 () [virtual]
Ieee80211DataFrame& Ieee80211DataFrame::operator= (const Ieee80211DataFrame & other)
Reimplemented from Ieee80211DataOrMgmtFrame.
bool Ieee80211DataFrame::operator== (const Ieee80211DataFrame &) [protected]
Reimplemented from Ieee80211DataOrMgmtFrame.
virtual void Ieee80211DataFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211DataOrMgmtFrame.
Referenced by doPacking().
virtual void Ieee80211DataFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211DataOrMgmtFrame.
Referenced by doUnpacking().
virtual void Ieee80211DataFrame::setAddress4 (const MACAddress & address4_var) [virtual]
Member Data Documentation
::MACAddress Ieee80211DataFrame::address4_var [protected]
Definition at line 354 of file Ieee80211Frame_m.h.
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h