INET Framework for OMNeT++/OMNEST: EtherJam Class Reference
EtherJam Class Reference
#include <EtherFrame_m.h>
Public Member Functions
EtherJam (const char *name=NULL, int kind=0)
EtherJam (const EtherJam &other)
virtual ~EtherJam ()
EtherJam & operator= (const EtherJam &other)
virtual EtherJam * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const EtherJam &)
Detailed Description
Class generated from linklayer/ethernet/EtherFrame.msg by opp_msgc.
 packet EtherJam
 {
 }
Definition at line 33 of file EtherFrame_m.h.
Constructor & Destructor Documentation
EtherJam::EtherJam (const char * name = NULL, int kind = 0)
Referenced by dup().
EtherJam::EtherJam (const EtherJam & other)
virtual EtherJam::~EtherJam () [virtual]
Member Function Documentation
virtual EtherJam* EtherJam::dup () const [inline, virtual]
Definition at line 45 of file EtherFrame_m.h.
{return new EtherJam(*this);}
EtherJam& EtherJam::operator= (const EtherJam & other)
bool EtherJam::operator== (const EtherJam &) [protected]
virtual void EtherJam::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void EtherJam::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
EtherFrame_m.h