INET Framework for OMNeT++/OMNEST: Ieee80211RTSFrame Class Reference
Ieee80211RTSFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211RTSFrame (const char *name=NULL, int kind=0)
Ieee80211RTSFrame (const Ieee80211RTSFrame &other)
virtual ~Ieee80211RTSFrame ()
Ieee80211RTSFrame & operator= (const Ieee80211RTSFrame &other)
virtual Ieee80211RTSFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211RTSFrame &)
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211RTSFrame extends Ieee80211TwoAddressFrame
 {
     type = ST_RTS;
 }
Definition at line 243 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211RTSFrame::Ieee80211RTSFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211RTSFrame::Ieee80211RTSFrame (const Ieee80211RTSFrame & other)
virtual Ieee80211RTSFrame::~Ieee80211RTSFrame () [virtual]
Member Function Documentation
virtual Ieee80211RTSFrame* Ieee80211RTSFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211TwoAddressFrame.
Definition at line 255 of file Ieee80211Frame_m.h.
{return new Ieee80211RTSFrame(*this);}
Ieee80211RTSFrame& Ieee80211RTSFrame::operator= (const Ieee80211RTSFrame & other)
Reimplemented from Ieee80211TwoAddressFrame.
bool Ieee80211RTSFrame::operator== (const Ieee80211RTSFrame &) [protected]
Reimplemented from Ieee80211TwoAddressFrame.
virtual void Ieee80211RTSFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211TwoAddressFrame.
Referenced by doPacking().
virtual void Ieee80211RTSFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211TwoAddressFrame.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h