INET Framework for OMNeT++/OMNEST: RSVPPathTear Class Reference
RSVPPathTear Class Reference
#include <RSVPPathMsg.h>
Public Member Functions
RSVPPathTear (const char *name=NULL, int kind=PTEAR_MESSAGE)
RSVPPathTear (const RSVPPathTear &other)
RSVPPathTear & operator= (const RSVPPathTear &other)
virtual RSVPPathTear * dup () const
IPAddress getNHOP ()
IPAddress getLIH ()
IPAddress getSrcAddress ()
int getLspId ()
Detailed Description
RSVP PATH TEAR message
This class adds convenience get() and set() methods to the generated base class, but no extra data.
Definition at line 54 of file RSVPPathMsg.h.
Constructor & Destructor Documentation
RSVPPathTear::RSVPPathTear (const char * name = NULL, int kind = PTEAR_MESSAGE) [inline]
Definition at line 57 of file RSVPPathMsg.h.
Referenced by dup().
: RSVPPathTear_Base(name,kind) {}
RSVPPathTear::RSVPPathTear (const RSVPPathTear & other) [inline]
Definition at line 58 of file RSVPPathMsg.h.
: RSVPPathTear_Base(other.getName()) {operator=(other);}
Member Function Documentation
virtual RSVPPathTear* RSVPPathTear::dup () const [inline, virtual]
Reimplemented from RSVPPathTear_Base.
Definition at line 60 of file RSVPPathMsg.h.
{return new RSVPPathTear(*this);}
IPAddress RSVPPathTear::getLIH () [inline]
Definition at line 63 of file RSVPPathMsg.h.
{return getHop().Logical_Interface_Handle;}
int RSVPPathTear::getLspId () [inline]
Definition at line 65 of file RSVPPathMsg.h.
Referenced by RSVP::processPathTearMsg().
{return getSenderTemplate().Lsp_Id;}
IPAddress RSVPPathTear::getNHOP () [inline]
Definition at line 62 of file RSVPPathMsg.h.
{return getHop().Next_Hop_Address;}
IPAddress RSVPPathTear::getSrcAddress () [inline]
Definition at line 64 of file RSVPPathMsg.h.
{return getSenderTemplate().SrcAddress;}
RSVPPathTear& RSVPPathTear::operator= (const RSVPPathTear & other) [inline]
Reimplemented from RSVPPathTear_Base.
Definition at line 59 of file RSVPPathMsg.h.
Referenced by RSVPPathTear().
{RSVPPathTear_Base::operator=(other); return *this;}
The documentation for this class was generated from the following file:
RSVPPathMsg.h