INET Framework for OMNeT++/OMNEST: Ieee80211ReassociationRequestFrame Class Reference
Ieee80211ReassociationRequestFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ReassociationRequestFrame (const char *name=NULL, int kind=0)
Ieee80211ReassociationRequestFrame (const Ieee80211ReassociationRequestFrame &other)
virtual ~Ieee80211ReassociationRequestFrame ()
Ieee80211ReassociationRequestFrame & operator= (const Ieee80211ReassociationRequestFrame &other)
virtual
Ieee80211ReassociationRequestFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211ReassociationRequestFrameBody & getBody ()
virtual const
Ieee80211ReassociationRequestFrameBody & getBody () const
virtual void setBody (const Ieee80211ReassociationRequestFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211ReassociationRequestFrame &)
Protected Attributes
::Ieee80211ReassociationRequestFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211ReassociationRequestFrame extends Ieee80211ManagementFrame
 {
     type = ST_REASSOCIATIONREQUEST;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211ReassociationRequestFrameBody body;
 }
Definition at line 748 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ReassociationRequestFrame::Ieee80211ReassociationRequestFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211ReassociationRequestFrame::Ieee80211ReassociationRequestFrame (const Ieee80211ReassociationRequestFrame & other)
virtual Ieee80211ReassociationRequestFrame::~Ieee80211ReassociationRequestFrame () [virtual]
Member Function Documentation
virtual Ieee80211ReassociationRequestFrame* Ieee80211ReassociationRequestFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 761 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ReassociationRequestFrame(*this);}
virtual const Ieee80211ReassociationRequestFrameBody& Ieee80211ReassociationRequestFrame::getBody () const [inline, virtual]
Definition at line 767 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211ReassociationRequestFrame*>(this)->getBody();}
virtual Ieee80211ReassociationRequestFrameBody& Ieee80211ReassociationRequestFrame::getBody () [virtual]
Ieee80211ReassociationRequestFrame& Ieee80211ReassociationRequestFrame::operator= (const Ieee80211ReassociationRequestFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211ReassociationRequestFrame::operator== (const Ieee80211ReassociationRequestFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211ReassociationRequestFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211ReassociationRequestFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211ReassociationRequestFrame::setBody (const Ieee80211ReassociationRequestFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211ReassociationRequestFrameBody Ieee80211ReassociationRequestFrame::body_var [protected]
Definition at line 751 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h