INET Framework for OMNeT++/OMNEST: ControlManetRouting Class Reference
ControlManetRouting Class Reference
#include <ControlManetRouting_m.h>
Public Member Functions
ControlManetRouting (const char *name=NULL, int kind=0)
ControlManetRouting (const ControlManetRouting &other)
virtual ~ControlManetRouting ()
ControlManetRouting & operator= (const ControlManetRouting &other)
virtual ControlManetRouting * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPAddress & getSrcAddress ()
virtual const IPAddress & getSrcAddress () const
virtual void setSrcAddress (const IPAddress &srcAddress_var)
virtual IPAddress & getDestAddress ()
virtual const IPAddress & getDestAddress () const
virtual void setDestAddress (const IPAddress &destAddress_var)
virtual int getOptionCode () const
virtual void setOptionCode (int optionCode_var)
Protected Member Functions
bool operator== (const ControlManetRouting &)
Protected Attributes
::IPAddress srcAddress_var
::IPAddress destAddress_var
int optionCode_var
Detailed Description
Class generated from networklayer/ipv4/ControlManetRouting.msg by opp_msgc.
 packet ControlManetRouting
 {
     IPAddress srcAddress;
     IPAddress destAddress;
     int optionCode enum(ManetControlType) = MANET_ROUTE_NO_OPTION;
 }
Definition at line 52 of file ControlManetRouting_m.h.
Constructor & Destructor Documentation
ControlManetRouting::ControlManetRouting (const char * name = NULL, int kind = 0)
Referenced by dup().
ControlManetRouting::ControlManetRouting (const ControlManetRouting & other)
virtual ControlManetRouting::~ControlManetRouting () [virtual]
Member Function Documentation
virtual ControlManetRouting* ControlManetRouting::dup () const [inline, virtual]
Definition at line 67 of file ControlManetRouting_m.h.
{return new ControlManetRouting(*this);}
virtual const IPAddress& ControlManetRouting::getDestAddress () const [inline, virtual]
Definition at line 76 of file ControlManetRouting_m.h.
Referenced by getDestAddress().
{return const_cast<ControlManetRouting*>(this)->getDestAddress();}
virtual IPAddress& ControlManetRouting::getDestAddress () [virtual]
virtual int ControlManetRouting::getOptionCode () const [virtual]
virtual const IPAddress& ControlManetRouting::getSrcAddress () const [inline, virtual]
Definition at line 73 of file ControlManetRouting_m.h.
Referenced by getSrcAddress().
{return const_cast<ControlManetRouting*>(this)->getSrcAddress();}
virtual IPAddress& ControlManetRouting::getSrcAddress () [virtual]
ControlManetRouting& ControlManetRouting::operator= (const ControlManetRouting & other)
bool ControlManetRouting::operator== (const ControlManetRouting &) [protected]
virtual void ControlManetRouting::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ControlManetRouting::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ControlManetRouting::setDestAddress (const IPAddress & destAddress_var) [virtual]
virtual void ControlManetRouting::setOptionCode (int optionCode_var) [virtual]
virtual void ControlManetRouting::setSrcAddress (const IPAddress & srcAddress_var) [virtual]
Member Data Documentation
::IPAddress ControlManetRouting::destAddress_var [protected]
Definition at line 56 of file ControlManetRouting_m.h.
int ControlManetRouting::optionCode_var [protected]
Definition at line 57 of file ControlManetRouting_m.h.
::IPAddress ControlManetRouting::srcAddress_var [protected]
Definition at line 55 of file ControlManetRouting_m.h.
The documentation for this class was generated from the following file:
ControlManetRouting_m.h