INET Framework for OMNeT++/OMNEST: IPRoutingDecision Class Reference
IPRoutingDecision Class Reference
#include <IPControlInfo_m.h>
Public Member Functions
IPRoutingDecision ()
IPRoutingDecision (const IPRoutingDecision &other)
virtual ~IPRoutingDecision ()
IPRoutingDecision & operator= (const IPRoutingDecision &other)
virtual IPRoutingDecision * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getInterfaceId () const
virtual void setInterfaceId (int interfaceId_var)
virtual IPAddress & getNextHopAddr ()
virtual const IPAddress & getNextHopAddr () const
virtual void setNextHopAddr (const IPAddress &nextHopAddr_var)
Protected Member Functions
bool operator== (const IPRoutingDecision &)
Protected Attributes
int interfaceId_var
::IPAddress nextHopAddr_var
Detailed Description
Class generated from networklayer/contract/IPControlInfo.msg by opp_msgc.
 class IPRoutingDecision
 {
     int interfaceId = -1;
     IPAddress nextHopAddr;
 }
Definition at line 116 of file IPControlInfo_m.h.
Constructor & Destructor Documentation
IPRoutingDecision::IPRoutingDecision ()
Referenced by dup().
IPRoutingDecision::IPRoutingDecision (const IPRoutingDecision & other)
virtual IPRoutingDecision::~IPRoutingDecision () [virtual]
Member Function Documentation
virtual IPRoutingDecision* IPRoutingDecision::dup () const [inline, virtual]
Definition at line 130 of file IPControlInfo_m.h.
{return new IPRoutingDecision(*this);}
virtual int IPRoutingDecision::getInterfaceId () const [virtual]
Referenced by ARP::processARPPacket(), and ARP::processOutboundPacket().
virtual const IPAddress& IPRoutingDecision::getNextHopAddr () const [inline, virtual]
Definition at line 138 of file IPControlInfo_m.h.
Referenced by getNextHopAddr().
{return const_cast<IPRoutingDecision*>(this)->getNextHopAddr();}
virtual IPAddress& IPRoutingDecision::getNextHopAddr () [virtual]
Referenced by ARP::processOutboundPacket().
IPRoutingDecision& IPRoutingDecision::operator= (const IPRoutingDecision & other)
bool IPRoutingDecision::operator== (const IPRoutingDecision &) [protected]
virtual void IPRoutingDecision::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void IPRoutingDecision::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void IPRoutingDecision::setInterfaceId (int interfaceId_var) [virtual]
Referenced by IP::handleARP(), and IP::sendDatagramToOutput().
virtual void IPRoutingDecision::setNextHopAddr (const IPAddress & nextHopAddr_var) [virtual]
Referenced by IP::sendDatagramToOutput().
Member Data Documentation
int IPRoutingDecision::interfaceId_var [protected]
Definition at line 119 of file IPControlInfo_m.h.
::IPAddress IPRoutingDecision::nextHopAddr_var [protected]
Definition at line 120 of file IPControlInfo_m.h.
The documentation for this class was generated from the following file:
IPControlInfo_m.h