INET Framework for OMNeT++/OMNEST: SCTPCommand Class Reference
SCTPCommand Class Reference
#include <SCTPCommand_m.h>
Public Member Functions
SCTPCommand (const char *name=NULL)
SCTPCommand (const SCTPCommand &other)
virtual ~SCTPCommand ()
SCTPCommand & operator= (const SCTPCommand &other)
virtual SCTPCommand * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getAssocId () const
virtual void setAssocId (int assocId_var)
virtual int getSid () const
virtual void setSid (int sid_var)
virtual int getNumMsgs () const
virtual void setNumMsgs (int numMsgs_var)
virtual int getSsn () const
virtual void setSsn (int ssn_var)
virtual unsigned short getSendUnordered () const
virtual void setSendUnordered (unsigned short sendUnordered_var)
virtual double getLifetime () const
virtual void setLifetime (double lifetime_var)
virtual IPvXAddress & getLocalAddr ()
virtual const IPvXAddress & getLocalAddr () const
virtual void setLocalAddr (const IPvXAddress &localAddr_var)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual int getGate () const
virtual void setGate (int gate_var)
Protected Member Functions
bool operator== (const SCTPCommand &)
Protected Attributes
int assocId_var
int sid_var
int numMsgs_var
int ssn_var
unsigned short sendUnordered_var
double lifetime_var
::IPvXAddress localAddr_var
::IPvXAddress remoteAddr_var
int gate_var
Detailed Description
Class generated from transport/contract/SCTPCommand.msg by opp_msgc.
 class SCTPCommand extends cPacket
 {
     int assocId = -1;
     int sid = -1;
     int numMsgs = 1;
     int ssn = -1;
     unsigned short sendUnordered = false;
     double lifetime = 0;
     IPvXAddress localAddr = IPvXAddress("0.0.0.0");
     IPvXAddress remoteAddr = IPvXAddress("0.0.0.0");
     int gate = -1;
 }
Definition at line 54 of file SCTPCommand_m.h.
Constructor & Destructor Documentation
SCTPCommand::SCTPCommand (const char * name = NULL)
Referenced by dup().
SCTPCommand::SCTPCommand (const SCTPCommand & other)
virtual SCTPCommand::~SCTPCommand () [virtual]
Member Function Documentation
virtual SCTPCommand* SCTPCommand::dup () const [inline, virtual]
Reimplemented in SCTPErrorInfo, SCTPOpenCommand, SCTPSendCommand, SCTPConnectInfo, SCTPStatusInfo, SCTPPathInfo, SCTPResetInfo, SCTPInfo, and SCTPRcvCommand.
Definition at line 75 of file SCTPCommand_m.h.
Referenced by SCTPServer::handleMessage().
{return new SCTPCommand(*this);}
virtual int SCTPCommand::getAssocId () const [virtual]
Referenced by SCTPSocket::connect(), SCTPServer::handleMessage(), SCTPPeer::handleMessage(), SCTP::handleMessage(), SCTPSocket::listen(), SCTPServer::makeAbortNotification(), SCTPServer::makeReceiveRequest(), SCTPPeer::socketDataNotificationArrived(), and SCTPClient::socketDataNotificationArrived().
virtual int SCTPCommand::getGate () const [virtual]
Referenced by SCTP::handleMessage().
virtual double SCTPCommand::getLifetime () const [virtual]
virtual const IPvXAddress& SCTPCommand::getLocalAddr () const [inline, virtual]
Definition at line 93 of file SCTPCommand_m.h.
Referenced by getLocalAddr().
{return const_cast<SCTPCommand*>(this)->getLocalAddr();}
virtual IPvXAddress& SCTPCommand::getLocalAddr () [virtual]
Referenced by SCTPSocket::processMessage().
virtual int SCTPCommand::getNumMsgs () const [virtual]
Referenced by SCTPPeer::handleMessage(), SCTPServer::makeAbortNotification(), SCTPServer::makeReceiveRequest(), SCTPAssociation::process_RECEIVE_REQUEST(), SCTPSocket::processMessage(), SCTPPeer::socketDataNotificationArrived(), and SCTPClient::socketDataNotificationArrived().
virtual const IPvXAddress& SCTPCommand::getRemoteAddr () const [inline, virtual]
Reimplemented in SCTPOpenCommand, and SCTPResetInfo.
Definition at line 96 of file SCTPCommand_m.h.
Referenced by getRemoteAddr().
{return const_cast<SCTPCommand*>(this)->getRemoteAddr();}
virtual IPvXAddress& SCTPCommand::getRemoteAddr () [virtual]
Reimplemented in SCTPOpenCommand, and SCTPResetInfo.
Referenced by SCTPAssociation::process_SEND(), and SCTPSocket::processMessage().
virtual unsigned short SCTPCommand::getSendUnordered () const [virtual]
Referenced by SCTPServer::handleMessage(), SCTPPeer::handleMessage(), SCTPAssociation::process_SEND(), SCTPPeer::socketDataArrived(), and SCTPClient::socketDataArrived().
virtual int SCTPCommand::getSid () const [virtual]
Referenced by SCTPPeer::handleMessage(), SCTPServer::makeAbortNotification(), SCTPServer::makeReceiveRequest(), SCTPAssociation::process_RECEIVE_REQUEST(), SCTPAssociation::process_SEND(), SCTPPeer::socketDataNotificationArrived(), and SCTPClient::socketDataNotificationArrived().
virtual int SCTPCommand::getSsn () const [virtual]
SCTPCommand& SCTPCommand::operator= (const SCTPCommand & other)
Reimplemented in SCTPErrorInfo, SCTPOpenCommand, SCTPSendCommand, SCTPConnectInfo, SCTPStatusInfo, SCTPPathInfo, SCTPResetInfo, SCTPInfo, and SCTPRcvCommand.
bool SCTPCommand::operator== (const SCTPCommand &) [protected]
Reimplemented in SCTPErrorInfo, SCTPOpenCommand, SCTPSendCommand, SCTPConnectInfo, SCTPStatusInfo, SCTPPathInfo, SCTPResetInfo, SCTPInfo, and SCTPRcvCommand.
virtual void SCTPCommand::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in SCTPErrorInfo, SCTPOpenCommand, SCTPSendCommand, SCTPConnectInfo, SCTPStatusInfo, SCTPPathInfo, SCTPResetInfo, SCTPInfo, and SCTPRcvCommand.
Referenced by doPacking().
virtual void SCTPCommand::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in SCTPErrorInfo, SCTPOpenCommand, SCTPSendCommand, SCTPConnectInfo, SCTPStatusInfo, SCTPPathInfo, SCTPResetInfo, SCTPInfo, and SCTPRcvCommand.
Referenced by doUnpacking().
virtual void SCTPCommand::setAssocId (int assocId_var) [virtual]
Referenced by SCTPSocket::abort(), SCTPSocket::close(), SCTPSocket::connect(), SCTPSocket::connectx(), SCTPServer::generateAndSend(), SCTPPeer::generateAndSend(), SCTPServer::handleMessage(), SCTPPeer::handleMessage(), SCTPServer::handleTimer(), SCTPPeer::handleTimer(), SCTPSocket::listen(), SCTPServer::makeAbortNotification(), SCTPServer::makeDefaultReceive(), SCTPServer::makeReceiveRequest(), SCTPAssociation::pathStatusIndication(), SCTPAssociation::pushUlp(), SCTPSocket::requestStatus(), SCTPSocket::send(), SCTPAssociation::sendDataArrivedNotification(), SCTPAssociation::sendEstabIndicationToApp(), SCTPAssociation::sendIndicationToApp(), SCTPPeer::sendQueueRequest(), SCTPClient::sendQueueRequest(), SCTPClient::setPrimaryPath(), SCTPSocket::shutdown(), SCTPPeer::shutdownReceivedArrived(), SCTPClient::shutdownReceivedArrived(), SCTPPeer::socketDataNotificationArrived(), and SCTPClient::socketDataNotificationArrived().
virtual void SCTPCommand::setGate (int gate_var) [virtual]
Referenced by SCTPAssociation::pushUlp().
virtual void SCTPCommand::setLifetime (double lifetime_var) [virtual]
virtual void SCTPCommand::setLocalAddr (const IPvXAddress & localAddr_var) [virtual]
Referenced by SCTPAssociation::pushUlp(), SCTPAssociation::sendEstabIndicationToApp(), and SCTPAssociation::sendIndicationToApp().
virtual void SCTPCommand::setNumMsgs (int numMsgs_var) [virtual]
Referenced by SCTPPeer::handleMessage(), SCTPServer::makeAbortNotification(), SCTPServer::makeDefaultReceive(), SCTPServer::makeReceiveRequest(), SCTPAssociation::sendDataArrivedNotification(), SCTPAssociation::sendEstabIndicationToApp(), SCTPAssociation::sendIndicationToApp(), SCTPPeer::socketDataNotificationArrived(), and SCTPClient::socketDataNotificationArrived().
virtual void SCTPCommand::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Reimplemented in SCTPOpenCommand, and SCTPResetInfo.
Referenced by SCTPAssociation::pushUlp(), SCTPAssociation::sendEstabIndicationToApp(), and SCTPAssociation::sendIndicationToApp().
virtual void SCTPCommand::setSendUnordered (unsigned short sendUnordered_var) [virtual]
Referenced by SCTPServer::generateAndSend(), SCTPPeer::generateAndSend(), SCTPServer::handleMessage(), SCTPPeer::handleMessage(), SCTPAssociation::pushUlp(), and SCTPSocket::send().
virtual void SCTPCommand::setSid (int sid_var) [virtual]
Referenced by SCTPServer::generateAndSend(), SCTPPeer::generateAndSend(), SCTPServer::handleMessage(), SCTPPeer::handleMessage(), SCTPServer::makeAbortNotification(), SCTPServer::makeDefaultReceive(), SCTPServer::makeReceiveRequest(), SCTPAssociation::pushUlp(), SCTPSocket::send(), SCTPAssociation::sendDataArrivedNotification(), SCTPPeer::socketDataNotificationArrived(), and SCTPClient::socketDataNotificationArrived().
virtual void SCTPCommand::setSsn (int ssn_var) [virtual]
Referenced by SCTPAssociation::pushUlp().
Member Data Documentation
int SCTPCommand::assocId_var [protected]
Definition at line 57 of file SCTPCommand_m.h.
int SCTPCommand::gate_var [protected]
Definition at line 65 of file SCTPCommand_m.h.
double SCTPCommand::lifetime_var [protected]
Definition at line 62 of file SCTPCommand_m.h.
::IPvXAddress SCTPCommand::localAddr_var [protected]
Definition at line 63 of file SCTPCommand_m.h.
int SCTPCommand::numMsgs_var [protected]
Definition at line 59 of file SCTPCommand_m.h.
::IPvXAddress SCTPCommand::remoteAddr_var [protected]
Reimplemented in SCTPOpenCommand, and SCTPResetInfo.
Definition at line 64 of file SCTPCommand_m.h.
unsigned short SCTPCommand::sendUnordered_var [protected]
Definition at line 61 of file SCTPCommand_m.h.
int SCTPCommand::sid_var [protected]
Definition at line 58 of file SCTPCommand_m.h.
int SCTPCommand::ssn_var [protected]
Definition at line 60 of file SCTPCommand_m.h.
The documentation for this class was generated from the following file:
SCTPCommand_m.h