INET Framework for OMNeT++/OMNEST: SCTPShutdownChunk Class Reference
SCTPShutdownChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPShutdownChunk (const char *name=NULL, int kind=0)
SCTPShutdownChunk (const SCTPShutdownChunk &other)
virtual ~SCTPShutdownChunk ()
SCTPShutdownChunk & operator= (const SCTPShutdownChunk &other)
virtual SCTPShutdownChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32 getCumTsnAck () const
virtual void setCumTsnAck (uint32 cumTsnAck_var)
Protected Member Functions
bool operator== (const SCTPShutdownChunk &)
Protected Attributes
uint32 cumTsnAck_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPShutdownChunk extends SCTPChunk
 {
      uint32 cumTsnAck;
 }
Definition at line 891 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPShutdownChunk::SCTPShutdownChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPShutdownChunk::SCTPShutdownChunk (const SCTPShutdownChunk & other)
virtual SCTPShutdownChunk::~SCTPShutdownChunk () [virtual]
Member Function Documentation
virtual SCTPShutdownChunk* SCTPShutdownChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 904 of file SCTPMessage_m.h.
Referenced by SCTPAssociation::retransmitShutdown(), and SCTPAssociation::sendShutdown().
{return new SCTPShutdownChunk(*this);}
virtual uint32 SCTPShutdownChunk::getCumTsnAck () const [virtual]
Referenced by SCTPAssociation::process_RCV_Message(), and TCPDumper::sctpDump().
SCTPShutdownChunk& SCTPShutdownChunk::operator= (const SCTPShutdownChunk & other)
Reimplemented from SCTPChunk.
bool SCTPShutdownChunk::operator== (const SCTPShutdownChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPShutdownChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPShutdownChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPShutdownChunk::setCumTsnAck (uint32 cumTsnAck_var) [virtual]
Referenced by SCTPAssociation::sendShutdown().
Member Data Documentation
uint32 SCTPShutdownChunk::cumTsnAck_var [protected]
Definition at line 894 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h