INET Framework for OMNeT++/OMNEST: LDPNotify Class Reference
LDPNotify Class Reference
#include <LDPPacket_m.h>
Public Member Functions
LDPNotify (const char *name=NULL, int kind=0)
LDPNotify (const LDPNotify &other)
virtual ~LDPNotify ()
LDPNotify & operator= (const LDPNotify &other)
virtual LDPNotify * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getStatus () const
virtual void setStatus (int status_var)
virtual FEC_TLV & getFec ()
virtual const FEC_TLV & getFec () const
virtual void setFec (const FEC_TLV &fec_var)
Protected Member Functions
bool operator== (const LDPNotify &)
Protected Attributes
int status_var
::FEC_TLV fec_var
Detailed Description
Class generated from networklayer/ldp/LDPPacket.msg by opp_msgc.
 packet LDPNotify extends LDPPacket
 {
     int status;
     FEC_TLV fec;
 }
Definition at line 261 of file LDPPacket_m.h.
Constructor & Destructor Documentation
LDPNotify::LDPNotify (const char * name = NULL, int kind = 0)
Referenced by dup().
LDPNotify::LDPNotify (const LDPNotify & other)
virtual LDPNotify::~LDPNotify () [virtual]
Member Function Documentation
virtual LDPNotify* LDPNotify::dup () const [inline, virtual]
Reimplemented from LDPPacket.
Definition at line 275 of file LDPPacket_m.h.
{return new LDPNotify(*this);}
virtual const FEC_TLV& LDPNotify::getFec () const [inline, virtual]
Definition at line 283 of file LDPPacket_m.h.
Referenced by getFec().
{return const_cast<LDPNotify*>(this)->getFec();}
virtual FEC_TLV& LDPNotify::getFec () [virtual]
Referenced by LDP::processNOTIFICATION().
virtual int LDPNotify::getStatus () const [virtual]
Referenced by LDP::processNOTIFICATION().
LDPNotify& LDPNotify::operator= (const LDPNotify & other)
Reimplemented from LDPPacket.
bool LDPNotify::operator== (const LDPNotify &) [protected]
Reimplemented from LDPPacket.
virtual void LDPNotify::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doPacking().
virtual void LDPNotify::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from LDPPacket.
Referenced by doUnpacking().
virtual void LDPNotify::setFec (const FEC_TLV & fec_var) [virtual]
Referenced by LDP::sendNotify().
virtual void LDPNotify::setStatus (int status_var) [virtual]
Referenced by LDP::sendNotify().
Member Data Documentation
::FEC_TLV LDPNotify::fec_var [protected]
Definition at line 265 of file LDPPacket_m.h.
int LDPNotify::status_var [protected]
Definition at line 264 of file LDPPacket_m.h.
The documentation for this class was generated from the following file:
LDPPacket_m.h