INET Framework for OMNeT++/OMNEST: ICMPv6TimeExceededMsg Class Reference
ICMPv6TimeExceededMsg Class Reference
#include <ICMPv6Message_m.h>
Public Member Functions
ICMPv6TimeExceededMsg (const char *name=NULL, int kind=0)
ICMPv6TimeExceededMsg (const ICMPv6TimeExceededMsg &other)
virtual ~ICMPv6TimeExceededMsg ()
ICMPv6TimeExceededMsg & operator= (const ICMPv6TimeExceededMsg &other)
virtual ICMPv6TimeExceededMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCode () const
virtual void setCode (int code_var)
Protected Member Functions
bool operator== (const ICMPv6TimeExceededMsg &)
Protected Attributes
int code_var
Detailed Description
Class generated from networklayer/icmpv6/ICMPv6Message.msg by opp_msgc.
 packet ICMPv6TimeExceededMsg extends ICMPv6Message
 {
     int code enum(ICMPv6_TIME_EX);
 }
Definition at line 239 of file ICMPv6Message_m.h.
Constructor & Destructor Documentation
ICMPv6TimeExceededMsg::ICMPv6TimeExceededMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPv6TimeExceededMsg::ICMPv6TimeExceededMsg (const ICMPv6TimeExceededMsg & other)
virtual ICMPv6TimeExceededMsg::~ICMPv6TimeExceededMsg () [virtual]
Member Function Documentation
virtual ICMPv6TimeExceededMsg* ICMPv6TimeExceededMsg::dup () const [inline, virtual]
Reimplemented from ICMPv6Message.
Definition at line 252 of file ICMPv6Message_m.h.
{return new ICMPv6TimeExceededMsg(*this);}
virtual int ICMPv6TimeExceededMsg::getCode () const [virtual]
Referenced by IPv6ErrorHandling::handleMessage().
ICMPv6TimeExceededMsg& ICMPv6TimeExceededMsg::operator= (const ICMPv6TimeExceededMsg & other)
Reimplemented from ICMPv6Message.
bool ICMPv6TimeExceededMsg::operator== (const ICMPv6TimeExceededMsg &) [protected]
Reimplemented from ICMPv6Message.
virtual void ICMPv6TimeExceededMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doPacking().
virtual void ICMPv6TimeExceededMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doUnpacking().
virtual void ICMPv6TimeExceededMsg::setCode (int code_var) [virtual]
Referenced by ICMPv6::createTimeExceededMsg().
Member Data Documentation
int ICMPv6TimeExceededMsg::code_var [protected]
Definition at line 242 of file ICMPv6Message_m.h.
The documentation for this class was generated from the following file:
ICMPv6Message_m.h