INET Framework for OMNeT++/OMNEST: PathNotifyMsg Class Reference
PathNotifyMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
PathNotifyMsg (const char *name=NULL, int kind=0)
PathNotifyMsg (const PathNotifyMsg &other)
virtual ~PathNotifyMsg ()
PathNotifyMsg & operator= (const PathNotifyMsg &other)
virtual PathNotifyMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual SessionObj_t & getSession ()
virtual const SessionObj_t & getSession () const
virtual void setSession (const SessionObj_t &session_var)
virtual SenderTemplateObj_t & getSender ()
virtual const SenderTemplateObj_t & getSender () const
virtual void setSender (const SenderTemplateObj_t &sender_var)
virtual int getStatus () const
virtual void setStatus (int status_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const PathNotifyMsg &)
Protected Attributes
::SessionObj_t session_var
::SenderTemplateObj_t sender_var
int status_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message PathNotifyMsg extends SignallingMsg
 {
     SessionObj_t session;
     SenderTemplateObj_t sender;
     int status;
     int command = MSG_PATH_NOTIFY;
 }
Definition at line 365 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
PathNotifyMsg::PathNotifyMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
PathNotifyMsg::PathNotifyMsg (const PathNotifyMsg & other)
virtual PathNotifyMsg::~PathNotifyMsg () [virtual]
Member Function Documentation
virtual PathNotifyMsg* PathNotifyMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 381 of file SignallingMsg_m.h.
{return new PathNotifyMsg(*this);}
virtual int PathNotifyMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual const SenderTemplateObj_t& PathNotifyMsg::getSender () const [inline, virtual]
Definition at line 390 of file SignallingMsg_m.h.
Referenced by getSender().
{return const_cast<PathNotifyMsg*>(this)->getSender();}
virtual SenderTemplateObj_t& PathNotifyMsg::getSender () [virtual]
Referenced by RSVP::processPATH_NOTIFY().
virtual const SessionObj_t& PathNotifyMsg::getSession () const [inline, virtual]
Definition at line 387 of file SignallingMsg_m.h.
Referenced by getSession().
{return const_cast<PathNotifyMsg*>(this)->getSession();}
virtual SessionObj_t& PathNotifyMsg::getSession () [virtual]
Referenced by RSVP::processPATH_NOTIFY().
virtual int PathNotifyMsg::getStatus () const [virtual]
Referenced by RSVP::processPATH_NOTIFY().
PathNotifyMsg& PathNotifyMsg::operator= (const PathNotifyMsg & other)
Reimplemented from SignallingMsg.
bool PathNotifyMsg::operator== (const PathNotifyMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void PathNotifyMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void PathNotifyMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void PathNotifyMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void PathNotifyMsg::setSender (const SenderTemplateObj_t & sender_var) [virtual]
Referenced by RSVP::sendPathNotify().
virtual void PathNotifyMsg::setSession (const SessionObj_t & session_var) [virtual]
Referenced by RSVP::sendPathNotify().
virtual void PathNotifyMsg::setStatus (int status_var) [virtual]
Referenced by RSVP::sendPathNotify().
Member Data Documentation
int PathNotifyMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 371 of file SignallingMsg_m.h.
::SenderTemplateObj_t PathNotifyMsg::sender_var [protected]
Definition at line 369 of file SignallingMsg_m.h.
::SessionObj_t PathNotifyMsg::session_var [protected]
Definition at line 368 of file SignallingMsg_m.h.
int PathNotifyMsg::status_var [protected]
Definition at line 370 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h