INET Framework for OMNeT++/OMNEST: OSPFLinkStateUpdatePacket Class Reference
OSPFLinkStateUpdatePacket Class Reference
#include <OSPFPacket_m.h>
Public Member Functions
OSPFLinkStateUpdatePacket (const char *name=NULL, int kind=0)
OSPFLinkStateUpdatePacket (const OSPFLinkStateUpdatePacket &other)
virtual ~OSPFLinkStateUpdatePacket ()
OSPFLinkStateUpdatePacket & operator= (const OSPFLinkStateUpdatePacket &other)
virtual OSPFLinkStateUpdatePacket * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned long getNumberOfLSAs () const
virtual void setNumberOfLSAs (unsigned long numberOfLSAs_var)
virtual void setRouterLSAsArraySize (unsigned int size)
virtual unsigned int getRouterLSAsArraySize () const
virtual OSPFRouterLSA & getRouterLSAs (unsigned int k)
virtual const OSPFRouterLSA & getRouterLSAs (unsigned int k) const
virtual void setRouterLSAs (unsigned int k, const OSPFRouterLSA &routerLSAs_var)
virtual void setNetworkLSAsArraySize (unsigned int size)
virtual unsigned int getNetworkLSAsArraySize () const
virtual OSPFNetworkLSA & getNetworkLSAs (unsigned int k)
virtual const OSPFNetworkLSA & getNetworkLSAs (unsigned int k) const
virtual void setNetworkLSAs (unsigned int k, const OSPFNetworkLSA &networkLSAs_var)
virtual void setSummaryLSAsArraySize (unsigned int size)
virtual unsigned int getSummaryLSAsArraySize () const
virtual OSPFSummaryLSA & getSummaryLSAs (unsigned int k)
virtual const OSPFSummaryLSA & getSummaryLSAs (unsigned int k) const
virtual void setSummaryLSAs (unsigned int k, const OSPFSummaryLSA &summaryLSAs_var)
virtual void setAsExternalLSAsArraySize (unsigned int size)
virtual unsigned int getAsExternalLSAsArraySize () const
virtual OSPFASExternalLSA & getAsExternalLSAs (unsigned int k)
virtual const OSPFASExternalLSA & getAsExternalLSAs (unsigned int k) const
virtual void setAsExternalLSAs (unsigned int k, const OSPFASExternalLSA &asExternalLSAs_var)
Protected Member Functions
bool operator== (const OSPFLinkStateUpdatePacket &)
Protected Attributes
unsigned long numberOfLSAs_var
::OSPFRouterLSA * routerLSAs_var
unsigned int routerLSAs_arraysize
::OSPFNetworkLSA * networkLSAs_var
unsigned int networkLSAs_arraysize
::OSPFSummaryLSA * summaryLSAs_var
unsigned int summaryLSAs_arraysize
::OSPFASExternalLSA * asExternalLSAs_var
unsigned int asExternalLSAs_arraysize
Detailed Description
Class generated from networklayer/ospfv2/OSPFPacket.msg by opp_msgc.
 packet OSPFLinkStateUpdatePacket extends OSPFPacket
 {
     unsigned long numberOfLSAs;
     OSPFRouterLSA routerLSAs[];
     OSPFNetworkLSA networkLSAs[];
     OSPFSummaryLSA summaryLSAs[];
     OSPFASExternalLSA asExternalLSAs[];
 }
Definition at line 812 of file OSPFPacket_m.h.
Constructor & Destructor Documentation
OSPFLinkStateUpdatePacket::OSPFLinkStateUpdatePacket (const char * name = NULL, int kind = 0)
Referenced by dup().
OSPFLinkStateUpdatePacket::OSPFLinkStateUpdatePacket (const OSPFLinkStateUpdatePacket & other)
virtual OSPFLinkStateUpdatePacket::~OSPFLinkStateUpdatePacket () [virtual]
Member Function Documentation
virtual OSPFLinkStateUpdatePacket* OSPFLinkStateUpdatePacket::dup () const [inline, virtual]
Reimplemented from OSPFPacket.
Definition at line 833 of file OSPFPacket_m.h.
{return new OSPFLinkStateUpdatePacket(*this);}
virtual const OSPFASExternalLSA& OSPFLinkStateUpdatePacket::getAsExternalLSAs (unsigned int k) const [inline, virtual]
Definition at line 858 of file OSPFPacket_m.h.
Referenced by getAsExternalLSAs().
{return const_cast<OSPFLinkStateUpdatePacket*>(this)->getAsExternalLSAs(k);}
virtual OSPFASExternalLSA& OSPFLinkStateUpdatePacket::getAsExternalLSAs (unsigned int k) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual unsigned int OSPFLinkStateUpdatePacket::getAsExternalLSAsArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual const OSPFNetworkLSA& OSPFLinkStateUpdatePacket::getNetworkLSAs (unsigned int k) const [inline, virtual]
Definition at line 848 of file OSPFPacket_m.h.
Referenced by getNetworkLSAs().
{return const_cast<OSPFLinkStateUpdatePacket*>(this)->getNetworkLSAs(k);}
virtual OSPFNetworkLSA& OSPFLinkStateUpdatePacket::getNetworkLSAs (unsigned int k) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual unsigned int OSPFLinkStateUpdatePacket::getNetworkLSAsArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual unsigned long OSPFLinkStateUpdatePacket::getNumberOfLSAs () const [virtual]
virtual const OSPFRouterLSA& OSPFLinkStateUpdatePacket::getRouterLSAs (unsigned int k) const [inline, virtual]
Definition at line 843 of file OSPFPacket_m.h.
Referenced by getRouterLSAs().
{return const_cast<OSPFLinkStateUpdatePacket*>(this)->getRouterLSAs(k);}
virtual OSPFRouterLSA& OSPFLinkStateUpdatePacket::getRouterLSAs (unsigned int k) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual unsigned int OSPFLinkStateUpdatePacket::getRouterLSAsArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual const OSPFSummaryLSA& OSPFLinkStateUpdatePacket::getSummaryLSAs (unsigned int k) const [inline, virtual]
Definition at line 853 of file OSPFPacket_m.h.
Referenced by getSummaryLSAs().
{return const_cast<OSPFLinkStateUpdatePacket*>(this)->getSummaryLSAs(k);}
virtual OSPFSummaryLSA& OSPFLinkStateUpdatePacket::getSummaryLSAs (unsigned int k) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual unsigned int OSPFLinkStateUpdatePacket::getSummaryLSAsArraySize () const [virtual]
Referenced by OSPF::MessageHandler::PrintLinkStateUpdatePacket(), OSPF::LinkStateUpdateHandler::ProcessPacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
OSPFLinkStateUpdatePacket& OSPFLinkStateUpdatePacket::operator= (const OSPFLinkStateUpdatePacket & other)
Reimplemented from OSPFPacket.
bool OSPFLinkStateUpdatePacket::operator== (const OSPFLinkStateUpdatePacket &) [protected]
Reimplemented from OSPFPacket.
virtual void OSPFLinkStateUpdatePacket::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doPacking().
virtual void OSPFLinkStateUpdatePacket::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OSPFPacket.
Referenced by doUnpacking().
virtual void OSPFLinkStateUpdatePacket::setAsExternalLSAs (unsigned int k, const OSPFASExternalLSA & asExternalLSAs_var) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setAsExternalLSAsArraySize (unsigned int size) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setNetworkLSAs (unsigned int k, const OSPFNetworkLSA & networkLSAs_var) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setNetworkLSAsArraySize (unsigned int size) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setNumberOfLSAs (unsigned long numberOfLSAs_var) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setRouterLSAs (unsigned int k, const OSPFRouterLSA & routerLSAs_var) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setRouterLSAsArraySize (unsigned int size) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setSummaryLSAs (unsigned int k, const OSPFSummaryLSA & summaryLSAs_var) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
virtual void OSPFLinkStateUpdatePacket::setSummaryLSAsArraySize (unsigned int size) [virtual]
Referenced by OSPF::Interface::CreateUpdatePacket(), and OSPF::Neighbor::RetransmitUpdatePacket().
Member Data Documentation
unsigned int OSPFLinkStateUpdatePacket::asExternalLSAs_arraysize [protected]
Definition at line 823 of file OSPFPacket_m.h.
::OSPFASExternalLSA* OSPFLinkStateUpdatePacket::asExternalLSAs_var [protected]
Definition at line 822 of file OSPFPacket_m.h.
unsigned int OSPFLinkStateUpdatePacket::networkLSAs_arraysize [protected]
Definition at line 819 of file OSPFPacket_m.h.
::OSPFNetworkLSA* OSPFLinkStateUpdatePacket::networkLSAs_var [protected]
Definition at line 818 of file OSPFPacket_m.h.
unsigned long OSPFLinkStateUpdatePacket::numberOfLSAs_var [protected]
Definition at line 815 of file OSPFPacket_m.h.
unsigned int OSPFLinkStateUpdatePacket::routerLSAs_arraysize [protected]
Definition at line 817 of file OSPFPacket_m.h.
::OSPFRouterLSA* OSPFLinkStateUpdatePacket::routerLSAs_var [protected]
Definition at line 816 of file OSPFPacket_m.h.
unsigned int OSPFLinkStateUpdatePacket::summaryLSAs_arraysize [protected]
Definition at line 821 of file OSPFPacket_m.h.
::OSPFSummaryLSA* OSPFLinkStateUpdatePacket::summaryLSAs_var [protected]
Definition at line 820 of file OSPFPacket_m.h.
The documentation for this class was generated from the following file:
OSPFPacket_m.h