INET Framework for OMNeT++/OMNEST: RTCPByePacket Class Reference
RTCPByePacket Class Reference
#include <RTCPPacket.h>
Public Member Functions
RTCPByePacket (const char *name=NULL)
RTCPByePacket (const RTCPByePacket &rtcpByePacket)
virtual ~RTCPByePacket ()
RTCPByePacket & operator= (const RTCPByePacket &rtcpByePacket)
virtual RTCPByePacket * dup () const
virtual uint32 getSSRC ()
virtual void setSSRC (uint32 ssrc)
Protected Attributes
uint32 _ssrc
Detailed Description
An RTCPByePacket is used to indicate that an rtp endsystem has left the session. This implementation offers less functionality than described in the rfc: Only one ssrc identifier can be stored in it and the reason for leaving isn't transmitted.
Definition at line 377 of file RTCPPacket.h.
Constructor & Destructor Documentation
RTCPByePacket::RTCPByePacket (const char * name = NULL)
Default constructor.
Definition at line 349 of file RTCPPacket.cc.
Referenced by dup().
                                             : RTCPPacket(name) {
    _packetType = RTCP_PT_BYE;
    _count = 1;
    _ssrc = 0;
    // space for the ssrc identifier
    addByteLength(4);
};
RTCPByePacket::RTCPByePacket (const RTCPByePacket & rtcpByePacket)
Copy constructor.
Definition at line 358 of file RTCPPacket.cc.
                                                               : RTCPPacket() {
    setName(rtcpByePacket.getName());
    operator=(rtcpByePacket);
};
RTCPByePacket::~RTCPByePacket () [virtual]
Destructor.
Definition at line 364 of file RTCPPacket.cc.
{
};
Member Function Documentation
RTCPByePacket * RTCPByePacket::dup () const [virtual]
Duplicates the RTCPByePacket by calling the copy constructor.
Reimplemented from RTCPPacket.
Definition at line 376 of file RTCPPacket.cc.
{
    return new RTCPByePacket(*this);
};
uint32 RTCPByePacket::getSSRC () [virtual]
Returns the ssrc identifier.
Definition at line 381 of file RTCPPacket.cc.
Referenced by RTCP::processIncomingRTCPPacket().
{
    return _ssrc;
};
RTCPByePacket & RTCPByePacket::operator= (const RTCPByePacket & rtcpByePacket)
Assignment operator.
Reimplemented from RTCPPacket.
Definition at line 369 of file RTCPPacket.cc.
Referenced by RTCPByePacket().
{
    RTCPPacket::operator=(rtcpByePacket);
    _ssrc = rtcpByePacket._ssrc;
    return *this;
};
void RTCPByePacket::setSSRC (uint32 ssrc) [virtual]
Sets the ssrc identifier.
Definition at line 386 of file RTCPPacket.cc.
Referenced by RTCP::createPacket().
{
    _ssrc = ssrc;
};
Member Data Documentation
uint32 RTCPByePacket::_ssrc [protected]
The ssrc identifier.
Definition at line 420 of file RTCPPacket.h.
Referenced by getSSRC(), operator=(), RTCPByePacket(), and setSSRC().
The documentation for this class was generated from the following files:
RTCPPacket.h
RTCPPacket.cc