INET Framework for OMNeT++/OMNEST: RSVPPathTear_Base Class Reference
RSVPPathTear_Base Class Reference
#include <RSVPPathMsg_m.h>
Public Member Functions
virtual ~RSVPPathTear_Base ()
virtual RSVPPathTear_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual RsvpHopObj_t & getHop ()
virtual const RsvpHopObj_t & getHop () const
virtual void setHop (const RsvpHopObj_t &hop_var)
virtual SenderTemplateObj_t & getSenderTemplate ()
virtual const SenderTemplateObj_t & getSenderTemplate () const
virtual void setSenderTemplate (const SenderTemplateObj_t &senderTemplate_var)
virtual bool getForce () const
virtual void setForce (bool force_var)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind_var)
Protected Member Functions
bool operator== (const RSVPPathTear_Base &)
RSVPPathTear_Base (const char *name=NULL, int kind=0)
RSVPPathTear_Base (const RSVPPathTear_Base &other)
RSVPPathTear_Base & operator= (const RSVPPathTear_Base &other)
Protected Attributes
::RsvpHopObj_t hop_var
::SenderTemplateObj_t senderTemplate_var
bool force_var
int rsvpKind_var
Detailed Description
Class generated from networklayer/rsvp_te/RSVPPathMsg.msg by opp_msgc.
 packet RSVPPathTear extends RSVPPacket
 {
     (true);
     RsvpHopObj_t hop;
     SenderTemplateObj_t senderTemplate;
     bool force;
     int rsvpKind = PTEAR_MESSAGE;
 }
RSVPPathTear_Base is only useful if it gets subclassed, and RSVPPathTear is derived from it. The minimum code to be written for RSVPPathTear is the following:
 class RSVPPathTear : public RSVPPathTear_Base
 {
   public:
     RSVPPathTear(const char *name=NULL, int kind=0) : RSVPPathTear_Base(name,kind) {}
     RSVPPathTear(const RSVPPathTear& other) : RSVPPathTear_Base(other.getName()) {operator=(other);}
     RSVPPathTear& operator=(const RSVPPathTear& other) {RSVPPathTear_Base::operator=(other); return *this;}
     virtual RSVPPathTear *dup() const {return new RSVPPathTear(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from RSVPPathTear_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(RSVPPathTear);
Definition at line 138 of file RSVPPathMsg_m.h.
Constructor & Destructor Documentation
RSVPPathTear_Base::RSVPPathTear_Base (const char * name = NULL, int kind = 0) [protected]
RSVPPathTear_Base::RSVPPathTear_Base (const RSVPPathTear_Base & other) [protected]
virtual RSVPPathTear_Base::~RSVPPathTear_Base () [virtual]
Member Function Documentation
virtual RSVPPathTear_Base* RSVPPathTear_Base::dup () const [inline, virtual]
Reimplemented from RSVPPacket.
Reimplemented in RSVPPathTear.
Definition at line 156 of file RSVPPathMsg_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class RSVPPathTear");}
virtual bool RSVPPathTear_Base::getForce () const [virtual]
Referenced by RSVP::processPathTearMsg().
virtual const RsvpHopObj_t& RSVPPathTear_Base::getHop () const [inline, virtual]
Definition at line 162 of file RSVPPathMsg_m.h.
Referenced by getHop().
{return const_cast<RSVPPathTear_Base*>(this)->getHop();}
virtual RsvpHopObj_t& RSVPPathTear_Base::getHop () [virtual]
Referenced by RSVPPathTear::getLIH(), and RSVPPathTear::getNHOP().
virtual int RSVPPathTear_Base::getRsvpKind () const [virtual]
Reimplemented from RSVPMessage.
virtual const SenderTemplateObj_t& RSVPPathTear_Base::getSenderTemplate () const [inline, virtual]
Definition at line 165 of file RSVPPathMsg_m.h.
Referenced by getSenderTemplate().
{return const_cast<RSVPPathTear_Base*>(this)->getSenderTemplate();}
virtual SenderTemplateObj_t& RSVPPathTear_Base::getSenderTemplate () [virtual]
Referenced by RSVPPathTear::getLspId(), RSVPPathTear::getSrcAddress(), and RSVP::processPathTearMsg().
RSVPPathTear_Base& RSVPPathTear_Base::operator= (const RSVPPathTear_Base & other) [protected]
Reimplemented from RSVPPacket.
Reimplemented in RSVPPathTear.
bool RSVPPathTear_Base::operator== (const RSVPPathTear_Base &) [protected]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathTear_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathTear_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from RSVPPacket_Base.
virtual void RSVPPathTear_Base::setForce (bool force_var) [virtual]
Referenced by RSVP::sendPathTearMessage().
virtual void RSVPPathTear_Base::setHop (const RsvpHopObj_t & hop_var) [virtual]
Referenced by RSVP::sendPathTearMessage().
virtual void RSVPPathTear_Base::setRsvpKind (int rsvpKind_var) [virtual]
Reimplemented from RSVPMessage.
virtual void RSVPPathTear_Base::setSenderTemplate (const SenderTemplateObj_t & senderTemplate_var) [virtual]
Referenced by RSVP::sendPathTearMessage().
Member Data Documentation
bool RSVPPathTear_Base::force_var [protected]
Definition at line 143 of file RSVPPathMsg_m.h.
::RsvpHopObj_t RSVPPathTear_Base::hop_var [protected]
Definition at line 141 of file RSVPPathMsg_m.h.
int RSVPPathTear_Base::rsvpKind_var [protected]
Reimplemented from RSVPMessage.
Definition at line 144 of file RSVPPathMsg_m.h.
::SenderTemplateObj_t RSVPPathTear_Base::senderTemplate_var [protected]
Definition at line 142 of file RSVPPathMsg_m.h.
The documentation for this class was generated from the following file:
RSVPPathMsg_m.h