INET Framework for OMNeT++/OMNEST: Ieee80211ProbeResponseFrame Class Reference
Ieee80211ProbeResponseFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211ProbeResponseFrame (const char *name=NULL, int kind=0)
Ieee80211ProbeResponseFrame (const Ieee80211ProbeResponseFrame &other)
virtual ~Ieee80211ProbeResponseFrame ()
Ieee80211ProbeResponseFrame & operator= (const Ieee80211ProbeResponseFrame &other)
virtual
Ieee80211ProbeResponseFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual
Ieee80211ProbeResponseFrameBody & getBody ()
virtual const
Ieee80211ProbeResponseFrameBody & getBody () const
virtual void setBody (const Ieee80211ProbeResponseFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211ProbeResponseFrame &)
Protected Attributes
::Ieee80211ProbeResponseFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211ProbeResponseFrame extends Ieee80211ManagementFrame
 {
     type = ST_PROBERESPONSE;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211ProbeResponseFrameBody body;
 }
Definition at line 896 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211ProbeResponseFrame::Ieee80211ProbeResponseFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211ProbeResponseFrame::Ieee80211ProbeResponseFrame (const Ieee80211ProbeResponseFrame & other)
virtual Ieee80211ProbeResponseFrame::~Ieee80211ProbeResponseFrame () [virtual]
Member Function Documentation
virtual Ieee80211ProbeResponseFrame* Ieee80211ProbeResponseFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 909 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211ProbeResponseFrame(*this);}
virtual const Ieee80211ProbeResponseFrameBody& Ieee80211ProbeResponseFrame::getBody () const [inline, virtual]
Definition at line 915 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211ProbeResponseFrame*>(this)->getBody();}
virtual Ieee80211ProbeResponseFrameBody& Ieee80211ProbeResponseFrame::getBody () [virtual]
Referenced by Ieee80211MgmtAP::handleProbeRequestFrame(), and Ieee80211MgmtSTA::handleProbeResponseFrame().
Ieee80211ProbeResponseFrame& Ieee80211ProbeResponseFrame::operator= (const Ieee80211ProbeResponseFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211ProbeResponseFrame::operator== (const Ieee80211ProbeResponseFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211ProbeResponseFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211ProbeResponseFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211ProbeResponseFrame::setBody (const Ieee80211ProbeResponseFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211ProbeResponseFrameBody Ieee80211ProbeResponseFrame::body_var [protected]
Definition at line 899 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h