INET Framework for OMNeT++/OMNEST: Ieee80211ACKFrame Class Reference
Ieee80211ACKFrame Class Reference
#include <Ieee80211Frame_m.h>
Public Member Functions
Ieee80211ACKFrame (const char *name=NULL, int kind=0)
Ieee80211ACKFrame (const Ieee80211ACKFrame &other)
virtual ~Ieee80211ACKFrame ()
Ieee80211ACKFrame & operator= (const Ieee80211ACKFrame &other)
virtual Ieee80211ACKFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const Ieee80211ACKFrame &)
Detailed Description
Class generated from linklayer/ieee80211/mac/Ieee80211Frame.msg by opp_msgc.
 packet Ieee80211ACKFrame extends Ieee80211OneAddressFrame
 {
     type = ST_ACK;
 }
Definition at line 176 of file Ieee80211Frame_m.h.
Constructor & Destructor Documentation
Ieee80211ACKFrame::Ieee80211ACKFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211ACKFrame::Ieee80211ACKFrame (const Ieee80211ACKFrame & other)
virtual Ieee80211ACKFrame::~Ieee80211ACKFrame () [virtual]
Member Function Documentation
virtual Ieee80211ACKFrame* Ieee80211ACKFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211OneAddressFrame.
Definition at line 188 of file Ieee80211Frame_m.h.
{return new Ieee80211ACKFrame(*this);}
Ieee80211ACKFrame& Ieee80211ACKFrame::operator= (const Ieee80211ACKFrame & other)
Reimplemented from Ieee80211OneAddressFrame.
bool Ieee80211ACKFrame::operator== (const Ieee80211ACKFrame &) [protected]
Reimplemented from Ieee80211OneAddressFrame.
virtual void Ieee80211ACKFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211OneAddressFrame.
Referenced by doPacking().
virtual void Ieee80211ACKFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211OneAddressFrame.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Ieee80211Frame_m.h