INET Framework for OMNeT++/OMNEST: TCPOpenCommand Class Reference
TCPOpenCommand Class Reference
#include <TCPCommand_m.h>
Public Member Functions
TCPOpenCommand ()
TCPOpenCommand (const TCPOpenCommand &other)
virtual ~TCPOpenCommand ()
TCPOpenCommand & operator= (const TCPOpenCommand &other)
virtual TCPOpenCommand * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPvXAddress & getLocalAddr ()
virtual const IPvXAddress & getLocalAddr () const
virtual void setLocalAddr (const IPvXAddress &localAddr_var)
virtual IPvXAddress & getRemoteAddr ()
virtual const IPvXAddress & getRemoteAddr () const
virtual void setRemoteAddr (const IPvXAddress &remoteAddr_var)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort_var)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort_var)
virtual bool getFork () const
virtual void setFork (bool fork_var)
virtual const char * getSendQueueClass () const
virtual void setSendQueueClass (const char *sendQueueClass_var)
virtual const char * getReceiveQueueClass () const
virtual void setReceiveQueueClass (const char *receiveQueueClass_var)
virtual const char * getTcpAlgorithmClass () const
virtual void setTcpAlgorithmClass (const char *tcpAlgorithmClass_var)
Protected Member Functions
bool operator== (const TCPOpenCommand &)
Protected Attributes
::IPvXAddress localAddr_var
::IPvXAddress remoteAddr_var
int localPort_var
int remotePort_var
bool fork_var
opp_string sendQueueClass_var
opp_string receiveQueueClass_var
opp_string tcpAlgorithmClass_var
Detailed Description
Class generated from transport/contract/TCPCommand.msg by opp_msgc.
 class TCPOpenCommand extends TCPCommand
 {
     IPvXAddress localAddr;
     IPvXAddress remoteAddr;
     int localPort = -1;
     int remotePort = -1;
     bool fork = false;
     string sendQueueClass;
     string receiveQueueClass;
     string tcpAlgorithmClass;
 }
Definition at line 181 of file TCPCommand_m.h.
Constructor & Destructor Documentation
TCPOpenCommand::TCPOpenCommand ()
Referenced by dup().
TCPOpenCommand::TCPOpenCommand (const TCPOpenCommand & other)
virtual TCPOpenCommand::~TCPOpenCommand () [virtual]
Member Function Documentation
virtual TCPOpenCommand* TCPOpenCommand::dup () const [inline, virtual]
Reimplemented from TCPCommand.
Definition at line 201 of file TCPCommand_m.h.
{return new TCPOpenCommand(*this);}
virtual bool TCPOpenCommand::getFork () const [virtual]
Referenced by tcp_old::TCPConnection::process_OPEN_PASSIVE(), and TCPConnection::process_OPEN_PASSIVE().
virtual const IPvXAddress& TCPOpenCommand::getLocalAddr () const [inline, virtual]
Definition at line 207 of file TCPCommand_m.h.
Referenced by getLocalAddr().
{return const_cast<TCPOpenCommand*>(this)->getLocalAddr();}
virtual IPvXAddress& TCPOpenCommand::getLocalAddr () [virtual]
Referenced by tcp_old::TCPConnection::process_OPEN_ACTIVE(), TCPConnection::process_OPEN_ACTIVE(), tcp_old::TCPConnection::process_OPEN_PASSIVE(), and TCPConnection::process_OPEN_PASSIVE().
virtual int TCPOpenCommand::getLocalPort () const [virtual]
Referenced by tcp_old::TCPConnection::process_OPEN_ACTIVE(), TCPConnection::process_OPEN_ACTIVE(), tcp_old::TCPConnection::process_OPEN_PASSIVE(), and TCPConnection::process_OPEN_PASSIVE().
virtual const char* TCPOpenCommand::getReceiveQueueClass () const [virtual]
Referenced by tcp_old::TCPConnection::initConnection(), and TCPConnection::initConnection().
virtual const IPvXAddress& TCPOpenCommand::getRemoteAddr () const [inline, virtual]
Definition at line 210 of file TCPCommand_m.h.
Referenced by getRemoteAddr().
{return const_cast<TCPOpenCommand*>(this)->getRemoteAddr();}
virtual IPvXAddress& TCPOpenCommand::getRemoteAddr () [virtual]
Referenced by tcp_old::TCPConnection::process_OPEN_ACTIVE(), and TCPConnection::process_OPEN_ACTIVE().
virtual int TCPOpenCommand::getRemotePort () const [virtual]
Referenced by tcp_old::TCPConnection::process_OPEN_ACTIVE(), and TCPConnection::process_OPEN_ACTIVE().
virtual const char* TCPOpenCommand::getSendQueueClass () const [virtual]
Referenced by tcp_old::TCPConnection::initConnection(), and TCPConnection::initConnection().
virtual const char* TCPOpenCommand::getTcpAlgorithmClass () const [virtual]
Referenced by tcp_old::TCPConnection::initConnection(), and TCPConnection::initConnection().
TCPOpenCommand& TCPOpenCommand::operator= (const TCPOpenCommand & other)
Reimplemented from TCPCommand.
bool TCPOpenCommand::operator== (const TCPOpenCommand &) [protected]
Reimplemented from TCPCommand.
virtual void TCPOpenCommand::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doPacking().
virtual void TCPOpenCommand::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TCPCommand.
Referenced by doUnpacking().
virtual void TCPOpenCommand::setFork (bool fork_var) [virtual]
Referenced by TCPSocket::listen().
virtual void TCPOpenCommand::setLocalAddr (const IPvXAddress & localAddr_var) [virtual]
Referenced by TCPSocket::connect(), and TCPSocket::listen().
virtual void TCPOpenCommand::setLocalPort (int localPort_var) [virtual]
Referenced by TCPSocket::connect(), and TCPSocket::listen().
virtual void TCPOpenCommand::setReceiveQueueClass (const char * receiveQueueClass_var) [virtual]
Referenced by TCPSocket::connect(), and TCPSocket::listen().
virtual void TCPOpenCommand::setRemoteAddr (const IPvXAddress & remoteAddr_var) [virtual]
Referenced by TCPSocket::connect().
virtual void TCPOpenCommand::setRemotePort (int remotePort_var) [virtual]
Referenced by TCPSocket::connect().
virtual void TCPOpenCommand::setSendQueueClass (const char * sendQueueClass_var) [virtual]
Referenced by TCPSocket::connect(), and TCPSocket::listen().
virtual void TCPOpenCommand::setTcpAlgorithmClass (const char * tcpAlgorithmClass_var) [virtual]
Referenced by TCPSocket::connect(), and TCPSocket::listen().
Member Data Documentation
bool TCPOpenCommand::fork_var [protected]
Definition at line 188 of file TCPCommand_m.h.
::IPvXAddress TCPOpenCommand::localAddr_var [protected]
Definition at line 184 of file TCPCommand_m.h.
int TCPOpenCommand::localPort_var [protected]
Definition at line 186 of file TCPCommand_m.h.
opp_string TCPOpenCommand::receiveQueueClass_var [protected]
Definition at line 190 of file TCPCommand_m.h.
::IPvXAddress TCPOpenCommand::remoteAddr_var [protected]
Definition at line 185 of file TCPCommand_m.h.
int TCPOpenCommand::remotePort_var [protected]
Definition at line 187 of file TCPCommand_m.h.
opp_string TCPOpenCommand::sendQueueClass_var [protected]
Definition at line 189 of file TCPCommand_m.h.
opp_string TCPOpenCommand::tcpAlgorithmClass_var [protected]
Definition at line 191 of file TCPCommand_m.h.
The documentation for this class was generated from the following file:
TCPCommand_m.h