INET Framework for OMNeT++/OMNEST: SCTPChunk Class Reference
SCTPChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPChunk (const char *name=NULL, int kind=0)
SCTPChunk (const SCTPChunk &other)
virtual ~SCTPChunk ()
SCTPChunk & operator= (const SCTPChunk &other)
virtual SCTPChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint8 getChunkType () const
virtual void setChunkType (uint8 chunkType_var)
Protected Member Functions
bool operator== (const SCTPChunk &)
Protected Attributes
uint8 chunkType_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPChunk extends cPacket
 {
      (false);
      uint8 chunkType;
 }
Definition at line 164 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPChunk::SCTPChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPChunk::SCTPChunk (const SCTPChunk & other)
virtual SCTPChunk::~SCTPChunk () [virtual]
Member Function Documentation
virtual SCTPChunk* SCTPChunk::dup () const [inline, virtual]
Reimplemented in SCTPErrorChunk, SCTPInitChunk, SCTPInitAckChunk, SCTPCookieEchoChunk, SCTPCookieAckChunk, SCTPDataChunk, SCTPForwardTsnChunk, SCTPSackChunk, SCTPAbortChunk, SCTPHeartbeatChunk, SCTPHeartbeatAckChunk, SCTPShutdownChunk, SCTPShutdownAckChunk, SCTPShutdownCompleteChunk, and SCTPErrorChunk_Base.
Definition at line 177 of file SCTPMessage_m.h.
{return new SCTPChunk(*this);}
virtual uint8 SCTPChunk::getChunkType () const [virtual]
Referenced by SCTPAssociation::disposeOf(), SCTPAssociation::process_RCV_Message(), TCPDumper::sctpDump(), and SCTPAssociation::sendToIP().
SCTPChunk& SCTPChunk::operator= (const SCTPChunk & other)
Reimplemented in SCTPErrorChunk, SCTPInitChunk, SCTPInitAckChunk, SCTPCookieEchoChunk, SCTPCookieAckChunk, SCTPDataChunk, SCTPForwardTsnChunk, SCTPSackChunk, SCTPAbortChunk, SCTPHeartbeatChunk, SCTPHeartbeatAckChunk, SCTPShutdownChunk, SCTPShutdownAckChunk, SCTPShutdownCompleteChunk, and SCTPErrorChunk_Base.
bool SCTPChunk::operator== (const SCTPChunk &) [protected]
Reimplemented in SCTPInitChunk, SCTPInitAckChunk, SCTPCookieEchoChunk, SCTPCookieAckChunk, SCTPDataChunk, SCTPForwardTsnChunk, SCTPSackChunk, SCTPAbortChunk, SCTPHeartbeatChunk, SCTPHeartbeatAckChunk, SCTPShutdownChunk, SCTPShutdownAckChunk, SCTPShutdownCompleteChunk, and SCTPErrorChunk_Base.
virtual void SCTPChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in SCTPInitChunk, SCTPInitAckChunk, SCTPCookieEchoChunk, SCTPCookieAckChunk, SCTPDataChunk, SCTPForwardTsnChunk, SCTPSackChunk, SCTPAbortChunk, SCTPHeartbeatChunk, SCTPHeartbeatAckChunk, SCTPShutdownChunk, SCTPShutdownAckChunk, SCTPShutdownCompleteChunk, and SCTPErrorChunk_Base.
Referenced by doPacking().
virtual void SCTPChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in SCTPInitChunk, SCTPInitAckChunk, SCTPCookieEchoChunk, SCTPCookieAckChunk, SCTPDataChunk, SCTPForwardTsnChunk, SCTPSackChunk, SCTPAbortChunk, SCTPHeartbeatChunk, SCTPHeartbeatAckChunk, SCTPShutdownChunk, SCTPShutdownAckChunk, SCTPShutdownCompleteChunk, and SCTPErrorChunk_Base.
Referenced by doUnpacking().
virtual void SCTPChunk::setChunkType (uint8 chunkType_var) [virtual]
Referenced by SCTPAssociation::createSack(), SCTPAssociation::retransmitInit(), SCTPAssociation::sendAbort(), SCTP::sendAbortFromMain(), SCTPAssociation::sendCookieAck(), SCTPAssociation::sendCookieEcho(), SCTPAssociation::sendHeartbeat(), SCTPAssociation::sendHeartbeatAck(), SCTPAssociation::sendInit(), SCTPAssociation::sendInitAck(), SCTPAssociation::sendShutdown(), SCTPAssociation::sendShutdownAck(), SCTPAssociation::sendShutdownComplete(), SCTP::sendShutdownCompleteFromMain(), and SCTPAssociation::transformDataChunk().
Member Data Documentation
uint8 SCTPChunk::chunkType_var [protected]
Definition at line 167 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h