INET Framework for OMNeT++/OMNEST: IPv6Datagram_Base Class Reference
IPv6Datagram_Base Class Reference
#include <IPv6Datagram_m.h>
Public Member Functions
virtual ~IPv6Datagram_Base ()
virtual IPv6Datagram_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPv6Address & getSrcAddress ()
virtual const IPv6Address & getSrcAddress () const
virtual void setSrcAddress (const IPv6Address &srcAddress_var)
virtual IPv6Address & getDestAddress ()
virtual const IPv6Address & getDestAddress () const
virtual void setDestAddress (const IPv6Address &destAddress_var)
virtual unsigned int getTrafficClass () const
virtual void setTrafficClass (unsigned int trafficClass_var)
virtual unsigned int getFlowLabel () const
virtual void setFlowLabel (unsigned int flowLabel_var)
virtual short getHopLimit () const
virtual void setHopLimit (short hopLimit_var)
virtual int getTransportProtocol () const
virtual void setTransportProtocol (int transportProtocol_var)
virtual void setExtensionHeaderArraySize (unsigned int size)
virtual unsigned int getExtensionHeaderArraySize () const
virtual IPv6ExtensionHeaderPtr & getExtensionHeader (unsigned int k)
virtual const
IPv6ExtensionHeaderPtr & getExtensionHeader (unsigned int k) const
virtual void setExtensionHeader (unsigned int k, const IPv6ExtensionHeaderPtr &extensionHeader_var)
Protected Member Functions
bool operator== (const IPv6Datagram_Base &)
IPv6Datagram_Base (const char *name=NULL, int kind=0)
IPv6Datagram_Base (const IPv6Datagram_Base &other)
IPv6Datagram_Base & operator= (const IPv6Datagram_Base &other)
Protected Attributes
::IPv6Address srcAddress_var
::IPv6Address destAddress_var
unsigned int trafficClass_var
unsigned int flowLabel_var
short hopLimit_var
int transportProtocol_var
::IPv6ExtensionHeaderPtr * extensionHeader_var
unsigned int extensionHeader_arraysize
Detailed Description
Class generated from networklayer/ipv6/IPv6Datagram.msg by opp_msgc.
 packet IPv6Datagram
 {
     (true);
     IPv6Address srcAddress;
     IPv6Address destAddress;
     unsigned int trafficClass;
     unsigned int flowLabel;
     short hopLimit = 0;
     int transportProtocol enum(IPProtocolId);
     IPv6ExtensionHeaderPtr extensionHeader[];
 }
IPv6Datagram_Base is only useful if it gets subclassed, and IPv6Datagram is derived from it. The minimum code to be written for IPv6Datagram is the following:
 class IPv6Datagram : public IPv6Datagram_Base
 {
   public:
     IPv6Datagram(const char *name=NULL, int kind=0) : IPv6Datagram_Base(name,kind) {}
     IPv6Datagram(const IPv6Datagram& other) : IPv6Datagram_Base(other.getName()) {operator=(other);}
     IPv6Datagram& operator=(const IPv6Datagram& other) {IPv6Datagram_Base::operator=(other); return *this;}
     virtual IPv6Datagram *dup() const {return new IPv6Datagram(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from IPv6Datagram_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(IPv6Datagram);
Definition at line 67 of file IPv6Datagram_m.h.
Constructor & Destructor Documentation
IPv6Datagram_Base::IPv6Datagram_Base (const char * name = NULL, int kind = 0) [protected]
IPv6Datagram_Base::IPv6Datagram_Base (const IPv6Datagram_Base & other) [protected]
virtual IPv6Datagram_Base::~IPv6Datagram_Base () [virtual]
Member Function Documentation
virtual IPv6Datagram_Base* IPv6Datagram_Base::dup () const [inline, virtual]
Reimplemented in IPv6Datagram.
Definition at line 89 of file IPv6Datagram_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class IPv6Datagram");}
virtual const IPv6Address& IPv6Datagram_Base::getDestAddress () const [inline, virtual]
Definition at line 98 of file IPv6Datagram_m.h.
Referenced by getDestAddress().
{return const_cast<IPv6Datagram_Base*>(this)->getDestAddress();}
virtual IPv6Address& IPv6Datagram_Base::getDestAddress () [virtual]
Referenced by IPv6FragBuf::addFragment(), IPv6::decapsulate(), TCPDumper::dumpIPv6(), IPv6::fragmentAndRoute(), IPv6::handleDatagramFromNetwork(), UDP::processICMPError(), IPv6::routeMulticastPacket(), IPv6::routePacket(), and ICMPv6::validateDatagramPromptingError().
virtual const IPv6ExtensionHeaderPtr& IPv6Datagram_Base::getExtensionHeader (unsigned int k) const [inline, virtual]
Definition at line 111 of file IPv6Datagram_m.h.
Referenced by getExtensionHeader().
{return const_cast<IPv6Datagram_Base*>(this)->getExtensionHeader(k);}
virtual IPv6ExtensionHeaderPtr& IPv6Datagram_Base::getExtensionHeader (unsigned int k) [virtual]
Reimplemented in IPv6Datagram.
virtual unsigned int IPv6Datagram_Base::getExtensionHeaderArraySize () const [virtual]
Reimplemented in IPv6Datagram.
virtual unsigned int IPv6Datagram_Base::getFlowLabel () const [virtual]
virtual short IPv6Datagram_Base::getHopLimit () const [virtual]
Referenced by IPv6::decapsulate(), IPv6::routeMulticastPacket(), IPv6::routePacket(), and IPv6::sendDatagramToOutput().
virtual const IPv6Address& IPv6Datagram_Base::getSrcAddress () const [inline, virtual]
Definition at line 95 of file IPv6Datagram_m.h.
Referenced by getSrcAddress().
{return const_cast<IPv6Datagram_Base*>(this)->getSrcAddress();}
virtual IPv6Address& IPv6Datagram_Base::getSrcAddress () [virtual]
Referenced by IPv6FragBuf::addFragment(), IPv6::decapsulate(), TCPDumper::dumpIPv6(), UDP::processICMPError(), IPv6::routePacket(), and ICMPv6::sendErrorMessage().
virtual unsigned int IPv6Datagram_Base::getTrafficClass () const [virtual]
Referenced by BasicDSCPClassifier::classifyPacket().
virtual int IPv6Datagram_Base::getTransportProtocol () const [virtual]
Referenced by IPv6::decapsulate(), IPv6::handleReceivedICMP(), IPv6::isLocalAddress(), and ICMPv6::validateDatagramPromptingError().
IPv6Datagram_Base& IPv6Datagram_Base::operator= (const IPv6Datagram_Base & other) [protected]
Reimplemented in IPv6Datagram.
Referenced by IPv6Datagram::IPv6Datagram().
bool IPv6Datagram_Base::operator== (const IPv6Datagram_Base &) [protected]
virtual void IPv6Datagram_Base::parsimPack (cCommBuffer * b) [virtual]
virtual void IPv6Datagram_Base::parsimUnpack (cCommBuffer * b) [virtual]
virtual void IPv6Datagram_Base::setDestAddress (const IPv6Address & destAddress_var) [virtual]
virtual void IPv6Datagram_Base::setExtensionHeader (unsigned int k, const IPv6ExtensionHeaderPtr & extensionHeader_var) [virtual]
Reimplemented in IPv6Datagram.
virtual void IPv6Datagram_Base::setExtensionHeaderArraySize (unsigned int size) [virtual]
Reimplemented in IPv6Datagram.
virtual void IPv6Datagram_Base::setFlowLabel (unsigned int flowLabel_var) [virtual]
virtual void IPv6Datagram_Base::setHopLimit (short hopLimit_var) [virtual]
Referenced by IPv6::routeMulticastPacket(), and IPv6::routePacket().
virtual void IPv6Datagram_Base::setSrcAddress (const IPv6Address & srcAddress_var) [virtual]
Referenced by IPv6::routePacket().
virtual void IPv6Datagram_Base::setTrafficClass (unsigned int trafficClass_var) [virtual]
virtual void IPv6Datagram_Base::setTransportProtocol (int transportProtocol_var) [virtual]
Member Data Documentation
::IPv6Address IPv6Datagram_Base::destAddress_var [protected]
Definition at line 71 of file IPv6Datagram_m.h.
unsigned int IPv6Datagram_Base::extensionHeader_arraysize [protected]
Definition at line 77 of file IPv6Datagram_m.h.
::IPv6ExtensionHeaderPtr* IPv6Datagram_Base::extensionHeader_var [protected]
Definition at line 76 of file IPv6Datagram_m.h.
unsigned int IPv6Datagram_Base::flowLabel_var [protected]
Definition at line 73 of file IPv6Datagram_m.h.
short IPv6Datagram_Base::hopLimit_var [protected]
Definition at line 74 of file IPv6Datagram_m.h.
::IPv6Address IPv6Datagram_Base::srcAddress_var [protected]
Definition at line 70 of file IPv6Datagram_m.h.
unsigned int IPv6Datagram_Base::trafficClass_var [protected]
Definition at line 72 of file IPv6Datagram_m.h.
int IPv6Datagram_Base::transportProtocol_var [protected]
Definition at line 75 of file IPv6Datagram_m.h.
The documentation for this class was generated from the following file:
IPv6Datagram_m.h