INET Framework for OMNeT++/OMNEST: RsbCommitTimerMsg Class Reference
RsbCommitTimerMsg Class Reference
#include <SignallingMsg_m.h>
Public Member Functions
RsbCommitTimerMsg (const char *name=NULL, int kind=0)
RsbCommitTimerMsg (const RsbCommitTimerMsg &other)
virtual ~RsbCommitTimerMsg ()
RsbCommitTimerMsg & operator= (const RsbCommitTimerMsg &other)
virtual RsbCommitTimerMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getId () const
virtual void setId (int id_var)
virtual int getCommand () const
virtual void setCommand (int command_var)
Protected Member Functions
bool operator== (const RsbCommitTimerMsg &)
Protected Attributes
int id_var
int command_var
Detailed Description
Class generated from networklayer/rsvp_te/SignallingMsg.msg by opp_msgc.
 message RsbCommitTimerMsg extends SignallingMsg
 {
     int id;
     int command = MSG_RSB_COMMIT_TIMER;
 }
Definition at line 204 of file SignallingMsg_m.h.
Constructor & Destructor Documentation
RsbCommitTimerMsg::RsbCommitTimerMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
RsbCommitTimerMsg::RsbCommitTimerMsg (const RsbCommitTimerMsg & other)
virtual RsbCommitTimerMsg::~RsbCommitTimerMsg () [virtual]
Member Function Documentation
virtual RsbCommitTimerMsg* RsbCommitTimerMsg::dup () const [inline, virtual]
Reimplemented from SignallingMsg.
Definition at line 218 of file SignallingMsg_m.h.
{return new RsbCommitTimerMsg(*this);}
virtual int RsbCommitTimerMsg::getCommand () const [virtual]
Reimplemented from SignallingMsg.
virtual int RsbCommitTimerMsg::getId () const [virtual]
Referenced by RSVP::processRSB_COMMIT_TIMER().
RsbCommitTimerMsg& RsbCommitTimerMsg::operator= (const RsbCommitTimerMsg & other)
Reimplemented from SignallingMsg.
bool RsbCommitTimerMsg::operator== (const RsbCommitTimerMsg &) [protected]
Reimplemented from SignallingMsg.
virtual void RsbCommitTimerMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doPacking().
virtual void RsbCommitTimerMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SignallingMsg.
Referenced by doUnpacking().
virtual void RsbCommitTimerMsg::setCommand (int command_var) [virtual]
Reimplemented from SignallingMsg.
virtual void RsbCommitTimerMsg::setId (int id_var) [virtual]
Referenced by RSVP::createEgressRSB(), and RSVP::createRSB().
Member Data Documentation
int RsbCommitTimerMsg::command_var [protected]
Reimplemented from SignallingMsg.
Definition at line 208 of file SignallingMsg_m.h.
int RsbCommitTimerMsg::id_var [protected]
Definition at line 207 of file SignallingMsg_m.h.
The documentation for this class was generated from the following file:
SignallingMsg_m.h