INET Framework for OMNeT++/OMNEST: IPv6FragmentHeader Class Reference
IPv6FragmentHeader Class Reference
#include <IPv6ExtensionHeaders_m.h>
Public Member Functions
IPv6FragmentHeader ()
IPv6FragmentHeader (const IPv6FragmentHeader &other)
virtual ~IPv6FragmentHeader ()
IPv6FragmentHeader & operator= (const IPv6FragmentHeader &other)
virtual IPv6FragmentHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned short getFragmentOffset () const
virtual void setFragmentOffset (unsigned short fragmentOffset_var)
virtual unsigned int getIdentification () const
virtual void setIdentification (unsigned int identification_var)
virtual bool getMoreFragments () const
virtual void setMoreFragments (bool moreFragments_var)
Protected Member Functions
bool operator== (const IPv6FragmentHeader &)
Protected Attributes
unsigned short fragmentOffset_var
unsigned int identification_var
bool moreFragments_var
Detailed Description
Class generated from networklayer/ipv6/IPv6ExtensionHeaders.msg by opp_msgc.
 class IPv6FragmentHeader extends IPv6ExtensionHeader
 {
     unsigned short fragmentOffset;
     unsigned int identification;
     bool moreFragments;
 }
Definition at line 111 of file IPv6ExtensionHeaders_m.h.
Constructor & Destructor Documentation
IPv6FragmentHeader::IPv6FragmentHeader ()
Referenced by dup().
IPv6FragmentHeader::IPv6FragmentHeader (const IPv6FragmentHeader & other)
virtual IPv6FragmentHeader::~IPv6FragmentHeader () [virtual]
Member Function Documentation
virtual IPv6FragmentHeader* IPv6FragmentHeader::dup () const [inline, virtual]
Reimplemented from IPv6ExtensionHeader.
Definition at line 126 of file IPv6ExtensionHeaders_m.h.
{return new IPv6FragmentHeader(*this);}
virtual unsigned short IPv6FragmentHeader::getFragmentOffset () const [virtual]
Referenced by IPv6FragBuf::addFragment().
virtual unsigned int IPv6FragmentHeader::getIdentification () const [virtual]
Referenced by IPv6FragBuf::addFragment().
virtual bool IPv6FragmentHeader::getMoreFragments () const [virtual]
Referenced by IPv6FragBuf::addFragment().
IPv6FragmentHeader& IPv6FragmentHeader::operator= (const IPv6FragmentHeader & other)
Reimplemented from IPv6ExtensionHeader.
bool IPv6FragmentHeader::operator== (const IPv6FragmentHeader &) [protected]
Reimplemented from IPv6ExtensionHeader_Base.
virtual void IPv6FragmentHeader::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doPacking().
virtual void IPv6FragmentHeader::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doUnpacking().
virtual void IPv6FragmentHeader::setFragmentOffset (unsigned short fragmentOffset_var) [virtual]
virtual void IPv6FragmentHeader::setIdentification (unsigned int identification_var) [virtual]
virtual void IPv6FragmentHeader::setMoreFragments (bool moreFragments_var) [virtual]
Member Data Documentation
unsigned short IPv6FragmentHeader::fragmentOffset_var [protected]
Definition at line 114 of file IPv6ExtensionHeaders_m.h.
unsigned int IPv6FragmentHeader::identification_var [protected]
Definition at line 115 of file IPv6ExtensionHeaders_m.h.
bool IPv6FragmentHeader::moreFragments_var [protected]
Definition at line 116 of file IPv6ExtensionHeaders_m.h.
The documentation for this class was generated from the following file:
IPv6ExtensionHeaders_m.h