INET Framework for OMNeT++/OMNEST: SCTPDataChunk Class Reference
SCTPDataChunk Class Reference
#include <SCTPMessage_m.h>
Public Member Functions
SCTPDataChunk (const char *name=NULL, int kind=0)
SCTPDataChunk (const SCTPDataChunk &other)
virtual ~SCTPDataChunk ()
SCTPDataChunk & operator= (const SCTPDataChunk &other)
virtual SCTPDataChunk * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getEBit () const
virtual void setEBit (bool eBit_var)
virtual bool getBBit () const
virtual void setBBit (bool bBit_var)
virtual bool getUBit () const
virtual void setUBit (bool uBit_var)
virtual uint32 getTsn () const
virtual void setTsn (uint32 tsn_var)
virtual uint16 getSid () const
virtual void setSid (uint16 sid_var)
virtual uint16 getSsn () const
virtual void setSsn (uint16 ssn_var)
virtual uint32 getPpid () const
virtual void setPpid (uint32 ppid_var)
virtual simtime_t getEnqueuingTime () const
virtual void setEnqueuingTime (simtime_t enqueuingTime_var)
Protected Member Functions
bool operator== (const SCTPDataChunk &)
Protected Attributes
bool eBit_var
bool bBit_var
bool uBit_var
uint32 tsn_var
uint16 sid_var
uint16 ssn_var
uint32 ppid_var
simtime_t enqueuingTime_var
Detailed Description
Class generated from transport/sctp/SCTPMessage.msg by opp_msgc.
 message SCTPDataChunk extends SCTPChunk
 {
     bool eBit = 0;
     bool bBit = 0;
     bool uBit = 0;
     uint32 tsn;
     uint16 sid;
     uint16 ssn;
     uint32 ppid;
     simtime_t enqueuingTime;
 }
Definition at line 585 of file SCTPMessage_m.h.
Constructor & Destructor Documentation
SCTPDataChunk::SCTPDataChunk (const char * name = NULL, int kind = 0)
Referenced by dup().
SCTPDataChunk::SCTPDataChunk (const SCTPDataChunk & other)
virtual SCTPDataChunk::~SCTPDataChunk () [virtual]
Member Function Documentation
virtual SCTPDataChunk* SCTPDataChunk::dup () const [inline, virtual]
Reimplemented from SCTPChunk.
Definition at line 605 of file SCTPMessage_m.h.
{return new SCTPDataChunk(*this);}
virtual bool SCTPDataChunk::getBBit () const [virtual]
Referenced by SCTPAssociation::makeVarFromMsg().
virtual bool SCTPDataChunk::getEBit () const [virtual]
Referenced by SCTPAssociation::makeVarFromMsg().
virtual simtime_t SCTPDataChunk::getEnqueuingTime () const [virtual]
virtual uint32 SCTPDataChunk::getPpid () const [virtual]
Referenced by SCTPAssociation::makeVarFromMsg(), and TCPDumper::sctpDump().
virtual uint16 SCTPDataChunk::getSid () const [virtual]
Referenced by SCTPAssociation::makeVarFromMsg(), SCTPAssociation::processDataArrived(), and TCPDumper::sctpDump().
virtual uint16 SCTPDataChunk::getSsn () const [virtual]
Referenced by SCTPAssociation::makeVarFromMsg(), and TCPDumper::sctpDump().
virtual uint32 SCTPDataChunk::getTsn () const [virtual]
Referenced by SCTPAssociation::makeVarFromMsg(), SCTPAssociation::processDataArrived(), and TCPDumper::sctpDump().
virtual bool SCTPDataChunk::getUBit () const [virtual]
Referenced by SCTPAssociation::makeVarFromMsg(), and SCTPAssociation::processDataArrived().
SCTPDataChunk& SCTPDataChunk::operator= (const SCTPDataChunk & other)
Reimplemented from SCTPChunk.
bool SCTPDataChunk::operator== (const SCTPDataChunk &) [protected]
Reimplemented from SCTPChunk.
virtual void SCTPDataChunk::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doPacking().
virtual void SCTPDataChunk::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from SCTPChunk.
Referenced by doUnpacking().
virtual void SCTPDataChunk::setBBit (bool bBit_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
virtual void SCTPDataChunk::setEBit (bool eBit_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
virtual void SCTPDataChunk::setEnqueuingTime (simtime_t enqueuingTime_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
virtual void SCTPDataChunk::setPpid (uint32 ppid_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
virtual void SCTPDataChunk::setSid (uint16 sid_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
virtual void SCTPDataChunk::setSsn (uint16 ssn_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
virtual void SCTPDataChunk::setTsn (uint32 tsn_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
virtual void SCTPDataChunk::setUBit (bool uBit_var) [virtual]
Referenced by SCTPAssociation::transformDataChunk().
Member Data Documentation
bool SCTPDataChunk::bBit_var [protected]
Definition at line 589 of file SCTPMessage_m.h.
bool SCTPDataChunk::eBit_var [protected]
Definition at line 588 of file SCTPMessage_m.h.
simtime_t SCTPDataChunk::enqueuingTime_var [protected]
Definition at line 595 of file SCTPMessage_m.h.
uint32 SCTPDataChunk::ppid_var [protected]
Definition at line 594 of file SCTPMessage_m.h.
uint16 SCTPDataChunk::sid_var [protected]
Definition at line 592 of file SCTPMessage_m.h.
uint16 SCTPDataChunk::ssn_var [protected]
Definition at line 593 of file SCTPMessage_m.h.
uint32 SCTPDataChunk::tsn_var [protected]
Definition at line 591 of file SCTPMessage_m.h.
bool SCTPDataChunk::uBit_var [protected]
Definition at line 590 of file SCTPMessage_m.h.
The documentation for this class was generated from the following file:
SCTPMessage_m.h