INET Framework for OMNeT++/OMNEST: Ieee80211BeaconFrame Class Reference
Ieee80211BeaconFrame Class Reference
#include <Ieee80211MgmtFrames_m.h>
Public Member Functions
Ieee80211BeaconFrame (const char *name=NULL, int kind=0)
Ieee80211BeaconFrame (const Ieee80211BeaconFrame &other)
virtual ~Ieee80211BeaconFrame ()
Ieee80211BeaconFrame & operator= (const Ieee80211BeaconFrame &other)
virtual Ieee80211BeaconFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Ieee80211BeaconFrameBody & getBody ()
virtual const
Ieee80211BeaconFrameBody & getBody () const
virtual void setBody (const Ieee80211BeaconFrameBody &body_var)
Protected Member Functions
bool operator== (const Ieee80211BeaconFrame &)
Protected Attributes
::Ieee80211BeaconFrameBody body_var
Detailed Description
Class generated from linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg by opp_msgc.
 packet Ieee80211BeaconFrame extends Ieee80211ManagementFrame
 {
     type = ST_BEACON;
     byteLength = 28+getBody().getBodyLength();
     Ieee80211BeaconFrameBody body;
 }
Definition at line 859 of file Ieee80211MgmtFrames_m.h.
Constructor & Destructor Documentation
Ieee80211BeaconFrame::Ieee80211BeaconFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
Ieee80211BeaconFrame::Ieee80211BeaconFrame (const Ieee80211BeaconFrame & other)
virtual Ieee80211BeaconFrame::~Ieee80211BeaconFrame () [virtual]
Member Function Documentation
virtual Ieee80211BeaconFrame* Ieee80211BeaconFrame::dup () const [inline, virtual]
Reimplemented from Ieee80211ManagementFrame.
Definition at line 872 of file Ieee80211MgmtFrames_m.h.
{return new Ieee80211BeaconFrame(*this);}
virtual const Ieee80211BeaconFrameBody& Ieee80211BeaconFrame::getBody () const [inline, virtual]
Definition at line 878 of file Ieee80211MgmtFrames_m.h.
Referenced by getBody().
{return const_cast<Ieee80211BeaconFrame*>(this)->getBody();}
virtual Ieee80211BeaconFrameBody& Ieee80211BeaconFrame::getBody () [virtual]
Referenced by Ieee80211MgmtSTA::handleBeaconFrame(), and Ieee80211MgmtAP::sendBeacon().
Ieee80211BeaconFrame& Ieee80211BeaconFrame::operator= (const Ieee80211BeaconFrame & other)
Reimplemented from Ieee80211ManagementFrame.
bool Ieee80211BeaconFrame::operator== (const Ieee80211BeaconFrame &) [protected]
Reimplemented from Ieee80211ManagementFrame.
virtual void Ieee80211BeaconFrame::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doPacking().
virtual void Ieee80211BeaconFrame::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from Ieee80211ManagementFrame.
Referenced by doUnpacking().
virtual void Ieee80211BeaconFrame::setBody (const Ieee80211BeaconFrameBody & body_var) [virtual]
Member Data Documentation
::Ieee80211BeaconFrameBody Ieee80211BeaconFrame::body_var [protected]
Definition at line 862 of file Ieee80211MgmtFrames_m.h.
The documentation for this class was generated from the following file:
Ieee80211MgmtFrames_m.h