INET Framework for OMNeT++/OMNEST: IPv6NeighbourSolicitation Class Reference
IPv6NeighbourSolicitation Class Reference
#include <IPv6NDMessage_m.h>
Public Member Functions
IPv6NeighbourSolicitation (const char *name=NULL, int kind=0)
IPv6NeighbourSolicitation (const IPv6NeighbourSolicitation &other)
virtual ~IPv6NeighbourSolicitation ()
IPv6NeighbourSolicitation & operator= (const IPv6NeighbourSolicitation &other)
virtual IPv6NeighbourSolicitation * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual IPv6Address & getTargetAddress ()
virtual const IPv6Address & getTargetAddress () const
virtual void setTargetAddress (const IPv6Address &targetAddress_var)
virtual MACAddress & getSourceLinkLayerAddress ()
virtual const MACAddress & getSourceLinkLayerAddress () const
virtual void setSourceLinkLayerAddress (const MACAddress &sourceLinkLayerAddress_var)
Protected Member Functions
bool operator== (const IPv6NeighbourSolicitation &)
Protected Attributes
::IPv6Address targetAddress_var
::MACAddress sourceLinkLayerAddress_var
Detailed Description
Class generated from networklayer/icmpv6/IPv6NDMessage.msg by opp_msgc.
 packet IPv6NeighbourSolicitation extends IPv6NDMessage
 {
     IPv6Address targetAddress;
     MACAddress sourceLinkLayerAddress;
 }
Definition at line 238 of file IPv6NDMessage_m.h.
Constructor & Destructor Documentation
IPv6NeighbourSolicitation::IPv6NeighbourSolicitation (const char * name = NULL, int kind = 0)
Referenced by dup().
IPv6NeighbourSolicitation::IPv6NeighbourSolicitation (const IPv6NeighbourSolicitation & other)
virtual IPv6NeighbourSolicitation::~IPv6NeighbourSolicitation () [virtual]
Member Function Documentation
virtual IPv6NeighbourSolicitation* IPv6NeighbourSolicitation::dup () const [inline, virtual]
Reimplemented from IPv6NDMessage.
Definition at line 252 of file IPv6NDMessage_m.h.
{return new IPv6NeighbourSolicitation(*this);}
virtual const MACAddress& IPv6NeighbourSolicitation::getSourceLinkLayerAddress () const [inline, virtual]
Definition at line 261 of file IPv6NDMessage_m.h.
Referenced by getSourceLinkLayerAddress().
{return const_cast<IPv6NeighbourSolicitation*>(this)->getSourceLinkLayerAddress();}
virtual MACAddress& IPv6NeighbourSolicitation::getSourceLinkLayerAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processNSForNonTentativeAddress(), IPv6NeighbourDiscovery::processNSWithSpecifiedSrcAddr(), IPv6NeighbourDiscovery::sendSolicitedNA(), and IPv6NeighbourDiscovery::validateNSPacket().
virtual const IPv6Address& IPv6NeighbourSolicitation::getTargetAddress () const [inline, virtual]
Definition at line 258 of file IPv6NDMessage_m.h.
Referenced by getTargetAddress().
{return const_cast<IPv6NeighbourSolicitation*>(this)->getTargetAddress();}
virtual IPv6Address& IPv6NeighbourSolicitation::getTargetAddress () [virtual]
Referenced by IPv6NeighbourDiscovery::processNSPacket(), IPv6NeighbourDiscovery::sendSolicitedNA(), and IPv6NeighbourDiscovery::validateNSPacket().
IPv6NeighbourSolicitation& IPv6NeighbourSolicitation::operator= (const IPv6NeighbourSolicitation & other)
Reimplemented from IPv6NDMessage.
bool IPv6NeighbourSolicitation::operator== (const IPv6NeighbourSolicitation &) [protected]
Reimplemented from IPv6NDMessage.
virtual void IPv6NeighbourSolicitation::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doPacking().
virtual void IPv6NeighbourSolicitation::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6NDMessage.
Referenced by doUnpacking().
virtual void IPv6NeighbourSolicitation::setSourceLinkLayerAddress (const MACAddress & sourceLinkLayerAddress_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendNSPacket().
virtual void IPv6NeighbourSolicitation::setTargetAddress (const IPv6Address & targetAddress_var) [virtual]
Referenced by IPv6NeighbourDiscovery::createAndSendNSPacket().
Member Data Documentation
::MACAddress IPv6NeighbourSolicitation::sourceLinkLayerAddress_var [protected]
Definition at line 242 of file IPv6NDMessage_m.h.
::IPv6Address IPv6NeighbourSolicitation::targetAddress_var [protected]
Definition at line 241 of file IPv6NDMessage_m.h.
The documentation for this class was generated from the following file:
IPv6NDMessage_m.h