INET Framework for OMNeT++/OMNEST: IPTimestampOption Class Reference
IPTimestampOption Class Reference
#include <IPDatagram_m.h>
Public Member Functions
IPTimestampOption ()
IPTimestampOption (const IPTimestampOption &other)
virtual ~IPTimestampOption ()
IPTimestampOption & operator= (const IPTimestampOption &other)
virtual IPTimestampOption * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getFlag () const
virtual void setFlag (int flag_var)
virtual short getOverflow () const
virtual void setOverflow (short overflow_var)
virtual short getNextAddressPtr () const
virtual void setNextAddressPtr (short nextAddressPtr_var)
virtual unsigned int getRecordAddressArraySize () const
virtual IPAddress & getRecordAddress (unsigned int k)
virtual const IPAddress & getRecordAddress (unsigned int k) const
virtual void setRecordAddress (unsigned int k, const IPAddress &recordAddress_var)
virtual unsigned int getRecordTimestampArraySize () const
virtual simtime_t getRecordTimestamp (unsigned int k) const
virtual void setRecordTimestamp (unsigned int k, simtime_t recordTimestamp_var)
Protected Member Functions
bool operator== (const IPTimestampOption &)
Protected Attributes
int flag_var
short overflow_var
short nextAddressPtr_var
::IPAddress recordAddress_var [MAX_TIMESTAMP_OPTION_ENTRIES]
simtime_t recordTimestamp_var [MAX_IPADDR_OPTION_ENTRIES]
Detailed Description
Class generated from networklayer/ipv4/IPDatagram.msg by opp_msgc.
 class IPTimestampOption
 {
     int flag enum(TimestampFlag);
     short overflow;
     short nextAddressPtr;
     IPAddress recordAddress[MAX_TIMESTAMP_OPTION_ENTRIES];
     simtime_t recordTimestamp[MAX_IPADDR_OPTION_ENTRIES];
 }
Definition at line 155 of file IPDatagram_m.h.
Constructor & Destructor Documentation
IPTimestampOption::IPTimestampOption ()
Referenced by dup().
IPTimestampOption::IPTimestampOption (const IPTimestampOption & other)
virtual IPTimestampOption::~IPTimestampOption () [virtual]
Member Function Documentation
virtual IPTimestampOption* IPTimestampOption::dup () const [inline, virtual]
Definition at line 172 of file IPDatagram_m.h.
{return new IPTimestampOption(*this);}
virtual int IPTimestampOption::getFlag () const [virtual]
virtual short IPTimestampOption::getNextAddressPtr () const [virtual]
virtual short IPTimestampOption::getOverflow () const [virtual]
virtual const IPAddress& IPTimestampOption::getRecordAddress (unsigned int k) const [inline, virtual]
Definition at line 185 of file IPDatagram_m.h.
Referenced by getRecordAddress().
{return const_cast<IPTimestampOption*>(this)->getRecordAddress(k);}
virtual IPAddress& IPTimestampOption::getRecordAddress (unsigned int k) [virtual]
virtual unsigned int IPTimestampOption::getRecordAddressArraySize () const [virtual]
virtual simtime_t IPTimestampOption::getRecordTimestamp (unsigned int k) const [virtual]
virtual unsigned int IPTimestampOption::getRecordTimestampArraySize () const [virtual]
IPTimestampOption& IPTimestampOption::operator= (const IPTimestampOption & other)
bool IPTimestampOption::operator== (const IPTimestampOption &) [protected]
virtual void IPTimestampOption::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void IPTimestampOption::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void IPTimestampOption::setFlag (int flag_var) [virtual]
virtual void IPTimestampOption::setNextAddressPtr (short nextAddressPtr_var) [virtual]
virtual void IPTimestampOption::setOverflow (short overflow_var) [virtual]
virtual void IPTimestampOption::setRecordAddress (unsigned int k, const IPAddress & recordAddress_var) [virtual]
virtual void IPTimestampOption::setRecordTimestamp (unsigned int k, simtime_t recordTimestamp_var) [virtual]
Member Data Documentation
int IPTimestampOption::flag_var [protected]
Definition at line 158 of file IPDatagram_m.h.
short IPTimestampOption::nextAddressPtr_var [protected]
Definition at line 160 of file IPDatagram_m.h.
short IPTimestampOption::overflow_var [protected]
Definition at line 159 of file IPDatagram_m.h.
::IPAddress IPTimestampOption::recordAddress_var[MAX_TIMESTAMP_OPTION_ENTRIES] [protected]
Definition at line 161 of file IPDatagram_m.h.
simtime_t IPTimestampOption::recordTimestamp_var[MAX_IPADDR_OPTION_ENTRIES] [protected]
Definition at line 162 of file IPDatagram_m.h.
The documentation for this class was generated from the following file:
IPDatagram_m.h