INET Framework for OMNeT++/OMNEST: IPv6HopByHopOptionsHeader Class Reference
IPv6HopByHopOptionsHeader Class Reference
#include <IPv6ExtensionHeaders_m.h>
Public Member Functions
IPv6HopByHopOptionsHeader ()
IPv6HopByHopOptionsHeader (const IPv6HopByHopOptionsHeader &other)
virtual ~IPv6HopByHopOptionsHeader ()
IPv6HopByHopOptionsHeader & operator= (const IPv6HopByHopOptionsHeader &other)
virtual IPv6HopByHopOptionsHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const IPv6HopByHopOptionsHeader &)
Detailed Description
Class generated from networklayer/ipv6/IPv6ExtensionHeaders.msg by opp_msgc.
 class IPv6HopByHopOptionsHeader extends IPv6ExtensionHeader
 {
 }
Definition at line 32 of file IPv6ExtensionHeaders_m.h.
Constructor & Destructor Documentation
IPv6HopByHopOptionsHeader::IPv6HopByHopOptionsHeader ()
Referenced by dup().
IPv6HopByHopOptionsHeader::IPv6HopByHopOptionsHeader (const IPv6HopByHopOptionsHeader & other)
virtual IPv6HopByHopOptionsHeader::~IPv6HopByHopOptionsHeader () [virtual]
Member Function Documentation
virtual IPv6HopByHopOptionsHeader* IPv6HopByHopOptionsHeader::dup () const [inline, virtual]
Reimplemented from IPv6ExtensionHeader.
Definition at line 44 of file IPv6ExtensionHeaders_m.h.
{return new IPv6HopByHopOptionsHeader(*this);}
IPv6HopByHopOptionsHeader& IPv6HopByHopOptionsHeader::operator= (const IPv6HopByHopOptionsHeader & other)
Reimplemented from IPv6ExtensionHeader.
bool IPv6HopByHopOptionsHeader::operator== (const IPv6HopByHopOptionsHeader &) [protected]
Reimplemented from IPv6ExtensionHeader_Base.
virtual void IPv6HopByHopOptionsHeader::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doPacking().
virtual void IPv6HopByHopOptionsHeader::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
IPv6ExtensionHeaders_m.h