INET Framework for OMNeT++/OMNEST: IPSourceRoutingOption Class Reference
IPSourceRoutingOption Class Reference
#include <IPDatagram_m.h>
Public Member Functions
IPSourceRoutingOption ()
IPSourceRoutingOption (const IPSourceRoutingOption &other)
virtual ~IPSourceRoutingOption ()
IPSourceRoutingOption & operator= (const IPSourceRoutingOption &other)
virtual IPSourceRoutingOption * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getRecordAddressArraySize () const
virtual IPAddress & getRecordAddress (unsigned int k)
virtual const IPAddress & getRecordAddress (unsigned int k) const
virtual void setRecordAddress (unsigned int k, const IPAddress &recordAddress_var)
virtual short getNextAddressPtr () const
virtual void setNextAddressPtr (short nextAddressPtr_var)
virtual short getLastAddressPtr () const
virtual void setLastAddressPtr (short lastAddressPtr_var)
Protected Member Functions
bool operator== (const IPSourceRoutingOption &)
Protected Attributes
::IPAddress recordAddress_var [MAX_IPADDR_OPTION_ENTRIES]
short nextAddressPtr_var
short lastAddressPtr_var
Detailed Description
Class generated from networklayer/ipv4/IPDatagram.msg by opp_msgc.
 class IPSourceRoutingOption
 {
     IPAddress recordAddress[MAX_IPADDR_OPTION_ENTRIES];
     short nextAddressPtr;
     short lastAddressPtr;
 }
Definition at line 206 of file IPDatagram_m.h.
Constructor & Destructor Documentation
IPSourceRoutingOption::IPSourceRoutingOption ()
Referenced by dup().
IPSourceRoutingOption::IPSourceRoutingOption (const IPSourceRoutingOption & other)
virtual IPSourceRoutingOption::~IPSourceRoutingOption () [virtual]
Member Function Documentation
virtual IPSourceRoutingOption* IPSourceRoutingOption::dup () const [inline, virtual]
Definition at line 221 of file IPDatagram_m.h.
{return new IPSourceRoutingOption(*this);}
virtual short IPSourceRoutingOption::getLastAddressPtr () const [virtual]
virtual short IPSourceRoutingOption::getNextAddressPtr () const [virtual]
virtual const IPAddress& IPSourceRoutingOption::getRecordAddress (unsigned int k) const [inline, virtual]
Definition at line 228 of file IPDatagram_m.h.
Referenced by getRecordAddress().
{return const_cast<IPSourceRoutingOption*>(this)->getRecordAddress(k);}
virtual IPAddress& IPSourceRoutingOption::getRecordAddress (unsigned int k) [virtual]
virtual unsigned int IPSourceRoutingOption::getRecordAddressArraySize () const [virtual]
IPSourceRoutingOption& IPSourceRoutingOption::operator= (const IPSourceRoutingOption & other)
bool IPSourceRoutingOption::operator== (const IPSourceRoutingOption &) [protected]
virtual void IPSourceRoutingOption::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void IPSourceRoutingOption::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void IPSourceRoutingOption::setLastAddressPtr (short lastAddressPtr_var) [virtual]
virtual void IPSourceRoutingOption::setNextAddressPtr (short nextAddressPtr_var) [virtual]
virtual void IPSourceRoutingOption::setRecordAddress (unsigned int k, const IPAddress & recordAddress_var) [virtual]
Member Data Documentation
short IPSourceRoutingOption::lastAddressPtr_var [protected]
Definition at line 211 of file IPDatagram_m.h.
short IPSourceRoutingOption::nextAddressPtr_var [protected]
Definition at line 210 of file IPDatagram_m.h.
::IPAddress IPSourceRoutingOption::recordAddress_var[MAX_IPADDR_OPTION_ENTRIES] [protected]
Definition at line 209 of file IPDatagram_m.h.
The documentation for this class was generated from the following file:
IPDatagram_m.h