INET Framework for OMNeT++/OMNEST: RSVPPathError Class Reference
RSVPPathError Class Reference
#include <RSVPPathMsg.h>
Public Member Functions
RSVPPathError (const char *name=NULL, int kind=PERROR_MESSAGE)
RSVPPathError (const RSVPPathError &other)
RSVPPathError & operator= (const RSVPPathError &other)
virtual RSVPPathError * dup () const
IPAddress getSrcAddress ()
int getLspId ()
double getBW ()
SenderTemplateObj_t & getSenderTemplate ()
void setSenderTemplate (const SenderTemplateObj_t &s)
SenderTspecObj_t & getSenderTspec ()
void setSenderTspec (const SenderTspecObj_t &s)
Detailed Description
RSVP PATH ERROR message
This class adds convenience get() and set() methods to the generated base class, but no extra data.
Definition at line 75 of file RSVPPathMsg.h.
Constructor & Destructor Documentation
RSVPPathError::RSVPPathError (const char * name = NULL, int kind = PERROR_MESSAGE) [inline]
Definition at line 78 of file RSVPPathMsg.h.
Referenced by dup().
: RSVPPathError_Base(name,kind) {}
RSVPPathError::RSVPPathError (const RSVPPathError & other) [inline]
Definition at line 79 of file RSVPPathMsg.h.
: RSVPPathError_Base(other.getName()) {operator=(other);}
Member Function Documentation
virtual RSVPPathError* RSVPPathError::dup () const [inline, virtual]
Reimplemented from RSVPPathError_Base.
Definition at line 81 of file RSVPPathMsg.h.
{return new RSVPPathError(*this);}
double RSVPPathError::getBW () [inline]
Definition at line 85 of file RSVPPathMsg.h.
{return getSender_descriptor().Sender_Tspec_Object.req_bandwidth;}
int RSVPPathError::getLspId () [inline]
Definition at line 84 of file RSVPPathMsg.h.
{return getSender_descriptor().Sender_Template_Object.Lsp_Id;}
SenderTemplateObj_t& RSVPPathError::getSenderTemplate () [inline]
Definition at line 87 of file RSVPPathMsg.h.
Referenced by RSVP::processPathErrMsg().
{return getSender_descriptor().Sender_Template_Object;}
SenderTspecObj_t& RSVPPathError::getSenderTspec () [inline]
Definition at line 89 of file RSVPPathMsg.h.
{return getSender_descriptor().Sender_Tspec_Object;}
IPAddress RSVPPathError::getSrcAddress () [inline]
Definition at line 83 of file RSVPPathMsg.h.
{return getSender_descriptor().Sender_Template_Object.SrcAddress;}
RSVPPathError& RSVPPathError::operator= (const RSVPPathError & other) [inline]
Reimplemented from RSVPPathError_Base.
Definition at line 80 of file RSVPPathMsg.h.
Referenced by RSVPPathError().
{RSVPPathError_Base::operator=(other); return *this;}
void RSVPPathError::setSenderTemplate (const SenderTemplateObj_t & s) [inline]
Definition at line 88 of file RSVPPathMsg.h.
Referenced by RSVP::sendPathErrorMessage().
{getSender_descriptor().Sender_Template_Object = s;}
void RSVPPathError::setSenderTspec (const SenderTspecObj_t & s) [inline]
Definition at line 90 of file RSVPPathMsg.h.
Referenced by RSVP::sendPathErrorMessage().
{getSender_descriptor().Sender_Tspec_Object = s;}
The documentation for this class was generated from the following file:
RSVPPathMsg.h