INET Framework for OMNeT++/OMNEST: IPv6DestinationOptionsHeader Class Reference
IPv6DestinationOptionsHeader Class Reference
#include <IPv6ExtensionHeaders_m.h>
Public Member Functions
IPv6DestinationOptionsHeader ()
IPv6DestinationOptionsHeader (const IPv6DestinationOptionsHeader &other)
virtual ~IPv6DestinationOptionsHeader ()
IPv6DestinationOptionsHeader & operator= (const IPv6DestinationOptionsHeader &other)
virtual
IPv6DestinationOptionsHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const IPv6DestinationOptionsHeader &)
Detailed Description
Class generated from networklayer/ipv6/IPv6ExtensionHeaders.msg by opp_msgc.
 class IPv6DestinationOptionsHeader extends IPv6ExtensionHeader
 {
 }
Definition at line 150 of file IPv6ExtensionHeaders_m.h.
Constructor & Destructor Documentation
IPv6DestinationOptionsHeader::IPv6DestinationOptionsHeader ()
Referenced by dup().
IPv6DestinationOptionsHeader::IPv6DestinationOptionsHeader (const IPv6DestinationOptionsHeader & other)
virtual IPv6DestinationOptionsHeader::~IPv6DestinationOptionsHeader () [virtual]
Member Function Documentation
virtual IPv6DestinationOptionsHeader* IPv6DestinationOptionsHeader::dup () const [inline, virtual]
Reimplemented from IPv6ExtensionHeader.
Definition at line 162 of file IPv6ExtensionHeaders_m.h.
{return new IPv6DestinationOptionsHeader(*this);}
IPv6DestinationOptionsHeader& IPv6DestinationOptionsHeader::operator= (const IPv6DestinationOptionsHeader & other)
Reimplemented from IPv6ExtensionHeader.
bool IPv6DestinationOptionsHeader::operator== (const IPv6DestinationOptionsHeader &) [protected]
Reimplemented from IPv6ExtensionHeader_Base.
virtual void IPv6DestinationOptionsHeader::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doPacking().
virtual void IPv6DestinationOptionsHeader::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from IPv6ExtensionHeader_Base.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
IPv6ExtensionHeaders_m.h