INET Framework for OMNeT++/OMNEST: ICMPv6PacketTooBigMsg Class Reference
ICMPv6PacketTooBigMsg Class Reference
#include <ICMPv6Message_m.h>
Public Member Functions
ICMPv6PacketTooBigMsg (const char *name=NULL, int kind=0)
ICMPv6PacketTooBigMsg (const ICMPv6PacketTooBigMsg &other)
virtual ~ICMPv6PacketTooBigMsg ()
ICMPv6PacketTooBigMsg & operator= (const ICMPv6PacketTooBigMsg &other)
virtual ICMPv6PacketTooBigMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCode () const
virtual void setCode (int code_var)
virtual int getMTU () const
virtual void setMTU (int MTU_var)
Protected Member Functions
bool operator== (const ICMPv6PacketTooBigMsg &)
Protected Attributes
int code_var
int MTU_var
Detailed Description
Class generated from networklayer/icmpv6/ICMPv6Message.msg by opp_msgc.
 packet ICMPv6PacketTooBigMsg extends ICMPv6Message
 {
     int code;
     int MTU;
 }
Definition at line 202 of file ICMPv6Message_m.h.
Constructor & Destructor Documentation
ICMPv6PacketTooBigMsg::ICMPv6PacketTooBigMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
ICMPv6PacketTooBigMsg::ICMPv6PacketTooBigMsg (const ICMPv6PacketTooBigMsg & other)
virtual ICMPv6PacketTooBigMsg::~ICMPv6PacketTooBigMsg () [virtual]
Member Function Documentation
virtual ICMPv6PacketTooBigMsg* ICMPv6PacketTooBigMsg::dup () const [inline, virtual]
Reimplemented from ICMPv6Message.
Definition at line 216 of file ICMPv6Message_m.h.
{return new ICMPv6PacketTooBigMsg(*this);}
virtual int ICMPv6PacketTooBigMsg::getCode () const [virtual]
virtual int ICMPv6PacketTooBigMsg::getMTU () const [virtual]
ICMPv6PacketTooBigMsg& ICMPv6PacketTooBigMsg::operator= (const ICMPv6PacketTooBigMsg & other)
Reimplemented from ICMPv6Message.
bool ICMPv6PacketTooBigMsg::operator== (const ICMPv6PacketTooBigMsg &) [protected]
Reimplemented from ICMPv6Message.
virtual void ICMPv6PacketTooBigMsg::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doPacking().
virtual void ICMPv6PacketTooBigMsg::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ICMPv6Message.
Referenced by doUnpacking().
virtual void ICMPv6PacketTooBigMsg::setCode (int code_var) [virtual]
Referenced by ICMPv6::createPacketTooBigMsg().
virtual void ICMPv6PacketTooBigMsg::setMTU (int MTU_var) [virtual]
Referenced by ICMPv6::createPacketTooBigMsg().
Member Data Documentation
int ICMPv6PacketTooBigMsg::code_var [protected]
Definition at line 205 of file ICMPv6Message_m.h.
int ICMPv6PacketTooBigMsg::MTU_var [protected]
Definition at line 206 of file ICMPv6Message_m.h.
The documentation for this class was generated from the following file:
ICMPv6Message_m.h